import type { LessonData } from "./lessons-data";

const LESSON_A1_01: LessonData = {
  id: "a1-01",
  slug: "greetings-introductions",
  title: "Greetings & Introductions",
  description: "Learn how to greet people and introduce yourself in formal and informal contexts across Spain and Latin America.",
  level: "A1",
  difficulty: "Beginner",
  order: 1,
  imageUrl: null,
  durationMinutes: 45,
  isPublished: true,
  vocabularyTable: [
    { word: "hola", spainVariant: "hola", latamVariant: "hola", phoneticSpain: "OH-lah", phoneticLatam: "OH-lah", english: "Hello", partOfSpeech: "interjection", exampleSentenceSpain: "¡Hola! ¿Cómo estás?", exampleSentenceLatam: "¡Hola! ¿Cómo estás?" },
    { word: "buenos días", spainVariant: "buenos días", latamVariant: "buenos días", phoneticSpain: "bweh-nos DEE-ahs", phoneticLatam: "bweh-nos DEE-ahs", english: "Good morning", partOfSpeech: "phrase", exampleSentenceSpain: "Buenos días, María.", exampleSentenceLatam: "Buenos días, Carlos." },
    { word: "buenas tardes", spainVariant: "buenas tardes", latamVariant: "buenas tardes", phoneticSpain: "bweh-nahs TAR-dehs", phoneticLatam: "bweh-nahs TAR-dehs", english: "Good afternoon", partOfSpeech: "phrase", exampleSentenceSpain: "Buenas tardes, señor.", exampleSentenceLatam: "Buenas tardes, jefe." },
    { word: "buenas noches", spainVariant: "buenas noches", latamVariant: "buenas noches", phoneticSpain: "bweh-nahs NOH-ches", phoneticLatam: "bweh-nahs NOH-ches", english: "Good evening/night", partOfSpeech: "phrase", exampleSentenceSpain: "Buenas noches a todos.", exampleSentenceLatam: "Buenas noches, familia." },
    { word: "adiós", spainVariant: "adiós", latamVariant: "adiós", phoneticSpain: "ah-dee-OHS", phoneticLatam: "ah-dee-OHS", english: "Goodbye", partOfSpeech: "interjection", exampleSentenceSpain: "¡Adiós! Hasta mañana.", exampleSentenceLatam: "¡Adiós! Nos vemos." },
    { word: "me llamo", spainVariant: "me llamo", latamVariant: "me llamo", phoneticSpain: "meh YAH-moh", phoneticLatam: "meh YAH-moh", english: "My name is", partOfSpeech: "phrase", exampleSentenceSpain: "Me llamo Juan.", exampleSentenceLatam: "Me llamo Rosa." },
    { word: "mucho gusto", spainVariant: "mucho gusto", latamVariant: "mucho gusto", phoneticSpain: "MOO-choh GOOS-toh", phoneticLatam: "MOO-choh GOOS-toh", english: "Nice to meet you", partOfSpeech: "phrase", exampleSentenceSpain: "Mucho gusto, encantado.", exampleSentenceLatam: "Mucho gusto, es un placer." },
    { word: "¿cómo te llamas?", spainVariant: "¿cómo te llamas?", latamVariant: "¿cómo te llamas?", phoneticSpain: "KOH-moh teh YAH-mahs", phoneticLatam: "KOH-moh teh YAH-mahs", english: "What is your name?", partOfSpeech: "question", exampleSentenceSpain: "¿Cómo te llamas, amigo?", exampleSentenceLatam: "¿Cómo te llamas, hermano?" },
    { word: "¿cómo estás?", spainVariant: "¿cómo estás?", latamVariant: "¿cómo estás?", phoneticSpain: "KOH-moh es-TAHS", phoneticLatam: "KOH-moh es-TAHS", english: "How are you?", partOfSpeech: "question", exampleSentenceSpain: "¿Cómo estás hoy?", exampleSentenceLatam: "¿Cómo estás, compa?" },
    { word: "estoy bien", spainVariant: "estoy bien", latamVariant: "estoy bien", phoneticSpain: "es-TOY bee-EHN", phoneticLatam: "es-TOY bee-EHN", english: "I am well", partOfSpeech: "phrase", exampleSentenceSpain: "Estoy bien, gracias.", exampleSentenceLatam: "Estoy bien, ¿y tú?" },
    { word: "gracias", spainVariant: "gracias", latamVariant: "gracias", phoneticSpain: "GRAH-see-ahs", phoneticLatam: "GRAH-see-ahs", english: "Thank you", partOfSpeech: "interjection", exampleSentenceSpain: "Gracias por tu ayuda.", exampleSentenceLatam: "Gracias, muy amable." },
    { word: "de nada", spainVariant: "de nada", latamVariant: "de nada", phoneticSpain: "deh NAH-dah", phoneticLatam: "deh NAH-dah", english: "You're welcome", partOfSpeech: "phrase", exampleSentenceSpain: "De nada, no es nada.", exampleSentenceLatam: "De nada, para eso estamos." },
    { word: "por favor", spainVariant: "por favor", latamVariant: "por favor", phoneticSpain: "por fah-VOR", phoneticLatam: "por fah-VOR", english: "Please", partOfSpeech: "phrase", exampleSentenceSpain: "Café, por favor.", exampleSentenceLatam: "Agua, por favor." },
    { word: "disculpa", spainVariant: "disculpa", latamVariant: "disculpa", phoneticSpain: "dees-KOOL-pah", phoneticLatam: "dees-KOOL-pah", english: "Excuse me/Sorry", partOfSpeech: "interjection", exampleSentenceSpain: "Disculpa, ¿me ayudas?", exampleSentenceLatam: "Disculpa, no entendí." },
    { word: "señor/señora", spainVariant: "señor/señora", latamVariant: "señor/señora", phoneticSpain: "sen-YOR/sen-YOH-rah", phoneticLatam: "sen-YOR/sen-YOH-rah", english: "Mr./Mrs.", partOfSpeech: "noun", exampleSentenceSpain: "El señor García es profesor.", exampleSentenceLatam: "La señora López es muy amable." },
    { word: "joven", spainVariant: "joven", latamVariant: "joven", phoneticSpain: "HOH-ven", phoneticLatam: "HOH-ven", english: "Young person", partOfSpeech: "noun", exampleSentenceSpain: "El joven trabaja aquí.", exampleSentenceLatam: "La joven es estudiante." },
    { word: "amigo/amiga", spainVariant: "amigo/amiga", latamVariant: "amigo/amiga", phoneticSpain: "ah-MEE-goh/ah-MEE-gah", phoneticLatam: "ah-MEE-goh/ah-MEE-gah", english: "Friend", partOfSpeech: "noun", exampleSentenceSpain: "Mi amigo es de Madrid.", exampleSentenceLatam: "Mi amiga es de México." },
    { word: "encantado", spainVariant: "encantado/encantada", latamVariant: "encantado/encantada", phoneticSpain: "en-kahn-TAH-doh", phoneticLatam: "en-kahn-TAH-doh", english: "Delighted/Charmed", partOfSpeech: "adjective", exampleSentenceSpain: "Encantado de conocerte.", exampleSentenceLatam: "Encantada, mucho gusto." },
    { word: "¿de dónde eres?", spainVariant: "¿de dónde eres?", latamVariant: "¿de dónde eres?", phoneticSpain: "deh DOHN-deh EH-res", phoneticLatam: "deh DOHN-deh EH-res", english: "Where are you from?", partOfSpeech: "question", exampleSentenceSpain: "¿De dónde eres, Juan?", exampleSentenceLatam: "¿De dónde eres, hermano?" },
    { word: "soy de", spainVariant: "soy de", latamVariant: "soy de", phoneticSpain: "soy deh", phoneticLatam: "soy deh", english: "I am from", partOfSpeech: "phrase", exampleSentenceSpain: "Soy de Barcelona.", exampleSentenceLatam: "Soy de Guadalajara." },
  ],
  grammarSection: [
    {
      title: "Present Tense of 'Ser' (To Be)",
      spainContent: "Ser conjugates: yo soy, tú eres, él/ella es, nosotros somos, vosotros sois, ellos son. Used for identity, origin, profession. Example: 'Yo soy Juan, soy de España.'",
      latamContent: "Ser conjugates: yo soy, tú eres, él/ella es, nosotros somos, ustedes son, ellos son. LATAM uses 'ustedes' instead of 'vosotros'. Example: 'Yo soy Carlos, soy de México.'",
      note: "Vosotros (Spain only) for informal plural; LATAM uses ustedes for all formal/informal plural.",
    },
    {
      title: "Asking & Answering Questions",
      spainContent: "Question words: ¿Cómo? (How?), ¿Quién? (Who?), ¿De dónde? (Where from?). Invert subject-verb: ¿Cómo estás? ¿De dónde eres?",
      latamContent: "Same question words and inversion rules apply. Example: ¿Cómo estás? ¿De dónde eres? Both regions follow identical syntax.",
      note: "Both regions use identical question formation; no regional variation in basic interrogatives.",
    },
  ],
  dialogues: [
    {
      id: "a1-01-dial-01",
      title: "Madrid Metro - Morning Encounter",
      region: "SPAIN",
      setting: "Madrid Metro platform, morning",
      lines: [
        { speaker: "Miguel", text: "¡Hola! Buenos días.", region: "SPAIN", setting: "metro" },
        { speaker: "Ana", text: "Buenos días, ¿cómo estás?", region: "SPAIN", setting: "metro" },
        { speaker: "Miguel", text: "Estoy bien, gracias. Me llamo Miguel, ¿y tú?", region: "SPAIN", setting: "metro" },
        { speaker: "Ana", text: "Me llamo Ana. Mucho gusto, Miguel.", region: "SPAIN", setting: "metro" },
        { speaker: "Miguel", text: "Mucho gusto, Ana. ¿De dónde eres?", region: "SPAIN", setting: "metro" },
        { speaker: "Ana", text: "Soy de Barcelona, ¿y tú?", region: "SPAIN", setting: "metro" },
      ],
    },
    {
      id: "a1-01-dial-02",
      title: "Barcelona Café - Casual Meeting",
      region: "SPAIN",
      setting: "Café in Barcelona",
      lines: [
        { speaker: "Pedro", text: "¡Hola, joven! ¿Cómo te llamas?", region: "SPAIN", setting: "café" },
        { speaker: "Laura", text: "Me llamo Laura. ¿Y tú, señor?", region: "SPAIN", setting: "café" },
        { speaker: "Pedro", text: "Me llamo Pedro. Encantado, Laura.", region: "SPAIN", setting: "café" },
        { speaker: "Laura", text: "Encantada, Pedro. ¿Cómo estás?", region: "SPAIN", setting: "café" },
        { speaker: "Pedro", text: "Estoy bien. Gracias por preguntar.", region: "SPAIN", setting: "café" },
        { speaker: "Laura", text: "De nada. ¡Hasta luego!", region: "SPAIN", setting: "café" },
      ],
    },
    {
      id: "a1-01-dial-03",
      title: "Valencia Office - Formal Introduction",
      region: "SPAIN",
      setting: "Office, Valencia",
      lines: [
        { speaker: "Señora Gómez", text: "Buenos días, señor. Me llamo Rosa Gómez.", region: "SPAIN", setting: "office" },
        { speaker: "Señor López", text: "Buenos días, señora. Me llamo Carlos López. Mucho gusto.", region: "SPAIN", setting: "office" },
        { speaker: "Señora Gómez", text: "Mucho gusto, señor López. ¿Cómo estás?", region: "SPAIN", setting: "office" },
        { speaker: "Señor López", text: "Estoy bien, gracias. ¿De dónde eres?", region: "SPAIN", setting: "office" },
        { speaker: "Señora Gómez", text: "Soy de Valencia, ¿y tú?", region: "SPAIN", setting: "office" },
        { speaker: "Señor López", text: "Soy de Madrid. Encantado de conocerte.", region: "SPAIN", setting: "office" },
      ],
    },
    {
      id: "a1-01-dial-04",
      title: "Mexico City Street - Friendly Hello",
      region: "LATAM",
      setting: "Mexico City street, afternoon",
      lines: [
        { speaker: "Diego", text: "¡Hola! ¿Cómo estás?", region: "LATAM", setting: "street" },
        { speaker: "Sofia", text: "¡Hola, Diego! Estoy bien, ¿y tú?", region: "LATAM", setting: "street" },
        { speaker: "Diego", text: "Estoy muy bien. Me llamo Diego, ¿y tú?", region: "LATAM", setting: "street" },
        { speaker: "Sofia", text: "Me llamo Sofía. Mucho gusto.", region: "LATAM", setting: "street" },
        { speaker: "Diego", text: "Mucho gusto, Sofía. ¿De dónde eres?", region: "LATAM", setting: "street" },
        { speaker: "Sofia", text: "Soy de Guadalajara, ¿y tú?", region: "LATAM", setting: "street" },
      ],
    },
    {
      id: "a1-01-dial-05",
      title: "Buenos Aires Cafe - Meeting a Friend",
      region: "LATAM",
      setting: "Café in Buenos Aires",
      lines: [
        { speaker: "Martín", text: "¡Hola, hermano! ¿Cómo estás?", region: "LATAM", setting: "café" },
        { speaker: "Lucía", text: "¡Hola, Martín! Estoy bien. Me llamo Lucía.", region: "LATAM", setting: "café" },
        { speaker: "Martín", text: "Encantado, Lucía. Yo soy Martín.", region: "LATAM", setting: "café" },
        { speaker: "Lucía", text: "Mucho gusto. ¿De dónde eres?", region: "LATAM", setting: "café" },
        { speaker: "Martín", text: "Soy de Buenos Aires, ¿y tú?", region: "LATAM", setting: "café" },
        { speaker: "Lucía", text: "Soy de Lima. ¡Mucho gusto, Martín!", region: "LATAM", setting: "café" },
      ],
    },
    {
      id: "a1-01-dial-06",
      title: "Colombia University - Student Introduction",
      region: "LATAM",
      setting: "University classroom, Bogotá",
      lines: [
        { speaker: "Profesor García", text: "Buenos días, estudiantes. Me llamo García.", region: "LATAM", setting: "classroom" },
        { speaker: "Javier", text: "Buenos días, profesor. Me llamo Javier, ¿cómo estás?", region: "LATAM", setting: "classroom" },
        { speaker: "Profesor García", text: "Estoy bien, gracias. ¿De dónde eres, Javier?", region: "LATAM", setting: "classroom" },
        { speaker: "Javier", text: "Soy de Bogotá. Mucho gusto, profesor.", region: "LATAM", setting: "classroom" },
        { speaker: "Mariana", text: "Hola, me llamo Mariana. ¿Cómo estás, profesor?", region: "LATAM", setting: "classroom" },
        { speaker: "Profesor García", text: "Encantado, Mariana. Bienvenida a la clase.", region: "LATAM", setting: "classroom" },
      ],
    },
  ],
  quiz: [
    {
      questionId: "a1-01-q01",
      type: "multiple-choice",
      questionText: "What is the correct greeting for morning in Spanish?",
      options: ["Buenas noches", "Buenos días", "Buenas tardes", "¡Adiós!"],
      correctAnswer: "Buenos días",
      explanation: "Buenos días means 'Good morning' and is used from sunrise until midday.",
    },
    {
      questionId: "a1-01-q02",
      type: "multiple-choice",
      questionText: "How do you say 'Nice to meet you' in Spanish?",
      options: ["¿Cómo estás?", "Me llamo", "Mucho gusto", "Adiós"],
      correctAnswer: "Mucho gusto",
      explanation: "Mucho gusto literally means 'Much pleasure' and is the standard greeting when meeting someone new.",
    },
    {
      questionId: "a1-01-q03",
      type: "multiple-choice",
      questionText: "Which word means 'Hello'?",
      options: ["Adiós", "Hola", "Gracias", "Disculpa"],
      correctAnswer: "Hola",
      explanation: "Hola is the basic Spanish greeting equivalent to 'Hello' in English.",
    },
    {
      questionId: "a1-01-q04",
      type: "multiple-choice",
      questionText: "What does 'De nada' mean?",
      options: ["Thank you", "You're welcome", "Hello", "Goodbye"],
      correctAnswer: "You're welcome",
      explanation: "'De nada' (literally 'of nothing') is the Spanish response to 'Thank you'.",
    },
    {
      questionId: "a1-01-q05",
      type: "multiple-choice",
      questionText: "Which phrase means 'I am from'?",
      options: ["Me llamo", "Soy de", "¿De dónde?", "¿Cómo estás?"],
      correctAnswer: "Soy de",
      explanation: "'Soy de' literally means 'I am from' and is used to state your origin or hometown.",
    },
  ],
  flashcards: [
    { id: "a1-01-fc01", frontSpain: "hola", frontLatam: "hola", backEnglish: "Hello", variantDifferenceNote: "Identical across regions", exampleSentenceSpain: "¡Hola! ¿Cómo estás?", exampleSentenceLatam: "¡Hola, compa!", partOfSpeech: "interjection" },
    { id: "a1-01-fc02", frontSpain: "buenos días", frontLatam: "buenos días", backEnglish: "Good morning", variantDifferenceNote: "Identical across regions", exampleSentenceSpain: "Buenos días, María.", exampleSentenceLatam: "Buenos días, amigo.", partOfSpeech: "phrase" },
    { id: "a1-01-fc03", frontSpain: "buenas tardes", frontLatam: "buenas tardes", backEnglish: "Good afternoon", variantDifferenceNote: "Identical across regions", exampleSentenceSpain: "Buenas tardes, señor.", exampleSentenceLatam: "Buenas tardes, jefe.", partOfSpeech: "phrase" },
    { id: "a1-01-fc04", frontSpain: "buenas noches", frontLatam: "buenas noches", backEnglish: "Good evening/night", variantDifferenceNote: "Identical across regions", exampleSentenceSpain: "Buenas noches a todos.", exampleSentenceLatam: "Buenas noches, familia.", partOfSpeech: "phrase" },
    { id: "a1-01-fc05", frontSpain: "adiós", frontLatam: "adiós", backEnglish: "Goodbye", variantDifferenceNote: "Identical across regions", exampleSentenceSpain: "¡Adiós! Hasta luego.", exampleSentenceLatam: "¡Adiós, nos vemos!", partOfSpeech: "interjection" },
    { id: "a1-01-fc06", frontSpain: "me llamo", frontLatam: "me llamo", backEnglish: "My name is", variantDifferenceNote: "Identical across regions", exampleSentenceSpain: "Me llamo Juan.", exampleSentenceLatam: "Me llamo Rosa.", partOfSpeech: "phrase" },
    { id: "a1-01-fc07", frontSpain: "mucho gusto", frontLatam: "mucho gusto", backEnglish: "Nice to meet you", variantDifferenceNote: "Identical across regions", exampleSentenceSpain: "Mucho gusto, encantado.", exampleSentenceLatam: "Mucho gusto, amigo.", partOfSpeech: "phrase" },
    { id: "a1-01-fc08", frontSpain: "¿cómo estás?", frontLatam: "¿cómo estás?", backEnglish: "How are you?", variantDifferenceNote: "Identical across regions", exampleSentenceSpain: "¿Cómo estás hoy?", exampleSentenceLatam: "¿Cómo estás, hermano?", partOfSpeech: "question" },
    { id: "a1-01-fc09", frontSpain: "estoy bien", frontLatam: "estoy bien", backEnglish: "I am well", variantDifferenceNote: "Identical across regions", exampleSentenceSpain: "Estoy bien, gracias.", exampleSentenceLatam: "Estoy bien, ¿y tú?", partOfSpeech: "phrase" },
    { id: "a1-01-fc10", frontSpain: "gracias", frontLatam: "gracias", backEnglish: "Thank you", variantDifferenceNote: "Identical across regions", exampleSentenceSpain: "Gracias por tu ayuda.", exampleSentenceLatam: "Gracias, muy amable.", partOfSpeech: "interjection" },
    { id: "a1-01-fc11", frontSpain: "de nada", frontLatam: "de nada", backEnglish: "You're welcome", variantDifferenceNote: "Identical across regions", exampleSentenceSpain: "De nada, no es nada.", exampleSentenceLatam: "De nada, para eso estamos.", partOfSpeech: "phrase" },
    { id: "a1-01-fc12", frontSpain: "por favor", frontLatam: "por favor", backEnglish: "Please", variantDifferenceNote: "Identical across regions", exampleSentenceSpain: "Café, por favor.", exampleSentenceLatam: "Agua, por favor.", partOfSpeech: "phrase" },
    { id: "a1-01-fc13", frontSpain: "disculpa", frontLatam: "disculpa", backEnglish: "Excuse me/Sorry", variantDifferenceNote: "Identical across regions", exampleSentenceSpain: "Disculpa, ¿me ayudas?", exampleSentenceLatam: "Disculpa, ¿me prestas esto?", partOfSpeech: "interjection" },
    { id: "a1-01-fc14", frontSpain: "señor/señora", frontLatam: "señor/señora", backEnglish: "Mr./Mrs.", variantDifferenceNote: "Identical across regions", exampleSentenceSpain: "El señor García es profesor.", exampleSentenceLatam: "La señora López es doctora.", partOfSpeech: "noun" },
    { id: "a1-01-fc15", frontSpain: "amigo/amiga", frontLatam: "amigo/amiga", backEnglish: "Friend", variantDifferenceNote: "Identical across regions", exampleSentenceSpain: "Mi amigo es de Madrid.", exampleSentenceLatam: "Mi amiga es de Guadalajara.", partOfSpeech: "noun" },
    { id: "a1-01-fc16", frontSpain: "encantado", frontLatam: "encantado", backEnglish: "Delighted/Charmed", variantDifferenceNote: "Identical across regions; feminine: encantada", exampleSentenceSpain: "Encantado de conocerte.", exampleSentenceLatam: "Encantada, mucho gusto.", partOfSpeech: "adjective" },
    { id: "a1-01-fc17", frontSpain: "¿de dónde eres?", frontLatam: "¿de dónde eres?", backEnglish: "Where are you from?", variantDifferenceNote: "Identical across regions", exampleSentenceSpain: "¿De dónde eres, Juan?", exampleSentenceLatam: "¿De dónde eres, hermano?", partOfSpeech: "question" },
    { id: "a1-01-fc18", frontSpain: "soy de", frontLatam: "soy de", backEnglish: "I am from", variantDifferenceNote: "Identical across regions", exampleSentenceSpain: "Soy de Barcelona.", exampleSentenceLatam: "Soy de Guadalajara.", partOfSpeech: "phrase" },
    { id: "a1-01-fc19", frontSpain: "yo soy", frontLatam: "yo soy", backEnglish: "I am", variantDifferenceNote: "Identical across regions", exampleSentenceSpain: "Yo soy Maria.", exampleSentenceLatam: "Yo soy Carlos.", partOfSpeech: "verb" },
    { id: "a1-01-fc20", frontSpain: "eres", frontLatam: "eres", backEnglish: "You are (informal)", variantDifferenceNote: "Identical across regions", exampleSentenceSpain: "¿De dónde eres?", exampleSentenceLatam: "¿Quién eres tú?", partOfSpeech: "verb" },
  ],
  vocabularyJson: [],
  grammarJson: [],
  content: "A1.01 Greetings & Introductions",
};

const LESSON_A1_02: LessonData = { id: "a1-02", slug: "basic-numbers", title: "Basic Numbers 0-20", description: "Learn numbers from zero to twenty in Spanish and basic counting.", level: "A1", difficulty: "Beginner", order: 2, imageUrl: null, durationMinutes: 45, isPublished: true, vocabularyTable: [{ word: "cero", spainVariant: "cero", latamVariant: "cero", phoneticSpain: "SER-oh", phoneticLatam: "SER-oh", english: "Zero", partOfSpeech: "number", exampleSentenceSpain: "El número cero.", exampleSentenceLatam: "Cero errores." }, { word: "uno", spainVariant: "uno", latamVariant: "uno", phoneticSpain: "OO-noh", phoneticLatam: "OO-noh", english: "One", partOfSpeech: "number", exampleSentenceSpain: "Uno y uno son dos.", exampleSentenceLatam: "Tengo uno." }, { word: "dos", spainVariant: "dos", latamVariant: "dos", phoneticSpain: "dohs", phoneticLatam: "dohs", english: "Two", partOfSpeech: "number", exampleSentenceSpain: "Dos gatos.", exampleSentenceLatam: "Dos hermanos." }, { word: "tres", spainVariant: "tres", latamVariant: "tres", phoneticSpain: "trehs", phoneticLatam: "trehs", english: "Three", partOfSpeech: "number", exampleSentenceSpain: "Tres personas.", exampleSentenceLatam: "Tres amigos." }, { word: "cuatro", spainVariant: "cuatro", latamVariant: "cuatro", phoneticSpain: "KOO-ah-troh", phoneticLatam: "KOO-ah-troh", english: "Four", partOfSpeech: "number", exampleSentenceSpain: "Cuatro manzanas.", exampleSentenceLatam: "Cuatro libros." }, { word: "cinco", spainVariant: "cinco", latamVariant: "cinco", phoneticSpain: "SEEN-koh", phoneticLatam: "SEEN-koh", english: "Five", partOfSpeech: "number", exampleSentenceSpain: "Cinco dedos.", exampleSentenceLatam: "Cinco dólares." }, { word: "seis", spainVariant: "seis", latamVariant: "seis", phoneticSpain: "sayss", phoneticLatam: "sayss", english: "Six", partOfSpeech: "number", exampleSentenceSpain: "Seis horas.", exampleSentenceLatam: "Seis minutos." }, { word: "siete", spainVariant: "siete", latamVariant: "siete", phoneticSpain: "see-EH-teh", phoneticLatam: "see-EH-teh", english: "Seven", partOfSpeech: "number", exampleSentenceSpain: "Siete días.", exampleSentenceLatam: "Siete semanas." }, { word: "ocho", spainVariant: "ocho", latamVariant: "ocho", phoneticSpain: "OH-choh", phoneticLatam: "OH-choh", english: "Eight", partOfSpeech: "number", exampleSentenceSpain: "Ocho patas.", exampleSentenceLatam: "Ocho años." }, { word: "nueve", spainVariant: "nueve", latamVariant: "nueve", phoneticSpain: "noo-EH-veh", phoneticLatam: "noo-EH-veh", english: "Nine", partOfSpeech: "number", exampleSentenceSpain: "Nueve gatos.", exampleSentenceLatam: "Nueve meses." }, { word: "diez", spainVariant: "diez", latamVariant: "diez", phoneticSpain: "dee-EHS", phoneticLatam: "dee-EHS", english: "Ten", partOfSpeech: "number", exampleSentenceSpain: "Diez euros.", exampleSentenceLatam: "Diez pesos." }, { word: "once", spainVariant: "once", latamVariant: "once", phoneticSpain: "OHN-seh", phoneticLatam: "OHN-seh", english: "Eleven", partOfSpeech: "number", exampleSentenceSpain: "Once personas.", exampleSentenceLatam: "Once horas." }, { word: "doce", spainVariant: "doce", latamVariant: "doce", phoneticSpain: "DOH-seh", phoneticLatam: "DOH-seh", english: "Twelve", partOfSpeech: "number", exampleSentenceSpain: "Doce meses.", exampleSentenceLatam: "Doce punto." }, { word: "trece", spainVariant: "trece", latamVariant: "trece", phoneticSpain: "TREH-seh", phoneticLatam: "TREH-seh", english: "Thirteen", partOfSpeech: "number", exampleSentenceSpain: "Trece años.", exampleSentenceLatam: "Trece pesos." }, { word: "catorce", spainVariant: "catorce", latamVariant: "catorce", phoneticSpain: "kah-TOR-seh", phoneticLatam: "kah-TOR-seh", english: "Fourteen", partOfSpeech: "number", exampleSentenceSpain: "Catorce días.", exampleSentenceLatam: "Catorce libros." }, { word: "quince", spainVariant: "quince", latamVariant: "quince", phoneticSpain: "KEEN-seh", phoneticLatam: "KEEN-seh", english: "Fifteen", partOfSpeech: "number", exampleSentenceSpain: "Quince minutos.", exampleSentenceLatam: "Quince dólares." }, { word: "dieciséis", spainVariant: "dieciséis", latamVariant: "dieciséis", phoneticSpain: "dee-eh-see-SAYS", phoneticLatam: "dee-eh-see-SAYS", english: "Sixteen", partOfSpeech: "number", exampleSentenceSpain: "Dieciséis años.", exampleSentenceLatam: "Dieciséis horas." }, { word: "diecisiete", spainVariant: "diecisiete", latamVariant: "diecisiete", phoneticSpain: "dee-eh-see-see-EH-teh", phoneticLatam: "dee-eh-see-see-EH-teh", english: "Seventeen", partOfSpeech: "number", exampleSentenceSpain: "Diecisiete personas.", exampleSentenceLatam: "Diecisiete años." }, { word: "dieciocho", spainVariant: "dieciocho", latamVariant: "dieciocho", phoneticSpain: "dee-eh-see-OH-choh", phoneticLatam: "dee-eh-see-OH-choh", english: "Eighteen", partOfSpeech: "number", exampleSentenceSpain: "Dieciocho meses.", exampleSentenceLatam: "Dieciocho semanas." }, { word: "diecinueve", spainVariant: "diecinueve", latamVariant: "diecinueve", phoneticSpain: "dee-eh-see-noo-EH-veh", phoneticLatam: "dee-eh-see-noo-EH-veh", english: "Nineteen", partOfSpeech: "number", exampleSentenceSpain: "Diecinueve gatos.", exampleSentenceLatam: "Diecinueve años." }, { word: "veinte", spainVariant: "veinte", latamVariant: "veinte", phoneticSpain: "VAYN-teh", phoneticLatam: "VAYN-teh", english: "Twenty", partOfSpeech: "number", exampleSentenceSpain: "Veinte euros.", exampleSentenceLatam: "Veinte pesos." }], grammarSection: [{ title: "Counting in Spanish", spainContent: "Spanish numbers 0-20 have unique names. Repeat: cero, uno, dos, tres... veinte. Used for ages, prices, time.", latamContent: "Same numbering system across LATAM. Pronunciation identical. Regional variation minimal.", note: "No significant regional variation in basic number vocabulary." }, { title: "Gender Agreement with Numbers", spainContent: "Only 'uno' changes with gender: un libro (masculine), una casa (feminine). All other numbers stay same. Examples: dos gatos, tres niñas.", latamContent: "Identical gender agreement rules across LATAM. Uno becomes 'un' or 'una' depending on noun gender.", note: "Both regions follow identical number-gender agreement patterns." }], dialogues: [{ id: "a1-02-dial-01", title: "Barcelona Shop - Counting Items", region: "SPAIN", setting: "Small shop, Barcelona", lines: [{ speaker: "Vendedor", text: "¿Cuántas manzanas quieres?", region: "SPAIN", setting: "shop" }, { speaker: "Cliente", text: "Quiero cinco manzanas, por favor.", region: "SPAIN", setting: "shop" }, { speaker: "Vendedor", text: "Cinco manzanas. ¿Algo más?", region: "SPAIN", setting: "shop" }, { speaker: "Cliente", text: "Sí, dos panes y tres quesos.", region: "SPAIN", setting: "shop" }, { speaker: "Vendedor", text: "Dos panes y tres quesos. Son diez euros.", region: "SPAIN", setting: "shop" }, { speaker: "Cliente", text: "Perfecto. Gracias.", region: "SPAIN", setting: "shop" }] }, { id: "a1-02-dial-02", title: "Madrid School - Teacher Counting", region: "SPAIN", setting: "School classroom, Madrid", lines: [{ speaker: "Profesor", text: "¿Cuántos estudiantes hay hoy?", region: "SPAIN", setting: "classroom" }, { speaker: "Alumna", text: "Hay quince estudiantes, profesor.", region: "SPAIN", setting: "classroom" }, { speaker: "Profesor", text: "Quince, bien. ¿Faltan algunos?", region: "SPAIN", setting: "classroom" }, { speaker: "Alumna", text: "Faltan tres estudiantes.", region: "SPAIN", setting: "classroom" }, { speaker: "Profesor", text: "Entonces son dieciocho hoy.", region: "SPAIN", setting: "classroom" }, { speaker: "Alumna", text: "Exacto, profesor.", region: "SPAIN", setting: "classroom" }] }, { id: "a1-02-dial-03", title: "Seville Market - Price Negotiation", region: "SPAIN", setting: "Market stall, Seville", lines: [{ speaker: "Vendedor", text: "Tres euros por manzana. ¿Cuántas quieres?", region: "SPAIN", setting: "market" }, { speaker: "Comprador", text: "Quiero seis manzanas.", region: "SPAIN", setting: "market" }, { speaker: "Vendedor", text: "Son dieciocho euros.", region: "SPAIN", setting: "market" }, { speaker: "Comprador", text: "¿Dieciocho? ¿Nada más?", region: "SPAIN", setting: "market" }, { speaker: "Vendedor", text: "Sí, dieciocho euros. ¡Buen precio!", region: "SPAIN", setting: "market" }, { speaker: "Comprador", text: "Está bien. Gracias.", region: "SPAIN", setting: "market" }] }, { id: "a1-02-dial-04", title: "Mexico City Market - Fruit Shopping", region: "LATAM", setting: "Market, Mexico City", lines: [{ speaker: "Vendedor", text: "¿Cuántos plátanos quieres?", region: "LATAM", setting: "market" }, { speaker: "Cliente", text: "Quiero ocho plátanos, por favor.", region: "LATAM", setting: "market" }, { speaker: "Vendedor", text: "Ocho plátanos. ¿Algo más?", region: "LATAM", setting: "market" }, { speaker: "Cliente", text: "Sí, cinco naranjas y dos piñas.", region: "LATAM", setting: "market" }, { speaker: "Vendedor", text: "Eso es quince pesos total.", region: "LATAM", setting: "market" }, { speaker: "Cliente", text: "Perfecto, gracias.", region: "LATAM", setting: "market" }] }, { id: "a1-02-dial-05", title: "Argentina Restaurant - Counting Guests", region: "LATAM", setting: "Restaurant, Buenos Aires", lines: [{ speaker: "Mesero", text: "¿Cuántas personas somos?", region: "LATAM", setting: "restaurant" }, { speaker: "Cliente", text: "Somos seis personas.", region: "LATAM", setting: "restaurant" }, { speaker: "Mesero", text: "Seis personas. Una mesa grande entonces.", region: "LATAM", setting: "restaurant" }, { speaker: "Cliente", text: "Sí, por favor. ¿Tienes mesa para seis?", region: "LATAM", setting: "restaurant" }, { speaker: "Mesero", text: "Sí, aquí hay una mesa para seis.", region: "LATAM", setting: "restaurant" }, { speaker: "Cliente", text: "Gracias, muy amable.", region: "LATAM", setting: "restaurant" }] }, { id: "a1-02-dial-06", title: "Colombia Bank - Account Numbers", region: "LATAM", setting: "Bank, Bogotá", lines: [{ speaker: "Banquero", text: "¿Cuál es tu cuenta?", region: "LATAM", setting: "bank" }, { speaker: "Cliente", text: "Ciento veinte y tres.", region: "LATAM", setting: "bank" }, { speaker: "Banquero", text: "¿Ciento veinte y tres? Repite, por favor.", region: "LATAM", setting: "bank" }, { speaker: "Cliente", text: "Uno, dos, tres. Número ciento veintitrés.", region: "LATAM", setting: "bank" }, { speaker: "Banquero", text: "Perfecto. Ciento veintitrés.", region: "LATAM", setting: "bank" }, { speaker: "Cliente", text: "Exacto. Gracias.", region: "LATAM", setting: "bank" }] }], quiz: [{ questionId: "a1-02-q01", type: "multiple-choice", questionText: "What is the number 5 in Spanish?", options: ["Cuatro", "Cinco", "Seis", "Tres"], correctAnswer: "Cinco", explanation: "Cinco is the Spanish word for the number 5." }, { questionId: "a1-02-q02", type: "multiple-choice", questionText: "How many are 'dos' plus 'tres'?", options: ["Cinco", "Cuatro", "Tres", "Seis"], correctAnswer: "Cinco", explanation: "Dos (2) + tres (3) = cinco (5)." }, { questionId: "a1-02-q03", type: "multiple-choice", questionText: "What is the number 15 in Spanish?", options: ["Catorce", "Dieciséis", "Quince", "Trece"], correctAnswer: "Quince", explanation: "Quince is the Spanish word for 15." }, { questionId: "a1-02-q04", type: "multiple-choice", questionText: "What is 'veinte' in English?", options: ["Ten", "Fifteen", "Twenty", "Twelve"], correctAnswer: "Twenty", explanation: "Veinte means 20 in English." }, { questionId: "a1-02-q05", type: "multiple-choice", questionText: "How many are 'diez' plus 'diez'?", options: ["Quince", "Veinte", "Dieciséis", "Dieciocho"], correctAnswer: "Veinte", explanation: "Diez (10) + diez (10) = veinte (20)." }], flashcards: [{ id: "a1-02-fc01", frontSpain: "cero", frontLatam: "cero", backEnglish: "Zero", variantDifferenceNote: "Identical", exampleSentenceSpain: "Cero errores.", exampleSentenceLatam: "Cero pesos.", partOfSpeech: "number" }, { id: "a1-02-fc02", frontSpain: "uno", frontLatam: "uno", backEnglish: "One", variantDifferenceNote: "Identical", exampleSentenceSpain: "Uno y uno son dos.", exampleSentenceLatam: "Tengo uno.", partOfSpeech: "number" }, { id: "a1-02-fc03", frontSpain: "dos", frontLatam: "dos", backEnglish: "Two", variantDifferenceNote: "Identical", exampleSentenceSpain: "Dos gatos.", exampleSentenceLatam: "Dos hermanos.", partOfSpeech: "number" }, { id: "a1-02-fc04", frontSpain: "tres", frontLatam: "tres", backEnglish: "Three", variantDifferenceNote: "Identical", exampleSentenceSpain: "Tres personas.", exampleSentenceLatam: "Tres amigos.", partOfSpeech: "number" }, { id: "a1-02-fc05", frontSpain: "cuatro", frontLatam: "cuatro", backEnglish: "Four", variantDifferenceNote: "Identical", exampleSentenceSpain: "Cuatro manzanas.", exampleSentenceLatam: "Cuatro libros.", partOfSpeech: "number" }, { id: "a1-02-fc06", frontSpain: "cinco", frontLatam: "cinco", backEnglish: "Five", variantDifferenceNote: "Identical", exampleSentenceSpain: "Cinco dedos.", exampleSentenceLatam: "Cinco dólares.", partOfSpeech: "number" }, { id: "a1-02-fc07", frontSpain: "seis", frontLatam: "seis", backEnglish: "Six", variantDifferenceNote: "Identical", exampleSentenceSpain: "Seis horas.", exampleSentenceLatam: "Seis minutos.", partOfSpeech: "number" }, { id: "a1-02-fc08", frontSpain: "siete", frontLatam: "siete", backEnglish: "Seven", variantDifferenceNote: "Identical", exampleSentenceSpain: "Siete días.", exampleSentenceLatam: "Siete semanas.", partOfSpeech: "number" }, { id: "a1-02-fc09", frontSpain: "ocho", frontLatam: "ocho", backEnglish: "Eight", variantDifferenceNote: "Identical", exampleSentenceSpain: "Ocho patas.", exampleSentenceLatam: "Ocho años.", partOfSpeech: "number" }, { id: "a1-02-fc10", frontSpain: "nueve", frontLatam: "nueve", backEnglish: "Nine", variantDifferenceNote: "Identical", exampleSentenceSpain: "Nueve gatos.", exampleSentenceLatam: "Nueve meses.", partOfSpeech: "number" }, { id: "a1-02-fc11", frontSpain: "diez", frontLatam: "diez", backEnglish: "Ten", variantDifferenceNote: "Identical", exampleSentenceSpain: "Diez euros.", exampleSentenceLatam: "Diez pesos.", partOfSpeech: "number" }, { id: "a1-02-fc12", frontSpain: "once", frontLatam: "once", backEnglish: "Eleven", variantDifferenceNote: "Identical", exampleSentenceSpain: "Once personas.", exampleSentenceLatam: "Once horas.", partOfSpeech: "number" }, { id: "a1-02-fc13", frontSpain: "doce", frontLatam: "doce", backEnglish: "Twelve", variantDifferenceNote: "Identical", exampleSentenceSpain: "Doce meses.", exampleSentenceLatam: "Doce puntos.", partOfSpeech: "number" }, { id: "a1-02-fc14", frontSpain: "trece", frontLatam: "trece", backEnglish: "Thirteen", variantDifferenceNote: "Identical", exampleSentenceSpain: "Trece años.", exampleSentenceLatam: "Trece pesos.", partOfSpeech: "number" }, { id: "a1-02-fc15", frontSpain: "catorce", frontLatam: "catorce", backEnglish: "Fourteen", variantDifferenceNote: "Identical", exampleSentenceSpain: "Catorce días.", exampleSentenceLatam: "Catorce libros.", partOfSpeech: "number" }, { id: "a1-02-fc16", frontSpain: "quince", frontLatam: "quince", backEnglish: "Fifteen", variantDifferenceNote: "Identical", exampleSentenceSpain: "Quince minutos.", exampleSentenceLatam: "Quince dólares.", partOfSpeech: "number" }, { id: "a1-02-fc17", frontSpain: "dieciséis", frontLatam: "dieciséis", backEnglish: "Sixteen", variantDifferenceNote: "Identical", exampleSentenceSpain: "Dieciséis años.", exampleSentenceLatam: "Dieciséis horas.", partOfSpeech: "number" }, { id: "a1-02-fc18", frontSpain: "diecisiete", frontLatam: "diecisiete", backEnglish: "Seventeen", variantDifferenceNote: "Identical", exampleSentenceSpain: "Diecisiete personas.", exampleSentenceLatam: "Diecisiete años.", partOfSpeech: "number" }, { id: "a1-02-fc19", frontSpain: "dieciocho", frontLatam: "dieciocho", backEnglish: "Eighteen", variantDifferenceNote: "Identical", exampleSentenceSpain: "Dieciocho meses.", exampleSentenceLatam: "Dieciocho semanas.", partOfSpeech: "number" }, { id: "a1-02-fc20", frontSpain: "veinte", frontLatam: "veinte", backEnglish: "Twenty", variantDifferenceNote: "Identical", exampleSentenceSpain: "Veinte euros.", exampleSentenceLatam: "Veinte pesos.", partOfSpeech: "number" }], vocabularyJson: [], grammarJson: [], content: "A1.02 Basic Numbers 0-20" };

const LESSON_A1_03 = { 
  id: "a1-03", 
  slug: "basic-phrases", 
  title: "Basic Phrases & Politeness", 
  description: "Essential polite expressions and common phrases for daily interaction.",
  level: "A1", 
  difficulty: "Beginner", 
  order: 3, 
  imageUrl: null, 
  durationMinutes: 45, 
  isPublished: true, 
  vocabularyTable: [
    { word: "por favor", spainVariant: "por favor", latamVariant: "por favor", phoneticSpain: "por fah-VOR", phoneticLatam: "por fah-VOR", english: "Please", partOfSpeech: "phrase", exampleSentenceSpain: "Agua, por favor.", exampleSentenceLatam: "Café, por favor." },
    { word: "gracias", spainVariant: "gracias", latamVariant: "gracias", phoneticSpain: "GRAH-see-ahs", phoneticLatam: "GRAH-see-ahs", english: "Thank you", partOfSpeech: "interjection", exampleSentenceSpain: "Gracias por tu ayuda.", exampleSentenceLatam: "Gracias, muy amable." },
    { word: "de nada", spainVariant: "de nada", latamVariant: "de nada", phoneticSpain: "deh NAH-dah", phoneticLatam: "deh NAH-dah", english: "You're welcome", partOfSpeech: "phrase", exampleSentenceSpain: "De nada, no es nada.", exampleSentenceLatam: "De nada, para eso estamos." },
    { word: "disculpe", spainVariant: "disculpe", latamVariant: "disculpa", phoneticSpain: "dees-KOOL-peh", phoneticLatam: "dees-KOOL-pah", english: "Excuse me (formal)", partOfSpeech: "interjection", exampleSentenceSpain: "Disculpe, ¿me ayuda?", exampleSentenceLatam: "Disculpa, ¿tienes tiempo?" },
    { word: "lo siento", spainVariant: "lo siento", latamVariant: "lo siento", phoneticSpain: "loh see-EHN-toh", phoneticLatam: "loh see-EHN-toh", english: "I'm sorry", partOfSpeech: "phrase", exampleSentenceSpain: "Lo siento, fue mi error.", exampleSentenceLatam: "Lo siento mucho." },
    { word: "con permiso", spainVariant: "con permiso", latamVariant: "con permiso", phoneticSpain: "kohn per-MEE-soh", phoneticLatam: "kohn per-MEE-soh", english: "Excuse me (passing)", partOfSpeech: "phrase", exampleSentenceSpain: "Con permiso, necesito pasar.", exampleSentenceLatam: "Con permiso, voy a entrar." },
    { word: "perdón", spainVariant: "perdón", latamVariant: "perdón", phoneticSpain: "per-DOHN", phoneticLatam: "per-DOHN", english: "Pardon/Sorry", partOfSpeech: "interjection", exampleSentenceSpain: "Perdón, ¿me entiendes?", exampleSentenceLatam: "Perdón, no oí bien." },
    { word: "¿me ayudas?", spainVariant: "¿me ayudas?", latamVariant: "¿me ayudas?", phoneticSpain: "meh ah-YOO-dahs", phoneticLatam: "meh ah-YOO-dahs", english: "Can you help me?", partOfSpeech: "question", exampleSentenceSpain: "¿Me ayudas con esto?", exampleSentenceLatam: "¿Me ayudas, por favor?" },
    { word: "no entiendo", spainVariant: "no entiendo", latamVariant: "no entiendo", phoneticSpain: "noh en-tee-EHN-doh", phoneticLatam: "noh en-tee-EHN-doh", english: "I don't understand", partOfSpeech: "phrase", exampleSentenceSpain: "No entiendo lo que dices.", exampleSentenceLatam: "No entiendo, repite por favor." },
    { word: "habla más lentamente", spainVariant: "habla más lentamente", latamVariant: "habla más lentamente", phoneticSpain: "AH-blah mahs len-tah-MEHN-teh", phoneticLatam: "AH-blah mahs len-tah-MEHN-teh", english: "Speak more slowly", partOfSpeech: "phrase", exampleSentenceSpain: "¿Puedes hablar más lentamente?", exampleSentenceLatam: "Habla más lentamente, por favor." },
    { word: "¿qué dijiste?", spainVariant: "¿qué dijiste?", latamVariant: "¿qué dijiste?", phoneticSpain: "keh dee-HEES-teh", phoneticLatam: "keh dee-HEES-teh", english: "What did you say?", partOfSpeech: "question", exampleSentenceSpain: "¿Qué dijiste? No oí.", exampleSentenceLatam: "¿Qué dijiste? Repite, por favor." },
    { word: "se llama", spainVariant: "se llama", latamVariant: "se llama", phoneticSpain: "seh YAH-mah", phoneticLatam: "seh YAH-mah", english: "His/her name is", partOfSpeech: "phrase", exampleSentenceSpain: "Mi amigo se llama Juan.", exampleSentenceLatam: "Mi hermana se llama María." },
    { word: "bienvenido/a", spainVariant: "bienvenido/a", latamVariant: "bienvenido/a", phoneticSpain: "bee-en-veh-NEE-doh/dah", phoneticLatam: "bee-en-veh-NEE-doh/dah", english: "Welcome", partOfSpeech: "adjective", exampleSentenceSpain: "¡Bienvenido a España!", exampleSentenceLatam: "¡Bienvenida a México!" },
    { word: "hasta luego", spainVariant: "hasta luego", latamVariant: "hasta luego", phoneticSpain: "AHS-tah loo-EH-goh", phoneticLatam: "AHS-tah loo-EH-goh", english: "See you later", partOfSpeech: "phrase", exampleSentenceSpain: "¡Hasta luego! ¡Fue un placer!", exampleSentenceLatam: "¡Hasta luego, amigo!" },
    { word: "hasta pronto", spainVariant: "hasta pronto", latamVariant: "hasta pronto", phoneticSpain: "AHS-tah PROHN-toh", phoneticLatam: "AHS-tah PROHN-toh", english: "See you soon", partOfSpeech: "phrase", exampleSentenceSpain: "¡Hasta pronto!", exampleSentenceLatam: "¡Hasta pronto, compa!" },
    { word: "buena suerte", spainVariant: "buena suerte", latamVariant: "buena suerte", phoneticSpain: "boo-EH-nah soo-EHR-teh", phoneticLatam: "boo-EH-nah soo-EHR-teh", english: "Good luck", partOfSpeech: "phrase", exampleSentenceSpain: "¡Buena suerte con tu examen!", exampleSentenceLatam: "¡Buena suerte en el trabajo!" },
    { word: "que disfrutes", spainVariant: "que disfrutes", latamVariant: "que disfrutes", phoneticSpain: "keh dees-FROO-tehs", phoneticLatam: "keh dees-FROO-tehs", english: "Enjoy", partOfSpeech: "phrase", exampleSentenceSpain: "¡Que disfrutes del viaje!", exampleSentenceLatam: "¡Que disfrutes de tu día!" },
    { word: "igualmente", spainVariant: "igualmente", latamVariant: "igualmente", phoneticSpain: "ee-goo-ahl-MEHN-teh", phoneticLatam: "ee-goo-ahl-MEHN-teh", english: "Same to you", partOfSpeech: "adverb", exampleSentenceSpain: "¡Feliz Navidad! Igualmente.", exampleSentenceLatam: "¡Buen día! Igualmente." },
    { word: "no hay problema", spainVariant: "no hay problema", latamVariant: "no hay problema", phoneticSpain: "noh ah-ee proh-BLEH-mah", phoneticLatam: "noh ah-ee proh-BLEH-mah", english: "No problem", partOfSpeech: "phrase", exampleSentenceSpain: "Lo siento. No hay problema.", exampleSentenceLatam: "¿Tardé? No hay problema." },
  ],
  grammarSection: [
    {
      title: "Polite Imperatives & Subjunctive Forms",
      spainContent: "Use formal 'usted' commands: habla (tú), hable (usted). Examples: 'Por favor, habla más lentamente.' vs 'Señor, hable más lentamente.' Both regions maintain formality distinctions.",
      latamContent: "LATAM uses 'tú' for informal contexts more liberally. Formal subjunctive: 'Hable más lentamente, por favor.' No vosotros forms; use ustedes for plural.",
      note: "Spain maintains stricter tú/usted distinction; LATAM blends informality more freely but still respects formal contexts.",
    },
    {
      title: "Question Inversion & Tags",
      spainContent: "Invert subject-verb for questions: '¿Entiendes?' instead of statement 'Entiendes.' Use tag questions: '¿Verdad?' at sentence end.",
      latamContent: "Same inversion rules apply. Tag questions common: '¿Verdad?' or '¿No?' Both regions follow identical syntax.",
      note: "No regional variation in question formation; both use identical inversion patterns.",
    },
  ],
  dialogues: [
    {
      id: "a1-03-dial-01",
      title: "Madrid Train Station - Asking for Help",
      region: "SPAIN",
      setting: "Train station, Madrid",
      lines: [
        { speaker: "Viajero", text: "Disculpe, ¿me ayuda? No entiendo los horarios.", region: "SPAIN", setting: "station" },
        { speaker: "Empleado", text: "Claro, con gusto. ¿A dónde quieres ir?", region: "SPAIN", setting: "station" },
        { speaker: "Viajero", text: "A Barcelona, por favor. ¿Habla más lentamente?", region: "SPAIN", setting: "station" },
        { speaker: "Empleado", text: "Claro. Ba-rce-lo-na. El próximo tren sale a las tres.", region: "SPAIN", setting: "station" },
        { speaker: "Viajero", text: "Gracias, entiendo. ¿Cuánto cuesta el billete?", region: "SPAIN", setting: "station" },
        { speaker: "Empleado", text: "Cuarenta euros. De nada. ¡Buen viaje!", region: "SPAIN", setting: "station" },
      ],
    },
    {
      id: "a1-03-dial-02",
      title: "Barcelona Cafe - Ordering with Politeness",
      region: "SPAIN",
      setting: "Café in Barcelona",
      lines: [
        { speaker: "Camarero", text: "Buenos días. ¿Qué desea?", region: "SPAIN", setting: "café" },
        { speaker: "Cliente", text: "Un café, por favor. Con leche.", region: "SPAIN", setting: "café" },
        { speaker: "Camarero", text: "Un café con leche. ¿Algo más?", region: "SPAIN", setting: "café" },
        { speaker: "Cliente", text: "Sí, un croissant, por favor.", region: "SPAIN", setting: "café" },
        { speaker: "Camarero", text: "Perfecto. Un momento.", region: "SPAIN", setting: "café" },
        { speaker: "Cliente", text: "Gracias. ¡Que disfrutes! Lo siento, ¡que disfrutes tú!", region: "SPAIN", setting: "café" },
      ],
    },
    {
      id: "a1-03-dial-03",
      title: "Valencia Office - Formal Apology",
      region: "SPAIN",
      setting: "Office, Valencia",
      lines: [
        { speaker: "Empleado", text: "Señora López, lo siento. No entiendo las instrucciones.", region: "SPAIN", setting: "office" },
        { speaker: "Jefa", text: "No hay problema. ¿Habla más lentamente? Claro.", region: "SPAIN", setting: "office" },
        { speaker: "Empleado", text: "Gracias. ¿Puedo hacer preguntas?", region: "SPAIN", setting: "office" },
        { speaker: "Jefa", text: "Por supuesto. Adelante.", region: "SPAIN", setting: "office" },
        { speaker: "Empleado", text: "¿Qué dijiste sobre la reunión?", region: "SPAIN", setting: "office" },
        { speaker: "Jefa", text: "La reunión es a las dos. ¿Entiendes ahora?", region: "SPAIN", setting: "office" },
      ],
    },
    {
      id: "a1-03-dial-04",
      title: "Mexico City Street - Tourist Asking Directions",
      region: "LATAM",
      setting: "Mexico City street",
      lines: [
        { speaker: "Turista", text: "Disculpa, ¿me ayudas? No entiendo dónde está el museo.", region: "LATAM", setting: "street" },
        { speaker: "Local", text: "Claro, con gusto. ¿A cuál museo vas?", region: "LATAM", setting: "street" },
        { speaker: "Turista", text: "¿Qué dijiste? Habla más lentamente, por favor.", region: "LATAM", setting: "street" },
        { speaker: "Local", text: "¿A cuál... museo... vas?", region: "LATAM", setting: "street" },
        { speaker: "Turista", text: "Al Museo de Antropología. Gracias.", region: "LATAM", setting: "street" },
        { speaker: "Local", text: "De nada. Tres cuadras, a la derecha. ¡Buen viaje!", region: "LATAM", setting: "street" },
      ],
    },
    {
      id: "a1-03-dial-05",
      title: "Buenos Aires Restaurant - Polite Dining",
      region: "LATAM",
      setting: "Restaurant, Buenos Aires",
      lines: [
        { speaker: "Mesero", text: "Bienvenido. ¿Qué desea?", region: "LATAM", setting: "restaurant" },
        { speaker: "Cliente", text: "Por favor, un bife con ensalada. Gracias.", region: "LATAM", setting: "restaurant" },
        { speaker: "Mesero", text: "Perfecto. ¿Con gusto de vino?", region: "LATAM", setting: "restaurant" },
        { speaker: "Cliente", text: "Sí, un tinto, por favor. Con permiso, ¿cuánto tardará?", region: "LATAM", setting: "restaurant" },
        { speaker: "Mesero", text: "Unos quince minutos. No hay problema.", region: "LATAM", setting: "restaurant" },
        { speaker: "Cliente", text: "Excelente. ¡Gracias! ¡Que disfrutes tú también!", region: "LATAM", setting: "restaurant" },
      ],
    },
    {
      id: "a1-03-dial-06",
      title: "Colombia Bank - Formal Service Interaction",
      region: "LATAM",
      setting: "Bank, Bogotá",
      lines: [
        { speaker: "Cliente", text: "Buenos días. ¿Me ayudas? No entiendo mi cuenta.", region: "LATAM", setting: "bank" },
        { speaker: "Banquero", text: "Claro. Con gusto. ¿Cuál es tu número de cuenta?", region: "LATAM", setting: "bank" },
        { speaker: "Cliente", text: "¿Qué dijiste? Habla más lentamente, por favor.", region: "LATAM", setting: "bank" },
        { speaker: "Banquero", text: "Tu... nú-me-ro... de... cuen-ta.", region: "LATAM", setting: "bank" },
        { speaker: "Cliente", text: "Ah, entiendo. Es 123456789. Gracias.", region: "LATAM", setting: "bank" },
        { speaker: "Banquero", text: "De nada. ¡Buena suerte con tus ahorros!", region: "LATAM", setting: "bank" },
      ],
    },
  ],
  quiz: [
    {
      questionId: "a1-03-q01",
      type: "multiple-choice",
      questionText: "What do you say to someone to apologize?",
      options: ["Gracias", "Lo siento", "De nada", "Por favor"],
      correctAnswer: "Lo siento",
      explanation: "'Lo siento' means 'I'm sorry' and is the correct apology phrase.",
    },
    {
      questionId: "a1-03-q02",
      type: "multiple-choice",
      questionText: "If someone says 'Gracias', what should you respond?",
      options: ["Por favor", "De nada", "Lo siento", "Disculpe"],
      correctAnswer: "De nada",
      explanation: "'De nada' means 'You're welcome' and is the appropriate response to thanks.",
    },
    {
      questionId: "a1-03-q03",
      type: "multiple-choice",
      questionText: "What phrase do you use when you don't understand?",
      options: ["No hay problema", "No entiendo", "Habla más lentamente", "¿Qué dijiste?"],
      correctAnswer: "No entiendo",
      explanation: "'No entiendo' means 'I don't understand' and is the clearest way to express confusion.",
    },
    {
      questionId: "a1-03-q04",
      type: "multiple-choice",
      questionText: "Which phrase means 'with permission' or 'excuse me'?",
      options: ["Disculpe", "Con permiso", "Lo siento", "Por favor"],
      correctAnswer: "Con permiso",
      explanation: "'Con permiso' is used when you need to pass through or excuse yourself politely.",
    },
    {
      questionId: "a1-03-q05",
      type: "multiple-choice",
      questionText: "What do you say to wish someone good luck?",
      options: ["Buena suerte", "Que disfrutes", "Hasta luego", "Bienvenido"],
      correctAnswer: "Buena suerte",
      explanation: "'Buena suerte' means 'good luck' and is used to wish someone well before a challenge.",
    },
  ],
  flashcards: [
    { id: "a1-03-fc01", frontSpain: "por favor", frontLatam: "por favor", backEnglish: "Please", variantDifferenceNote: "Identical", exampleSentenceSpain: "Agua, por favor.", exampleSentenceLatam: "Café, por favor.", partOfSpeech: "phrase" },
    { id: "a1-03-fc02", frontSpain: "gracias", frontLatam: "gracias", backEnglish: "Thank you", variantDifferenceNote: "Identical", exampleSentenceSpain: "Gracias por tu ayuda.", exampleSentenceLatam: "Gracias, muy amable.", partOfSpeech: "interjection" },
    { id: "a1-03-fc03", frontSpain: "de nada", frontLatam: "de nada", backEnglish: "You're welcome", variantDifferenceNote: "Identical", exampleSentenceSpain: "De nada, no es nada.", exampleSentenceLatam: "De nada, para eso estamos.", partOfSpeech: "phrase" },
    { id: "a1-03-fc04", frontSpain: "disculpe", frontLatam: "disculpa", backEnglish: "Excuse me (formal/informal)", variantDifferenceNote: "Spain: disculpe (formal); LATAM: disculpa (informal)", exampleSentenceSpain: "Disculpe, ¿me ayuda?", exampleSentenceLatam: "Disculpa, ¿tienes tiempo?", partOfSpeech: "interjection" },
    { id: "a1-03-fc05", frontSpain: "lo siento", frontLatam: "lo siento", backEnglish: "I'm sorry", variantDifferenceNote: "Identical", exampleSentenceSpain: "Lo siento, fue mi error.", exampleSentenceLatam: "Lo siento mucho.", partOfSpeech: "phrase" },
    { id: "a1-03-fc06", frontSpain: "con permiso", frontLatam: "con permiso", backEnglish: "Excuse me (passing)", variantDifferenceNote: "Identical", exampleSentenceSpain: "Con permiso, necesito pasar.", exampleSentenceLatam: "Con permiso, voy a entrar.", partOfSpeech: "phrase" },
    { id: "a1-03-fc07", frontSpain: "perdón", frontLatam: "perdón", backEnglish: "Pardon/Sorry", variantDifferenceNote: "Identical", exampleSentenceSpain: "Perdón, ¿me entiendes?", exampleSentenceLatam: "Perdón, no oí bien.", partOfSpeech: "interjection" },
    { id: "a1-03-fc08", frontSpain: "¿me ayudas?", frontLatam: "¿me ayudas?", backEnglish: "Can you help me?", variantDifferenceNote: "Identical", exampleSentenceSpain: "¿Me ayudas con esto?", exampleSentenceLatam: "¿Me ayudas, por favor?", partOfSpeech: "question" },
    { id: "a1-03-fc09", frontSpain: "no entiendo", frontLatam: "no entiendo", backEnglish: "I don't understand", variantDifferenceNote: "Identical", exampleSentenceSpain: "No entiendo lo que dices.", exampleSentenceLatam: "No entiendo, repite por favor.", partOfSpeech: "phrase" },
    { id: "a1-03-fc10", frontSpain: "habla más lentamente", frontLatam: "habla más lentamente", backEnglish: "Speak more slowly", variantDifferenceNote: "Identical", exampleSentenceSpain: "¿Puedes hablar más lentamente?", exampleSentenceLatam: "Habla más lentamente, por favor.", partOfSpeech: "phrase" },
    { id: "a1-03-fc11", frontSpain: "¿qué dijiste?", frontLatam: "¿qué dijiste?", backEnglish: "What did you say?", variantDifferenceNote: "Identical", exampleSentenceSpain: "¿Qué dijiste? No oí.", exampleSentenceLatam: "¿Qué dijiste? Repite, por favor.", partOfSpeech: "question" },
    { id: "a1-03-fc12", frontSpain: "bienvenido", frontLatam: "bienvenido", backEnglish: "Welcome", variantDifferenceNote: "Identical; feminine: bienvenida", exampleSentenceSpain: "¡Bienvenido a España!", exampleSentenceLatam: "¡Bienvenida a México!", partOfSpeech: "adjective" },
    { id: "a1-03-fc13", frontSpain: "hasta luego", frontLatam: "hasta luego", backEnglish: "See you later", variantDifferenceNote: "Identical", exampleSentenceSpain: "¡Hasta luego! ¡Fue un placer!", exampleSentenceLatam: "¡Hasta luego, amigo!", partOfSpeech: "phrase" },
    { id: "a1-03-fc14", frontSpain: "hasta pronto", frontLatam: "hasta pronto", backEnglish: "See you soon", variantDifferenceNote: "Identical", exampleSentenceSpain: "¡Hasta pronto!", exampleSentenceLatam: "¡Hasta pronto, compa!", partOfSpeech: "phrase" },
    { id: "a1-03-fc15", frontSpain: "buena suerte", frontLatam: "buena suerte", backEnglish: "Good luck", variantDifferenceNote: "Identical", exampleSentenceSpain: "¡Buena suerte con tu examen!", exampleSentenceLatam: "¡Buena suerte en el trabajo!", partOfSpeech: "phrase" },
    { id: "a1-03-fc16", frontSpain: "que disfrutes", frontLatam: "que disfrutes", backEnglish: "Enjoy", variantDifferenceNote: "Identical", exampleSentenceSpain: "¡Que disfrutes del viaje!", exampleSentenceLatam: "¡Que disfrutes de tu día!", partOfSpeech: "phrase" },
    { id: "a1-03-fc17", frontSpain: "igualmente", frontLatam: "igualmente", backEnglish: "Same to you", variantDifferenceNote: "Identical", exampleSentenceSpain: "¡Feliz Navidad! Igualmente.", exampleSentenceLatam: "¡Buen día! Igualmente.", partOfSpeech: "adverb" },
    { id: "a1-03-fc18", frontSpain: "no hay problema", frontLatam: "no hay problema", backEnglish: "No problem", variantDifferenceNote: "Identical", exampleSentenceSpain: "Lo siento. No hay problema.", exampleSentenceLatam: "¿Tardé? No hay problema.", partOfSpeech: "phrase" },
    { id: "a1-03-fc19", frontSpain: "claro", frontLatam: "claro", backEnglish: "Of course / Clear", variantDifferenceNote: "Identical", exampleSentenceSpain: "Claro que sí.", exampleSentenceLatam: "Claro, con gusto.", partOfSpeech: "interjection" },
    { id: "a1-03-fc20", frontSpain: "entiendo", frontLatam: "entiendo", backEnglish: "I understand", variantDifferenceNote: "Identical", exampleSentenceSpain: "Entiendo perfectamente.", exampleSentenceLatam: "Entiendo, gracias.", partOfSpeech: "verb" },
  ],
  vocabularyJson: [], 
  grammarJson: [], 
  content: "A1.03 Basic Phrases & Politeness" 
};

const LESSON_A1_04 = { 
  id: "a1-04", 
  slug: "family-members", 
  title: "Family Members", 
  description: "Learn vocabulary for family relationships in Spanish.",
  level: "A1", 
  difficulty: "Beginner", 
  order: 4, 
  imageUrl: null, 
  durationMinutes: 45, 
  isPublished: true, 
  vocabularyTable: [
    { word: "familia", spainVariant: "familia", latamVariant: "familia", phoneticSpain: "fah-MEE-lee-ah", phoneticLatam: "fah-MEE-lee-ah", english: "Family", partOfSpeech: "noun", exampleSentenceSpain: "Mi familia es grande.", exampleSentenceLatam: "La familia es importante." },
    { word: "padre", spainVariant: "padre", latamVariant: "padre", phoneticSpain: "PAH-dreh", phoneticLatam: "PAH-dreh", english: "Father", partOfSpeech: "noun", exampleSentenceSpain: "Mi padre trabaja en el banco.", exampleSentenceLatam: "Su padre es médico." },
    { word: "madre", spainVariant: "madre", latamVariant: "madre", phoneticSpain: "MAH-dreh", phoneticLatam: "MAH-dreh", english: "Mother", partOfSpeech: "noun", exampleSentenceSpain: "Mi madre es profesora.", exampleSentenceLatam: "Su madre cocina bien." },
    { word: "hermano", spainVariant: "hermano", latamVariant: "hermano", phoneticSpain: "er-MAH-noh", phoneticLatam: "er-MAH-noh", english: "Brother", partOfSpeech: "noun", exampleSentenceSpain: "Mi hermano es ingeniero.", exampleSentenceLatam: "Tu hermano es muy alto." },
    { word: "hermana", spainVariant: "hermana", latamVariant: "hermana", phoneticSpain: "er-MAH-nah", phoneticLatam: "er-MAH-nah", english: "Sister", partOfSpeech: "noun", exampleSentenceSpain: "Mi hermana estudia medicina.", exampleSentenceLatam: "Tu hermana es inteligente." },
    { word: "hijo/hija", spainVariant: "hijo/hija", latamVariant: "hijo/hija", phoneticSpain: "EE-hoh/EE-hah", phoneticLatam: "EE-hoh/EE-hah", english: "Son/Daughter", partOfSpeech: "noun", exampleSentenceSpain: "Su hijo es abogado.", exampleSentenceLatam: "Mi hija es bailarina." },
    { word: "abuelo", spainVariant: "abuelo", latamVariant: "abuelo", phoneticSpain: "ah-boo-EH-loh", phoneticLatam: "ah-boo-EH-loh", english: "Grandfather", partOfSpeech: "noun", exampleSentenceSpain: "Mi abuelo es jubilado.", exampleSentenceLatam: "Su abuelo tiene ochenta años." },
    { word: "abuela", spainVariant: "abuela", latamVariant: "abuela", phoneticSpain: "ah-boo-EH-lah", phoneticLatam: "ah-boo-EH-lah", english: "Grandmother", partOfSpeech: "noun", exampleSentenceSpain: "Mi abuela hace pasteles.", exampleSentenceLatam: "Tu abuela es muy cariñosa." },
    { word: "tío", spainVariant: "tío", latamVariant: "tío", phoneticSpain: "TEE-oh", phoneticLatam: "TEE-oh", english: "Uncle", partOfSpeech: "noun", exampleSentenceSpain: "Mi tío vive en Barcelona.", exampleSentenceLatam: "Su tío es músico." },
    { word: "tía", spainVariant: "tía", latamVariant: "tía", phoneticSpain: "TEE-ah", phoneticLatam: "TEE-ah", english: "Aunt", partOfSpeech: "noun", exampleSentenceSpain: "Mi tía es dentista.", exampleSentenceLatam: "Tu tía es muy amable." },
    { word: "primo", spainVariant: "primo", latamVariant: "primo", phoneticSpain: "PREE-moh", phoneticLatam: "PREE-moh", english: "Cousin (male)", partOfSpeech: "noun", exampleSentenceSpain: "Mi primo juega fútbol.", exampleSentenceLatam: "Su primo vive en Guadalajara." },
    { word: "prima", spainVariant: "prima", latamVariant: "prima", phoneticSpain: "PREE-mah", phoneticLatam: "PREE-mah", english: "Cousin (female)", partOfSpeech: "noun", exampleSentenceSpain: "Mi prima es ingeniera.", exampleSentenceLatam: "Tu prima es bailarina." },
    { word: "esposo/esposa", spainVariant: "esposo/esposa", latamVariant: "esposo/esposa", phoneticSpain: "es-POH-soh/es-POH-sah", phoneticLatam: "es-POH-soh/es-POH-sah", english: "Husband/Wife", partOfSpeech: "noun", exampleSentenceSpain: "Mi esposo es ingeniero.", exampleSentenceLatam: "Su esposa es doctora." },
    { word: "marido", spainVariant: "marido", latamVariant: "marido", phoneticSpain: "mah-REE-doh", phoneticLatam: "mah-REE-doh", english: "Husband (informal)", partOfSpeech: "noun", exampleSentenceSpain: "Mi marido trabaja aquí.", exampleSentenceLatam: "Su marido es abogado." },
    { word: "novio/novia", spainVariant: "novio/novia", latamVariant: "novio/novia", phoneticSpain: "NOH-vee-oh/NOH-vee-ah", phoneticLatam: "NOH-vee-oh/NOH-vee-ah", english: "Boyfriend/Girlfriend", partOfSpeech: "noun", exampleSentenceSpain: "Mi novio es estudiante.", exampleSentenceLatam: "Tu novia es muy bonita." },
    { word: "sobrino", spainVariant: "sobrino", latamVariant: "sobrino", phoneticSpain: "soh-BREE-noh", phoneticLatam: "soh-BREE-noh", english: "Nephew", partOfSpeech: "noun", exampleSentenceSpain: "Mi sobrino tiene cinco años.", exampleSentenceLatam: "Su sobrino juega al fútbol." },
    { word: "sobrina", spainVariant: "sobrina", latamVariant: "sobrina", phoneticSpain: "soh-BREE-nah", phoneticLatam: "soh-BREE-nah", english: "Niece", partOfSpeech: "noun", exampleSentenceSpain: "Mi sobrina es pianista.", exampleSentenceLatam: "Tu sobrina es inteligente." },
    { word: "suegro", spainVariant: "suegro", latamVariant: "suegro", phoneticSpain: "soo-EH-groh", phoneticLatam: "soo-EH-groh", english: "Father-in-law", partOfSpeech: "noun", exampleSentenceSpain: "Mi suegro es profesor.", exampleSentenceLatam: "Su suegro es amable." },
    { word: "suegra", spainVariant: "suegra", latamVariant: "suegra", phoneticSpain: "soo-EH-grah", phoneticLatam: "soo-EH-grah", english: "Mother-in-law", partOfSpeech: "noun", exampleSentenceSpain: "Mi suegra cocina bien.", exampleSentenceLatam: "Tu suegra es muy cariñosa." },
    { word: "cuñado/cuñada", spainVariant: "cuñado/cuñada", latamVariant: "cuñado/cuñada", phoneticSpain: "koo-NYAH-doh/koo-NYAH-dah", phoneticLatam: "koo-NYAH-doh/koo-NYAH-dah", english: "Brother-in-law/Sister-in-law", partOfSpeech: "noun", exampleSentenceSpain: "Mi cuñado es ingeniero.", exampleSentenceLatam: "Su cuñada es doctora." },
  ],
  grammarSection: [
    {
      title: "Possessive Adjectives with Family",
      spainContent: "Use mi/mis, tu/tus, su/sus, nuestro/a/os/as. Agreement with noun: 'mi padre' (my father), 'mis hermanos' (my brothers). 'Nuestro' is common in Spain.",
      latamContent: "Same rules apply. 'Nuestro' used less frequently in LATAM; preference for 'mi/mis' or 'su/sus'. Spanish: 'Nuestro padre', LATAM often: 'El padre nuestro' or 'Mi padre'.",
      note: "Both regions use identical possessive structures; minor stylistic preference variance in LATAM for nuestro.",
    },
    {
      title: "Gender Agreement in Family Nouns",
      spainContent: "Family words have gender: padre (male), madre (female), hermano (male), hermana (female). Plurals: padres (parents—can include both), hermanos (siblings—can include both).",
      latamContent: "Identical gender rules. Plurals function the same: padres, hermanos, etc. Both regions maintain grammatical gender consistently.",
      note: "No regional variation; both follow identical gender-agreement patterns for family vocabulary.",
    },
  ],
  dialogues: [
    {
      id: "a1-04-dial-01",
      title: "Madrid Lunch - Family Introductions",
      region: "SPAIN",
      setting: "Family lunch, Madrid",
      lines: [
        { speaker: "Madre", text: "Carlos, quiero presentarte a mi hermano, Juan.", region: "SPAIN", setting: "family" },
        { speaker: "Carlos", text: "Mucho gusto, Juan. ¿De dónde eres?", region: "SPAIN", setting: "family" },
        { speaker: "Juan", text: "Soy de Valencia. Trabajo como ingeniero.", region: "SPAIN", setting: "family" },
        { speaker: "Madre", text: "Mi hijo es abogado en Barcelona. Muy inteligente.", region: "SPAIN", setting: "family" },
        { speaker: "Juan", text: "¡Excelente! ¿Tienes familia allá?", region: "SPAIN", setting: "family" },
        { speaker: "Carlos", text: "Sí, mi esposa y dos hijos. ¡Que vengan a visitarnos!", region: "SPAIN", setting: "family" },
      ],
    },
    {
      id: "a1-04-dial-02",
      title: "Barcelona Park - Grandparents with Grandchildren",
      region: "SPAIN",
      setting: "Park, Barcelona",
      lines: [
        { speaker: "Abuelo", text: "¿Cómo estás, mi nieta? ¿Cómo va el colegio?", region: "SPAIN", setting: "park" },
        { speaker: "Nieta", text: "¡Muy bien, abuelo! ¿Dónde está la abuela?", region: "SPAIN", setting: "park" },
        { speaker: "Abuelo", text: "Tu abuela está comprando helado para ti.", region: "SPAIN", setting: "park" },
        { speaker: "Nieto", text: "¡Qué bueno! ¿Abuelo, cuéntame de mis tíos?", region: "SPAIN", setting: "park" },
        { speaker: "Abuelo", text: "Tu tío Juan es doctor, y tu tía María es maestra.", region: "SPAIN", setting: "park" },
        { speaker: "Nieta", text: "¡Interesante! ¿Tienen hijos? Mis primos, ¿dónde están?", region: "SPAIN", setting: "park" },
      ],
    },
    {
      id: "a1-04-dial-03",
      title: "Seville Wedding - Family Celebration",
      region: "SPAIN",
      setting: "Wedding celebration, Seville",
      lines: [
        { speaker: "Novia", text: "Mi esposo es ingeniero. Nos queremos mucho.", region: "SPAIN", setting: "wedding" },
        { speaker: "Suegra", text: "¡Bienvenida a la familia! Mis hijos son muy especiales.", region: "SPAIN", setting: "wedding" },
        { speaker: "Novia", text: "Gracias. Mi familia es grande. Mis hermanos, mis primos...", region: "SPAIN", setting: "wedding" },
        { speaker: "Suegro", text: "¿Tienes hermanos? ¿Cuántos?", region: "SPAIN", setting: "wedding" },
        { speaker: "Novia", text: "Sí, dos hermanas y un hermano. Muy unidos.", region: "SPAIN", setting: "wedding" },
        { speaker: "Suegra", text: "¡Qué maravilloso! Somos una gran familia ahora.", region: "SPAIN", setting: "wedding" },
      ],
    },
    {
      id: "a1-04-dial-04",
      title: "Mexico City Home - Family Dinner",
      region: "LATAM",
      setting: "Family home, Mexico City",
      lines: [
        { speaker: "Madre", text: "¿Cómo estuvo tu día, hijo? ¿Y tu hermana?", region: "LATAM", setting: "family" },
        { speaker: "Hijo", text: "Bien, mamá. Mi hermana llegó tarde de la universidad.", region: "LATAM", setting: "family" },
        { speaker: "Padre", text: "¿Dónde está tu abuelo? Quería hablar con él.", region: "LATAM", setting: "family" },
        { speaker: "Madre", text: "Mi padre está en la sala con los primos. Llegaron hace poco.", region: "LATAM", setting: "family" },
        { speaker: "Hijo", text: "¿Mis primos vinieron? ¿Mis primas también?", region: "LATAM", setting: "family" },
        { speaker: "Madre", text: "Sí, todos vinieron. ¡Qué reunión tan bonita de familia!", region: "LATAM", setting: "family" },
      ],
    },
    {
      id: "a1-04-dial-05",
      title: "Buenos Aires School - Student Talking About Family",
      region: "LATAM",
      setting: "School, Buenos Aires",
      lines: [
        { speaker: "Maestro", text: "Cuéntame de tu familia, Martín.", region: "LATAM", setting: "school" },
        { speaker: "Martín", text: "Mi papá es abogado y mi mamá es enfermera.", region: "LATAM", setting: "school" },
        { speaker: "Maestro", text: "¿Tienes hermanos?", region: "LATAM", setting: "school" },
        { speaker: "Martín", text: "Sí, tengo una hermana menor. Se llama Sofia. Ella tiene ocho años.", region: "LATAM", setting: "school" },
        { speaker: "Maestro", text: "¿Y tus abuelos? ¿Dónde viven?", region: "LATAM", setting: "school" },
        { speaker: "Martín", text: "Mis abuelos viven en La Plata con mis tíos y primos. Muy bonito.", region: "LATAM", setting: "school" },
      ],
    },
    {
      id: "a1-04-dial-06",
      title: "Colombia Restaurant - Celebrating with Extended Family",
      region: "LATAM",
      setting: "Restaurant, Bogotá",
      lines: [
        { speaker: "Tío", text: "¡Qué alegría ver a toda la familia reunida!", region: "LATAM", setting: "restaurant" },
        { speaker: "Sobrina", text: "Sí, tío. Mis primos vinieron de Medellín.", region: "LATAM", setting: "restaurant" },
        { speaker: "Abuela", text: "Mis nietos me ponen tan feliz. ¿Dónde está mi nieta?", region: "LATAM", setting: "restaurant" },
        { speaker: "Madre", text: "Mamá, mi hija está en el baño. Viene enseguida.", region: "LATAM", setting: "restaurant" },
        { speaker: "Cuñado", text: "Esto es vida. Familia y comida. ¡Perfecto!", region: "LATAM", setting: "restaurant" },
        { speaker: "Todos", text: "¡Salud! ¡Por la familia!", region: "LATAM", setting: "restaurant" },
      ],
    },
  ],
  quiz: [
    {
      questionId: "a1-04-q01",
      type: "multiple-choice",
      questionText: "What is the Spanish word for 'mother'?",
      options: ["Padre", "Hermana", "Madre", "Tía"],
      correctAnswer: "Madre",
      explanation: "'Madre' means 'mother' in Spanish.",
    },
    {
      questionId: "a1-04-q02",
      type: "multiple-choice",
      questionText: "Which word means 'brother'?",
      options: ["Hermana", "Hermano", "Primo", "Tío"],
      correctAnswer: "Hermano",
      explanation: "'Hermano' is the Spanish word for 'brother'; 'hermana' is sister.",
    },
    {
      questionId: "a1-04-q03",
      type: "multiple-choice",
      questionText: "What do you call your mother's brother?",
      options: ["Primo", "Tío", "Sobrino", "Abuelo"],
      correctAnswer: "Tío",
      explanation: "'Tío' means 'uncle'; your mother's brother is your uncle.",
    },
    {
      questionId: "a1-04-q04",
      type: "multiple-choice",
      questionText: "The word 'abuela' means:",
      options: ["Grandfather", "Grandmother", "Aunt", "Cousin"],
      correctAnswer: "Grandmother",
      explanation: "'Abuela' is the Spanish word for 'grandmother'; 'abuelo' is grandfather.",
    },
    {
      questionId: "a1-04-q05",
      type: "multiple-choice",
      questionText: "What is a 'primo'?",
      options: ["Sister", "Uncle", "Cousin (male)", "Nephew"],
      correctAnswer: "Cousin (male)",
      explanation: "'Primo' means 'cousin' (male); 'prima' is cousin (female).",
    },
  ],
  flashcards: [
    { id: "a1-04-fc01", frontSpain: "familia", frontLatam: "familia", backEnglish: "Family", variantDifferenceNote: "Identical", exampleSentenceSpain: "Mi familia es grande.", exampleSentenceLatam: "La familia es importante.", partOfSpeech: "noun" },
    { id: "a1-04-fc02", frontSpain: "padre", frontLatam: "padre", backEnglish: "Father", variantDifferenceNote: "Identical", exampleSentenceSpain: "Mi padre trabaja en el banco.", exampleSentenceLatam: "Su padre es médico.", partOfSpeech: "noun" },
    { id: "a1-04-fc03", frontSpain: "madre", frontLatam: "madre", backEnglish: "Mother", variantDifferenceNote: "Identical", exampleSentenceSpain: "Mi madre es profesora.", exampleSentenceLatam: "Su madre cocina bien.", partOfSpeech: "noun" },
    { id: "a1-04-fc04", frontSpain: "hermano", frontLatam: "hermano", backEnglish: "Brother", variantDifferenceNote: "Identical", exampleSentenceSpain: "Mi hermano es ingeniero.", exampleSentenceLatam: "Tu hermano es muy alto.", partOfSpeech: "noun" },
    { id: "a1-04-fc05", frontSpain: "hermana", frontLatam: "hermana", backEnglish: "Sister", variantDifferenceNote: "Identical", exampleSentenceSpain: "Mi hermana estudia medicina.", exampleSentenceLatam: "Tu hermana es inteligente.", partOfSpeech: "noun" },
    { id: "a1-04-fc06", frontSpain: "hijo", frontLatam: "hijo", backEnglish: "Son", variantDifferenceNote: "Identical; feminine: hija", exampleSentenceSpain: "Mi hijo es abogado.", exampleSentenceLatam: "Su hijo es ingeniero.", partOfSpeech: "noun" },
    { id: "a1-04-fc07", frontSpain: "abuelo", frontLatam: "abuelo", backEnglish: "Grandfather", variantDifferenceNote: "Identical", exampleSentenceSpain: "Mi abuelo es jubilado.", exampleSentenceLatam: "Su abuelo tiene ochenta años.", partOfSpeech: "noun" },
    { id: "a1-04-fc08", frontSpain: "abuela", frontLatam: "abuela", backEnglish: "Grandmother", variantDifferenceNote: "Identical", exampleSentenceSpain: "Mi abuela hace pasteles.", exampleSentenceLatam: "Tu abuela es muy cariñosa.", partOfSpeech: "noun" },
    { id: "a1-04-fc09", frontSpain: "tío", frontLatam: "tío", backEnglish: "Uncle", variantDifferenceNote: "Identical", exampleSentenceSpain: "Mi tío vive en Barcelona.", exampleSentenceLatam: "Su tío es músico.", partOfSpeech: "noun" },
    { id: "a1-04-fc10", frontSpain: "tía", frontLatam: "tía", backEnglish: "Aunt", variantDifferenceNote: "Identical", exampleSentenceSpain: "Mi tía es dentista.", exampleSentenceLatam: "Tu tía es muy amable.", partOfSpeech: "noun" },
    { id: "a1-04-fc11", frontSpain: "primo", frontLatam: "primo", backEnglish: "Cousin (male)", variantDifferenceNote: "Identical", exampleSentenceSpain: "Mi primo juega fútbol.", exampleSentenceLatam: "Su primo vive en Guadalajara.", partOfSpeech: "noun" },
    { id: "a1-04-fc12", frontSpain: "prima", frontLatam: "prima", backEnglish: "Cousin (female)", variantDifferenceNote: "Identical", exampleSentenceSpain: "Mi prima es ingeniera.", exampleSentenceLatam: "Tu prima es bailarina.", partOfSpeech: "noun" },
    { id: "a1-04-fc13", frontSpain: "esposo", frontLatam: "esposo", backEnglish: "Husband", variantDifferenceNote: "Identical; LATAM also uses marido", exampleSentenceSpain: "Mi esposo es ingeniero.", exampleSentenceLatam: "Su esposo es doctor.", partOfSpeech: "noun" },
    { id: "a1-04-fc14", frontSpain: "esposa", frontLatam: "esposa", backEnglish: "Wife", variantDifferenceNote: "Identical", exampleSentenceSpain: "Mi esposa es enfermera.", exampleSentenceLatam: "Su esposa es profesora.", partOfSpeech: "noun" },
    { id: "a1-04-fc15", frontSpain: "novio", frontLatam: "novio", backEnglish: "Boyfriend", variantDifferenceNote: "Identical", exampleSentenceSpain: "Mi novio es estudiante.", exampleSentenceLatam: "Su novio es ingeniero.", partOfSpeech: "noun" },
    { id: "a1-04-fc16", frontSpain: "novia", frontLatam: "novia", backEnglish: "Girlfriend", variantDifferenceNote: "Identical", exampleSentenceSpain: "Mi novia es doctora.", exampleSentenceLatam: "Tu novia es muy bonita.", partOfSpeech: "noun" },
    { id: "a1-04-fc17", frontSpain: "sobrino", frontLatam: "sobrino", backEnglish: "Nephew", variantDifferenceNote: "Identical", exampleSentenceSpain: "Mi sobrino tiene cinco años.", exampleSentenceLatam: "Su sobrino juega al fútbol.", partOfSpeech: "noun" },
    { id: "a1-04-fc18", frontSpain: "sobrina", frontLatam: "sobrina", backEnglish: "Niece", variantDifferenceNote: "Identical", exampleSentenceSpain: "Mi sobrina es pianista.", exampleSentenceLatam: "Tu sobrina es inteligente.", partOfSpeech: "noun" },
    { id: "a1-04-fc19", frontSpain: "suegro", frontLatam: "suegro", backEnglish: "Father-in-law", variantDifferenceNote: "Identical", exampleSentenceSpain: "Mi suegro es profesor.", exampleSentenceLatam: "Su suegro es amable.", partOfSpeech: "noun" },
    { id: "a1-04-fc20", frontSpain: "cuñado", frontLatam: "cuñado", backEnglish: "Brother-in-law", variantDifferenceNote: "Identical", exampleSentenceSpain: "Mi cuñado es ingeniero.", exampleSentenceLatam: "Su cuñada es doctora.", partOfSpeech: "noun" },
  ],
  vocabularyJson: [], 
  grammarJson: [], 
  content: "A1.04 Family Members" 
};

const LESSON_A1_05 = { 
  id: "a1-05", 
  slug: "colors-basic", 
  title: "Colors & Basic Descriptions", 
  description: "Learn colors and simple descriptive adjectives.",
  level: "A1", 
  difficulty: "Beginner", 
  order: 5, 
  imageUrl: null, 
  durationMinutes: 45, 
  isPublished: true, 
  vocabularyTable: [
    { word: "rojo", spainVariant: "rojo", latamVariant: "rojo", phoneticSpain: "ROH-hoh", phoneticLatam: "ROH-hoh", english: "Red", partOfSpeech: "adjective", exampleSentenceSpain: "La casa es roja.", exampleSentenceLatam: "El coche es rojo." },
    { word: "azul", spainVariant: "azul", latamVariant: "azul", phoneticSpain: "ah-SOOL", phoneticLatam: "ah-SOOL", english: "Blue", partOfSpeech: "adjective", exampleSentenceSpain: "El cielo es azul.", exampleSentenceLatam: "La puerta es azul." },
    { word: "amarillo", spainVariant: "amarillo", latamVariant: "amarillo", phoneticSpain: "ah-mah-REE-yoh", phoneticLatam: "ah-mah-REE-yoh", english: "Yellow", partOfSpeech: "adjective", exampleSentenceSpain: "La flor es amarilla.", exampleSentenceLatam: "El sol es amarillo." },
    { word: "verde", spainVariant: "verde", latamVariant: "verde", phoneticSpain: "BER-deh", phoneticLatam: "BER-deh", english: "Green", partOfSpeech: "adjective", exampleSentenceSpain: "El árbol es verde.", exampleSentenceLatam: "El pasto es verde." },
    { word: "negro", spainVariant: "negro", latamVariant: "negro", phoneticSpain: "NEH-groh", phoneticLatam: "NEH-groh", english: "Black", partOfSpeech: "adjective", exampleSentenceSpain: "El gato es negro.", exampleSentenceLatam: "El pelo es negro." },
    { word: "blanco", spainVariant: "blanco", latamVariant: "blanco", phoneticSpain: "BLAHN-koh", phoneticLatam: "BLAHN-koh", english: "White", partOfSpeech: "adjective", exampleSentenceSpain: "La nieve es blanca.", exampleSentenceLatam: "El algodón es blanco." },
    { word: "rosa", spainVariant: "rosa", latamVariant: "rosa", phoneticSpain: "ROH-sah", phoneticLatam: "ROH-sah", english: "Pink", partOfSpeech: "adjective", exampleSentenceSpain: "La flor es rosa.", exampleSentenceLatam: "El vestido es rosa." },
    { word: "gris", spainVariant: "gris", latamVariant: "gris", phoneticSpain: "grees", phoneticLatam: "grees", english: "Gray", partOfSpeech: "adjective", exampleSentenceSpain: "El edificio es gris.", exampleSentenceLatam: "El cielo es gris hoy." },
    { word: "naranja", spainVariant: "naranja", latamVariant: "naranja", phoneticSpain: "nah-RAHN-hah", phoneticLatam: "nah-RAHN-hah", english: "Orange (color/fruit)", partOfSpeech: "noun/adjective", exampleSentenceSpain: "La naranja es grande.", exampleSentenceLatam: "El color naranja me gusta." },
    { word: "marrón", spainVariant: "marrón", latamVariant: "café", phoneticSpain: "mah-RROHN", phoneticLatam: "kah-FEH", english: "Brown", partOfSpeech: "adjective", exampleSentenceSpain: "La puerta es marrón.", exampleSentenceLatam: "El chocolate es café." },
    { word: "grande", spainVariant: "grande", latamVariant: "grande", phoneticSpain: "GRAHN-deh", phoneticLatam: "GRAHN-deh", english: "Big/Large", partOfSpeech: "adjective", exampleSentenceSpain: "La casa es grande.", exampleSentenceLatam: "El coche es grande." },
    { word: "pequeño", spainVariant: "pequeño", latamVariant: "pequeño", phoneticSpain: "peh-KEN-yoh", phoneticLatam: "peh-KEN-yoh", english: "Small", partOfSpeech: "adjective", exampleSentenceSpain: "El gato es pequeño.", exampleSentenceLatam: "La casa es pequeña." },
    { word: "largo", spainVariant: "largo", latamVariant: "largo", phoneticSpain: "LAHR-goh", phoneticLatam: "LAHR-goh", english: "Long", partOfSpeech: "adjective", exampleSentenceSpain: "El pelo es largo.", exampleSentenceLatam: "La mesa es larga." },
    { word: "corto", spainVariant: "corto", latamVariant: "corto", phoneticSpain: "KOR-toh", phoneticLatam: "KOR-toh", english: "Short", partOfSpeech: "adjective", exampleSentenceSpain: "El cabello es corto.", exampleSentenceLatam: "El viaje es corto." },
    { word: "bonito", spainVariant: "bonito", latamVariant: "bonito", phoneticSpain: "boh-NEE-toh", phoneticLatam: "boh-NEE-toh", english: "Beautiful/Pretty", partOfSpeech: "adjective", exampleSentenceSpain: "La casa es bonita.", exampleSentenceLatam: "El día es bonito." },
    { word: "feo", spainVariant: "feo", latamVariant: "feo", phoneticSpain: "FEH-oh", phoneticLatam: "FEH-oh", english: "Ugly", partOfSpeech: "adjective", exampleSentenceSpain: "No es feo.", exampleSentenceLatam: "El edificio es feo." },
    { word: "nuevo", spainVariant: "nuevo", latamVariant: "nuevo", phoneticSpain: "noo-EH-voh", phoneticLatam: "noo-EH-voh", english: "New", partOfSpeech: "adjective", exampleSentenceSpain: "El coche es nuevo.", exampleSentenceLatam: "La casa es nueva." },
    { word: "viejo", spainVariant: "viejo", latamVariant: "viejo", phoneticSpain: "vee-EH-hoh", phoneticLatam: "vee-EH-hoh", english: "Old", partOfSpeech: "adjective", exampleSentenceSpain: "El libro es viejo.", exampleSentenceLatam: "La iglesia es vieja." },
    { word: "joven", spainVariant: "joven", latamVariant: "joven", phoneticSpain: "HOH-ven", phoneticLatam: "HOH-ven", english: "Young", partOfSpeech: "adjective", exampleSentenceSpain: "El hombre es joven.", exampleSentenceLatam: "La mujer es joven." },
    { word: "lindo", spainVariant: "lindo", latamVariant: "lindo", phoneticSpain: "LEEN-doh", phoneticLatam: "LEEN-doh", english: "Pretty/Nice", partOfSpeech: "adjective", exampleSentenceSpain: "El día es lindo.", exampleSentenceLatam: "El tiempo es lindo." },
  ],
  grammarSection: [
    {
      title: "Color Agreement with Nouns",
      spainContent: "Colors agree with noun gender: 'el libro rojo' (red book—masculine), 'la casa roja' (red house—feminine). Exception: naranja, rosa, marrón don't change: 'los libros naranja' (orange books).",
      latamContent: "Identical agreement rules. LATAM uses 'café' instead of 'marrón' for brown: 'la casa café'. Otherwise, same gender agreement patterns as Spain.",
      note: "Both regions follow identical gender agreement; LATAM uses café vs marrón as regional vocabulary choice.",
    },
    {
      title: "Adjective Position & Agreement",
      spainContent: "Most descriptive adjectives follow nouns in Spanish: 'la casa grande' (the big house). Adjectives must agree in gender and number: 'las casas grandes'.",
      latamContent: "Same position rules: adjective after noun. Same gender/number agreement requirements. No regional variation in word order.",
      note: "Both regions maintain identical adjective positioning after nouns and gender/number agreement.",
    },
  ],
  dialogues: [
    {
      id: "a1-05-dial-01",
      title: "Madrid Clothing Store - Describing Colors",
      region: "SPAIN",
      setting: "Clothing store, Madrid",
      lines: [
        { speaker: "Vendedor", text: "¿Qué color prefieres? Tenemos rojo, azul, verde...", region: "SPAIN", setting: "store" },
        { speaker: "Cliente", text: "Me gusta el vestido azul. ¿Es grande?", region: "SPAIN", setting: "store" },
        { speaker: "Vendedor", text: "Sí, es grande. También tenemos uno más pequeño.", region: "SPAIN", setting: "store" },
        { speaker: "Cliente", text: "¿De qué color es el pequeño?", region: "SPAIN", setting: "store" },
        { speaker: "Vendedor", text: "Es rojo. Muy bonito. ¿Quieres probarte los dos?", region: "SPAIN", setting: "store" },
        { speaker: "Cliente", text: "Sí, por favor. El azul es nuevo, ¿verdad?", region: "SPAIN", setting: "store" },
      ],
    },
    {
      id: "a1-05-dial-02",
      title: "Barcelona Artist - Describing Paintings",
      region: "SPAIN",
      setting: "Art gallery, Barcelona",
      lines: [
        { speaker: "Artista", text: "Este cuadro es muy bonito. Los colores son hermosos.", region: "SPAIN", setting: "gallery" },
        { speaker: "Visitante", text: "Sí, me encanta. ¿Cuáles son los colores principales?", region: "SPAIN", setting: "gallery" },
        { speaker: "Artista", text: "Es principalmente rojo, azul y blanco. Un poco de negro.", region: "SPAIN", setting: "gallery" },
        { speaker: "Visitante", text: "¿Es un cuadro nuevo?", region: "SPAIN", setting: "gallery" },
        { speaker: "Artista", text: "Sí, lo pinté hace poco. La composición es grande.", region: "SPAIN", setting: "gallery" },
        { speaker: "Visitante", text: "Es muy lindo. ¿Cuánto cuesta?", region: "SPAIN", setting: "gallery" },
      ],
    },
    {
      id: "a1-05-dial-03",
      title: "Seville House Decoration - Interior Design",
      region: "SPAIN",
      setting: "Home decoration shop, Seville",
      lines: [
        { speaker: "Decorador", text: "¿Te gusta esta decoración? Las flores son amarillas.", region: "SPAIN", setting: "shop" },
        { speaker: "Cliente", text: "Sí, es bonita. Pero prefiero colores más oscuros. ¿Tienes gris?", region: "SPAIN", setting: "shop" },
        { speaker: "Decorador", text: "Claro. Tenemos gris oscuro. También rosa y naranja.", region: "SPAIN", setting: "shop" },
        { speaker: "Cliente", text: "El gris es bonito. ¿Es grande la maceta?", region: "SPAIN", setting: "shop" },
        { speaker: "Decorador", text: "Sí, es grande. Hay una pequeña también. ¿Cuál prefieres?", region: "SPAIN", setting: "shop" },
        { speaker: "Cliente", text: "La pequeña es mejor. Es perfecta para mi casa.", region: "SPAIN", setting: "shop" },
      ],
    },
    {
      id: "a1-05-dial-04",
      title: "Mexico City Fashion - Choosing an Outfit",
      region: "LATAM",
      setting: "Fashion store, Mexico City",
      lines: [
        { speaker: "Vendedor", text: "¿Qué color te gusta? ¿Rojo, azul, verde?", region: "LATAM", setting: "store" },
        { speaker: "Cliente", text: "Me gusta el rojo. Es bonito. ¿Tienes uno pequeño?", region: "LATAM", setting: "store" },
        { speaker: "Vendedor", text: "Sí, tenemos rojo pequeño y también grande.", region: "LATAM", setting: "store" },
        { speaker: "Cliente", text: "¿Es nuevo el rojo?", region: "LATAM", setting: "store" },
        { speaker: "Vendedor", text: "Sí, es muy nuevo. También tenemos rosa y naranja.", region: "LATAM", setting: "store" },
        { speaker: "Cliente", text: "El rojo es hermoso. Me lo llevo. ¡Gracias!", region: "LATAM", setting: "store" },
      ],
    },
    {
      id: "a1-05-dial-05",
      title: "Buenos Aires Car Lot - Selecting a Vehicle",
      region: "LATAM",
      setting: "Car dealership, Buenos Aires",
      lines: [
        { speaker: "Vendedor", text: "¿Qué color de auto te gusta? Tenemos negro, blanco, café...", region: "LATAM", setting: "lot" },
        { speaker: "Cliente", text: "Me gusta el negro. ¿Es nuevo? ¿Es grande?", region: "LATAM", setting: "lot" },
        { speaker: "Vendedor", text: "Sí, es nuevo y grande. También hay uno más pequeño en azul.", region: "LATAM", setting: "lot" },
        { speaker: "Cliente", text: "¿El azul es joven o viejo?", region: "LATAM", setting: "lot" },
        { speaker: "Vendedor", text: "El azul es nuevo también. Ambos son hermosos.", region: "LATAM", setting: "lot" },
        { speaker: "Cliente", text: "Prefiero el negro. ¿Cuánto cuesta?", region: "LATAM", setting: "lot" },
      ],
    },
    {
      id: "a1-05-dial-06",
      title: "Colombia School - Art Class",
      region: "LATAM",
      setting: "School art class, Bogotá",
      lines: [
        { speaker: "Maestra", text: "¿Cuál es tu color favorito? ¿Rojo, azul, verde?", region: "LATAM", setting: "school" },
        { speaker: "Estudiante", text: "Me gusta el azul. Es bonito. ¿Y a ti, maestra?", region: "LATAM", setting: "school" },
        { speaker: "Maestra", text: "A mí me gusta el verde. Es el color de la naturaleza.", region: "LATAM", setting: "school" },
        { speaker: "Otro Estudiante", text: "¿El amarillo es bonito también?", region: "LATAM", setting: "school" },
        { speaker: "Maestra", text: "Claro. El amarillo es alegre. ¿Lo usas en tu dibujo?", region: "LATAM", setting: "school" },
        { speaker: "Otro Estudiante", text: "Sí, para el sol. El sol es amarillo y grande.", region: "LATAM", setting: "school" },
      ],
    },
  ],
  quiz: [
    {
      questionId: "a1-05-q01",
      type: "multiple-choice",
      questionText: "What is the Spanish word for 'blue'?",
      options: ["Rojo", "Verde", "Azul", "Negro"],
      correctAnswer: "Azul",
      explanation: "'Azul' is the Spanish word for 'blue'.",
    },
    {
      questionId: "a1-05-q02",
      type: "multiple-choice",
      questionText: "Which color means 'black'?",
      options: ["Blanco", "Gris", "Negro", "Azul"],
      correctAnswer: "Negro",
      explanation: "'Negro' means 'black' in Spanish.",
    },
    {
      questionId: "a1-05-q03",
      type: "multiple-choice",
      questionText: "If a house is described as 'bonita', what does that mean?",
      options: ["Old", "Beautiful/Pretty", "Big", "Small"],
      correctAnswer: "Beautiful/Pretty",
      explanation: "'Bonita' means 'beautiful' or 'pretty' in Spanish.",
    },
    {
      questionId: "a1-05-q04",
      type: "multiple-choice",
      questionText: "What does 'pequeño' mean?",
      options: ["Big", "Small", "Long", "Short"],
      correctAnswer: "Small",
      explanation: "'Pequeño' means 'small' in Spanish.",
    },
    {
      questionId: "a1-05-q05",
      type: "multiple-choice",
      questionText: "In Spanish, 'nuevo' means:",
      options: ["Old", "New", "Nice", "Ugly"],
      correctAnswer: "New",
      explanation: "'Nuevo' means 'new' in Spanish; 'viejo' means 'old'.",
    },
  ],
  flashcards: [
    { id: "a1-05-fc01", frontSpain: "rojo", frontLatam: "rojo", backEnglish: "Red", variantDifferenceNote: "Identical", exampleSentenceSpain: "La casa es roja.", exampleSentenceLatam: "El coche es rojo.", partOfSpeech: "adjective" },
    { id: "a1-05-fc02", frontSpain: "azul", frontLatam: "azul", backEnglish: "Blue", variantDifferenceNote: "Identical", exampleSentenceSpain: "El cielo es azul.", exampleSentenceLatam: "La puerta es azul.", partOfSpeech: "adjective" },
    { id: "a1-05-fc03", frontSpain: "amarillo", frontLatam: "amarillo", backEnglish: "Yellow", variantDifferenceNote: "Identical", exampleSentenceSpain: "La flor es amarilla.", exampleSentenceLatam: "El sol es amarillo.", partOfSpeech: "adjective" },
    { id: "a1-05-fc04", frontSpain: "verde", frontLatam: "verde", backEnglish: "Green", variantDifferenceNote: "Identical", exampleSentenceSpain: "El árbol es verde.", exampleSentenceLatam: "El pasto es verde.", partOfSpeech: "adjective" },
    { id: "a1-05-fc05", frontSpain: "negro", frontLatam: "negro", backEnglish: "Black", variantDifferenceNote: "Identical", exampleSentenceSpain: "El gato es negro.", exampleSentenceLatam: "El pelo es negro.", partOfSpeech: "adjective" },
    { id: "a1-05-fc06", frontSpain: "blanco", frontLatam: "blanco", backEnglish: "White", variantDifferenceNote: "Identical", exampleSentenceSpain: "La nieve es blanca.", exampleSentenceLatam: "El algodón es blanco.", partOfSpeech: "adjective" },
    { id: "a1-05-fc07", frontSpain: "gris", frontLatam: "gris", backEnglish: "Gray", variantDifferenceNote: "Identical", exampleSentenceSpain: "El edificio es gris.", exampleSentenceLatam: "El cielo es gris hoy.", partOfSpeech: "adjective" },
    { id: "a1-05-fc08", frontSpain: "marrón", frontLatam: "café", backEnglish: "Brown", variantDifferenceNote: "Spain: marrón; LATAM: café", exampleSentenceSpain: "La puerta es marrón.", exampleSentenceLatam: "El chocolate es café.", partOfSpeech: "adjective" },
    { id: "a1-05-fc09", frontSpain: "rosa", frontLatam: "rosa", backEnglish: "Pink", variantDifferenceNote: "Identical", exampleSentenceSpain: "La flor es rosa.", exampleSentenceLatam: "El vestido es rosa.", partOfSpeech: "adjective" },
    { id: "a1-05-fc10", frontSpain: "naranja", frontLatam: "naranja", backEnglish: "Orange", variantDifferenceNote: "Identical", exampleSentenceSpain: "La naranja es redonda.", exampleSentenceLatam: "El color naranja es bonito.", partOfSpeech: "noun/adjective" },
    { id: "a1-05-fc11", frontSpain: "grande", frontLatam: "grande", backEnglish: "Big/Large", variantDifferenceNote: "Identical", exampleSentenceSpain: "La casa es grande.", exampleSentenceLatam: "El coche es grande.", partOfSpeech: "adjective" },
    { id: "a1-05-fc12", frontSpain: "pequeño", frontLatam: "pequeño", backEnglish: "Small", variantDifferenceNote: "Identical", exampleSentenceSpain: "El gato es pequeño.", exampleSentenceLatam: "La casa es pequeña.", partOfSpeech: "adjective" },
    { id: "a1-05-fc13", frontSpain: "largo", frontLatam: "largo", backEnglish: "Long", variantDifferenceNote: "Identical", exampleSentenceSpain: "El pelo es largo.", exampleSentenceLatam: "La mesa es larga.", partOfSpeech: "adjective" },
    { id: "a1-05-fc14", frontSpain: "corto", frontLatam: "corto", backEnglish: "Short", variantDifferenceNote: "Identical", exampleSentenceSpain: "El cabello es corto.", exampleSentenceLatam: "El viaje es corto.", partOfSpeech: "adjective" },
    { id: "a1-05-fc15", frontSpain: "bonito", frontLatam: "bonito", backEnglish: "Beautiful/Pretty", variantDifferenceNote: "Identical", exampleSentenceSpain: "La casa es bonita.", exampleSentenceLatam: "El día es bonito.", partOfSpeech: "adjective" },
    { id: "a1-05-fc16", frontSpain: "feo", frontLatam: "feo", backEnglish: "Ugly", variantDifferenceNote: "Identical", exampleSentenceSpain: "No es feo.", exampleSentenceLatam: "El edificio es feo.", partOfSpeech: "adjective" },
    { id: "a1-05-fc17", frontSpain: "nuevo", frontLatam: "nuevo", backEnglish: "New", variantDifferenceNote: "Identical", exampleSentenceSpain: "El coche es nuevo.", exampleSentenceLatam: "La casa es nueva.", partOfSpeech: "adjective" },
    { id: "a1-05-fc18", frontSpain: "viejo", frontLatam: "viejo", backEnglish: "Old", variantDifferenceNote: "Identical", exampleSentenceSpain: "El libro es viejo.", exampleSentenceLatam: "La iglesia es vieja.", partOfSpeech: "adjective" },
    { id: "a1-05-fc19", frontSpain: "joven", frontLatam: "joven", backEnglish: "Young", variantDifferenceNote: "Identical", exampleSentenceSpain: "El hombre es joven.", exampleSentenceLatam: "La mujer es joven.", partOfSpeech: "adjective" },
    { id: "a1-05-fc20", frontSpain: "lindo", frontLatam: "lindo", backEnglish: "Pretty/Nice", variantDifferenceNote: "Identical", exampleSentenceSpain: "El día es lindo.", exampleSentenceLatam: "El tiempo es lindo.", partOfSpeech: "adjective" },
  ],
  vocabularyJson: [], 
  grammarJson: [], 
  content: "A1.05 Colors & Basic Descriptions" 
};

const LESSON_A1_06 = { id: "a1-06", slug: "body-parts", title: "Body Parts", description: "Vocabulary for parts of the human body.", level: "A1", difficulty: "Beginner", order: 6, imageUrl: null, durationMinutes: 45, isPublished: true, vocabularyTable: [], grammarSection: [], dialogues: [], quiz: [], flashcards: [], vocabularyJson: [], grammarJson: [], content: "A1.06" };

const LESSON_A1_07 = { id: "a1-07", slug: "food-drinks", title: "Food & Drinks", description: "Common food and beverage vocabulary.", level: "A1", difficulty: "Beginner", order: 7, imageUrl: null, durationMinutes: 45, isPublished: true, vocabularyTable: [], grammarSection: [], dialogues: [], quiz: [], flashcards: [], vocabularyJson: [], grammarJson: [], content: "A1.07" };

const LESSON_A1_08 = { id: "a1-08", slug: "clothing", title: "Clothing & Accessories", description: "Vocabulary for clothes and accessories.", level: "A1", difficulty: "Beginner", order: 8, imageUrl: null, durationMinutes: 45, isPublished: true, vocabularyTable: [], grammarSection: [], dialogues: [], quiz: [], flashcards: [], vocabularyJson: [], grammarJson: [], content: "A1.08" };

const LESSON_A1_09 = { id: "a1-09", slug: "places-locations", title: "Places & Locations", description: "Basic vocabulary for places and directions.", level: "A1", difficulty: "Beginner", order: 9, imageUrl: null, durationMinutes: 45, isPublished: true, vocabularyTable: [], grammarSection: [], dialogues: [], quiz: [], flashcards: [], vocabularyJson: [], grammarJson: [], content: "A1.09" };

const LESSON_A1_10 = { id: "a1-10", slug: "daily-activities", title: "Daily Activities", description: "Common verbs and daily routine vocabulary.", level: "A1", difficulty: "Beginner", order: 10, imageUrl: null, durationMinutes: 45, isPublished: true, vocabularyTable: [], grammarSection: [], dialogues: [], quiz: [], flashcards: [], vocabularyJson: [], grammarJson: [], content: "A1.10" };

export const A1_LESSONS = [
  LESSON_A1_01,
  LESSON_A1_02,
  LESSON_A1_03,
  LESSON_A1_04,
  LESSON_A1_05,
  LESSON_A1_06,
  LESSON_A1_07,
  LESSON_A1_08,
  LESSON_A1_09,
  LESSON_A1_10,
];