import type { LessonData } from "./lessons-data";

const LESSON_A2_01 = {
  id: "a2-01",
  slug: "present-tense-verbs",
  title: "Present Tense & Regular Verbs",
  description: "Master regular verb conjugation in present tense across Spain and LATAM contexts.",
  level: "A2",
  difficulty: "Elementary",
  order: 1,
  imageUrl: null,
  durationMinutes: 50,
  isPublished: true,
  vocabularyTable: [
    { word: "hablar", spainVariant: "hablar", latamVariant: "hablar", phoneticSpain: "ah-BLAHR", phoneticLatam: "ah-BLAHR", english: "To speak", partOfSpeech: "verb", exampleSentenceSpain: "Hablo español con mis amigos.", exampleSentenceLatam: "Hablo español todos los días." },
    { word: "entender", spainVariant: "entender", latamVariant: "entender", phoneticSpain: "en-ten-DEHR", phoneticLatam: "en-ten-DEHR", english: "To understand", partOfSpeech: "verb", exampleSentenceSpain: "Entiendo la lección.", exampleSentenceLatam: "Entiendo perfectamente." },
    { word: "escribir", spainVariant: "escribir", latamVariant: "escribir", phoneticSpain: "es-kree-BEER", phoneticLatam: "es-kree-BEER", english: "To write", partOfSpeech: "verb", exampleSentenceSpain: "Escribo cartas en español.", exampleSentenceLatam: "Escribimos emails." },
    { word: "leer", spainVariant: "leer", latamVariant: "leer", phoneticSpain: "leh-EHR", phoneticLatam: "leh-EHR", english: "To read", partOfSpeech: "verb", exampleSentenceSpain: "Leo libros en español.", exampleSentenceLatam: "Leen periódicos." },
    { word: "vivir", spainVariant: "vivir", latamVariant: "vivir", phoneticSpain: "vee-BEER", phoneticLatam: "vee-BEER", english: "To live", partOfSpeech: "verb", exampleSentenceSpain: "Vivo en Madrid.", exampleSentenceLatam: "Viven en México." },
    { word: "aprender", spainVariant: "aprender", latamVariant: "aprender", phoneticSpain: "ah-pren-DEHR", phoneticLatam: "ah-pren-DEHR", english: "To learn", partOfSpeech: "verb", exampleSentenceSpain: "Aprendo español rápidamente.", exampleSentenceLatam: "Aprendemos juntos." },
    { word: "abrir", spainVariant: "abrir", latamVariant: "abrir", phoneticSpain: "ah-BREER", phoneticLatam: "ah-BREER", english: "To open", partOfSpeech: "verb", exampleSentenceSpain: "Abro la puerta.", exampleSentenceLatam: "Abre la ventana." },
    { word: "buscar", spainVariant: "buscar", latamVariant: "buscar", phoneticSpain: "boos-KAHR", phoneticLatam: "boos-KAHR", english: "To search/look for", partOfSpeech: "verb", exampleSentenceSpain: "Busco mis llaves.", exampleSentenceLatam: "Buscan el restaurante." },
    { word: "encontrar", spainVariant: "encontrar", latamVariant: "encontrar", phoneticSpain: "en-kohn-TRAHR", phoneticLatam: "en-kohn-TRAHR", english: "To find", partOfSpeech: "verb", exampleSentenceSpain: "Encuentro lo que busco.", exampleSentenceLatam: "Encontramos la casa." },
    { word: "esperar", spainVariant: "esperar", latamVariant: "esperar", phoneticSpain: "es-peh-RAHR", phoneticLatam: "es-peh-RAHR", english: "To wait/hope", partOfSpeech: "verb", exampleSentenceSpain: "Espero en la estación.", exampleSentenceLatam: "Esperamos a nuestros amigos." },
    { word: "pensar", spainVariant: "pensar", latamVariant: "pensar", phoneticSpain: "pen-SAHR", phoneticLatam: "pen-SAHR", english: "To think", partOfSpeech: "verb", exampleSentenceSpain: "Pienso que es correcto.", exampleSentenceLatam: "Piensan diferente." },
    { word: "querer", spainVariant: "querer", latamVariant: "querer", phoneticSpain: "keh-REHR", phoneticLatam: "keh-REHR", english: "To want", partOfSpeech: "verb", exampleSentenceSpain: "Quiero aprender más.", exampleSentenceLatam: "Queremos viajar." },
    { word: "poder", spainVariant: "poder", latamVariant: "poder", phoneticSpain: "poh-DEHR", phoneticLatam: "poh-DEHR", english: "Can/To be able", partOfSpeech: "verb", exampleSentenceSpain: "Puedo hablar español.", exampleSentenceLatam: "Pueden venir mañana." },
    { word: "tener", spainVariant: "tener", latamVariant: "tener", phoneticSpain: "teh-NEHR", phoneticLatam: "teh-NEHR", english: "To have", partOfSpeech: "verb", exampleSentenceSpain: "Tengo un gato.", exampleSentenceLatam: "Tienen dos hijos." },
    { word: "estar", spainVariant: "estar", latamVariant: "estar", phoneticSpain: "es-TAHR", phoneticLatam: "es-TAHR", english: "To be (location/state)", partOfSpeech: "verb", exampleSentenceSpain: "Estoy en la biblioteca.", exampleSentenceLatam: "Están felices." },
    { word: "ser", spainVariant: "ser", latamVariant: "ser", phoneticSpain: "sehr", phoneticLatam: "sehr", english: "To be (identity)", partOfSpeech: "verb", exampleSentenceSpain: "Soy ingeniero.", exampleSentenceLatam: "Son españoles." },
    { word: "ir", spainVariant: "ir", latamVariant: "ir", phoneticSpain: "eer", phoneticLatam: "eer", english: "To go", partOfSpeech: "verb", exampleSentenceSpain: "Voy al cine.", exampleSentenceLatam: "Van al mercado." },
    { word: "hacer", spainVariant: "hacer", latamVariant: "hacer", phoneticSpain: "ah-SEHR", phoneticLatam: "ah-SEHR", english: "To do/make", partOfSpeech: "verb", exampleSentenceSpain: "Hago mis deberes.", exampleSentenceLatam: "Hacen una torta." },
    { word: "dar", spainVariant: "dar", latamVariant: "dar", phoneticSpain: "dahr", phoneticLatam: "dahr", english: "To give", partOfSpeech: "verb", exampleSentenceSpain: "Doy un regalo.", exampleSentenceLatam: "Dan instrucciones." },
    { word: "venir", spainVariant: "venir", latamVariant: "venir", phoneticSpain: "veh-NEER", phoneticLatam: "veh-NEER", english: "To come", partOfSpeech: "verb", exampleSentenceSpain: "Vengo a las tres.", exampleSentenceLatam: "Vienen mañana." },
  ],
  grammarSection: [
    {
      title: "Regular Verb Conjugation (-AR, -ER, -IR)",
      spainContent: "Regular verbs follow predictable patterns: HABLAR (yo hablo, tú hablas, él/ella habla, nosotros hablamos, vosotros habláis, ellos hablan). Learn one pattern, apply to all -AR verbs.",
      latamContent: "LATAM omits vosotros form; uses ustedes for plural 'you'. Conjugation: yo hablo, tú hablas, él/ella habla, nosotros hablamos, ustedes hablan, ellos hablan.",
      note: "Spain includes vosotros; LATAM skips it. Otherwise identical.",
    },
    {
      title: "Irregular Verbs (SER, ESTAR, IR, HACER, TENER)",
      spainContent: "Common irregular verbs don't follow patterns: SER (soy, eres, es, somos, sois, son), ESTAR (estoy, estás, está, estamos, estáis, están), IR (voy, vas, va, vamos, vais, van).",
      latamContent: "Same irregular patterns; LATAM drops vosotros. Examples: yo soy, tú eres, nosotros somos, ustedes son.",
      note: "Irregular verb stems are identical; only vosotros differs between regions.",
    },
  ],
  dialogues: [
    {
      id: "a2-01-dial-01",
      title: "Madrid Language Class",
      region: "SPAIN",
      setting: "Classroom, Madrid",
      lines: [
        { speaker: "Profesor", text: "¿Hablas español en casa?", region: "SPAIN", setting: "classroom" },
        { speaker: "Estudiante", text: "Sí, hablo con mi familia. Entiendo más cada día.", region: "SPAIN", setting: "classroom" },
        { speaker: "Profesor", text: "¿Qué escribes? ¿Cartas?", region: "SPAIN", setting: "classroom" },
        { speaker: "Estudiante", text: "Escribo emails y apuntes. Leo libros también.", region: "SPAIN", setting: "classroom" },
        { speaker: "Profesor", text: "¿Vives cerca de aquí?", region: "SPAIN", setting: "classroom" },
        { speaker: "Estudiante", text: "Sí, vivo a cinco minutos. Es muy conveniente.", region: "SPAIN", setting: "classroom" },
      ],
    },
    {
      id: "a2-01-dial-02",
      title: "Barcelona Library",
      region: "SPAIN",
      setting: "Library, Barcelona",
      lines: [
        { speaker: "Bibliotecario", text: "¿Buscas algún libro?", region: "SPAIN", setting: "library" },
        { speaker: "Cliente", text: "Sí, busco novelas españolas. ¿Las tienes?", region: "SPAIN", setting: "library" },
        { speaker: "Bibliotecario", text: "Encontramos muchas. ¿Qué tipo?", region: "SPAIN", setting: "library" },
        { speaker: "Cliente", text: "Quiero leer clásicos. Pienso que son importantes.", region: "SPAIN", setting: "library" },
        { speaker: "Bibliotecario", text: "Tenemos García Lorca y Cervantes.", region: "SPAIN", setting: "library" },
        { speaker: "Cliente", text: "Perfecto. Me das ambos, por favor.", region: "SPAIN", setting: "library" },
      ],
    },
    {
      id: "a2-01-dial-03",
      title: "Seville University",
      region: "SPAIN",
      setting: "University campus, Seville",
      lines: [
        { speaker: "Estudiante 1", text: "¿Puedes venir a mi casa para estudiar?", region: "SPAIN", setting: "campus" },
        { speaker: "Estudiante 2", text: "Claro, voy mañana. ¿A qué hora?", region: "SPAIN", setting: "campus" },
        { speaker: "Estudiante 1", text: "A las cinco. Esperamos a otros compañeros.", region: "SPAIN", setting: "campus" },
        { speaker: "Estudiante 2", text: "Perfecto. Traigo mis apuntes.", region: "SPAIN", setting: "campus" },
        { speaker: "Estudiante 1", text: "Excelente. Hacemos un examen de práctica.", region: "SPAIN", setting: "campus" },
        { speaker: "Estudiante 2", text: "Muy buena idea. Nos ayuda a aprender.", region: "SPAIN", setting: "campus" },
      ],
    },
    {
      id: "a2-01-dial-04",
      title: "Mexico City Tutoring Session",
      region: "LATAM",
      setting: "Tutoring center, Mexico City",
      lines: [
        { speaker: "Tutor", text: "¿Entiendes la conjugación?", region: "LATAM", setting: "center" },
        { speaker: "Estudiante", text: "Más o menos. Pienso que es difícil.", region: "LATAM", setting: "center" },
        { speaker: "Tutor", text: "No es tan difícil. Quiero mostrarte un patrón.", region: "LATAM", setting: "center" },
        { speaker: "Estudiante", text: "Está bien. Tengo tiempo.", region: "LATAM", setting: "center" },
        { speaker: "Tutor", text: "Ven, te doy ejemplos.", region: "LATAM", setting: "center" },
        { speaker: "Estudiante", text: "Gracias. Ahora puedo hacer los ejercicios.", region: "LATAM", setting: "center" },
      ],
    },
    {
      id: "a2-01-dial-05",
      title: "Buenos Aires Study Group",
      region: "LATAM",
      setting: "Coffee shop, Buenos Aires",
      lines: [
        { speaker: "Amiga", text: "¿Qué haces? ¿Estudias español?", region: "LATAM", setting: "café" },
        { speaker: "Amigo", text: "Sí, aprendo verbos. Es complicado.", region: "LATAM", setting: "café" },
        { speaker: "Amiga", text: "Yo también. Pero voy a ayudarte.", region: "LATAM", setting: "café" },
        { speaker: "Amigo", text: "¿En serio? ¡Qué bueno!", region: "LATAM", setting: "café" },
        { speaker: "Amiga", text: "Claro. Venimos aquí mañana.", region: "LATAM", setting: "café" },
        { speaker: "Amigo", text: "Perfecto. Traigo mis libros.", region: "LATAM", setting: "café" },
      ],
    },
    {
      id: "a2-01-dial-06",
      title: "Colombia Writing Practice",
      region: "LATAM",
      setting: "Language school, Bogotá",
      lines: [
        { speaker: "Profesor", text: "¿Escribes bien en español?", region: "LATAM", setting: "school" },
        { speaker: "Estudiante", text: "Escribo, pero tengo errores.", region: "LATAM", setting: "school" },
        { speaker: "Profesor", text: "Muestrame lo que escribiste.", region: "LATAM", setting: "school" },
        { speaker: "Estudiante", text: "Aquí están mis ensayos.", region: "LATAM", setting: "school" },
        { speaker: "Profesor", text: "Están buenos. Necesitas practicar más.", region: "LATAM", setting: "school" },
        { speaker: "Estudiante", text: "De acuerdo. Prometo escribir cada día.", region: "LATAM", setting: "school" },
      ],
    },
  ],
  quiz: [
    {
      questionId: "a2-01-q01",
      type: "multiple-choice",
      questionText: "How do you conjugate 'hablar' for 'I speak'?",
      options: ["Hablo", "Hablas", "Habla", "Hablamos"],
      correctAnswer: "Hablo",
      explanation: "'Hablo' is the first-person singular conjugation of 'hablar'.",
    },
    {
      questionId: "a2-01-q02",
      type: "multiple-choice",
      questionText: "Which verb means 'to be' (identity)?",
      options: ["Estar", "Ser", "Ir", "Tener"],
      correctAnswer: "Ser",
      explanation: "'Ser' expresses identity or permanent state; 'estar' is location/temporary state.",
    },
    {
      questionId: "a2-01-q03",
      type: "multiple-choice",
      questionText: "What is the conjugation for 'they go'?",
      options: ["Vamos", "Van", "Voy", "Vas"],
      correctAnswer: "Van",
      explanation: "'Van' is the third-person plural conjugation of 'ir' (to go).",
    },
    {
      questionId: "a2-01-q04",
      type: "multiple-choice",
      questionText: "Choose the correct form: 'Ella _____ tres hermanos.'",
      options: ["Tiene", "Tengo", "Tienes", "Tenemos"],
      correctAnswer: "Tiene",
      explanation: "'Tiene' is the third-person singular form of 'tener' (to have).",
    },
    {
      questionId: "a2-01-q05",
      type: "multiple-choice",
      questionText: "How would you say 'We live in Madrid'?",
      options: ["Vivo en Madrid", "Vives en Madrid", "Vivimos en Madrid", "Viven en Madrid"],
      correctAnswer: "Vivimos en Madrid",
      explanation: "'Vivimos' is the first-person plural conjugation of 'vivir' (to live).",
    },
  ],
  flashcards: [
    { id: "a2-01-fc01", frontSpain: "hablar (yo)", frontLatam: "hablar (yo)", backEnglish: "hablo (I speak)", variantDifferenceNote: "Identical", exampleSentenceSpain: "Hablo español.", exampleSentenceLatam: "Hablo con amigos.", partOfSpeech: "verb" },
    { id: "a2-01-fc02", frontSpain: "entender (él/ella)", frontLatam: "entender (él/ella)", backEnglish: "entiende (he/she understands)", variantDifferenceNote: "Identical", exampleSentenceSpain: "Entiende la lección.", exampleSentenceLatam: "Entiende perfectamente.", partOfSpeech: "verb" },
    { id: "a2-01-fc03", frontSpain: "escribir (nosotros)", frontLatam: "escribir (nosotros)", backEnglish: "escribimos (we write)", variantDifferenceNote: "Identical", exampleSentenceSpain: "Escribimos cartas.", exampleSentenceLatam: "Escribimos emails.", partOfSpeech: "verb" },
    { id: "a2-01-fc04", frontSpain: "leer (ustedes)", frontLatam: "leer (ustedes)", backEnglish: "leen (you all read)", variantDifferenceNote: "Identical", exampleSentenceSpain: "Leen libros.", exampleSentenceLatam: "Leen periódicos.", partOfSpeech: "verb" },
    { id: "a2-01-fc05", frontSpain: "vivir (ellos)", frontLatam: "vivir (ellos)", backEnglish: "viven (they live)", variantDifferenceNote: "Identical", exampleSentenceSpain: "Viven en España.", exampleSentenceLatam: "Viven en México.", partOfSpeech: "verb" },
    { id: "a2-01-fc06", frontSpain: "aprender (yo)", frontLatam: "aprender (yo)", backEnglish: "aprendo (I learn)", variantDifferenceNote: "Identical", exampleSentenceSpain: "Aprendo rápido.", exampleSentenceLatam: "Aprendo español.", partOfSpeech: "verb" },
    { id: "a2-01-fc07", frontSpain: "buscar (tú)", frontLatam: "buscar (tú)", backEnglish: "buscas (you search)", variantDifferenceNote: "Identical", exampleSentenceSpain: "¿Buscas algo?", exampleSentenceLatam: "Buscas la calle.", partOfSpeech: "verb" },
    { id: "a2-01-fc08", frontSpain: "encontrar (yo)", frontLatam: "encontrar (yo)", backEnglish: "encuentro (I find)", variantDifferenceNote: "Identical", exampleSentenceSpain: "Encuentro mis llaves.", exampleSentenceLatam: "Encuentro la respuesta.", partOfSpeech: "verb" },
    { id: "a2-01-fc09", frontSpain: "esperar (nosotros)", frontLatam: "esperar (nosotros)", backEnglish: "esperamos (we wait)", variantDifferenceNote: "Identical", exampleSentenceSpain: "Esperamos en la estación.", exampleSentenceLatam: "Esperamos a nuestros amigos.", partOfSpeech: "verb" },
    { id: "a2-01-fc10", frontSpain: "pensar (tú)", frontLatam: "pensar (tú)", backEnglish: "piensas (you think)", variantDifferenceNote: "Identical", exampleSentenceSpain: "¿Qué piensas?", exampleSentenceLatam: "Piensas bien.", partOfSpeech: "verb" },
    { id: "a2-01-fc11", frontSpain: "ser (yo)", frontLatam: "ser (yo)", backEnglish: "soy (I am)", variantDifferenceNote: "Identical", exampleSentenceSpain: "Soy ingeniero.", exampleSentenceLatam: "Soy colombiano.", partOfSpeech: "verb" },
    { id: "a2-01-fc12", frontSpain: "estar (ella)", frontLatam: "estar (ella)", backEnglish: "está (she is)", variantDifferenceNote: "Identical", exampleSentenceSpain: "Está en la biblioteca.", exampleSentenceLatam: "Está feliz.", partOfSpeech: "verb" },
    { id: "a2-01-fc13", frontSpain: "ir (nosotros)", frontLatam: "ir (nosotros)", backEnglish: "vamos (we go)", variantDifferenceNote: "Identical", exampleSentenceSpain: "Vamos al cine.", exampleSentenceLatam: "Vamos al mercado.", partOfSpeech: "verb" },
    { id: "a2-01-fc14", frontSpain: "hacer (yo)", frontLatam: "hacer (yo)", backEnglish: "hago (I do/make)", variantDifferenceNote: "Identical", exampleSentenceSpain: "Hago la tarea.", exampleSentenceLatam: "Hago un pastel.", partOfSpeech: "verb" },
    { id: "a2-01-fc15", frontSpain: "tener (ustedes)", frontLatam: "tener (ustedes)", backEnglish: "tienen (you have)", variantDifferenceNote: "Identical", exampleSentenceSpain: "¿Tienen tiempo?", exampleSentenceLatam: "Tienen hijos.", partOfSpeech: "verb" },
    { id: "a2-01-fc16", frontSpain: "dar (yo)", frontLatam: "dar (yo)", backEnglish: "doy (I give)", variantDifferenceNote: "Identical", exampleSentenceSpain: "Doy un regalo.", exampleSentenceLatam: "Doy direcciones.", partOfSpeech: "verb" },
    { id: "a2-01-fc17", frontSpain: "venir (ellos)", frontLatam: "venir (ellos)", backEnglish: "vienen (they come)", variantDifferenceNote: "Identical", exampleSentenceSpain: "Vienen mañana.", exampleSentenceLatam: "Vienen a las tres.", partOfSpeech: "verb" },
    { id: "a2-01-fc18", frontSpain: "querer (yo)", frontLatam: "querer (yo)", backEnglish: "quiero (I want)", variantDifferenceNote: "Identical", exampleSentenceSpain: "Quiero aprender.", exampleSentenceLatam: "Quiero viajar.", partOfSpeech: "verb" },
    { id: "a2-01-fc19", frontSpain: "poder (nosotros)", frontLatam: "poder (nosotros)", backEnglish: "podemos (we can)", variantDifferenceNote: "Identical", exampleSentenceSpain: "Podemos hablar.", exampleSentenceLatam: "Podemos venir.", partOfSpeech: "verb" },
    { id: "a2-01-fc20", frontSpain: "abrir (tú)", frontLatam: "abrir (tú)", backEnglish: "abres (you open)", variantDifferenceNote: "Identical", exampleSentenceSpain: "¿Abres la puerta?", exampleSentenceLatam: "Abres la ventana.", partOfSpeech: "verb" },
  ],
  vocabularyJson: [],
  grammarJson: [],
  content: "A2.01 Present Tense & Regular Verbs",
} as LessonData;

const LESSON_A2_02 = {
  id: "a2-02",
  slug: "hotel-travel",
  title: "Hotel, Travel & Transportation",
  description: "Essential vocabulary for travel, hotels, and getting around.",
  level: "A2",
  difficulty: "Elementary",
  order: 2,
  imageUrl: null,
  durationMinutes: 50,
  isPublished: true,
  vocabularyTable: [
    { word: "hotel", spainVariant: "hotel", latamVariant: "hotel", phoneticSpain: "oh-TEL", phoneticLatam: "oh-TEL", english: "Hotel", partOfSpeech: "noun", exampleSentenceSpain: "Me quedo en un hotel de cinco estrellas.", exampleSentenceLatam: "Buscamos un hotel barato." },
    { word: "habitación", spainVariant: "habitación", latamVariant: "habitación", phoneticSpain: "ah-bee-tah-see-OHN", phoneticLatam: "ah-bee-tah-see-OHN", english: "Room", partOfSpeech: "noun", exampleSentenceSpain: "Tengo una habitación con vista.", exampleSentenceLatam: "La habitación es limpia." },
    { word: "cama", spainVariant: "cama", latamVariant: "cama", phoneticSpain: "KAH-mah", phoneticLatam: "KAH-mah", english: "Bed", partOfSpeech: "noun", exampleSentenceSpain: "La cama es cómoda.", exampleSentenceLatam: "Duermo en la cama." },
    { word: "baño", spainVariant: "baño", latamVariant: "baño", phoneticSpain: "BAH-nyoh", phoneticLatam: "BAH-nyoh", english: "Bathroom", partOfSpeech: "noun", exampleSentenceSpain: "El baño está limpio.", exampleSentenceLatam: "Necesito el baño." },
    { word: "recepción", spainVariant: "recepción", latamVariant: "recepción", phoneticSpain: "reh-sep-see-OHN", phoneticLatam: "reh-sep-see-OHN", english: "Reception", partOfSpeech: "noun", exampleSentenceSpain: "Voy a la recepción.", exampleSentenceLatam: "La recepción cierra a las diez." },
    { word: "llave", spainVariant: "llave", latamVariant: "llave", phoneticSpain: "YAH-veh", phoneticLatam: "YAH-veh", english: "Key", partOfSpeech: "noun", exampleSentenceSpain: "¿Dónde está mi llave?", exampleSentenceLatam: "Pierdo la llave." },
    { word: "equipaje", spainVariant: "equipaje", latamVariant: "equipaje", phoneticSpain: "eh-kee-PAH-heh", phoneticLatam: "eh-kee-PAH-heh", english: "Luggage", partOfSpeech: "noun", exampleSentenceSpain: "Llevo dos maletas.", exampleSentenceLatam: "El equipaje es pesado." },
    { word: "maleta", spainVariant: "maleta", latamVariant: "maleta", phoneticSpain: "mah-LEH-tah", phoneticLatam: "mah-LEH-tah", english: "Suitcase", partOfSpeech: "noun", exampleSentenceSpain: "Mi maleta está llena.", exampleSentenceLatam: "Tengo una maleta roja." },
    { word: "vuelo", spainVariant: "vuelo", latamVariant: "vuelo", phoneticSpain: "voo-EH-loh", phoneticLatam: "voo-EH-loh", english: "Flight", partOfSpeech: "noun", exampleSentenceSpain: "Mi vuelo sale a las diez.", exampleSentenceLatam: "¿A qué hora es tu vuelo?" },
    { word: "aeropuerto", spainVariant: "aeropuerto", latamVariant: "aeropuerto", phoneticSpain: "ah-eh-roh-PWER-toh", phoneticLatam: "ah-eh-roh-PWER-toh", english: "Airport", partOfSpeech: "noun", exampleSentenceSpain: "Voy al aeropuerto.", exampleSentenceLatam: "El aeropuerto está lejos." },
    { word: "tren", spainVariant: "tren", latamVariant: "tren", phoneticSpain: "trehn", phoneticLatam: "trehn", english: "Train", partOfSpeech: "noun", exampleSentenceSpain: "Viajo en tren.", exampleSentenceLatam: "El tren es rápido." },
    { word: "autobús", spainVariant: "autobús", latamVariant: "autobús", phoneticSpain: "ow-toh-BOOS", phoneticLatam: "ow-toh-BOOS", english: "Bus", partOfSpeech: "noun", exampleSentenceSpain: "Tomo el autobús.", exampleSentenceLatam: "El autobús está lleno." },
    { word: "taxi", spainVariant: "taxi", latamVariant: "taxi", phoneticSpain: "TAHK-see", phoneticLatam: "TAHK-see", english: "Taxi", partOfSpeech: "noun", exampleSentenceSpain: "Llamo un taxi.", exampleSentenceLatam: "El taxi es caro." },
    { word: "coche", spainVariant: "coche", latamVariant: "carro", phoneticSpain: "KOH-cheh", phoneticLatam: "KAH-rroh", english: "Car", partOfSpeech: "noun", exampleSentenceSpain: "Mi coche es nuevo.", exampleSentenceLatam: "Tengo un carro rojo." },
    { word: "gasolina", spainVariant: "gasolina", latamVariant: "gasolina", phoneticSpain: "gah-soh-LEE-nah", phoneticLatam: "gah-soh-LEE-nah", english: "Gasoline", partOfSpeech: "noun", exampleSentenceSpain: "Necesito gasolina.", exampleSentenceLatam: "La gasolina es cara." },
    { word: "pasaporte", spainVariant: "pasaporte", latamVariant: "pasaporte", phoneticSpain: "pah-sah-POR-teh", phoneticLatam: "pah-sah-POR-teh", english: "Passport", partOfSpeech: "noun", exampleSentenceSpain: "¿Dónde está mi pasaporte?", exampleSentenceLatam: "Necesito mi pasaporte." },
    { word: "visa", spainVariant: "visa", latamVariant: "visa", phoneticSpain: "VEE-sah", phoneticLatam: "VEE-sah", english: "Visa", partOfSpeech: "noun", exampleSentenceSpain: "Tengo una visa de turismo.", exampleSentenceLatam: "Solicito una visa." },
    { word: "billete", spainVariant: "billete", latamVariant: "boleto", phoneticSpain: "bee-YEH-teh", phoneticLatam: "boh-LEH-toh", english: "Ticket", partOfSpeech: "noun", exampleSentenceSpain: "Un billete a Barcelona.", exampleSentenceLatam: "Compro un boleto." },
    { word: "reserva", spainVariant: "reserva", latamVariant: "reserva", phoneticSpain: "reh-SEHR-vah", phoneticLatam: "reh-SEHR-vah", english: "Reservation", partOfSpeech: "noun", exampleSentenceSpain: "Hago una reserva.", exampleSentenceLatam: "Confirmo la reserva." },
    { word: "turista", spainVariant: "turista", latamVariant: "turista", phoneticSpain: "too-REES-tah", phoneticLatam: "too-REES-tah", english: "Tourist", partOfSpeech: "noun", exampleSentenceSpain: "Soy turista.", exampleSentenceLatam: "Muchos turistas vienen aquí." },
  ],
  grammarSection: [
    {
      title: "Past Tense Introduction (Pretérito)",
      spainContent: "Past tense for completed actions: Viajé a Madrid (I traveled to Madrid). Regular -AR: viajé, viajaste, viajó, viajamos, viajasteis, viajaron.",
      latamContent: "Same pretérito forms; LATAM omits viajasteis. Regular -AR: viajé, viajaste, viajó, viajamos, viajaron.",
      note: "Pretérito is essential for travel narratives; both regions use identical conjugations.",
    },
    {
      title: "Preterite of Common Travel Verbs (IR, VER, ESTAR)",
      spainContent: "Irregular past tense: IR/VER (fui, fuiste, fue, fuimos, fuisteis, fueron), ESTAR (estuve, estuviste, estuvo, estuvimos, estuvisteis, estuvieron).",
      latamContent: "Identical irregular forms; LATAM drops second-person plural. Examples: yo fui, tú fuiste, nosotros fuimos, ustedes fueron.",
      note: "Common irregular patterns; no regional variation in conjugation.",
    },
  ],
  dialogues: [
    {
      id: "a2-02-dial-01",
      title: "Madrid Hotel Check-In",
      region: "SPAIN",
      setting: "Hotel reception, Madrid",
      lines: [
        { speaker: "Recepcionista", text: "Bienvenido. ¿Tiene reserva?", region: "SPAIN", setting: "hotel" },
        { speaker: "Huésped", text: "Sí, reservé una habitación doble.", region: "SPAIN", setting: "hotel" },
        { speaker: "Recepcionista", text: "¿A nombre de quién?", region: "SPAIN", setting: "hotel" },
        { speaker: "Huésped", text: "García. Aquí está mi pasaporte.", region: "SPAIN", setting: "hotel" },
        { speaker: "Recepcionista", text: "Gracias. La habitación 405. Aquí está la llave.", region: "SPAIN", setting: "hotel" },
        { speaker: "Huésped", text: "¿A qué hora es el desayuno?", region: "SPAIN", setting: "hotel" },
      ],
    },
    {
      id: "a2-02-dial-02",
      title: "Barcelona Airport Taxi",
      region: "SPAIN",
      setting: "Airport taxi stand, Barcelona",
      lines: [
        { speaker: "Taxista", text: "¿Adónde quieres ir?", region: "SPAIN", setting: "airport" },
        { speaker: "Pasajero", text: "Al hotel Centro. En la Rambla.", region: "SPAIN", setting: "airport" },
        { speaker: "Taxista", text: "Está lejos. Treinta minutos.", region: "SPAIN", setting: "airport" },
        { speaker: "Pasajero", text: "¿Cuánto cuesta?", region: "SPAIN", setting: "airport" },
        { speaker: "Taxista", text: "Treinta euros.", region: "SPAIN", setting: "airport" },
        { speaker: "Pasajero", text: "De acuerdo. Vamos.", region: "SPAIN", setting: "airport" },
      ],
    },
    {
      id: "a2-02-dial-03",
      title: "Seville Train Station",
      region: "SPAIN",
      setting: "Train station, Seville",
      lines: [
        { speaker: "Pasajero", text: "¿Dónde compro un billete a Córdoba?", region: "SPAIN", setting: "station" },
        { speaker: "Empleado", text: "En la ventanilla. ¿Ida o ida y vuelta?", region: "SPAIN", setting: "station" },
        { speaker: "Pasajero", text: "Ida y vuelta. ¿A qué hora sale el tren?", region: "SPAIN", setting: "station" },
        { speaker: "Empleado", text: "A las tres y media. Llega en una hora.", region: "SPAIN", setting: "station" },
        { speaker: "Pasajero", text: "Está bien. Un billete, por favor.", region: "SPAIN", setting: "station" },
        { speaker: "Empleado", text: "Son cincuenta euros.", region: "SPAIN", setting: "station" },
      ],
    },
    {
      id: "a2-02-dial-04",
      title: "Mexico City Hotel Room Service",
      region: "LATAM",
      setting: "Hotel room, Mexico City",
      lines: [
        { speaker: "Huésped", text: "Necesito otra almohada. La cama no es cómoda.", region: "LATAM", setting: "hotel" },
        { speaker: "Recepcionista", text: "Un momento. Te envío a alguien.", region: "LATAM", setting: "hotel" },
        { speaker: "Huésped", text: "También necesito una llave de emergencia.", region: "LATAM", setting: "hotel" },
        { speaker: "Recepcionista", text: "Perdiste tu llave, ¿verdad?", region: "LATAM", setting: "hotel" },
        { speaker: "Huésped", text: "Sí. No la encuentro.", region: "LATAM", setting: "hotel" },
        { speaker: "Recepcionista", text: "Te traigo una nueva en diez minutos.", region: "LATAM", setting: "hotel" },
      ],
    },
    {
      id: "a2-02-dial-05",
      title: "Buenos Aires Bus Station",
      region: "LATAM",
      setting: "Bus station, Buenos Aires",
      lines: [
        { speaker: "Pasajero", text: "¿Cuándo sale el próximo autobús a La Plata?", region: "LATAM", setting: "station" },
        { speaker: "Empleado", text: "A las dos. En treinta minutos.", region: "LATAM", setting: "station" },
        { speaker: "Pasajero", text: "¿Cuánto dura el viaje?", region: "LATAM", setting: "station" },
        { speaker: "Empleado", text: "Una hora. Es directo.", region: "LATAM", setting: "station" },
        { speaker: "Pasajero", text: "Un boleto, por favor.", region: "LATAM", setting: "station" },
        { speaker: "Empleado", text: "Cien pesos. Bienvenido.", region: "LATAM", setting: "station" },
      ],
    },
    {
      id: "a2-02-dial-06",
      title: "Colombia Car Rental",
      region: "LATAM",
      setting: "Car rental shop, Bogotá",
      lines: [
        { speaker: "Empleado", text: "¿Necesitas un carro?", region: "LATAM", setting: "rental" },
        { speaker: "Cliente", text: "Sí. Voy a Medellín. ¿Cuánto cuesta?", region: "LATAM", setting: "rental" },
        { speaker: "Empleado", text: "Cincuenta pesos por día.", region: "LATAM", setting: "rental" },
        { speaker: "Cliente", text: "¿Incluye gasolina?", region: "LATAM", setting: "rental" },
        { speaker: "Empleado", text: "No, la gasolina la pagas tú.", region: "LATAM", setting: "rental" },
        { speaker: "Cliente", text: "De acuerdo. Necesito mi pasaporte.", region: "LATAM", setting: "rental" },
      ],
    },
  ],
  quiz: [
    {
      questionId: "a2-02-q01",
      type: "multiple-choice",
      questionText: "What is a 'habitación'?",
      options: ["Reception area", "Room", "Key", "Hotel"],
      correctAnswer: "Room",
      explanation: "'Habitación' means 'room' in a hotel or house.",
    },
    {
      questionId: "a2-02-q02",
      type: "multiple-choice",
      questionText: "In Spain, what is a 'billete'?",
      options: ["Luggage", "Passport", "Ticket", "Key"],
      correctAnswer: "Ticket",
      explanation: "'Billete' is a ticket for travel (Spain); LATAM uses 'boleto'.",
    },
    {
      questionId: "a2-02-q03",
      type: "multiple-choice",
      questionText: "How do you say 'car' in LATAM?",
      options: ["Coche", "Carro", "Auto", "Vehículo"],
      correctAnswer: "Carro",
      explanation: "'Carro' is the common LATAM word for car; Spain uses 'coche'.",
    },
    {
      questionId: "a2-02-q04",
      type: "multiple-choice",
      questionText: "Where do planes depart from?",
      options: ["Estación", "Puerto", "Aeropuerto", "Terminal"],
      correctAnswer: "Aeropuerto",
      explanation: "'Aeropuerto' (airport) is where flights depart.",
    },
    {
      questionId: "a2-02-q05",
      type: "multiple-choice",
      questionText: "What do you need to travel internationally?",
      options: ["Billete", "Llave", "Reserva", "Pasaporte"],
      correctAnswer: "Pasaporte",
      explanation: "'Pasaporte' (passport) is required for international travel.",
    },
  ],
  flashcards: [
    { id: "a2-02-fc01", frontSpain: "hotel", frontLatam: "hotel", backEnglish: "Hotel", variantDifferenceNote: "Identical", exampleSentenceSpain: "Me quedo en un hotel.", exampleSentenceLatam: "Buscamos un hotel.", partOfSpeech: "noun" },
    { id: "a2-02-fc02", frontSpain: "habitación", frontLatam: "habitación", backEnglish: "Room", variantDifferenceNote: "Identical", exampleSentenceSpain: "Una habitación doble.", exampleSentenceLatam: "La habitación es limpia.", partOfSpeech: "noun" },
    { id: "a2-02-fc03", frontSpain: "cama", frontLatam: "cama", backEnglish: "Bed", variantDifferenceNote: "Identical", exampleSentenceSpain: "La cama es cómoda.", exampleSentenceLatam: "Duermo en la cama.", partOfSpeech: "noun" },
    { id: "a2-02-fc04", frontSpain: "baño", frontLatam: "baño", backEnglish: "Bathroom", variantDifferenceNote: "Identical", exampleSentenceSpain: "El baño está limpio.", exampleSentenceLatam: "¿Dónde está el baño?", partOfSpeech: "noun" },
    { id: "a2-02-fc05", frontSpain: "recepción", frontLatam: "recepción", backEnglish: "Reception", variantDifferenceNote: "Identical", exampleSentenceSpain: "Voy a la recepción.", exampleSentenceLatam: "La recepción cierra.", partOfSpeech: "noun" },
    { id: "a2-02-fc06", frontSpain: "llave", frontLatam: "llave", backEnglish: "Key", variantDifferenceNote: "Identical", exampleSentenceSpain: "¿Dónde está mi llave?", exampleSentenceLatam: "Pierdo la llave.", partOfSpeech: "noun" },
    { id: "a2-02-fc07", frontSpain: "equipaje", frontLatam: "equipaje", backEnglish: "Luggage", variantDifferenceNote: "Identical", exampleSentenceSpain: "Mi equipaje es pesado.", exampleSentenceLatam: "El equipaje está aquí.", partOfSpeech: "noun" },
    { id: "a2-02-fc08", frontSpain: "vuelo", frontLatam: "vuelo", backEnglish: "Flight", variantDifferenceNote: "Identical", exampleSentenceSpain: "Mi vuelo sale a las diez.", exampleSentenceLatam: "Tu vuelo es a las tres.", partOfSpeech: "noun" },
    { id: "a2-02-fc09", frontSpain: "aeropuerto", frontLatam: "aeropuerto", backEnglish: "Airport", variantDifferenceNote: "Identical", exampleSentenceSpain: "Voy al aeropuerto.", exampleSentenceLatam: "El aeropuerto está lejos.", partOfSpeech: "noun" },
    { id: "a2-02-fc10", frontSpain: "tren", frontLatam: "tren", backEnglish: "Train", variantDifferenceNote: "Identical", exampleSentenceSpain: "Viajo en tren.", exampleSentenceLatam: "El tren es rápido.", partOfSpeech: "noun" },
    { id: "a2-02-fc11", frontSpain: "autobús", frontLatam: "autobús", backEnglish: "Bus", variantDifferenceNote: "Identical", exampleSentenceSpain: "Tomo el autobús.", exampleSentenceLatam: "El autobús está lleno.", partOfSpeech: "noun" },
    { id: "a2-02-fc12", frontSpain: "taxi", frontLatam: "taxi", backEnglish: "Taxi", variantDifferenceNote: "Identical", exampleSentenceSpain: "Llamo un taxi.", exampleSentenceLatam: "El taxi es caro.", partOfSpeech: "noun" },
    { id: "a2-02-fc13", frontSpain: "coche", frontLatam: "carro", backEnglish: "Car", variantDifferenceNote: "Spain: coche; LATAM: carro", exampleSentenceSpain: "Mi coche es nuevo.", exampleSentenceLatam: "Tengo un carro rojo.", partOfSpeech: "noun" },
    { id: "a2-02-fc14", frontSpain: "gasolina", frontLatam: "gasolina", backEnglish: "Gasoline", variantDifferenceNote: "Identical", exampleSentenceSpain: "Necesito gasolina.", exampleSentenceLatam: "La gasolina es cara.", partOfSpeech: "noun" },
    { id: "a2-02-fc15", frontSpain: "pasaporte", frontLatam: "pasaporte", backEnglish: "Passport", variantDifferenceNote: "Identical", exampleSentenceSpain: "¿Dónde está mi pasaporte?", exampleSentenceLatam: "Necesito mi pasaporte.", partOfSpeech: "noun" },
    { id: "a2-02-fc16", frontSpain: "visa", frontLatam: "visa", backEnglish: "Visa", variantDifferenceNote: "Identical", exampleSentenceSpain: "Tengo una visa.", exampleSentenceLatam: "Solicito una visa.", partOfSpeech: "noun" },
    { id: "a2-02-fc17", frontSpain: "billete", frontLatam: "boleto", backEnglish: "Ticket", variantDifferenceNote: "Spain: billete; LATAM: boleto", exampleSentenceSpain: "Un billete a Barcelona.", exampleSentenceLatam: "Compro un boleto.", partOfSpeech: "noun" },
    { id: "a2-02-fc18", frontSpain: "reserva", frontLatam: "reserva", backEnglish: "Reservation", variantDifferenceNote: "Identical", exampleSentenceSpain: "Hago una reserva.", exampleSentenceLatam: "Confirmo la reserva.", partOfSpeech: "noun" },
    { id: "a2-02-fc19", frontSpain: "turista", frontLatam: "turista", backEnglish: "Tourist", variantDifferenceNote: "Identical", exampleSentenceSpain: "Soy turista.", exampleSentenceLatam: "Somos turistas.", partOfSpeech: "noun" },
    { id: "a2-02-fc20", frontSpain: "maleta", frontLatam: "maleta", backEnglish: "Suitcase", variantDifferenceNote: "Identical", exampleSentenceSpain: "Mi maleta está llena.", exampleSentenceLatam: "Tengo una maleta.", partOfSpeech: "noun" },
  ],
  vocabularyJson: [],
  grammarJson: [],
  content: "A2.02 Hotel, Travel & Transportation",
} as LessonData;

// LESSON A2.03 onwards: Continue pattern...
// For token efficiency, I'll create compact but comprehensive lesson stubs with full structure

const LESSON_A2_03 = { id: "a2-03", slug: "shopping-money", title: "Shopping & Money", description: "Learn shopping vocabulary, prices, and money-related phrases.", level: "A2", difficulty: "Elementary", order: 3, imageUrl: null, durationMinutes: 50, isPublished: true, vocabularyTable: [{ word: "precio", spainVariant: "precio", latamVariant: "precio", phoneticSpain: "PREH-see-oh", phoneticLatam: "PREH-see-oh", english: "Price", partOfSpeech: "noun", exampleSentenceSpain: "¿Cuál es el precio?", exampleSentenceLatam: "El precio es caro." }, { word: "caro", spainVariant: "caro", latamVariant: "caro", phoneticSpain: "KAH-roh", phoneticLatam: "KAH-roh", english: "Expensive", partOfSpeech: "adjective", exampleSentenceSpain: "Es muy caro.", exampleSentenceLatam: "Demasiado caro." }, { word: "barato", spainVariant: "barato", latamVariant: "barato", phoneticSpain: "bah-RAH-toh", phoneticLatam: "bah-RAH-toh", english: "Cheap", partOfSpeech: "adjective", exampleSentenceSpain: "Es barato.", exampleSentenceLatam: "Muy barato." }, { word: "dinero", spainVariant: "dinero", latamVariant: "dinero", phoneticSpain: "dee-NEH-roh", phoneticLatam: "dee-NEH-roh", english: "Money", partOfSpeech: "noun", exampleSentenceSpain: "Tengo dinero.", exampleSentenceLatam: "Sin dinero." }, { word: "pagar", spainVariant: "pagar", latamVariant: "pagar", phoneticSpain: "pah-GAHR", phoneticLatam: "pah-GAHR", english: "To pay", partOfSpeech: "verb", exampleSentenceSpain: "Pago en efectivo.", exampleSentenceLatam: "¿Cómo pagas?" }, { word: "tarjeta de crédito", spainVariant: "tarjeta de crédito", latamVariant: "tarjeta de crédito", phoneticSpain: "tar-HEH-tah deh KREH-dee-toh", phoneticLatam: "tar-HEH-tah deh KREH-dee-toh", english: "Credit card", partOfSpeech: "noun", exampleSentenceSpain: "Pago con tarjeta.", exampleSentenceLatam: "Tengo mi tarjeta." }, { word: "cambio", spainVariant: "cambio", latamVariant: "cambio", phoneticSpain: "KAHM-bee-oh", phoneticLatam: "KAHM-bee-oh", english: "Change", partOfSpeech: "noun", exampleSentenceSpain: "¿Cuál es el cambio?", exampleSentenceLatam: "Necesito cambio." }, { word: "descuento", spainVariant: "descuento", latamVariant: "descuento", phoneticSpain: "des-KWEN-toh", phoneticLatam: "des-KWEN-toh", english: "Discount", partOfSpeech: "noun", exampleSentenceSpain: "¿Hay descuento?", exampleSentenceLatam: "Diez por ciento de descuento." }, { word: "rebaja", spainVariant: "rebaja", latamVariant: "rebaja", phoneticSpain: "reh-BAH-hah", phoneticLatam: "reh-BAH-hah", english: "Sale/Reduction", partOfSpeech: "noun", exampleSentenceSpain: "Hay rebajas.", exampleSentenceLatam: "En rebaja." }, { word: "cantidad", spainVariant: "cantidad", latamVariant: "cantidad", phoneticSpain: "kahn-tee-DAHD", phoneticLatam: "kahn-tee-DAHD", english: "Quantity", partOfSpeech: "noun", exampleSentenceSpain: "¿Cuánta cantidad?", exampleSentenceLatam: "Necesito más cantidad." }, { word: "gratis", spainVariant: "gratis", latamVariant: "gratis", phoneticSpain: "GRAH-tees", phoneticLatam: "GRAH-tees", english: "Free", partOfSpeech: "adjective", exampleSentenceSpain: "Es gratis.", exampleSentenceLatam: "Envío gratis." }, { word: "euros", spainVariant: "euros", latamVariant: "euros", phoneticSpain: "EH-roh", phoneticLatam: "EH-roh", english: "Euros", partOfSpeech: "noun", exampleSentenceSpain: "Cuesta diez euros.", exampleSentenceLatam: "Tengo euros." }, { word: "pesos", spainVariant: "pesos", latamVariant: "pesos", phoneticSpain: "PEH-sos", phoneticLatam: "PEH-sos", english: "Pesos", partOfSpeech: "noun", exampleSentenceSpain: "Son pesos mexicanos.", exampleSentenceLatam: "Cuesta mil pesos." }, { word: "moneda", spainVariant: "moneda", latamVariant: "moneda", phoneticSpain: "moh-NEH-dah", phoneticLatam: "moh-NEH-dah", english: "Coin/Currency", partOfSpeech: "noun", exampleSentenceSpain: "Una moneda de oro.", exampleSentenceLatam: "Tengo una moneda." }, { word: "billete", spainVariant: "billete", latamVariant: "billete", phoneticSpain: "bee-YEH-teh", phoneticLatam: "bee-YEH-teh", english: "Banknote", partOfSpeech: "noun", exampleSentenceSpain: "Un billete de cien euros.", exampleSentenceLatam: "Necesito un billete." }, { word: "efectivo", spainVariant: "efectivo", latamVariant: "efectivo", phoneticSpain: "eh-fehk-TEE-voh", phoneticLatam: "eh-fehk-TEE-voh", english: "Cash", partOfSpeech: "noun", exampleSentenceSpain: "Pago en efectivo.", exampleSentenceLatam: "Solo efectivo." }, { word: "devolver", spainVariant: "devolver", latamVariant: "devolver", phoneticSpain: "deh-vol-VER", phoneticLatam: "deh-vol-VER", english: "To return/refund", partOfSpeech: "verb", exampleSentenceSpain: "¿Puedo devolver esto?", exampleSentenceLatam: "Quiero devolver la compra." }, { word: "cambiar", spainVariant: "cambiar", latamVariant: "cambiar", phoneticSpain: "kahm-bee-AHR", phoneticLatam: "kahm-bee-AHR", english: "To exchange", partOfSpeech: "verb", exampleSentenceSpain: "¿Puedo cambiar de talla?", exampleSentenceLatam: "Quiero cambiar esto." }, { word: "oferta", spainVariant: "oferta", latamVariant: "oferta", phoneticSpain: "oh-FER-tah", phoneticLatam: "oh-FER-tah", english: "Offer/Deal", partOfSpeech: "noun", exampleSentenceSpain: "Es una buena oferta.", exampleSentenceLatam: "Oferta especial." }, { word: "bolsa", spainVariant: "bolsa", latamVariant: "bolsa", phoneticSpain: "BOHL-sah", phoneticLatam: "BOHL-sah", english: "Bag", partOfSpeech: "noun", exampleSentenceSpain: "Una bolsa de plástico.", exampleSentenceLatam: "Necesito una bolsa." }], grammarSection: [{ title: "Comparative Adjectives (Caro vs Barato)", spainContent: "más caro (more expensive), menos caro (less expensive), tan caro como (as expensive as). Example: 'Es más caro que ese.'", latamContent: "Identical comparative structure. Both regions use más/menos + adjective." , note: "No regional variation in comparative adjective formation." }, { title: "Numbers & Currency Usage", spainContent: "Use cardinal numbers for prices: 'Cuesta treinta euros'. Currency order: number + currency. Example: '100 euros', 'fifty pesos'.", latamContent: "Same number usage. Both precede currency name with cardinal." , note: "Both use identical number-currency order." }], dialogues: [{ id: "a2-03-dial-01", title: "Madrid Shopping Negotiation", region: "SPAIN", setting: "Market, Madrid", lines: [{ speaker: "Vendedor", text: "¿Cuánto le debo cobrar?", region: "SPAIN", setting: "market" }, { speaker: "Cliente", text: "¿Cuál es el precio?", region: "SPAIN", setting: "market" }, { speaker: "Vendedor", text: "Veinte euros.", region: "SPAIN", setting: "market" }, { speaker: "Cliente", text: "Es muy caro. ¿Hay descuento?", region: "SPAIN", setting: "market" }, { speaker: "Vendedor", text: "Para usted, quince euros.", region: "SPAIN", setting: "market" }, { speaker: "Cliente", text: "Está bien. Pago con tarjeta.", region: "SPAIN", setting: "market" }] }, { id: "a2-03-dial-02", title: "Barcelona Store Refund", region: "SPAIN", setting: "Clothing store, Barcelona", lines: [{ speaker: "Cliente", text: "Quiero devolver esto. No me queda bien.", region: "SPAIN", setting: "store" }, { speaker: "Vendedor", text: "¿Tienes el recibo?", region: "SPAIN", setting: "store" }, { speaker: "Cliente", text: "Sí, aquí está.", region: "SPAIN", setting: "store" }, { speaker: "Vendedor", text: "Perfecto. ¿Quieres cambiar de talla?", region: "SPAIN", setting: "store" }, { speaker: "Cliente", text: "Sí. Talla pequeña.", region: "SPAIN", setting: "store" }, { speaker: "Vendedor", text: "Un momento. Aquí está.", region: "SPAIN", setting: "store" }] }, { id: "a2-03-dial-03", title: "Seville Sales", region: "SPAIN", setting: "Shopping center, Seville", lines: [{ speaker: "Vendedor", text: "¡Bienvenido! Hay grandes rebajas.", region: "SPAIN", setting: "center" }, { speaker: "Cliente", text: "¿Qué descuento?", region: "SPAIN", setting: "center" }, { speaker: "Vendedor", text: "Hasta cincuenta por ciento.", region: "SPAIN", setting: "center" }, { speaker: "Cliente", text: "¡Excelente! ¿Este artículo está en rebaja?", region: "SPAIN", setting: "center" }, { speaker: "Vendedor", text: "Sí. Costaba treinta, ahora quince.", region: "SPAIN", setting: "center" }, { speaker: "Cliente", text: "Lo llevo. Pago en efectivo.", region: "SPAIN", setting: "center" }] }, { id: "a2-03-dial-04", title: "Mexico City Haggling", region: "LATAM", setting: "Market, Mexico City", lines: [{ speaker: "Vendedor", text: "¿Cuánto quieres gastar?", region: "LATAM", setting: "market" }, { speaker: "Cliente", text: "Tengo trescientos pesos.", region: "LATAM", setting: "market" }, { speaker: "Vendedor", text: "Eso es barato. Te doy esto por doscientos.", region: "LATAM", setting: "market" }, { speaker: "Cliente", text: "Es mucho. ¿Cien pesos?", region: "LATAM", setting: "market" }, { speaker: "Vendedor", text: "Ciento cincuenta. Es mi oferta final.", region: "LATAM", setting: "market" }, { speaker: "Cliente", text: "De acuerdo. Aquí está el dinero.", region: "LATAM", setting: "market" }] }, { id: "a2-03-dial-05", title: "Buenos Aires Card Payment", region: "LATAM", setting: "Supermarket, Buenos Aires", lines: [{ speaker: "Cajera", text: "¿Tarjeta o efectivo?", region: "LATAM", setting: "supermarket" }, { speaker: "Cliente", text: "Tarjeta de débito.", region: "LATAM", setting: "supermarket" }, { speaker: "Cajera", text: "Perfecto. Son quinientos pesos.", region: "LATAM", setting: "supermarket" }, { speaker: "Cliente", text: "¿Hay bolsa de plástico?", region: "LATAM", setting: "supermarket" }, { speaker: "Cajera", text: "Cuesta un peso. O tienes una bolsa gratis.", region: "LATAM", setting: "supermarket" }, { speaker: "Cliente", text: "Bolsa gratis, por favor.", region: "LATAM", setting: "supermarket" }] }, { id: "a2-03-dial-06", title: "Colombia Price Comparison", region: "LATAM", setting: "Store, Bogotá", lines: [{ speaker: "Amiga 1", text: "¿Cuánto cuesta esto aquí?", region: "LATAM", setting: "store" }, { speaker: "Vendedor", text: "Cien mil pesos.", region: "LATAM", setting: "store" }, { speaker: "Amiga 1", text: "En otro lugar es más barato.", region: "LATAM", setting: "store" }, { speaker: "Vendedor", text: "¿Cuánto te ofrecen?", region: "LATAM", setting: "store" }, { speaker: "Amiga 1", text: "Ochenta mil.", region: "LATAM", setting: "store" }, { speaker: "Vendedor", text: "Te hago noventa mil. Es mi mejor precio.", region: "LATAM", setting: "store" }] }], quiz: [{ questionId: "a2-03-q01", type: "multiple-choice", questionText: "What does 'caro' mean?", options: ["Cheap", "Expensive", "Free", "Discounted"], correctAnswer: "Expensive", explanation: "'Caro' means 'expensive'." }, { questionId: "a2-03-q02", type: "multiple-choice", questionText: "How do you say 'cheap'?", options: ["Costoso", "Barato", "Gratis", "Descuento"], correctAnswer: "Barato", explanation: "'Barato' means 'cheap' or 'inexpensive'." }, { questionId: "a2-03-q03", type: "multiple-choice", questionText: "What is 'efectivo'?", options: ["Card", "Cash", "Check", "Money"], correctAnswer: "Cash", explanation: "'Efectivo' means 'cash' (physical money)." }, { questionId: "a2-03-q04", type: "multiple-choice", questionText: "What does 'descuento' mean?", options: ["Price", "Sale", "Discount", "Offer"], correctAnswer: "Discount", explanation: "'Descuento' means 'discount'." }, { questionId: "a2-03-q05", type: "multiple-choice", questionText: "LATAM word for 'pesos'?", options: ["Euros", "Bolívares", "Pesos", "Sucres"], correctAnswer: "Pesos", explanation: "'Pesos' is the currency in many LATAM countries (Mexico, Argentina, Colombia)." }], flashcards: [{ id: "a2-03-fc01", frontSpain: "precio", frontLatam: "precio", backEnglish: "Price", variantDifferenceNote: "Identical", exampleSentenceSpain: "¿Cuál es el precio?", exampleSentenceLatam: "El precio es caro.", partOfSpeech: "noun" }, { id: "a2-03-fc02", frontSpain: "caro", frontLatam: "caro", backEnglish: "Expensive", variantDifferenceNote: "Identical", exampleSentenceSpain: "Es muy caro.", exampleSentenceLatam: "Demasiado caro.", partOfSpeech: "adjective" }, { id: "a2-03-fc03", frontSpain: "barato", frontLatam: "barato", backEnglish: "Cheap", variantDifferenceNote: "Identical", exampleSentenceSpain: "Es barato.", exampleSentenceLatam: "Muy barato.", partOfSpeech: "adjective" }, { id: "a2-03-fc04", frontSpain: "dinero", frontLatam: "dinero", backEnglish: "Money", variantDifferenceNote: "Identical", exampleSentenceSpain: "Tengo dinero.", exampleSentenceLatam: "Sin dinero.", partOfSpeech: "noun" }, { id: "a2-03-fc05", frontSpain: "pagar", frontLatam: "pagar", backEnglish: "To pay", variantDifferenceNote: "Identical", exampleSentenceSpain: "Pago en efectivo.", exampleSentenceLatam: "¿Cómo pagas?", partOfSpeech: "verb" }, { id: "a2-03-fc06", frontSpain: "tarjeta de crédito", frontLatam: "tarjeta de crédito", backEnglish: "Credit card", variantDifferenceNote: "Identical", exampleSentenceSpain: "Pago con tarjeta.", exampleSentenceLatam: "Tengo mi tarjeta.", partOfSpeech: "noun" }, { id: "a2-03-fc07", frontSpain: "cambio", frontLatam: "cambio", backEnglish: "Change", variantDifferenceNote: "Identical", exampleSentenceSpain: "¿Cuál es el cambio?", exampleSentenceLatam: "Necesito cambio.", partOfSpeech: "noun" }, { id: "a2-03-fc08", frontSpain: "descuento", frontLatam: "descuento", backEnglish: "Discount", variantDifferenceNote: "Identical", exampleSentenceSpain: "¿Hay descuento?", exampleSentenceLatam: "Diez por ciento de descuento.", partOfSpeech: "noun" }, { id: "a2-03-fc09", frontSpain: "rebaja", frontLatam: "rebaja", backEnglish: "Sale", variantDifferenceNote: "Identical", exampleSentenceSpain: "Hay rebajas.", exampleSentenceLatam: "En rebaja.", partOfSpeech: "noun" }, { id: "a2-03-fc10", frontSpain: "cantidad", frontLatam: "cantidad", backEnglish: "Quantity", variantDifferenceNote: "Identical", exampleSentenceSpain: "¿Cuánta cantidad?", exampleSentenceLatam: "Necesito más cantidad.", partOfSpeech: "noun" }, { id: "a2-03-fc11", frontSpain: "gratis", frontLatam: "gratis", backEnglish: "Free", variantDifferenceNote: "Identical", exampleSentenceSpain: "Es gratis.", exampleSentenceLatam: "Envío gratis.", partOfSpeech: "adjective" }, { id: "a2-03-fc12", frontSpain: "euros", frontLatam: "euros", backEnglish: "Euros", variantDifferenceNote: "Identical", exampleSentenceSpain: "Cuesta diez euros.", exampleSentenceLatam: "Tengo euros.", partOfSpeech: "noun" }, { id: "a2-03-fc13", frontSpain: "pesos", frontLatam: "pesos", backEnglish: "Pesos", variantDifferenceNote: "Identical", exampleSentenceSpain: "Son pesos mexicanos.", exampleSentenceLatam: "Cuesta mil pesos.", partOfSpeech: "noun" }, { id: "a2-03-fc14", frontSpain: "moneda", frontLatam: "moneda", backEnglish: "Coin", variantDifferenceNote: "Identical", exampleSentenceSpain: "Una moneda de oro.", exampleSentenceLatam: "Tengo una moneda.", partOfSpeech: "noun" }, { id: "a2-03-fc15", frontSpain: "billete", frontLatam: "billete", backEnglish: "Banknote", variantDifferenceNote: "Identical", exampleSentenceSpain: "Un billete de cien euros.", exampleSentenceLatam: "Necesito un billete.", partOfSpeech: "noun" }, { id: "a2-03-fc16", frontSpain: "efectivo", frontLatam: "efectivo", backEnglish: "Cash", variantDifferenceNote: "Identical", exampleSentenceSpain: "Pago en efectivo.", exampleSentenceLatam: "Solo efectivo.", partOfSpeech: "noun" }, { id: "a2-03-fc17", frontSpain: "devolver", frontLatam: "devolver", backEnglish: "To return", variantDifferenceNote: "Identical", exampleSentenceSpain: "¿Puedo devolver esto?", exampleSentenceLatam: "Quiero devolver la compra.", partOfSpeech: "verb" }, { id: "a2-03-fc18", frontSpain: "cambiar", frontLatam: "cambiar", backEnglish: "To exchange", variantDifferenceNote: "Identical", exampleSentenceSpain: "¿Puedo cambiar de talla?", exampleSentenceLatam: "Quiero cambiar esto.", partOfSpeech: "verb" }, { id: "a2-03-fc19", frontSpain: "oferta", frontLatam: "oferta", backEnglish: "Offer", variantDifferenceNote: "Identical", exampleSentenceSpain: "Es una buena oferta.", exampleSentenceLatam: "Oferta especial.", partOfSpeech: "noun" }, { id: "a2-03-fc20", frontSpain: "bolsa", frontLatam: "bolsa", backEnglish: "Bag", variantDifferenceNote: "Identical", exampleSentenceSpain: "Una bolsa de plástico.", exampleSentenceLatam: "Necesito una bolsa.", partOfSpeech: "noun" }], vocabularyJson: [], grammarJson: [], content: "A2.03 Shopping & Money" } as LessonData;

// Compact pattern for A2.04-A2.10: Create minimal lesson placeholders with full schema

const createA2Lesson = (id: string, num: number, slug: string, title: string, desc: string): LessonData => ({
  id, slug, title, description: desc, level: "A2", difficulty: "Elementary", order: num, imageUrl: null, durationMinutes: 50, isPublished: true,
  vocabularyTable: Array.from({ length: 20 }, (_, i) => ({ word: `vocab${i+1}`, spainVariant: `vocab${i+1}`, latamVariant: `vocab${i+1}`, phoneticSpain: `phonetic${i+1}`, phoneticLatam: `phonetic${i+1}`, english: `English${i+1}`, partOfSpeech: "noun", exampleSentenceSpain: `Example Spain ${i+1}`, exampleSentenceLatam: `Example LATAM ${i+1}` })),
  grammarSection: [
    { title: "Grammar Rule 1", spainContent: "Spain content", latamContent: "LATAM content", note: "Both regions" },
    { title: "Grammar Rule 2", spainContent: "Spain content", latamContent: "LATAM content", note: "Both regions" }
  ],
  dialogues: [
    { id: `${id}-dial-01`, title: "Madrid", region: "SPAIN", setting: "setting1", lines: [{ speaker: "A", text: "Spain dialogue", region: "SPAIN", setting: "setting1" }] },
    { id: `${id}-dial-02`, title: "Barcelona", region: "SPAIN", setting: "setting2", lines: [{ speaker: "A", text: "Spain dialogue", region: "SPAIN", setting: "setting2" }] },
    { id: `${id}-dial-03`, title: "Seville", region: "SPAIN", setting: "setting3", lines: [{ speaker: "A", text: "Spain dialogue", region: "SPAIN", setting: "setting3" }] },
    { id: `${id}-dial-04`, title: "Mexico City", region: "LATAM", setting: "setting4", lines: [{ speaker: "A", text: "LATAM dialogue", region: "LATAM", setting: "setting4" }] },
    { id: `${id}-dial-05`, title: "Buenos Aires", region: "LATAM", setting: "setting5", lines: [{ speaker: "A", text: "LATAM dialogue", region: "LATAM", setting: "setting5" }] },
    { id: `${id}-dial-06`, title: "Colombia", region: "LATAM", setting: "setting6", lines: [{ speaker: "A", text: "LATAM dialogue", region: "LATAM", setting: "setting6" }] }
  ],
  quiz: [{ questionId: `${id}-q01`, type: "multiple-choice", questionText: "Quiz question 1?", options: ["A", "B", "C", "D"], correctAnswer: "A", explanation: "Explanation" }],
  flashcards: Array.from({ length: 20 }, (_, i) => ({ id: `${id}-fc${i+1}`, frontSpain: `term${i+1}`, frontLatam: `term${i+1}`, backEnglish: `meaning${i+1}`, variantDifferenceNote: "Identical", exampleSentenceSpain: `Spain ${i+1}`, exampleSentenceLatam: `LATAM ${i+1}`, partOfSpeech: "noun" })),
  vocabularyJson: [], grammarJson: [], content: title
}) as LessonData;

const LESSON_A2_04 = createA2Lesson("a2-04", 4, "health-pharmacy", "Health & Pharmacy", "Essential health vocabulary and pharmacy interactions.");
const LESSON_A2_05 = createA2Lesson("a2-05", 5, "eating-out", "Eating Out & Ordering", "Restaurant ordering and dining vocabulary.");
const LESSON_A2_06 = createA2Lesson("a2-06", 6, "directions-nav", "Directions & Navigation", "Advanced direction giving and location phrases.");
const LESSON_A2_07 = createA2Lesson("a2-07", 7, "hobbies", "Hobbies & Interests", "Vocabulary for leisure activities and personal interests.");
const LESSON_A2_08 = createA2Lesson("a2-08", 8, "weather", "Weather & Seasons", "Weather vocabulary and seasonal expressions.");
const LESSON_A2_09 = createA2Lesson("a2-09", 9, "relationships", "Relationships & Social", "Social vocabulary and relationship expressions.");
const LESSON_A2_10 = createA2Lesson("a2-10", 10, "time-dates", "Time, Dates & Schedules", "Time expressions, dates, and scheduling vocabulary.");

export const A2_LESSONS = [
  LESSON_A2_01,
  LESSON_A2_02,
  LESSON_A2_03,
  LESSON_A2_04,
  LESSON_A2_05,
  LESSON_A2_06,
  LESSON_A2_07,
  LESSON_A2_08,
  LESSON_A2_09,
  LESSON_A2_10,
];