import type { LessonData } from "./lessons-data";

const LESSON_C2_01: LessonData = {
  id: "c2-01",
  title: "Classical & Modern Literature",
  level: "C2",
  description:
    "Analyzing structural shifts in Peninsular prose vs LATAM magical realism syntax. Deep dive into authorial voice, narrative technique, and stylistic evolution.",
  regionalVocabulary: [
    {
      term: "la prosa estructurada",
      regionVariants: { spain: "la narrativa peninsular", latam: "la narrativa latinoamericana" },
      definition: "Narrative prose structure and technique",
      phonamicSpain: "lah PRO-sah es-trook-too-RAH-dah",
      phonamicLatam: "lah PRO-sah es-trook-too-RAH-dah",
      examples: ["García Márquez utiliza la prosa mágica.", "La estructura narrativa de Cortázar es experimental."],
    },
    {
      term: "el realismo mágico",
      regionVariants: { spain: "la ficción fantástica", latam: "el realismo mágico" },
      definition: "Magical realism; narrative blending reality and the fantastical",
      phonamicSpain: "el reh-ah-LEES-moh MAH-hee-koh",
      phonamicLatam: "el reh-ah-LEES-moh MAH-hee-koh",
      examples: ["El realismo mágico caracteriza la literatura latinoamericana.", "García Márquez perfeccionó el realismo mágico."],
    },
    {
      term: "la voz narrativa",
      regionVariants: { spain: "la perspectiva del narrador", latam: "la perspectiva narrativa" },
      definition: "Narrative voice; authorial perspective and tone",
      phonamicSpain: "lah vohz nah-rah-THEE-vah",
      phonamicLatam: "lah vohz nah-rah-tee-VAH",
      examples: ["La voz narrativa de Unamuno es introspectiva.", "La perspectiva de Cortázar es fragmentada."],
    },
    {
      term: "la disolución temporal",
      regionVariants: { spain: "la ruptura cronológica", latam: "el desorden temporal" },
      definition: "Temporal dissolution; non-linear time structure in narrative",
      phonamicSpain: "lah dee-so-loo-see-OHN tem-poh-RAHL",
      phonamicLatam: "lah dee-so-loo-see-OHN tem-poh-RAHL",
      examples: ["Cortázar experimenta con la disolución temporal.", "El tiempo lineal desaparece en la novela."],
    },
    {
      term: "el monólogo interior",
      regionVariants: { spain: "la corriente de conciencia", latam: "el flujo de conciencia" },
      definition: "Stream of consciousness; interior monologue technique",
      phonamicSpain: "el moh-NOH-loh-goh in-te-ree-OHR",
      phonamicLatam: "el moh-NOH-loh-goh in-te-ree-OHR",
      examples: ["Joyce utiliza el monólogo interior.", "La corriente de conciencia revela la mente del personaje."],
    },
    {
      term: "la metáfora extendida",
      regionVariants: { spain: "el símbolo desarrollado", latam: "la metáfora sostenida" },
      definition: "Extended metaphor; sustained symbolic language",
      phonamicSpain: "lah me-TAH-foh-rah ex-ten-DEE-dah",
      phonamicLatam: "lah me-TAH-foh-rah ex-ten-DEE-dah",
      examples: ["La muerte es una metáfora extendida en la novela.", "Los símbolos desarrollados enriquecen la narrativa."],
    },
    {
      term: "la intertextualidad",
      regionVariants: { spain: "las referencias literarias", latam: "los ecos textuales" },
      definition: "Intertextuality; references and echoes between texts",
      phonamicSpain: "lah in-ter-teks-too-ah-lee-DAHD",
      phonamicLatam: "lah in-ter-teks-too-ah-lee-DAHD",
      examples: ["Borges juega con la intertextualidad.", "Las referencias a Cervantes enriquecen la obra."],
    },
    {
      term: "el pastiche literario",
      regionVariants: { spain: "la imitación estilística", latam: "la parodia literaria" },
      definition: "Literary pastiche; stylistic imitation or parody",
      phonamicSpain: "el pas-TEESH lee-te-RAH-ree-oh",
      phonamicLatam: "el pas-TEESH lee-te-RAH-ree-oh",
      examples: ["Cortázar utiliza el pastiche para criticar géneros literarios.", "La parodia exagera los estilos clásicos."],
    },
    {
      term: "la fragmentación narrativa",
      regionVariants: { spain: "la estructura fragmentada", latam: "la discontinuidad narrativa" },
      definition: "Narrative fragmentation; discontinuous story structure",
      phonamicSpain: "lah frag-men-tah-see-OHN nah-rah-THEE-vah",
      phonamicLatam: "lah frag-men-tah-see-OHN nah-rah-tee-VAH",
      examples: ["La fragmentación narrativa desorienta al lector.", "Los capítulos no siguen un orden cronológico."],
    },
    {
      term: "el perspectivismo narrativo",
      regionVariants: { spain: "las múltiples perspectivas", latam: "la polifonía narrativa" },
      definition: "Narrative perspectivism; multiple simultaneous viewpoints",
      phonamicSpain: "el per-spec-tee-VEES-moh nah-rah-THEE-voh",
      phonamicLatam: "el per-spec-tee-VEES-moh nah-rah-tee-VOH",
      examples: ["La novela presenta el perspectivismo narrativo total.", "Cada personaje tiene su propia voz."],
    },
    {
      term: "la densidad simbólica",
      regionVariants: { spain: "la riqueza metafórica", latam: "la abundancia de símbolos" },
      definition: "Symbolic density; concentration of symbolic language",
      phonamicSpain: "lah den-see-DAHD seem-BOH-lee-kah",
      phonamicLatam: "lah den-see-DAHD seem-BOH-lee-kah",
      examples: ["La densidad simbólica de la obra es abrumadora.", "Cada elemento tiene múltiples significados."],
    },
    {
      term: "la autorreferencialidad",
      regionVariants: { spain: "la reflexividad textual", latam: "el metarrelato" },
      definition: "Self-referentiality; text that refers to itself and its own creation",
      phonamicSpain: "lah ow-toh-re-fen-see-ah-lee-DAHD",
      phonamicLatam: "lah ow-toh-re-fen-see-ah-lee-DAHD",
      examples: ["Borges practica la autorreferencialidad extrema.", "El narrador es consciente de su propia ficción."],
    },
    {
      term: "el realismo sucio",
      regionVariants: { spain: "la narrativa brutal", latam: "el minimalismo narrativo" },
      definition: "Dirty realism; gritty, minimalist literary style",
      phonamicSpain: "el reh-ah-LEES-moh SOO-see-oh",
      phonamicLatam: "el reh-ah-LEES-moh SOO-see-oh",
      examples: ["El realismo sucio rechaza la ornamentación.", "Los detalles crudos crean autenticidad."],
    },
    {
      term: "la nostalgia estilística",
      regionVariants: { spain: "la evocación del pasado literario", latam: "el retorno a géneros antiguos" },
      definition: "Stylistic nostalgia; evocation of past literary forms",
      phonamicSpain: "lah nos-TAHL-hee-ah es-tee-LEES-tee-kah",
      phonamicLatam: "lah nos-TAHL-hee-ah es-tee-LEES-tee-kah",
      examples: ["La nostalgia estilística evoca novelas picarescas.", "Revivir géneros antiguos con nuevo sentido."],
    },
    {
      term: "la experimentación formal",
      regionVariants: { spain: "la ruptura de convenciones", latam: "la innovación estructural" },
      definition: "Formal experimentation; breaking narrative conventions",
      phonamicSpain: "lah ex-per-ee-men-tah-see-OHN for-MAHL",
      phonamicLatam: "lah ex-per-ee-men-tah-see-OHN for-MAHL",
      examples: ["La experimentación formal rechaza la narrativa lineal.", "Nuevas estructuras desafían las expectativas del lector."],
    },
    {
      term: "la poesía en prosa",
      regionVariants: { spain: "la prosa poética", latam: "el poema en prosa" },
      definition: "Poetry in prose; lyrical, poetic narrative language",
      phonamicSpain: "lah poh-eh-SEE-ah en PROH-sah",
      phonamicLatam: "lah poh-eh-SEE-ah en PROH-sah",
      examples: ["Baudelaire perfecciona la poesía en prosa.", "La belleza lírica enriquece la narrativa."],
    },
    {
      term: "la sinestesia narrativa",
      regionVariants: { spain: "la confusión sensorial", latam: "la mezcla de sentidos" },
      definition: "Narrative synesthesia; blending of sensory descriptions",
      phonamicSpain: "lah see-nes-TEH-see-ah nah-rah-THEE-vah",
      phonamicLatam: "lah see-nes-TEH-see-ah nah-rah-tee-VAH",
      examples: ["La sinestesia describe colores sonoros.", "Los sentidos se entrelazan en la descripción."],
    },
    {
      term: "la deconstrucción textual",
      regionVariants: { spain: "el cuestionamiento de significados", latam: "el análisis de sentidos" },
      definition: "Textual deconstruction; analysis and dismantling of meaning",
      phonamicSpain: "lah de-kons-trook-see-OHN teks-TOO-ahl",
      phonamicLatam: "lah de-kons-trook-see-OHN teks-TOO-ahl",
      examples: ["La deconstrucción cuestiona los significados fijos.", "El sentido se disuelve y se reconstruye."],
    },
  ],
  grammarSections: [
    {
      title: "Subjunctive in Literary Analysis",
      rules: [
        "Use subjunctive after expressions of possibility, doubt, and interpretation in literary criticism",
        "Pattern: 'Es posible que el narrador intente...' (It's possible that the narrator intends...)",
        "In Peninsular Spanish: stronger emphasis on subjunctive uncertainty; LATAM often permits indicative in informal contexts",
        "Literary convention favors subjunctive for analytical distance and hedging",
      ],
      culturalNote:
        "Spanish academic prose preserves subjunctive rigor; LATAM criticism often blends subjunctive/indicative for conversational tone.",
    },
    {
      title: "Conditional Perfect for Counterfactual Analysis",
      rules: [
        "Form: habría + past participle (I would have written...)",
        "Used to speculate on alternative literary outcomes or authorial intentions",
        "Pattern: 'Si Cortázar hubiera seguido la estructura lineal, la novela habría sido diferente.'",
        "Conveys sophisticated literary hypotheticals",
      ],
      culturalNote:
        "Common in both Spain and LATAM academic discourse; demonstrates mastery of advanced speculation in literary commentary.",
    },
  ],
  dialogueScenarios: [
    {
      region: "spain",
      setting: "Universidad de Madrid - Seminario de Literatura Moderna",
      characters: ["Profesora Alicia (literature professor)", "Eduardo (graduate student)"],
      dialogue: [
        { speaker: "Profesora Alicia", text: "Eduardo, explica cómo Cortázar subvierte la estructura narrativa en 'Rayuela'." },
        { speaker: "Eduardo", text: "El autor fragmenta completamente la linealidad. Propone múltiples órdenes de lectura, desafiando la pasividad del lector." },
        { speaker: "Profesora Alicia", text: "Exactamente. ¿Y cuál sería el efecto si la novela mantuviera una estructura convencional?" },
        { speaker: "Eduardo", text: "Habría perdido la capacidad de cuestionar nuestra relación con el texto. La fragmentación es el mensaje." },
        { speaker: "Profesora Alicia", text: "Bien. Observa también el perspectivismo: cada capítulo adopta una voz narrativa distinta. ¿Cómo interpreta esto?" },
        { speaker: "Eduardo", text: "Sugiere que no existe una verdad única. La realidad es multifacética, percibida simultáneamente desde perspectivas incompatibles." },
      ],
    },
    {
      region: "spain",
      setting: "Café Literario, Barcelona",
      characters: ["Mariana (writer)", "Jaume (critic)"],
      dialogue: [
        { speaker: "Jaume", text: "Tu última novela incorpora elementos de realismo mágico sin ser propiamente mágica. ¿Intención deliberada?" },
        { speaker: "Mariana", text: "Intento habitar el espacio entre lo real y lo imposible. La técnica de García Márquez me fascina, pero la rechazo en su forma pura." },
        { speaker: "Jaume", text: "Observo pastiche, entonces. ¿O más bien diálogo intertextual?" },
        { speaker: "Mariana", text: "Conversación consciente con la tradición. Cito, subviero, reconstruyo. La autorreferencialidad expone el proceso." },
        { speaker: "Jaume", text: "Arriesgado. Muchos lectores encontrarán la densidad simbólica excesiva." },
        { speaker: "Mariana", text: "Tal vez. Pero si sacrificara la complejidad por accesibilidad, la novela pierde su integridad." },
      ],
    },
    {
      region: "spain",
      setting: "Biblioteca Nacional de España - Sala de Estudios",
      characters: ["Prof. González (archivist)", "Laura (PhD candidate)"],
      dialogue: [
        { speaker: "Prof. González", text: "Analiza el monólogo interior de Molly Bloom en el 'Ulises' de Joyce y su influencia en Castellanos." },
        { speaker: "Laura", text: "Castellanos absorbe la técnica: la corriente de conciencia sin puntuación, la yuxtaposición de recuerdos disociados." },
        { speaker: "Prof. González", text: "Pero ¿reproduce simplemente, o transforma?" },
        { speaker: "Laura", text: "Transforma radicalmente. Mientras Joyce fragmenta la consciencia mediante multiplicidad formal, Castellanos la desmorona desde la intención introspectiva. El efecto es más visceral." },
        { speaker: "Prof. González", text: "Interesante distinción. ¿Podrías articularla más?" },
        { speaker: "Laura", text: "Joyce expone la mente como caos; Castellanos revela la mente como conflicto existencial. La forma sirve a psicologías distintas." },
      ],
    },
    {
      region: "latam",
      setting: "ITAM, Ciudad de México - Seminario Avanzado",
      characters: ["Maestro Rodríguez (professor)", "Carlos (advanced student)"],
      dialogue: [
        { speaker: "Maestro Rodríguez", text: "García Márquez y Vargas Llosa emplean técnicas afines pero persiguen intenciones opuestas. Explica." },
        { speaker: "Carlos", text: "García Márquez integra lo fantástico en lo cotidiano sin justificación realista. Vargas Llosa, aun siendo innovador, ancla la fantasía en contexto histórico y político." },
        { speaker: "Maestro Rodríguez", text: "¿Diferencia ideológica, entonces?" },
        { speaker: "Carlos", text: "Exacto. García Márquez celebra la ambigüedad; Vargas Llosa insiste en que la realidad política prevalece sobre la imaginación." },
        { speaker: "Maestro Rodríguez", text: "¿Y Cortázar? ¿Dónde se sitúa en este espectro?" },
        { speaker: "Carlos", text: "Cortázar rechaza ambos. Su fragmentación narrativa propone que ni la magia ni la política importan; importa cómo el lector construye significado." },
      ],
    },
    {
      region: "latam",
      setting: "Librería El Fondo, Santiago de Chile",
      characters: ["Sofía (bookseller/critic)", "Miguel (author)"],
      dialogue: [
        { speaker: "Sofía", text: "Tu novela practica la experimentación formal con moderación. ¿Miedo a alienar lectores?" },
        { speaker: "Miguel", text: "No miedo: responsabilidad. La innovación debe servir al tema, no ostentarse." },
        { speaker: "Sofía", text: "Muchos contemporáneos considerarían eso conservadurismo." },
        { speaker: "Miguel", text: "Quizá. Pero reviso a Llosa, Cortázar, Valenzuela. Descubro que los más radicales integran estructura y propósito indisolublemente." },
        { speaker: "Sofía", text: "¿Ejemplo?" },
        { speaker: "Miguel", text: "'Operación masacre' de Valenzuela: la fragmentación documenta la represión misma. Forma y contenido son idénticos." },
      ],
    },
    {
      region: "latam",
      setting: "Universidad Nacional Autónoma de México - Sala de Seminarios",
      characters: ["Dra. Sáenz (literature specialist)", "Julia (graduate student)"],
      dialogue: [
        { speaker: "Dra. Sáenz", text: "Examina el desorden temporal en 'La muerte de Artemio Cruz'. ¿Estrategia narrativa o reflejo psicológico?" },
        { speaker: "Julia", text: "Ambos. La disolución temporal replica la fragmentación mental de Artemio en su lecho de muerte, pero también cuestiona cómo narramos la historia personal." },
        { speaker: "Dra. Sáenz", text: "¿Por qué Fuentes eligió deliberadamente rechazar la cronología?" },
        { speaker: "Julia", text: "Para revelar que la identidad no es lineal ni coherente. Artemio existe simultáneamente como joven ambicioso, hombre poderoso y anciano moribundo. La estructura expone esta multiplicidad." },
        { speaker: "Dra. Sáenz", text: "Entonces, la forma es inseparable del significado existencial." },
        { speaker: "Julia", text: "Completamente. Sin la fragmentación, la novela sería otra biografía. Con ella, se convierte en investigación metafísica sobre la identidad." },
      ],
    },
  ],
  quizzes: [
    {
      question: "¿Cuál es la diferencia fundamental entre la prosa de García Márquez y la de Cortázar?",
      options: [
        "García Márquez mantiene una narrativa lineal; Cortázar la fragmenta completamente.",
        "García Márquez integra lo mágico en lo cotidiano sin justificación; Cortázar cuestiona la estructura narrativa misma.",
        "García Márquez es más realista; Cortázar es puramente fantástico.",
        "No existe diferencia significativa; ambos practican el realismo mágico idénticamente.",
      ],
      correctAnswer: 1,
      explanation:
        "García Márquez usa realismo mágico para aceptar lo fantástico como normal (ej: Remedios la Bella asciende), mientras que Cortázar desmorona la narrativa lineal misma, cuestionando cómo la estructura de una novela moldea el significado ('Rayuela').",
    },
    {
      question: "¿Qué es la intertextualidad en el contexto de la literatura moderna?",
      options: [
        "La capacidad de un texto de referirse a otros textos previos mediante citas, alusiones, y ecos estilísticos.",
        "La inclusión de múltiples perspectivas narrativas dentro de una sola novela.",
        "El uso de técnicas de poesía dentro de la prosa narrativa.",
        "La fragmentación del tiempo lineal en la estructura de la novela.",
      ],
      correctAnswer: 0,
      explanation:
        "La intertextualidad describe cómo los textos literarios dialogan con otros textos. Borges ejemplifica esto magistralmente: sus cuentos citan, reinterpretan y parodian obras clásicas, creando nuevos significados mediante las alusiones.",
    },
    {
      question: "¿Cuál es el efecto narrativo del perspectivismo en 'Cien años de soledad'?",
      options: [
        "Crea una perspectiva única del narrador omnisciente.",
        "Permite múltiples interpretaciones simultáneas de los mismos eventos, reflejando la complejidad de la realidad.",
        "Simplifica la trama mediante la eliminación de perspectivas secundarias.",
        "Establece una jerarquía clara entre perspectivas narrativas.",
      ],
      correctAnswer: 1,
      explanation:
        "García Márquez entrelaza múltiples perspectivas sobre Macondo, permitiendo que el mismo evento sea visto desde ángulos contradictorios, reflejando cómo la realidad es multifacética y las verdades son relativas.",
    },
    {
      question: "¿Qué distingue la autorreferencialidad en Borges de la de Cortázar?",
      options: [
        "Borges no es autorreferencial; Cortázar sí.",
        "Borges practica autorreferencialidad mediante la inversión intelectual (bibliotecas, espejos, laberintos); Cortázar la expone mediante la ruptura formal de la novela misma.",
        "Ambos son idénticamente autorreferenciales.",
        "Cortázar es autorreferencial; Borges practica el realismo mágico.",
      ],
      correctAnswer: 1,
      explanation:
        "Borges crea un universo donde los libros contienen otros libros infinitamente (bibliotecas infinitas, el Aleph). Cortázar, en cambio, interrumpe 'Rayuela' con notas al pie del editor ficticio, exponiendo el proceso de construcción narrativa mismo.",
    },
    {
      question: "¿Cuál es la función de la densidad simbólica en la literatura de vanguardia?",
      options: [
        "Simplificar la lectura mediante símbolos explícitos.",
        "Crear múltiples capas de significado que requieren análisis profundo y permiten diversas interpretaciones.",
        "Eliminar la necesidad de interpretación mediante símbolos obvios.",
        "Decorar la narrativa sin afectar el significado central.",
      ],
      correctAnswer: 1,
      explanation:
        "La densidad simbólica deliberada (como en las novelas de Fuentes o los cuentos de Borges) obliga al lector a participar activamente en la construcción del significado, rechazando la pasividad interpretativa.",
    },
  ],
  flashcards: [
    { id: "c2-01-fc01", frontSpain: "realismo mágico", frontLatam: "realismo mágico", backEnglish: "Integration of magical elements into realistic narratives without explanation, normalizing the fantastic (García Márquez)", variantDifferenceNote: "Identical across regions; established term", exampleSentenceSpain: "El realismo mágico de García Márquez desafía la lógica convencional.", exampleSentenceLatam: "García Márquez popularizó el realismo mágico en toda América Latina.", partOfSpeech: "noun" },
    { id: "c2-01-fc02", frontSpain: "fragmentación narrativa", frontLatam: "fragmentación narrativa", backEnglish: "Breaking linear story structure into discontinuous, non-chronological pieces (Cortázar, Fuentes)", variantDifferenceNote: "Identical across regions; literary terminology", exampleSentenceSpain: "La fragmentación narrativa de Cortázar desorienta al lector deliberadamente.", exampleSentenceLatam: "Fuentes utiliza la fragmentación para revelar múltiples perspectivas.", partOfSpeech: "noun" },
    { id: "c2-01-fc03", frontSpain: "perspectivismo", frontLatam: "perspectivismo", backEnglish: "Multiple simultaneous viewpoints revealing the multiplicity and relativity of reality", variantDifferenceNote: "Identical across regions; philosophical term", exampleSentenceSpain: "El perspectivismo de García Márquez permite múltiples interpretaciones.", exampleSentenceLatam: "El perspectivismo narrativo enriquece la complejidad de la novela.", partOfSpeech: "noun" },
    { id: "c2-01-fc04", frontSpain: "autorreferencialidad", frontLatam: "autorreferencialidad", backEnglish: "Text that refers to itself, to its own creation, exposing the fictionality of narrative (Borges)", variantDifferenceNote: "Identical across regions; metafictional concept", exampleSentenceSpain: "La autorreferencialidad de Borges expone la construcción del texto.", exampleSentenceLatam: "Borges practica la autorreferencialidad extrema en 'Ficciones'.", partOfSpeech: "noun" },
    { id: "c2-01-fc05", frontSpain: "monólogo interior", frontLatam: "monólogo interior", backEnglish: "Stream of consciousness technique revealing unfiltered thought processes (Joyce influence)", variantDifferenceNote: "Identical across regions; literary technique", exampleSentenceSpain: "El monólogo interior de Joyce influye en la prosa moderna.", exampleSentenceLatam: "El monólogo interior revela la mente del personaje sin filtro.", partOfSpeech: "noun" },
    { id: "c2-01-fc06", frontSpain: "intertextualidad", frontLatam: "intertextualidad", backEnglish: "References, citations, and dialogues between texts, creating new meanings through textual echoes", variantDifferenceNote: "Identical across regions; literary theory term", exampleSentenceSpain: "La intertextualidad de Borges crea redes de significado complejas.", exampleSentenceLatam: "La intertextualidad permite que los textos dialoguen entre sí.", partOfSpeech: "noun" },
    { id: "c2-01-fc07", frontSpain: "metáfora extendida", frontLatam: "metáfora extendida", backEnglish: "Sustained symbolic language woven throughout a narrative, functioning at multiple levels", variantDifferenceNote: "Identical across regions; rhetorical device", exampleSentenceSpain: "La metáfora extendida del laberinto permea toda la novela.", exampleSentenceLatam: "La metáfora extendida funciona como estructura narrativa.", partOfSpeech: "noun" },
    { id: "c2-01-fc08", frontSpain: "disolución temporal", frontLatam: "disolución temporal", backEnglish: "Non-linear time structure; rejection of chronological progression in narrative", variantDifferenceNote: "Identical across regions; narrative technique", exampleSentenceSpain: "La disolución temporal en 'Rayuela' confunde deliberadamente al lector.", exampleSentenceLatam: "La disolución temporal revela la multiplicidad del ser.", partOfSpeech: "noun" },
    { id: "c2-01-fc09", frontSpain: "pastiche literario", frontLatam: "pastiche literario", backEnglish: "Deliberate imitation or parody of a literary style or genre, often for critical purposes", variantDifferenceNote: "Identical across regions; postmodern technique", exampleSentenceSpain: "El pastiche literario de Cortázar critica géneros establecidos.", exampleSentenceLatam: "El pastiche permite que los autores jueguen con tradiciones.", partOfSpeech: "noun" },
    { id: "c2-01-fc10", frontSpain: "densidad simbólica", frontLatam: "densidad simbólica", backEnglish: "Concentration of layered symbolic meanings requiring active reader interpretation", variantDifferenceNote: "Identical across regions; literary analysis term", exampleSentenceSpain: "La densidad simbólica de Fuentes exige análisis profundo.", exampleSentenceLatam: "La densidad simbólica enriquece la experiencia de lectura.", partOfSpeech: "noun" },
    { id: "c2-01-fc11", frontSpain: "deconstrucción textual", frontLatam: "deconstrucción textual", backEnglish: "Analysis dismantling fixed meanings, revealing instability of signification in texts", variantDifferenceNote: "Identical across regions; deconstructive theory", exampleSentenceSpain: "La deconstrucción textual cuestiona significados aparentes.", exampleSentenceLatam: "La deconstrucción revela las contradicciones internas del texto.", partOfSpeech: "noun" },
    { id: "c2-01-fc12", frontSpain: "sinestesia narrativa", frontLatam: "sinestesia narrativa", backEnglish: "Blending of sensory descriptions; describing visual elements in auditory terms, etc.", variantDifferenceNote: "Identical across regions; stylistic technique", exampleSentenceSpain: "La sinestesia narrativa describe colores como sonidos.", exampleSentenceLatam: "La sinestesia entrelaza los sentidos en la descripción.", partOfSpeech: "noun" },
    { id: "c2-01-fc13", frontSpain: "poesía en prosa", frontLatam: "poesía en prosa", backEnglish: "Lyrical, poetic language within narrative prose; hybrid form elevating prose to poetry", variantDifferenceNote: "Identical across regions; literary form", exampleSentenceSpain: "La poesía en prosa de Baudelaire influye en modernistas.", exampleSentenceLatam: "La poesía en prosa eleva lo ordinario a lo sublime.", partOfSpeech: "noun" },
    { id: "c2-01-fc14", frontSpain: "realismo sucio", frontLatam: "realismo sucio", backEnglish: "Minimalist, gritty narrative style focusing on unglamorous reality without ornament", variantDifferenceNote: "Identical across regions; literary movement", exampleSentenceSpain: "El realismo sucio rechaza la ornamentación estilística.", exampleSentenceLatam: "El realismo sucio presenta la vida tal como es.", partOfSpeech: "noun" },
    { id: "c2-01-fc15", frontSpain: "experimentación formal", frontLatam: "experimentación formal", backEnglish: "Breaking narrative conventions through innovative structure, typography, or technique", variantDifferenceNote: "Identical across regions; avant-garde concept", exampleSentenceSpain: "La experimentación formal de vanguardia desafía expectativas.", exampleSentenceLatam: "La experimentación abre nuevas posibilidades narrativas.", partOfSpeech: "noun" },
    { id: "c2-01-fc16", frontSpain: "nostalgia estilística", frontLatam: "nostalgia estilística", backEnglish: "Evoking past literary forms or genres while simultaneously critiquing or transforming them", variantDifferenceNote: "Identical across regions; postmodern approach", exampleSentenceSpain: "La nostalgia estilística evoca novelas picarescas con ironía.", exampleSentenceLatam: "La nostalgia permite reinterpretación de formas antiguas.", partOfSpeech: "noun" },
    { id: "c2-01-fc17", frontSpain: "voz narrativa", frontLatam: "voz narrativa", backEnglish: "Distinct authorial voice; unique perspective and tone of the narrator shaping interpretation", variantDifferenceNote: "Identical across regions; narrative element", exampleSentenceSpain: "La voz narrativa de Unamuno es intensamente personal.", exampleSentenceLatam: "La voz narrativa de Cortázar es única e inconfundible.", partOfSpeech: "noun" },
    { id: "c2-01-fc18", frontSpain: "perspectiva del narrador", frontLatam: "perspectiva del narrador", backEnglish: "Narrative perspective determining what is revealed, hidden, or interpreted by the reader", variantDifferenceNote: "Identical across regions; literary analysis", exampleSentenceSpain: "La perspectiva del narrador omnisciente todo lo sabe.", exampleSentenceLatam: "La perspectiva del narrador limita o expande la comprensión.", partOfSpeech: "noun" },
    { id: "c2-01-fc19", frontSpain: "ruptura cronológica", frontLatam: "ruptura cronológica", backEnglish: "Deliberate breaking of sequential time; rejection of linear temporal progression", variantDifferenceNote: "Identical across regions; narrative disruption", exampleSentenceSpain: "La ruptura cronológica desorient a deliberadamente.", exampleSentenceLatam: "La ruptura del tiempo expone múltiples realidades.", partOfSpeech: "noun" },
    { id: "c2-01-fc20", frontSpain: "flujo de conciencia", frontLatam: "flujo de conciencia", backEnglish: "Continuous stream of thoughts, memories, and sensations without logical organization", variantDifferenceNote: "Identical across regions; psychological technique", exampleSentenceSpain: "El flujo de conciencia revela la mente sin censura.", exampleSentenceLatam: "El flujo de conciencia es técnica de Joyce adoptada globalmente.", partOfSpeech: "noun" },
  ],
};

const LESSON_C2_02: LessonData = {
  id: "c2-02",
  title: "Abstract Philosophical Debates",
  level: "C2",
  description:
    "Formulating systemic existential arguments across historical academic tracks. Mastery of nuanced philosophical discourse, conditional argumentation, and epistemological positioning.",
  regionalVocabulary: [
    {
      term: "la ontología del ser",
      regionVariants: { spain: "el ser existencial", latam: "la esencia del ser" },
      definition: "Ontology; the study of being and existence itself",
      phonamicSpain: "lah on-toh-loh-HEE-ah del ser",
      phonamicLatam: "lah on-toh-loh-HEE-ah del ser",
      examples: ["Heidegger reformula la ontología medieval.", "La pregunta sobre el ser fundamenta toda filosofía."],
    },
    {
      term: "la epistemología del conocimiento",
      regionVariants: { spain: "la teoría del saber", latam: "los límites del conocimiento" },
      definition: "Epistemology; theory of knowledge and its foundations",
      phonamicSpain: "lah eh-pees-teh-moh-loh-HEE-ah",
      phonamicLatam: "lah eh-pees-teh-moh-loh-HEE-ah",
      examples: ["Descartes establece los fundamentos de la epistemología moderna.", "¿Cómo conocemos? Esta pregunta epistemológica es central."],
    },
    {
      term: "la fenomenología de la experiencia",
      regionVariants: { spain: "la estructura de la vivencia", latam: "cómo experimentamos lo real" },
      definition: "Phenomenology; study of consciousness and experience",
      phonamicSpain: "lah fe-noh-meh-noh-loh-HEE-ah",
      phonamicLatam: "lah fe-noh-meh-noh-loh-HEE-ah",
      examples: ["Husserl desarrolla la fenomenología moderna.", "La experiencia vivida es anterior al pensamiento conceptual."],
    },
    {
      term: "la dialéctica hegeliana",
      regionVariants: { spain: "la síntesis de contradicciones", latam: "tesis, antítesis, síntesis" },
      definition: "Hegelian dialectic; reconciliation of contradictions through thesis-antithesis-synthesis",
      phonamicSpain: "lah dee-ah-LEC-tee-kah eh-hel-ee-AH-nah",
      phonamicLatam: "lah dee-ah-LEC-tee-kah eh-hel-ee-AH-nah",
      examples: ["La dialéctica hegeliana modela toda filosofía posterior.", "Las contradicciones se resuelven en síntesis superior."],
    },
    {
      term: "la metafísica de la substancia",
      regionVariants: { spain: "la naturaleza última de las cosas", latam: "qué es lo fundamental" },
      definition: "Metaphysics of substance; what fundamentally exists",
      phonamicSpain: "lah me-tah-FEE-see-kah",
      phonamicLatam: "lah me-tah-FEE-see-kah",
      examples: ["Aristóteles define la substancia como lo que existe independientemente.", "¿Qué es realmente fundamental: la materia o el espíritu?"],
    },
    {
      term: "el nihilismo existencial",
      regionVariants: { spain: "la negación de valores absolutos", latam: "la falta de esencia" },
      definition: "Existential nihilism; rejection of inherent meaning or values",
      phonamicSpain: "el nee-ee-LEES-moh ex-ee-sten-see-AHL",
      phonamicLatam: "el nee-ee-LEES-moh ex-ee-sten-see-AHL",
      examples: ["Nietzsche critica el nihilismo pero lo aborda críticamente.", "Si no hay Dios, ¿existe valor alguno?"],
    },
    {
      term: "la hermenéutica de la interpretación",
      regionVariants: { spain: "el arte de comprender", latam: "cómo interpretamos significados" },
      definition: "Hermeneutics; theory of interpretation and understanding",
      phonamicSpain: "lah er-meh-NOO-tee-kah",
      phonamicLatam: "lah er-meh-NOO-tee-kah",
      examples: ["Gadamer desarrolla la hermenéutica moderna.", "Toda comprensión es interpretación; la objetividad es ilusoria."],
    },
    {
      term: "la aporía lógica",
      regionVariants: { spain: "la paradoja insoluble", latam: "el problema sin solución" },
      definition: "Aporia; logical paradox or unsolvable contradiction",
      phonamicSpain: "lah ah-poh-REE-ah LOH-hee-kah",
      phonamicLatam: "lah ah-poh-REE-ah LOH-hee-kah",
      examples: ["La aporía socrática expone los límites del conocimiento.", "¿Cómo salir de una contradicción lógica fundamental?"],
    },
    {
      term: "la teleología histórica",
      regionVariants: { spain: "el sentido de la historia", latam: "hacia dónde va la historia" },
      definition: "Historical teleology; idea that history moves toward predetermined ends",
      phonamicSpain: "lah te-leh-oh-loh-HEE-ah ees-TOH-ree-kah",
      phonamicLatam: "lah te-leh-oh-loh-HEE-ah ees-TOH-ree-kah",
      examples: ["Hegel propone una teleología dialéctica de la historia.", "¿Existe progreso inevitable o la historia es contingente?"],
    },
    {
      term: "la trascendencia kantiana",
      regionVariants: { spain: "lo que va más allá de la experiencia", latam: "aquello inaccesible" },
      definition: "Kantian transcendence; what lies beyond possible experience",
      phonamicSpain: "lah tras-sen-DEN-see-ah kan-tee-AH-nah",
      phonamicLatam: "lah tras-sen-DEN-see-ah kan-tee-AH-nah",
      examples: ["Kant limita el conocimiento a lo fenoménico, no lo nouménico.", "La cosa en sí permanece eternamente trascendente."],
    },
    {
      term: "el constructivismo social",
      regionVariants: { spain: "la construcción de significados colectivos", latam: "cómo la sociedad crea realidad" },
      definition: "Social constructivism; meaning is constructed through social interaction",
      phonamicSpain: "el kons-trook-tee-VEES-moh soh-see-AHL",
      phonamicLatam: "el kons-trook-tee-VEES-moh soh-see-AHL",
      examples: ["El género es un constructo social, no una esencia.", "La realidad es socialmente construida, no dada."],
    },
    {
      term: "la alteridad radical",
      regionVariants: { spain: "el otro irreducible", latam: "la diferencia absoluta" },
      definition: "Radical alterity; irreducible otherness that resists assimilation",
      phonamicSpain: "lah ahl-te-ree-DAHD rah-dee-KAHL",
      phonamicLatam: "lah ahl-te-ree-DAHD rah-dee-KAHL",
      examples: ["Levinas enfatiza la alteridad del otro.", "No podemos reducir el otro a categorías propias."],
    },
    {
      term: "la immanencia cartesiana",
      regionVariants: { spain: "la certeza del pensamiento", latam: "el yo pienso" },
      definition: "Cartesian immanence; the immediate certainty of thought itself",
      phonamicSpain: "lah ee-mah-NEN-see-ah kar-te-see-AH-nah",
      phonamicLatam: "lah ee-mah-NEN-see-ah kar-te-see-AH-nah",
      examples: ["Descartes establece el cogito como punto de partida indudable.", "Pienso, luego existo: la certeza más fundamental."],
    },
    {
      term: "la contingencia ontológica",
      regionVariants: { spain: "la posibilidad de no ser", latam: "lo que podría no existir" },
      definition: "Ontological contingency; what could possibly not exist",
      phonamicSpain: "lah kon-tin-HEN-see-ah on-toh-LOH-hee-kah",
      phonamicLatam: "lah kon-tin-HEN-see-ah on-toh-LOH-hee-kah",
      examples: ["Todo lo contingente requiere una causa necesaria.", "¿Por qué existe algo en lugar de nada?"],
    },
    {
      term: "la esencia vs la existencia",
      regionVariants: { spain: "la naturaleza vs el acto de ser", latam: "qué somos vs que estamos aquí" },
      definition: "Essence vs existence; nature versus actual being",
      phonamicSpain: "lah es-EN-see-ah vs la egg-zee-STEN-see-ah",
      phonamicLatam: "lah es-EN-see-ah vs la egg-zee-STEN-see-ah",
      examples: ["Sartre invierte la relación: la existencia precede la esencia.", "Los seres humanos existen primero, luego definen su naturaleza."],
    },
    {
      term: "el solipsismo metodológico",
      regionVariants: { spain: "dudar de todo excepto el pensamiento propio", latam: "el yo como único cierto" },
      definition: "Methodological solipsism; systematic doubt of everything except one's own thought",
      phonamicSpain: "el soh-leep-SEES-moh me-toh-doh-LOH-hee-koh",
      phonamicLatam: "el soh-leep-SEES-moh me-toh-doh-LOH-hee-koh",
      examples: ["El método cartesiano practica un solipsismo metodológico temporal.", "¿Cómo trascender la certeza solo de mi propio pensamiento?"],
    },
    {
      term: "la reducción fenomenológica",
      regionVariants: { spain: "poner entre paréntesis la realidad", latam: "suspender la creencia en el mundo" },
      definition: "Phenomenological reduction; suspending belief in external reality to examine consciousness",
      phonamicSpain: "lah re-dook-see-OHN fe-noh-meh-noh-LOH-hee-kah",
      phonamicLatam: "lah re-dook-see-OHN fe-noh-meh-noh-LOH-hee-kah",
      examples: ["Husserl propone la epoché o reducción fenomenológica.", "Suspendemos la realidad para examinar cómo la consciencia la constituye."],
    },
    {
      term: "la diferancia derridiana",
      regionVariants: { spain: "la diferencia y la postergación de sentido", latam: "el diferimiento del significado" },
      definition: "Derridean différance; play of difference and deferral of meaning",
      phonamicSpain: "lah dee-fe-REN-see-ah de-ree-dee-AH-nah",
      phonamicLatam: "lah dee-fe-REN-see-ah de-ree-dee-AH-nah",
      examples: ["Derrida cuestiona la presencia y la identidad mediante la diferancia.", "El significado nunca está completamente presente; siempre se difiere."],
    },
    {
      term: "el acto de habla performativo",
      regionVariants: { spain: "la palabra que actúa", latam: "decir es hacer" },
      definition: "Performative speech act; utterance that performs an action rather than describing",
      phonamicSpain: "el AHK-toh de AH-blah per-for-mah-TEE-voh",
      phonamicLatam: "el AHK-toh de AH-blah per-for-mah-TEE-voh",
      examples: ["Austin muestra que 'prometo' realiza una acción, no describe.", "El lenguaje no solo describe la realidad; también la modifica."],
    },
  ],
  grammarSections: [
    {
      title: "Conditional Subjunctive for Philosophical Speculation",
      rules: [
        "Form: Si + imperfect subjunctive, conditional + imperfect subjunctive",
        "Pattern: 'Si existiera Dios, ¿cuál sería la naturaleza del mal?' (If God existed, what would be the nature of evil?)",
        "Used to formulate counterfactual philosophical arguments and thought experiments",
        "Spanish: subjunctive maintains uncertainty; omitting subjunctive weakens the hypothetical nature",
      ],
      culturalNote:
        "Peninsular Spanish maintains stricter subjunctive in philosophical contexts; LATAM varies more in formality but preserves subjunctive in academic settings.",
    },
    {
      title: "The Passive Voice for Objective Argumentation",
      rules: [
        "Form: ser + past participle (es considerado, fue propuesto)",
        "Used to distance the speaker from claims, lending objectivity to arguments",
        "Alternative: se + third person verb (se propone que...)",
        "Intellectual convention: passive voice conveys neutrality and scholarly distance",
      ],
      culturalNote:
        "Peninsular academic Spanish favors passive voice heavily; LATAM permits more active voice even in formal contexts, but philosophical discourse in both regions uses passive for neutrality.",
    },
  ],
  dialogueScenarios: [
    {
      region: "spain",
      setting: "Universidad de Salamanca - Seminario de Filosofía Medieval",
      characters: ["Profesor García (medieval philosopher)", "Alejandro (PhD student)"],
      dialogue: [
        { speaker: "Profesor García", text: "Tomás de Aquino sintetiza Aristóteles con la teología cristiana. ¿Cómo resuelve la contradicción entre el ser necesario y la contingencia?" },
        { speaker: "Alejandro", text: "Propone la distinción entre esencia y existencia. En los seres contingentes, la esencia no incluye la existencia; esta debe ser conferida por un ser necesario." },
        { speaker: "Profesor García", text: "Exactamente. ¿Y si ese argumento fuera circular? Si Dios debe ser causa de toda existencia, ¿qué causa la existencia de Dios?" },
        { speaker: "Alejandro", text: "Aquino responde que Dios es el único ser cuya esencia es su existencia. La distinción no aplica a Dios." },
        { speaker: "Profesor García", text: "Interesante. Pero ¿no asume esto lo que debe demostrar? Aceptamos como dado que existe un ser en el que esencia y existencia coinciden." },
        { speaker: "Alejandro", text: "Cierto. Es un límite lógico, una aporía: no podemos trascender la pregunta mediante la razón pura." },
      ],
    },
    {
      region: "spain",
      setting: "Café Filosófico, Valladolid",
      characters: ["Marta (epistemologist)", "Luis (skeptic)"],
      dialogue: [
        { speaker: "Luis", text: "Afirmas que el conocimiento científico es válido. Pero ¿cuál es el fundamento de esa validez?" },
        { speaker: "Marta", text: "La intersubjetividad: los resultados son verificables por múltiples observadores bajo condiciones idénticas." },
        { speaker: "Luis", text: "Pero la validez de esa verificación descansa en suposiciones no verificadas: que nuestros sentidos son confiables, que la lógica es universal..." },
        { speaker: "Marta", text: "Así es. Toda epistemología descansa en fundamentos últimos que no pueden justificarse sin circularidad." },
        { speaker: "Luis", text: "¿Entonces admites que el conocimiento es fundamentalmente frágil?" },
        { speaker: "Marta", text: "Sí, pero la fragilidad epistemológica no invalida la práctica científica. Operamos bajo la mejor justificación disponible." },
      ],
    },
    {
      region: "spain",
      setting: "Instituto de Investigaciones Filosóficas, Madrid",
      characters: ["Dr. Ruiz (phenomenologist)", "Isabel (student)"],
      dialogue: [
        { speaker: "Dr. Ruiz", text: "Husserl propone la epoché: suspendemos la creencia en el mundo para examinar la consciencia. ¿Cómo es posible suspender el mundo mientras vivimos en él?" },
        { speaker: "Isabel", text: "Es una suspensión metodológica, no literal. Continuamos viviendo, pero examinamos cómo la consciencia constituye el significado del mundo." },
        { speaker: "Dr. Ruiz", text: "Pero ¿no es la suspensión misma un acto que presupone la realidad del mundo? Si el mundo no es real, ¿qué suspendemos?" },
        { speaker: "Isabel", text: "Suspendemos la creencia en la independencia del mundo, no la experiencia. El mundo se revela como correlato de la consciencia." },
        { speaker: "Dr. Ruiz", text: "Entonces la fenomenología es idealismo: la realidad depende de la consciencia." },
        { speaker: "Isabel", text: "Husserl lo rechazaría, pero sí: la experiencia y su significado son correlativos. No podemos acceder al mundo 'en sí', solo como vivido." },
      ],
    },
    {
      region: "latam",
      setting: "UNAM, Ciudad de México - Seminario de Filosofía Contemporánea",
      characters: ["Maestro Velázquez (philosopher)", "Natalia (advanced student)"],
      dialogue: [
        { speaker: "Maestro Velázquez", text: "Sartre afirma que la existencia precede la esencia: primero existimos, luego nos definimos. ¿Contradice esto la naturaleza humana?" },
        { speaker: "Natalia", text: "Exacto. Si no tenemos esencia predeterminada, somos totalmente libres—y totalmente responsables—de construirnos a nosotros mismos." },
        { speaker: "Maestro Velázquez", text: "Pero ¿no heredamos limitaciones biológicas, culturales, sociales? ¿Cómo es libertad absoluta si estamos condicionados?" },
        { speaker: "Natalia", text: "Sartre diría que la libertad no significa ausencia de limitaciones, sino ausencia de esencia determinada. Respondemos creativamente a nuestras circunstancias." },
        { speaker: "Maestro Velázquez", text: "¿Y si esa respuesta creativa es ella misma determinada por factores inconscientes, como sugiere Lacan?" },
        { speaker: "Natalia", text: "Entonces la libertad sería ilusión. Pero Sartre insistiría que incluso ante lo inconsciente, la libertad es la forma en que asumimos nuestras limitaciones." },
      ],
    },
    {
      region: "latam",
      setting: "Colegio de México - Seminario Avanzado",
      characters: ["Dra. Morales (hermeneutics specialist)", "Carlos (graduate student)"],
      dialogue: [
        { speaker: "Dra. Morales", text: "Gadamer argumenta que toda comprensión es interpretación, que la objetividad pura es imposible. ¿No elimina esto la diferencia entre ciencia y opinión?" },
        { speaker: "Carlos", text: "No elimina: reconoce que los intérpretes aportan sus propios horizontes históricos. Pero la verdad emerge del diálogo entre horizonte histórico e horizonte del texto." },
        { speaker: "Dra. Morales", text: "Entonces, ¿cómo distinguimos entre una interpretación válida y una distorsión?" },
        { speaker: "Carlos", text: "Por la coherencia interna de la interpretación y su poder explicativo. Una interpretación coherente con el texto como totalidad tiene más validez que una arbitraria." },
        { speaker: "Dra. Morales", text: "Pero ¿no circulamos? Juzgamos coherencia con el texto usando criterios que el texto mismo debe validar." },
        { speaker: "Carlos", text: "Sí: el círculo hermenéutico es inevitable. Pero no es vicioso; es el proceso mediante el cual comprendemos cualquier cosa." },
      ],
    },
    {
      region: "latam",
      setting: "Universidad de Buenos Aires - Sala de Seminarios",
      characters: ["Prof. Fuente (metaphysician)", "Rodrigo (doctoral student)"],
      dialogue: [
        { speaker: "Prof. Fuente", text: "Heidegger pregunta: '¿Por qué existe algo en lugar de nada?' ¿Es esta pregunta significativa o un sin sentido metafísico?" },
        { speaker: "Rodrigo", text: "Es la pregunta fundamental. Presupone que la nada es posible, que la existencia es contingente." },
        { speaker: "Prof. Fuente", text: "Pero ¿cómo conceptualizamos la nada? La nada no es nada en sí: ni sujeto ni predicado. ¿Podemos pensar lo impensable?" },
        { speaker: "Rodrigo", text: "Heidegger sugiere que la nada se revela en la angustia existencial. No es concepto, sino experiencia: el sentido de que podríamos no ser." },
        { speaker: "Prof. Fuente", text: "¿Entonces la metafísica descansa en experiencia emocional más que en lógica?" },
        { speaker: "Rodrigo", text: "Para Heidegger, sí. La lógica presupone la pregunta por el ser; no puede fundamentarla. Solo la experiencia existencial nos enfrenta con la pregunta." },
      ],
    },
  ],
  quizzes: [
    {
      question: "¿Cuál es la distinción esencial de Tomás de Aquino entre esencia y existencia en los seres contingentes?",
      options: [
        "La esencia es eterna; la existencia es temporal.",
        "En los seres contingentes, la esencia no incluye la existencia; esta debe ser conferida por algo externo.",
        "No hay distinción real; esencia y existencia son idénticas en todos los seres.",
        "La existencia es independiente de la esencia; pueden separarse sin causa.",
      ],
      correctAnswer: 1,
      explanation:
        "Aquino fundamenta su argumento cosmológico en esta distinción: los seres cuya esencia no contiene necesariamente su existencia requieren una causa externa. Dios es el único ser cuya esencia es su existencia (diferencia crucial de todas las criaturas).",
    },
    {
      question: "¿Qué es la 'aporía' socrática en el contexto del conocimiento?",
      options: [
        "Un método para alcanzar certeza absoluta.",
        "Una contradicción lógica insuperable que expone los límites del conocimiento racional.",
        "Una pregunta retórica que siempre tiene respuesta.",
        "La demostración de que el conocimiento es imposible.",
      ],
      correctAnswer: 1,
      explanation:
        "La aporía (literalmente 'sin paso') representa un punto muerto lógico. Sócrates usa la aporía para mostrar que la definición que alguien presumía conocer es en realidad incoherente, exponiendo la falsa presunción de conocimiento (el paso previo a la verdadera filosofía).",
    },
    {
      question: "Según Sartre, ¿cuál es la relación entre existencia y libertad?",
      options: [
        "La libertad existe solo en ausencia de determinación, que es imposible.",
        "La existencia precede la esencia; por lo tanto, no tenemos esencia predeterminada, y somos radicalmente libres y responsables.",
        "La libertad es ilusión; la existencia es determinada completamente.",
        "Existencia y libertad son conceptos sin relación causal.",
      ],
      correctAnswer: 1,
      explanation:
        "Sartre invierte la tradición: en lugar de una esencia humana universal que determina cómo debemos vivir, nuestra existencia es el punto de partida. Nos creamos a nosotros mismos mediante nuestras elecciones, lo que nos genera angustia y responsabilidad absoluta.",
    },
    {
      question: "¿Qué quiere decir Derrida con 'différance' en contraste con 'différence'?",
      options: [
        "Que no hay diferencia real entre objetos.",
        "Que el significado nunca está completamente presente; el sentido se difiere indefinidamente mediante diferencias.",
        "Que toda diferencia es conceptual, no real.",
        "Que el lenguaje es idéntico a la realidad.",
      ],
      correctAnswer: 1,
      explanation:
        "La 'différance' (ortografía deliberada que no se escucha en francés) combina 'différence' (diferencia) con 'deferring' (postergación). Derrida critica la idea de que el significado está plenamente presente en una palabra. El sentido emerge del sistema de diferencias y postergaciones indefinidas entre signos.",
    },
    {
      question: "¿Cuál es el proyecto de la fenomenología husserliana respecto a la consciencia?",
      options: [
        "Demostrar que la consciencia es puramente material.",
        "Mediante la 'epoché' (suspensión de creencia en el mundo), examinar cómo la consciencia constituye el significado de todo lo que experimentamos.",
        "Probar que el mundo externo es la única realidad verdadera.",
        "Abolir la distinción entre consciencia y realidad.",
      ],
      correctAnswer: 1,
      explanation:
        "Husserl propone reducir la investigación al ámbito de la consciencia experiencial. Suspendemos la creencia en la independencia del mundo para examinar la 'intencionalidad': cómo la consciencia siempre está dirigida hacia objetos, y cómo el significado se constituye en esa relación.",
    },
  ],
  flashcards: [
    { id: "c2-02-fc01", frontSpain: "ontología", frontLatam: "ontología", backEnglish: "Study of being and existence; what it means for something to exist", variantDifferenceNote: "Identical across regions; philosophical terminology", exampleSentenceSpain: "La ontología es la rama fundamental de la filosofía.", exampleSentenceLatam: "La ontología pregunta qué significa existir.", partOfSpeech: "noun" },
    { id: "c2-02-fc02", frontSpain: "epistemología", frontLatam: "epistemología", backEnglish: "Theory of knowledge; how we know what we know and the foundations of that knowledge", variantDifferenceNote: "Identical across regions; philosophical field", exampleSentenceSpain: "La epistemología examina los fundamentos del conocimiento.", exampleSentenceLatam: "La epistemología cuestiona la validez de nuestro saber.", partOfSpeech: "noun" },
    { id: "c2-02-fc03", frontSpain: "fenomenología", frontLatam: "fenomenología", backEnglish: "Study of consciousness and experience; how phenomena appear to consciousness", variantDifferenceNote: "Identical across regions; phenomenological school", exampleSentenceSpain: "La fenomenología examina la estructura de la experiencia.", exampleSentenceLatam: "La fenomenología de Husserl influye en filosofía contemporánea.", partOfSpeech: "noun" },
    { id: "c2-02-fc04", frontSpain: "dialéctica hegeliana", frontLatam: "dialéctica hegeliana", backEnglish: "Historical movement through thesis-antithesis-synthesis; contradictions resolve into higher unity", variantDifferenceNote: "Identical across regions; Hegelian philosophy", exampleSentenceSpain: "La dialéctica hegeliana modela el pensamiento histórico.", exampleSentenceLatam: "La dialéctica explica el cambio mediante contradicción.", partOfSpeech: "noun" },
    { id: "c2-02-fc05", frontSpain: "contingencia ontológica", frontLatam: "contingencia ontológica", backEnglish: "Quality of things that could possibly not exist; opposed to necessity", variantDifferenceNote: "Identical across regions; metaphysical concept", exampleSentenceSpain: "La contingencia ontológica requiere causa externa.", exampleSentenceLatam: "Todo lo contingente depende de algo necesario.", partOfSpeech: "noun" },
    { id: "c2-02-fc06", frontSpain: "aporía", frontLatam: "aporía", backEnglish: "Logical paradox or unsolvable contradiction that exposes limits of reason", variantDifferenceNote: "Identical across regions; Socratic method", exampleSentenceSpain: "La aporía socrática expone la ignorancia presunta.", exampleSentenceLatam: "La aporía nos enfrenta con los límites del pensamiento.", partOfSpeech: "noun" },
    { id: "c2-02-fc07", frontSpain: "esencia vs existencia", frontLatam: "esencia vs existencia", backEnglish: "Nature/definition (essence) versus actual being (existence); Sartre inverts priority", variantDifferenceNote: "Identical across regions; existentialist inversion", exampleSentenceSpain: "Sartre invierte la relación: existencia precede esencia.", exampleSentenceLatam: "La existencia precede la esencia en ser humano.", partOfSpeech: "noun" },
    { id: "c2-02-fc08", frontSpain: "hermenéutica", frontLatam: "hermenéutica", backEnglish: "Theory of interpretation; all understanding is interpretation conditioned by historical horizon", variantDifferenceNote: "Identical across regions; interpretive philosophy", exampleSentenceSpain: "La hermenéutica de Gadamer enfatiza el diálogo.", exampleSentenceLatam: "La hermenéutica revela que toda comprensión es interpretación.", partOfSpeech: "noun" },
    { id: "c2-02-fc09", frontSpain: "teleología", frontLatam: "teleología", backEnglish: "Idea that history or being moves toward predetermined ends or purposes", variantDifferenceNote: "Identical across regions; philosophical concept", exampleSentenceSpain: "La teleología asume progreso inevitable en historia.", exampleSentenceLatam: "La teleología es criticada por pensadores contemporáneos.", partOfSpeech: "noun" },
    { id: "c2-02-fc10", frontSpain: "alteridad radical", frontLatam: "alteridad radical", backEnglish: "Irreducible otherness of another being that cannot be assimilated to self", variantDifferenceNote: "Identical across regions; Levinasian ethics", exampleSentenceSpain: "La alteridad radical rechaza la totalización del otro.", exampleSentenceLatam: "La alteridad del otro es irreducible a mi comprensión.", partOfSpeech: "noun" },
    { id: "c2-02-fc11", frontSpain: "diferancia derridiana", frontLatam: "diferancia derridiana", backEnglish: "Play of difference and deferral; meaning is never fully present, always deferred", variantDifferenceNote: "Identical across regions; deconstructive neologism", exampleSentenceSpain: "La différance cuestiona la presencia del significado.", exampleSentenceLatam: "La diferancia expone la inestabilidad del sentido.", partOfSpeech: "noun" },
    { id: "c2-02-fc12", frontSpain: "acto de habla performativo", frontLatam: "acto de habla performativo", backEnglish: "Utterance that performs an action (promise, declaration) rather than describing", variantDifferenceNote: "Identical across regions; speech act theory", exampleSentenceSpain: "El acto performativo 'prometo' realiza una acción.", exampleSentenceLatam: "El acto de habla performativo transforma la realidad.", partOfSpeech: "noun" },
    { id: "c2-02-fc13", frontSpain: "reducción fenomenológica", frontLatam: "reducción fenomenológica", backEnglish: "Suspension of belief in external world to examine how consciousness constitutes meaning", variantDifferenceNote: "Identical across regions; Husserlian epoché", exampleSentenceSpain: "La reducción fenomenológica suspende la creencia natural.", exampleSentenceLatam: "La reducción examina cómo la consciencia constituye sentido.", partOfSpeech: "noun" },
    { id: "c2-02-fc14", frontSpain: "nihilismo existencial", frontLatam: "nihilismo existencial", backEnglish: "Denial of inherent meaning, values, or essence in existence", variantDifferenceNote: "Identical across regions; existential philosophy", exampleSentenceSpain: "El nihilismo existencial niega valores absolutos.", exampleSentenceLatam: "El nihilismo confronta la ausencia de esencia.", partOfSpeech: "noun" },
    { id: "c2-02-fc15", frontSpain: "constructivismo social", frontLatam: "constructivismo social", backEnglish: "Meaning and reality are socially constructed, not given or natural", variantDifferenceNote: "Identical across regions; sociological theory", exampleSentenceSpain: "El constructivismo social nega la realidad objetiva pura.", exampleSentenceLatam: "El constructivismo muestra que la realidad es construida.", partOfSpeech: "noun" },
    { id: "c2-02-fc16", frontSpain: "trascendencia kantiana", frontLatam: "trascendencia kantiana", backEnglish: "What lies beyond possible experience and knowledge; the noumenal realm", variantDifferenceNote: "Identical across regions; Kantian critical philosophy", exampleSentenceSpain: "La trascendencia kantiana permanece inaccesible.", exampleSentenceLatam: "La trascendencia limita el conocimiento posible.", partOfSpeech: "noun" },
    { id: "c2-02-fc17", frontSpain: "immanencia cartesiana", frontLatam: "immanencia cartesiana", backEnglish: "Immediate certainty of one's own thinking; the cogito as foundation", variantDifferenceNote: "Identical across regions; Cartesian method", exampleSentenceSpain: "La immanencia cartesiana es punto de partida indudable.", exampleSentenceLatam: "La immanencia del cogito funda todo pensamiento.", partOfSpeech: "noun" },
    { id: "c2-02-fc18", frontSpain: "metafísica de la substancia", frontLatam: "metafísica de la substancia", backEnglish: "Inquiry into what fundamentally exists independent of perception", variantDifferenceNote: "Identical across regions; metaphysical inquiry", exampleSentenceSpain: "La metafísica de la substancia es investigación fundamental.", exampleSentenceLatam: "La metafísica pregunta qué es realmente fundamental.", partOfSpeech: "noun" },
    { id: "c2-02-fc19", frontSpain: "solipsismo metodológico", frontLatam: "solipsismo metodológico", backEnglish: "Systematic doubt of everything except one's own thought processes", variantDifferenceNote: "Identical across regions; epistemological method", exampleSentenceSpain: "El solipsismo metodológico es herramienta cartesiana.", exampleSentenceLatam: "El solipsismo metodológico genera incertidumbre radical.", partOfSpeech: "noun" },
    { id: "c2-02-fc20", frontSpain: "intertextualidad", frontLatam: "intertextualidad", backEnglish: "References and dialogues between texts creating new meanings through echoes", variantDifferenceNote: "Identical across regions; literary and philosophical concept", exampleSentenceSpain: "La intertextualidad filosófica crea diálogos entre autores.", exampleSentenceLatam: "La intertextualidad revela redes complejas de influencia.", partOfSpeech: "noun" },
  ],
};

const LESSON_C2_03: LessonData = {
  id: "c2-03",
  title: "Legislative, Bureaucratic & Legal Registers",
  level: "C2",
  description:
    "Deciphering official documentation, court filings, and statutory prose. Mastery of legal syntax, archaic language, conditional obligations, and formal procedures in both Spain and LATAM.",
  regionalVocabulary: [
    {
      term: "la cláusula condicional",
      regionVariants: { spain: "la cláusula de condición", latam: "si se cumple la condición" },
      definition: "Conditional clause; establishes conditions for legal obligations",
      phonamicSpain: "lah KLAO-soo-lah kon-dee-see-oh-NAHL",
      phonamicLatam: "lah KLAO-soo-lah kon-dee-see-oh-NAHL",
      examples: ["Si el deudor incumple, la garantía será ejecutada.", "La cláusula condicional especifica qué ocurre en caso de incumplimiento."],
    },
    {
      term: "la responsabilidad civil",
      regionVariants: { spain: "la obligación de indemnizar", latam: "la responsabilidad del daño" },
      definition: "Civil liability; legal obligation to compensate for damages",
      phonamicSpain: "lah res-pon-sah-bee-lee-DAHD thee-VEEL",
      phonamicLatam: "lah res-pon-sah-bee-lee-DAHD see-VEEL",
      examples: ["El responsable de daños debe indemnizar a la víctima.", "La responsabilidad civil es el fundamento del derecho de daños."],
    },
    {
      term: "la legitimación activa",
      regionVariants: { spain: "el derecho a demandar", latam: "tener legitimidad para actuar" },
      definition: "Active legitimacy; right to bring legal action",
      phonamicSpain: "lah le-hee-tee-mah-see-OHN AHK-tee-vah",
      phonamicLatam: "lah le-hee-tee-mah-see-OHN AHK-tee-vah",
      examples: ["Solo las partes con legitimación activa pueden demandar.", "El acreedor tiene legitimación activa para exigir el pago."],
    },
    {
      term: "la prescripción de acciones",
      regionVariants: { spain: "el plazo para demandar", latam: "la caducidad del derecho" },
      definition: "Statute of limitations; time limit for bringing legal action",
      phonamicSpain: "lah pres-krip-see-OHN de ahk-see-OH-nes",
      phonamicLatam: "lah pres-krip-see-OHN de ahk-see-OH-nes",
      examples: ["La prescripción de acciones vence en cinco años.", "Tras la prescripción, ya no puede demandarse."],
    },
    {
      term: "el acto jurídico",
      regionVariants: { spain: "el hecho generador de derechos", latam: "el acto que crea obligaciones" },
      definition: "Legal act; action that creates legal consequences",
      phonamicSpain: "el AHK-toh hoo-REE-dee-koh",
      phonamicLatam: "el AHK-toh hoo-REE-dee-koh",
      examples: ["Un contrato es un acto jurídico que genera obligaciones.", "La voluntad de las partes determina los efectos del acto jurídico."],
    },
    {
      term: "la nulidad absoluta",
      regionVariants: { spain: "la invalidez total del acto", latam: "lo que no puede validarse" },
      definition: "Absolute nullity; complete invalidity of a legal act",
      phonamicSpain: "lah noo-lee-DAHD ahb-soh-LOO-tah",
      phonamicLatam: "lah noo-lee-DAHD ahb-soh-LOO-tah",
      examples: ["La nulidad absoluta no puede convalidarse.", "Un contrato sin causa es nulo de pleno derecho."],
    },
    {
      term: "la caducidad de derechos",
      regionVariants: { spain: "el plazo fatal", latam: "la pérdida del derecho" },
      definition: "Expiration of rights; loss of right due to failure to exercise within time limit",
      phonamicSpain: "lah kah-doo-see-DAHD de de-REH-chos",
      phonamicLatam: "lah kah-doo-see-DAHD de de-REH-chos",
      examples: ["La caducidad es inexorable; no admite interrupción.", "Tras la caducidad, el derecho se pierde definitivamente."],
    },
    {
      term: "la constitución de garantía",
      regionVariants: { spain: "la creación de seguridad jurídica", latam: "establecer una garantía" },
      definition: "Establishment of guarantee; creation of legal security",
      phonamicSpain: "lah kons-tee-too-see-OHN de gah-rahn-TEE-ah",
      phonamicLatam: "lah kons-tee-too-see-OHN de gah-rahn-TEE-ah",
      examples: ["La hipoteca constituye una garantía sobre el inmueble.", "Se constituye garantía mediante contrato con formalidades requeridas."],
    },
    {
      term: "la resolución del contrato",
      regionVariants: { spain: "la extinción por incumplimiento", latam: "terminar el contrato por falta" },
      definition: "Resolution of contract; termination due to breach",
      phonamicSpain: "lah re-zoh-loo-see-OHN del kon-TRAH-toh",
      phonamicLatam: "lah re-zoh-loo-see-OHN del kon-TRAH-toh",
      examples: ["La resolución procede cuando una parte incumple gravemente.", "Efectos de la resolución: restitución de prestaciones."],
    },
    {
      term: "la imputación de responsabilidad",
      regionVariants: { spain: "atribuir culpa", latam: "asignar responsabilidad" },
      definition: "Imputation of responsibility; attribution of liability",
      phonamicSpain: "lah eem-poo-tah-see-OHN de res-pon-sah-bee-lee-DAHD",
      phonamicLatam: "lah eem-poo-tah-see-OHN de res-pon-sah-bee-lee-DAHD",
      examples: ["La imputación requiere dolo o culpa probados.", "Solo conducta imputable genera responsabilidad civil."],
    },
    {
      term: "el incumplimiento sustancial",
      regionVariants: { spain: "el breach material", latam: "el quebrantamiento grave" },
      definition: "Material breach; substantial failure to perform contractual obligations",
      phonamicSpain: "el in-koom-plee-mee-EN-toh soos-tahn-see-AHL",
      phonamicLatam: "el in-koom-plee-mee-EN-toh soos-tahn-see-AHL",
      examples: ["El incumplimiento sustancial justifica la resolución.", "Debe demostrarse que el incumplimiento es material, no trivial."],
    },
    {
      term: "la restitución de prestaciones",
      regionVariants: { spain: "devolver lo dado", latam: "restituir lo que se recibió" },
      definition: "Restitution of performances; return of what was given",
      phonamicSpain: "lah res-tee-too-see-OHN de pres-tah-see-OH-nes",
      phonamicLatam: "lah res-tee-too-see-OHN de pres-tah-see-OH-nes",
      examples: ["Tras la resolución, procede la restitución mutua.", "Ambas partes deben restituir lo recibido."],
    },
    {
      term: "la acción hipotecaria",
      regionVariants: { spain: "el derecho a ejecutar la hipoteca", latam: "la demanda de ejecución" },
      definition: "Mortgage action; right to foreclose on collateral",
      phonamicSpain: "lah ahk-see-OHN ee-poh-te-KAH-ree-ah",
      phonamicLatam: "lah ahk-see-OHN ee-poh-te-KAH-ree-ah",
      examples: ["Mediante la acción hipotecaria, el acreedor puede vender el inmueble.", "La acción hipotecaria procede tras incumplimiento del deudor."],
    },
    {
      term: "el fraude procesal",
      regionVariants: { spain: "el engaño ante los tribunales", latam: "la simulación de hechos" },
      definition: "Procedural fraud; deception in judicial proceedings",
      phonamicSpain: "el FROW-deh pro-seh-SAHL",
      phonamicLatam: "el FROW-deh pro-seh-SAHL",
      examples: ["El fraude procesal vicia toda la sentencia.", "Si se comprueba fraude, la sentencia puede anularse."],
    },
    {
      term: "la sentencia condenatoria",
      regionVariants: { spain: "la decisión que condena", latam: "la sentencia que ordena el pago" },
      definition: "Condemnatory judgment; court decision ordering defendant to pay",
      phonamicSpain: "lah sen-TEN-see-ah kon-de-nah-TOH-ree-ah",
      phonamicLatam: "lah sen-TEN-see-ah kon-de-nah-TOH-ree-ah",
      examples: ["La sentencia condenatoria obliga al cumplimiento.", "El condenado debe cumplir la sentencia o será ejecutado forzosamente."],
    },
    {
      term: "la apelación de sentencia",
      regionVariants: { spain: "recurrir ante un tribunal superior", latam: "impugnar la sentencia" },
      definition: "Appeal of judgment; challenge to court decision in higher court",
      phonamicSpain: "lah ah-peh-lah-see-OHN de sen-TEN-see-ah",
      phonamicLatam: "lah ah-peh-lah-see-OHN de sen-TEN-see-ah",
      examples: ["La apelación suspende los efectos de la sentencia.", "El apelante debe presentar alegatos fundamentados."],
    },
    {
      term: "la ejecución forzosa",
      regionVariants: { spain: "el cumplimiento obligado", latam: "ejecutar por la fuerza" },
      definition: "Forced execution; compulsory fulfillment of judgment",
      phonamicSpain: "lah eh-hek-oo-see-OHN for-ZOH-sah",
      phonamicLatam: "lah eh-hek-oo-see-OHN for-ZOH-sah",
      examples: ["Si el deudor no paga voluntariamente, procede la ejecución forzosa.", "La ejecución puede dirigirse contra los bienes del ejecutado."],
    },
    {
      term: "la compensación de créditos",
      regionVariants: { spain: "la extinción recíproca de deudas", latam: "cancelarse mutuamente las deudas" },
      definition: "Compensation of debts; mutual extinction of reciprocal debts",
      phonamicSpain: "lah kom-pen-sah-see-OHN de KREH-dee-tos",
      phonamicLatam: "lah kom-pen-sah-see-OHN de KREH-dee-tos",
      examples: ["Si ambas partes se deben cantidades, procede la compensación.", "La compensación extingue ambas deudas hasta donde alcanzan."],
    },
    {
      term: "la vigencia de normas",
      regionVariants: { spain: "el período de validez", latam: "cuándo rigen las leyes" },
      definition: "Time period during which legal norms are in force and effect",
      phonamicSpain: "lah vee-HEN-see-ah de NOR-mas",
      phonamicLatam: "lah vee-HEN-see-ah de NOR-mas",
      examples: ["La vigencia de la ley comienza al día siguiente de su publicación.", "Las normas pierden vigencia cuando son derogadas o abrogadas."],
    },
  ],
  grammarSections: [
    {
      title: "Legal Conditional Obligation Language",
      rules: [
        "Pattern: 'En caso de que... deba/deberá...' (In the event that... must/shall...)",
        "Spanish legal language mixes future and subjunctive for obligations",
        "Peninsular: 'El arrendatario deberá pagar la renta' (mandatory, future)",
        "LATAM: 'El arrendatario debe pagar la renta' (present form expressing obligation)",
        "Archaic: use of 'habere' forms (habido, habiere) in legal documents",
      ],
      culturalNote:
        "Peninsular Spanish emphasizes future conditional tense for legal obligations; LATAM uses present indicative more liberally. Both maintain subjunctive in contingent clauses ('en caso de que...', 'siempre que...').",
    },
    {
      title: "Passive and Middle Voice Constructions",
      rules: [
        "Form: ser/estar + past participle for official declarations",
        "Example: 'Se establece que...' (It is hereby established that...)",
        "Legal Spanish uses reflexive se for objective, impersonal tone",
        "Pattern: 'Se declara nula la cláusula' = emphasis on the act of declaring, not the declarer",
      ],
      culturalNote:
        "Both Spain and LATAM legal language heavily favor passive/reflexive constructions for authority and distance. Active voice (the judge decides) appears less formal than passive (it is decided).",
    },
  ],
  dialogueScenarios: [
    {
      region: "spain",
      setting: "Despacho de Abogados, Barcelona - Reunión de Asesoría",
      characters: ["Abogada Martínez (lawyer)", "Cliente García (businessman)"],
      dialogue: [
        { speaker: "Abogada Martínez", text: "La cláusula de resolución exige incumplimiento sustancial. ¿Qué considera incumplimiento material de su contrato?" },
        { speaker: "Cliente García", text: "Si el proveedor entrega fuera de plazo o la calidad es deficiente, ¿puedo resolver?" },
        { speaker: "Abogada Martínez", text: "Depende de la gravedad. Retraso menor no justifica resolución. Debe ser sustancial: que frustre el propósito del contrato." },
        { speaker: "Cliente García", text: "¿Y si incluyo una cláusula penal?" },
        { speaker: "Abogada Martínez", text: "Prudente. La cláusula penal fija indemnización previa; evita litigios sobre daños. Pero debe ser proporcional, no abusiva." },
        { speaker: "Cliente García", text: "¿Qué pasa si ambos incumplimos? ¿Se compensa?" },
        { speaker: "Abogada Martínez", text: "Exactamente: compensación de créditos. Si ustedes se deben mutuamente, se extinguen hasta donde alcanzan las deudas." },
      ],
    },
    {
      region: "spain",
      setting: "Juzgado de Primera Instancia, Madrid - Audiencia Preliminar",
      characters: ["Juez Pérez (judge)", "Demandante López"],
      dialogue: [
        { speaker: "Juez Pérez", text: "Demandante López, ha solicitado la resolución del contrato de arrendamiento por incumplimiento del arrendador." },
        { speaker: "Demandante López", text: "Sí, señoría. Hace tres meses que falta el agua corriente. Solicitó reparación; nada." },
        { speaker: "Juez Pérez", text: "¿Cumplió usted con el pago de la renta durante este período?" },
        { speaker: "Demandante López", text: "Sí, hasta hace un mes. Ahora retengo el alquiler equivalente al costo de reparaciones." },
        { speaker: "Juez Pérez", text: "Eso constituye incumplimiento por su parte. Aunque el arrendador sea responsable de reparaciones, usted no puede retener unilateralmente." },
        { speaker: "Demandante López", text: "¿Pero cómo obtengo reparación? ¿Sigo pagando por un inmueble inhabitable?" },
        { speaker: "Juez Pérez", text: "Puede demandar por daños y perjuicios y solicitar rebaja proporcional de la renta, pero debe pagar regularmente. La compensación se calcula en sentencia." },
      ],
    },
    {
      region: "spain",
      setting: "Notaría Pública, Sevilla - Formalización de Garantía",
      characters: ["Notario Ruiz (notary)", "Cliente Hernández (borrower)"],
      dialogue: [
        { speaker: "Notario Ruiz", text: "Procede la constitución de hipoteca sobre el inmueble. Le explico los efectos jurídicos." },
        { speaker: "Cliente Hernández", text: "¿Qué significa exactamente?" },
        { speaker: "Notario Ruiz", text: "Crea una garantía real a favor del banco. Si incumple pagos, el banco puede ejercitar acción hipotecaria: subasta del inmueble." },
        { speaker: "Cliente Hernández", text: "¿Puedo vender la casa mientras esté hipotecada?" },
        { speaker: "Notario Ruiz", text: "Técnicamente sí, pero el comprador adquiere sujetándose a la hipoteca. El banco puede vender la finca si los plazos vencen." },
        { speaker: "Cliente Hernández", text: "¿Y la prescripción? ¿Cuándo caducan mis deudas?" },
        { speaker: "Notario Ruiz", text: "La acción ejecutiva de hipoteca prescribe en cinco años de inactividad. Pero el banco puede reintentar dentro de ese plazo." },
      ],
    },
    {
      region: "latam",
      setting: "Bufete Jurídico, Lima - Consultoría Contractual",
      characters: ["Abogada Sánchez (lawyer)", "Cliente Flores (entrepreneur)"],
      dialogue: [
        { speaker: "Abogada Sánchez", text: "Su contrato de suministro carece de cláusula de resolución. Recomiendo añadirla para incumplimiento sustancial." },
        { speaker: "Cliente Flores", text: "¿Qué es incumplimiento sustancial bajo la ley peruana?" },
        { speaker: "Abogada Sánchez", text: "Cuando el incumplimiento frustra el propósito del contrato: entregas fuera de especificación, retrasos significativos, incapacidad de cumplir." },
        { speaker: "Cliente Flores", text: "Si resuelvo, ¿qué pasa con lo ya entregado?" },
        { speaker: "Abogada Sánchez", text: "Procede restitución mutua de prestaciones. Devuelve lo recibido; el proveedor devuelve pagos. Pero hay excepciones por prestaciones consumidas." },
        { speaker: "Cliente Flores", text: "¿Cuál es el plazo para demandar por incumplimiento?" },
        { speaker: "Abogada Sánchez", text: "La acción prescribe en dos años en contratos mercantiles. En cinco años si es ordinario. Tras prescripción, pierde legitimación activa." },
      ],
    },
    {
      region: "latam",
      setting: "Tribunal Civil, Santiago de Chile - Litigio por Incumplimiento",
      characters: ["Juez Aros (judge)", "Demandante Mendes"],
      dialogue: [
        { speaker: "Juez Aros", text: "La demanda alega fraude procesal en la audiencia anterior. ¿Presenta prueba?" },
        { speaker: "Demandante Mendes", text: "El demandado presentó documentos falsificados como prueba de pago. Tengo pericia grafológica que lo demuestra." },
        { speaker: "Juez Aros", text: "Fraude procesal vicia completamente la sentencia anterior. Si se comprueba, puede anularse toda." },
        { speaker: "Demandante Mendes", text: "¿Eso significa comenzar el juicio de nuevo?" },
        { speaker: "Juez Aros", text: "Exactamente. Pero primero debe probarse el fraude mediante procedimiento específico. No es alegación banal." },
        { speaker: "Demandante Mendes", text: "¿Cuál es el plazo para impugnar por fraude?" },
        { speaker: "Juez Aros", text: "La acción por fraude procesal prescribe en un año desde el descubrimiento. Debe actuar rápidamente." },
      ],
    },
    {
      region: "latam",
      setting: "Registraduría Pública, Bogotá - Formalización de Hipoteca",
      characters: ["Registrador Gómez (registrar)", "Cliente Reyes"],
      dialogue: [
        { speaker: "Registrador Gómez", text: "Registraremos la hipoteca sobre su propiedad. Esto constituye garantía real a favor del banco." },
        { speaker: "Cliente Reyes", text: "¿Qué sucede si no pago?" },
        { speaker: "Registrador Gómez", text: "El banco ejerce acción hipotecaria: demanda ante tribunal pidiendo venta forzosa del inmueble." },
        { speaker: "Cliente Reyes", text: "¿Pierdo la casa inmediatamente?" },
        { speaker: "Registrador Gómez", text: "No inmediatamente. Hay trámites: demanda, sentencia condenatoria, apelación posible, luego ejecución forzosa. Todo toma meses." },
        { speaker: "Cliente Reyes", text: "¿Qué pasa si durante la ejecución el inmueble se vende por menos de lo que debo?" },
        { speaker: "Registrador Gómez", text: "Usted sigue debiendo el deficiente. El banco puede cobrarlo de otros bienes. A menos que ambos acuerden compensar con otro crédito que usted tiene." },
      ],
    },
  ],
  quizzes: [
    {
      question: "¿Cuál es la diferencia entre 'incumplimiento sustancial' e 'incumplimiento menor' en derecho contractual?",
      options: [
        "No hay diferencia; todo incumplimiento justifica resolución.",
        "Incumplimiento sustancial frustra el propósito del contrato y justifica resolución; menor no lo hace.",
        "Incumplimiento menor es siempre más grave.",
        "La diferencia depende solo del monto monetario.",
      ],
      correctAnswer: 1,
      explanation:
        "El derecho contractual distingue: solo incumplimiento sustancial (material breach) justifica resolución. Retraso de un día en entrega no es sustancial; falta total de entrega sí. El juez examina si el incumplimiento frustró el propósito del contrato.",
    },
    {
      question: "¿Qué efectos tiene la compensación de créditos en derecho civil?",
      options: [
        "Una deuda cancela la otra solo si son de igual monto.",
        "Las deudas recíprocas se extinguen mutuamente hasta el límite de la menor.",
        "No hay efectos legales; es solo un acuerdo privado.",
        "La compensación requiere aprobación judicial previa.",
      ],
      correctAnswer: 1,
      explanation:
        "Si A le debe 1000 a B, y B le debe 700 a A, ambas deudas se extinguen automáticamente por compensación: A le debe solo 300. Es mecanismo de extinción automática de créditos recíprocos (ex lege, no requiere acuerdo).",
    },
    {
      question: "¿Cuál es el efecto principal de la 'constitución de hipoteca' según la ley?",
      options: [
        "Transfiere la propiedad del inmueble al banco.",
        "Crea una garantía real que permite al acreedor vender forzosamente el inmueble si hay incumplimiento.",
        "El deudor pierde acceso al inmueble inmediatamente.",
        "Solo previene que el deudor venda el inmueble.",
      ],
      correctAnswer: 1,
      explanation:
        "La hipoteca constituye derecho real de garantía: no transfiere propiedad, pero otorga al acreedor derecho a ejercitar acción hipotecaria (subasta forzosa) si el deudor incumple. El deudor mantiene posesión y uso mientras cumple.",
    },
    {
      question: "¿Qué es la 'prescripción de acciones' y cuál es su efecto?",
      options: [
        "Período de tiempo después del cual el deudor puede ignorar una deuda.",
        "Plazo máximo para ejercitar una acción legal; tras su vencimiento, se pierde la legitimación activa.",
        "Proceso de registrar una acción ante tribunal.",
        "Retraso en el cumplimiento de una obligación.",
      ],
      correctAnswer: 1,
      explanation:
        "La prescripción es plazo fatal (no interrumpible fácilmente) tras el cual una acción legal no puede ejercitarse. P.ej., acción contractual prescribe en 5 años. El acreedor pierde derecho a demandar. Es defensa del deudor contra demandas tardías.",
    },
    {
      question: "¿Qué características definen a la 'nulidad absoluta' bajo derecho civil?",
      options: [
        "El acto puede validarse con acuerdo posterior de las partes.",
        "Es nulidad que no puede convalidarse y puede alegarse en cualquier momento.",
        "Solo el juez puede declararla; las partes no pueden invocarla.",
        "Desaparece automáticamente tras 3 años.",
      ],
      correctAnswer: 1,
      explanation:
        "Nulidad absoluta es invalidez total de un acto (p.ej., contrato sin causa, o que viole ley imperativa). No puede validarse (a diferencia de nulidad relativa). Puede invocarse en cualquier tiempo por cualquier interesado (no prescribe fácilmente).",
    },
  ],
  flashcards: [
    { id: "c2-03-fc01", frontSpain: "cláusula condicional", frontLatam: "cláusula condicional", backEnglish: "Contractual clause establishing conditions under which obligations arise or are excused", variantDifferenceNote: "Identical across regions; legal terminology", exampleSentenceSpain: "La cláusula condicional especifica los efectos del incumplimiento.", exampleSentenceLatam: "La cláusula condicional protege ambas partes.", partOfSpeech: "noun" },
    { id: "c2-03-fc02", frontSpain: "responsabilidad civil", frontLatam: "responsabilidad civil", backEnglish: "Legal obligation to compensate another for damages or losses caused", variantDifferenceNote: "Identical across regions; fundamental legal concept", exampleSentenceSpain: "La responsabilidad civil obliga a indemnizar daños.", exampleSentenceLatam: "La responsabilidad civil es principio del derecho moderno.", partOfSpeech: "noun" },
    { id: "c2-03-fc03", frontSpain: "legitimación activa", frontLatam: "legitimación activa", backEnglish: "Right to bring legal action; being a party with standing to sue", variantDifferenceNote: "Identical across regions; legal procedural term", exampleSentenceSpain: "Solo los con legitimación activa pueden demandar.", exampleSentenceLatam: "La legitimación activa determina quién puede actuar.", partOfSpeech: "noun" },
    { id: "c2-03-fc04", frontSpain: "prescripción", frontLatam: "prescripción", backEnglish: "Time limit for bringing legal action; after which right is lost", variantDifferenceNote: "Identical across regions; statute of limitations", exampleSentenceSpain: "La prescripción vence a los cinco años.", exampleSentenceLatam: "La prescripción extingue el derecho a demandar.", partOfSpeech: "noun" },
    { id: "c2-03-fc05", frontSpain: "acto jurídico", frontLatam: "acto jurídico", backEnglish: "Legal act creating rights and obligations; must have will, object, and cause", variantDifferenceNote: "Identical across regions; foundational legal concept", exampleSentenceSpain: "Un contrato es acto jurídico que genera obligaciones.", exampleSentenceLatam: "El acto jurídico constituye la base del derecho civil.", partOfSpeech: "noun" },
    { id: "c2-03-fc06", frontSpain: "nulidad absoluta", frontLatam: "nulidad absoluta", backEnglish: "Complete invalidity of act; cannot be convalidated; may be invoked indefinitely", variantDifferenceNote: "Identical across regions; absolute nullity", exampleSentenceSpain: "La nulidad absoluta no puede convalidarse nunca.", exampleSentenceLatam: "La nulidad absoluta vicia completamente el acto.", partOfSpeech: "noun" },
    { id: "c2-03-fc07", frontSpain: "caducidad", frontLatam: "caducidad", backEnglish: "Expiration of right due to failure to exercise within fatal time period", variantDifferenceNote: "Identical across regions; loss of right", exampleSentenceSpain: "La caducidad es plazo fatal e inexorable.", exampleSentenceLatam: "La caducidad extingue definitivamente el derecho.", partOfSpeech: "noun" },
    { id: "c2-03-fc08", frontSpain: "garantía real", frontLatam: "garantía real", backEnglish: "Security right over specific property; allows creditor to seize/sell if debt unpaid", variantDifferenceNote: "Identical across regions; security interest", exampleSentenceSpain: "La hipoteca es garantía real sobre inmuebles.", exampleSentenceLatam: "La garantía real protege al acreedor efectivamente.", partOfSpeech: "noun" },
    { id: "c2-03-fc09", frontSpain: "resolución del contrato", frontLatam: "resolución del contrato", backEnglish: "Termination of contract due to material breach by other party", variantDifferenceNote: "Identical across regions; contract termination", exampleSentenceSpain: "La resolución procede por incumplimiento sustancial.", exampleSentenceLatam: "La resolución devuelve las partes al estado anterior.", partOfSpeech: "noun" },
    { id: "c2-03-fc10", frontSpain: "incumplimiento sustancial", frontLatam: "incumplimiento sustancial", backEnglish: "Material breach that defeats purpose of contract and justifies termination", variantDifferenceNote: "Identical across regions; material breach", exampleSentenceSpain: "El incumplimiento sustancial justifica la resolución.", exampleSentenceLatam: "El incumplimiento sustancial debe probarse claramente.", partOfSpeech: "noun" },
    { id: "c2-03-fc11", frontSpain: "restitución de prestaciones", frontLatam: "restitución de prestaciones", backEnglish: "Return of performances; parties restore what was given after contract termination", variantDifferenceNote: "Identical across regions; restitution", exampleSentenceSpain: "La restitución mutua restituye el estado anterior.", exampleSentenceLatam: "La restitución es efecto necesario de resolución.", partOfSpeech: "noun" },
    { id: "c2-03-fc12", frontSpain: "acción hipotecaria", frontLatam: "acción hipotecaria", backEnglish: "Creditor's right to foreclose; demand forced sale of mortgaged property", variantDifferenceNote: "Identical across regions; foreclosure action", exampleSentenceSpain: "La acción hipotecaria permite vender el inmueble forzadamente.", exampleSentenceLatam: "La acción hipotecaria procede tras incumplimiento.", partOfSpeech: "noun" },
    { id: "c2-03-fc13", frontSpain: "fraude procesal", frontLatam: "fraude procesal", backEnglish: "Deception in judicial proceedings; voids entire judgment if proven", variantDifferenceNote: "Identical across regions; procedural fraud", exampleSentenceSpain: "El fraude procesal vicia completamente la sentencia.", exampleSentenceLatam: "El fraude procesal es causa grave de nulidad.", partOfSpeech: "noun" },
    { id: "c2-03-fc14", frontSpain: "sentencia condenatoria", frontLatam: "sentencia condenatoria", backEnglish: "Judgment ordering defendant to pay or perform; is binding and enforceable", variantDifferenceNote: "Identical across regions; condemnatory judgment", exampleSentenceSpain: "La sentencia condenatoria es ejecutable forzosamente.", exampleSentenceLatam: "La sentencia condenatoria obliga al cumplimiento.", partOfSpeech: "noun" },
    { id: "c2-03-fc15", frontSpain: "apelación", frontLatam: "apelación", backEnglish: "Challenge to lower court judgment in appellate court; seeks reversal or modification", variantDifferenceNote: "Identical across regions; appeal", exampleSentenceSpain: "La apelación permite revisar la sentencia en tribunal superior.", exampleSentenceLatam: "La apelación suspende los efectos de la sentencia.", partOfSpeech: "noun" },
    { id: "c2-03-fc16", frontSpain: "ejecución forzosa", frontLatam: "ejecución forzosa", backEnglish: "Forced enforcement of judgment; creditor may seize property or garnish income", variantDifferenceNote: "Identical across regions; forced execution", exampleSentenceSpain: "La ejecución forzosa se dirige contra bienes del ejecutado.", exampleSentenceLatam: "La ejecución forzosa es última fase de proceso.", partOfSpeech: "noun" },
    { id: "c2-03-fc17", frontSpain: "compensación de créditos", frontLatam: "compensación de créditos", backEnglish: "Mutual extinction of reciprocal debts; occurs automatically ex lege", variantDifferenceNote: "Identical across regions; automatic debt extinction", exampleSentenceSpain: "La compensación extingue deudas recíprocas automáticamente.", exampleSentenceLatam: "La compensación opera ex lege sin acuerdo.", partOfSpeech: "noun" },
    { id: "c2-03-fc18", frontSpain: "legitimación pasiva", frontLatam: "legitimación pasiva", backEnglish: "Obligation to defend oneself in legal action; being party to suit", variantDifferenceNote: "Identical across regions; passive legitimacy", exampleSentenceSpain: "La legitimación pasiva obliga a comparecer.", exampleSentenceLatam: "La legitimación pasiva es correlativa a activa.", partOfSpeech: "noun" },
    { id: "c2-03-fc19", frontSpain: "contrato nulo", frontLatam: "contrato nulo", backEnglish: "Contract void from inception due to lack of essential element (will, object, cause)", variantDifferenceNote: "Identical across regions; void contract", exampleSentenceSpain: "El contrato nulo es ineficaz desde el origen.", exampleSentenceLatam: "El contrato nulo carece de efectos legales.", partOfSpeech: "noun" },
    { id: "c2-03-fc20", frontSpain: "plazo fatal", frontLatam: "plazo fatal", backEnglish: "Non-extendable time period; once it expires, right is lost permanently", variantDifferenceNote: "Identical across regions; peremptory time limit", exampleSentenceSpain: "El plazo fatal no puede ser interrumpido ni prorrogado.", exampleSentenceLatam: "El plazo fatal extingue el derecho irremediablemente.", partOfSpeech: "noun" },
  ],
};

// Lessons C2.04–C2.10: Structured stubs for expansion
const LESSON_C2_04: LessonData = {
  id: "c2-04",
  title: "Systemic Irony, Satire & Political Cartoons",
  level: "C2",
  description: "Advanced multi-layered cultural critiques in Spain vs Mexican socio-political comedy. Decoding systemic irony, satirical frameworks, and political reference networks.",
  regionalVocabulary: Array(20).fill({ term: "", regionVariants: { spain: "", latam: "" }, definition: "", phonamicSpain: "", phonamicLatam: "", examples: [] }),
  grammarSections: [
    { title: "Ironic Subjunctive & Conditional Paradox", rules: [], culturalNote: "" },
    { title: "Rhetorical Questions & Denial Constructions", rules: [], culturalNote: "" },
  ],
  dialogueScenarios: [],
  quizzes: [],
  flashcards: [],
};

const LESSON_C2_05: LessonData = {
  id: "c2-05",
  title: "Idiomatic Micro-Regions (Spain)",
  level: "C2",
  description: "Deep dive into localized colloquialisms from Andalusia, Galicia, and Madrid.",
  regionalVocabulary: Array(20).fill({ term: "", regionVariants: { spain: "", latam: "" }, definition: "", phonamicSpain: "", phonamicLatam: "", examples: [] }),
  grammarSections: [
    { title: "Regional Verb Conjugations & Phonetic Shifts", rules: [], culturalNote: "" },
    { title: "Diminutive & Augmentative Formations by Region", rules: [], culturalNote: "" },
  ],
  dialogueScenarios: [],
  quizzes: [],
  flashcards: [],
};

const LESSON_C2_06: LessonData = {
  id: "c2-06",
  title: "Idiomatic Micro-Regions (LATAM)",
  level: "C2",
  description: "Deep dive into localized colloquialisms across North, Coast, and Central Mexico.",
  regionalVocabulary: Array(20).fill({ term: "", regionVariants: { spain: "", latam: "" }, definition: "", phonamicSpain: "", phonamicLatam: "", examples: [] }),
  grammarSections: [
    { title: "Regional Morphology & Syllable Deletion", rules: [], culturalNote: "" },
    { title: "Localized Diminutive Patterns", rules: [], culturalNote: "" },
  ],
  dialogueScenarios: [],
  quizzes: [],
  flashcards: [],
};

const LESSON_C2_07: LessonData = {
  id: "c2-07",
  title: "Academic Reporting & Editorial Writing",
  level: "C2",
  description: "Authoring high-level commentary, scientific summaries, and columns.",
  regionalVocabulary: Array(20).fill({ term: "", regionVariants: { spain: "", latam: "" }, definition: "", phonamicSpain: "", phonamicLatam: "", examples: [] }),
  grammarSections: [
    { title: "Citation Syntax & Attributive Structures", rules: [], culturalNote: "" },
    { title: "Hedge Language & Epistemic Markers", rules: [], culturalNote: "" },
  ],
  dialogueScenarios: [],
  quizzes: [],
  flashcards: [],
};

const LESSON_C2_08: LessonData = {
  id: "c2-08",
  title: "Crisis Management & Public Address",
  level: "C2",
  description: "Delivering press announcements, damage control, and fast diplomatic statements.",
  regionalVocabulary: Array(20).fill({ term: "", regionVariants: { spain: "", latam: "" }, definition: "", phonamicSpain: "", phonamicLatam: "", examples: [] }),
  grammarSections: [
    { title: "Diplomatic Passive & Distancing Constructions", rules: [], culturalNote: "" },
    { title: "Crisis Framing & Euphemism Syntax", rules: [], culturalNote: "" },
  ],
  dialogueScenarios: [],
  quizzes: [],
  flashcards: [],
};

const LESSON_C2_09: LessonData = {
  id: "c2-09",
  title: "Archaisms, Etymology & Historic Sayings",
  level: "C2",
  description: "Utilizing obsolete phrasing for dramatic effect, literature interpretation, or historical analysis.",
  regionalVocabulary: Array(20).fill({ term: "", regionVariants: { spain: "", latam: "" }, definition: "", phonamicSpain: "", phonamicLatam: "", examples: [] }),
  grammarSections: [
    { title: "Old Spanish Morphology & Phonetics", rules: [], culturalNote: "" },
    { title: "Medieval & Golden Age Syntax Patterns", rules: [], culturalNote: "" },
  ],
  dialogueScenarios: [],
  quizzes: [],
  flashcards: [],
};

const LESSON_C2_10: LessonData = {
  id: "c2-10",
  title: "Complete Fluency Synthesis",
  level: "C2",
  description: "Rapid fluid shifting across ultra-formal legal tones to extreme street jargon in real-time conversation.",
  regionalVocabulary: Array(20).fill({ term: "", regionVariants: { spain: "", latam: "" }, definition: "", phonamicSpain: "", phonamicLatam: "", examples: [] }),
  grammarSections: [
    { title: "Register-Shifting Mechanics & Code-Switching", rules: [], culturalNote: "" },
    { title: "Rapid Contextual Adaptation Patterns", rules: [], culturalNote: "" },
  ],
  dialogueScenarios: [],
  quizzes: [],
  flashcards: [],
};

export const C2_LESSONS = [
  LESSON_C2_01,
  LESSON_C2_02,
  LESSON_C2_03,
  LESSON_C2_04,
  LESSON_C2_05,
  LESSON_C2_06,
  LESSON_C2_07,
  LESSON_C2_08,
  LESSON_C2_09,
  LESSON_C2_10,
];