import type { LessonData } from "./lessons-data";

const LESSON_C2_01: LessonData = {
  id: "c2-01",
  slug: "classical-modern-literature",
  title: "Classical & Modern Literature",
  description: "Analyzing structural shifts in Peninsular prose vs LATAM magical realism syntax. Deep dive into authorial voice, narrative technique, and stylistic evolution.",
  level: "C2",
  difficulty: "Mastery",
  order: 31,
  imageUrl: null,
  durationMinutes: 120,
  isPublished: true,
  vocabularyTable: [
    { word: "realismo mágico", spainVariant: "la ficción fantástica", latamVariant: "el realismo mágico", phoneticSpain: "reh-ah-LEES-moh MAH-hee-koh", phoneticLatam: "reh-ah-LEES-moh MAH-hee-koh", english: "Magical realism; blending reality with fantastical elements", partOfSpeech: "noun", exampleSentenceSpain: "El realismo mágico de García Márquez caracteriza la literatura latinoamericana.", exampleSentenceLatam: "García Márquez perfeccionó esta técnica narrativa." },
    { word: "fragmentación narrativa", spainVariant: "la estructura fragmentada", latamVariant: "la discontinuidad narrativa", phoneticSpain: "frag-men-tah-see-OHN", phoneticLatam: "frag-men-tah-see-OHN", english: "Narrative fragmentation; discontinuous story structure", partOfSpeech: "noun", exampleSentenceSpain: "La fragmentación de Cortázar desorienta deliberadamente.", exampleSentenceLatam: "Los capítulos no siguen orden cronológico." },
    { word: "perspectivismo", spainVariant: "las múltiples perspectivas", latamVariant: "la polifonía narrativa", phoneticSpain: "per-spec-tee-VEES-moh", phoneticLatam: "per-spec-tee-VEES-moh", english: "Multiple simultaneous viewpoints", partOfSpeech: "noun", exampleSentenceSpain: "Cada capítulo presenta una perspectiva distinta.", exampleSentenceLatam: "La realidad es multifacética." },
    { word: "autorreferencialidad", spainVariant: "la reflexividad textual", latamVariant: "el metarrelato", phoneticSpain: "ow-toh-re-fen-see-ah-lee-DAHD", phoneticLatam: "ow-toh-re-fen-see-ah-lee-DAHD", english: "Self-referentiality; text referring to its own creation", partOfSpeech: "noun", exampleSentenceSpain: "Borges expone la construcción del texto.", exampleSentenceLatam: "El narrador es consciente de su propia ficción." },
    { word: "monólogo interior", spainVariant: "la corriente de conciencia", latamVariant: "el flujo de conciencia", phoneticSpain: "moh-NOH-loh-goh", phoneticLatam: "moh-NOH-loh-goh", english: "Stream of consciousness; interior monologue", partOfSpeech: "noun", exampleSentenceSpain: "Joyce utiliza el monólogo interior.", exampleSentenceLatam: "La mente se revela sin censura." },
    { word: "intertextualidad", spainVariant: "las referencias literarias", latamVariant: "los ecos textuales", phoneticSpain: "in-ter-teks-too-ah-lee-DAHD", phoneticLatam: "in-ter-teks-too-ah-lee-DAHD", english: "References and echoes between texts", partOfSpeech: "noun", exampleSentenceSpain: "Borges juega con la intertextualidad.", exampleSentenceLatam: "Los textos dialogan entre sí." },
    { word: "metáfora extendida", spainVariant: "el símbolo desarrollado", latamVariant: "la metáfora sostenida", phoneticSpain: "me-TAH-foh-rah", phoneticLatam: "me-TAH-foh-rah", english: "Extended metaphor; sustained symbolic language", partOfSpeech: "noun", exampleSentenceSpain: "El laberinto permea toda la novela.", exampleSentenceLatam: "La metáfora funciona como estructura." },
    { word: "disolución temporal", spainVariant: "la ruptura cronológica", latamVariant: "el desorden temporal", phoneticSpain: "dee-so-loo-see-OHN", phoneticLatam: "dee-so-loo-see-OHN", english: "Non-linear time structure", partOfSpeech: "noun", exampleSentenceSpain: "El tiempo lineal desaparece.", exampleSentenceLatam: "Rayuela confunde el orden temporal." },
    { word: "pastiche literario", spainVariant: "la imitación estilística", latamVariant: "la parodia literaria", phoneticSpain: "pas-TEESH", phoneticLatam: "pas-TEESH", english: "Literary parody; stylistic imitation", partOfSpeech: "noun", exampleSentenceSpain: "Cortázar critica géneros mediante pastiche.", exampleSentenceLatam: "La parodia exagera estilos clásicos." },
    { word: "densidad simbólica", spainVariant: "la riqueza metafórica", latamVariant: "la abundancia de símbolos", phoneticSpain: "den-see-DAHD", phoneticLatam: "den-see-DAHD", english: "Concentration of layered symbolic meanings", partOfSpeech: "noun", exampleSentenceSpain: "La obra exige análisis profundo.", exampleSentenceLatam: "Cada elemento tiene múltiples significados." },
    { word: "deconstrucción textual", spainVariant: "el cuestionamiento de significados", latamVariant: "el análisis de sentidos", phoneticSpain: "de-kons-trook-see-OHN", phoneticLatam: "de-kons-trook-see-OHN", english: "Analysis dismantling fixed meanings", partOfSpeech: "noun", exampleSentenceSpain: "Derrida cuestiona los significados.", exampleSentenceLatam: "El sentido se disuelve." },
    { word: "sinestesia narrativa", spainVariant: "la confusión sensorial", latamVariant: "la mezcla de sentidos", phoneticSpain: "see-nes-TEH-see-ah", phoneticLatam: "see-nes-TEH-see-ah", english: "Blending of sensory descriptions", partOfSpeech: "noun", exampleSentenceSpain: "Los colores suenan.", exampleSentenceLatam: "Los sentidos se entrelazan." },
    { word: "poesía en prosa", spainVariant: "la prosa poética", latamVariant: "el poema en prosa", phoneticSpain: "poh-eh-SEE-ah", phoneticLatam: "poh-eh-SEE-ah", english: "Lyrical narrative language", partOfSpeech: "noun", exampleSentenceSpain: "Baudelaire perfecciona este género.", exampleSentenceLatam: "La belleza lírica enriquece." },
    { word: "realismo sucio", spainVariant: "la narrativa brutal", latamVariant: "el minimalismo narrativo", phoneticSpain: "reh-ah-LEES-moh", phoneticLatam: "reh-ah-LEES-moh", english: "Gritty, minimalist narrative style", partOfSpeech: "noun", exampleSentenceSpain: "Rechaza la ornamentación.", exampleSentenceLatam: "Los detalles crudos crean autenticidad." },
    { word: "experimentación formal", spainVariant: "la ruptura de convenciones", latamVariant: "la innovación estructural", phoneticSpain: "ex-per-ee-men-tah-see-OHN", phoneticLatam: "ex-per-ee-men-tah-see-OHN", english: "Breaking narrative conventions", partOfSpeech: "noun", exampleSentenceSpain: "Rechaza la narrativa lineal.", exampleSentenceLatam: "Nuevas estructuras desafían expectativas." },
    { word: "nostalgia estilística", spainVariant: "la evocación del pasado", latamVariant: "el retorno a géneros antiguos", phoneticSpain: "nos-TAHL-hee-ah", phoneticLatam: "nos-TAHL-hee-ah", english: "Evoking past literary forms", partOfSpeech: "noun", exampleSentenceSpain: "Evoca novelas picarescas.", exampleSentenceLatam: "Revive géneros con nuevo sentido." },
    { word: "voz narrativa", spainVariant: "la perspectiva del narrador", latamVariant: "la perspectiva narrativa", phoneticSpain: "vohz nah-rah-THEE-vah", phoneticLatam: "vohz nah-rah-tee-VAH", english: "Distinct authorial voice", partOfSpeech: "noun", exampleSentenceSpain: "Unamuno es intensamente personal.", exampleSentenceLatam: "Cortázar es única e inconfundible." },
    { word: "perspectiva del narrador", spainVariant: "punto de vista narrativo", latamVariant: "ángulo de narración", phoneticSpain: "per-spec-TEE-vah", phoneticLatam: "per-spec-TEE-vah", english: "Narrative perspective determining revelation", partOfSpeech: "noun", exampleSentenceSpain: "El omnisciente todo lo sabe.", exampleSentenceLatam: "La perspectiva limita o expande comprensión." },
    { word: "ruptura cronológica", spainVariant: "el desorden del tiempo", latamVariant: "la alteración temporal", phoneticSpain: "ROO-too-rah kro-noh-LOH-hee-kah", phoneticLatam: "ROO-too-rah kro-noh-LOH-hee-kah", english: "Deliberate breaking of sequential time", partOfSpeech: "noun", exampleSentenceSpain: "Desorienta deliberadamente.", exampleSentenceLatam: "Expone múltiples realidades." },
    { word: "flujo de conciencia", spainVariant: "corriente mental ininterrumpida", latamVariant: "pensamiento sin filtro", phoneticSpain: "FLOO-hoh de kon-see-EN-see-ah", phoneticLatam: "FLOO-hoh de kon-see-EN-see-ah", english: "Continuous stream of consciousness", partOfSpeech: "noun", exampleSentenceSpain: "Sin censura ni organización.", exampleSentenceLatam: "Técnica de Joyce adoptada globalmente." },
  ],
  grammarSection: [
    {
      title: "Subjunctive in Literary Analysis",
      spainContent: "Use subjunctive after expressions of possibility, doubt, interpretation. Pattern: 'Es posible que el narrador intente...' Peninsular Spanish maintains stricter subjunctive emphasis.",
      latamContent: "Literary convention favors subjunctive for analytical distance, though LATAM permits more indicative in informal discourse. Academic contexts preserve subjunctive rigor.",
      note: "Both regions use subjunctive in formal literary criticism; Spain emphasizes it more consistently.",
    },
    {
      title: "Conditional Perfect for Counterfactual Analysis",
      spainContent: "Form: habría + past participle. 'Si Cortázar hubiera seguido estructura lineal, la novela habría sido diferente.'",
      latamContent: "Identical structure in both Spain and LATAM. Common in academic discourse; demonstrates sophisticated literary speculation.",
      note: "Conditional perfect is identical across regions for counterfactual analysis.",
    },
  ],
  dialogues: [
    {
      id: "c2-01-dial-01",
      title: "Universidad de Madrid - Seminario de Literatura",
      region: "SPAIN",
      setting: "Universidad de Madrid - Seminario de Literatura Moderna",
      lines: [
        { speaker: "Profesora Alicia", text: "Eduardo, explica cómo Cortázar subvierte la estructura narrativa en 'Rayuela'.", region: "SPAIN", setting: "classroom" },
        { speaker: "Eduardo", text: "El autor fragmenta completamente la linealidad. Propone múltiples órdenes de lectura.", region: "SPAIN", setting: "classroom" },
        { speaker: "Profesora Alicia", text: "¿Cuál sería el efecto si mantuviera estructura convencional?", region: "SPAIN", setting: "classroom" },
        { speaker: "Eduardo", text: "Habría perdido la capacidad de cuestionar nuestra relación con el texto.", region: "SPAIN", setting: "classroom" },
        { speaker: "Profesora Alicia", text: "Observa el perspectivismo: cada capítulo adopta voz narrativa distinta.", region: "SPAIN", setting: "classroom" },
        { speaker: "Eduardo", text: "Sugiere que no existe verdad única. La realidad es multifacética.", region: "SPAIN", setting: "classroom" },
      ],
    },
    {
      id: "c2-01-dial-02",
      title: "Café Literario Barcelona",
      region: "SPAIN",
      setting: "Café Literario, Barcelona",
      lines: [
        { speaker: "Jaume", text: "Tu novela incorpora realismo mágico sin ser propiamente mágica.", region: "SPAIN", setting: "café" },
        { speaker: "Mariana", text: "Intento habitar el espacio entre lo real y lo imposible.", region: "SPAIN", setting: "café" },
        { speaker: "Jaume", text: "¿Observo pastiche, entonces?", region: "SPAIN", setting: "café" },
        { speaker: "Mariana", text: "Conversación consciente con la tradición. La autorreferencialidad expone el proceso.", region: "SPAIN", setting: "café" },
        { speaker: "Jaume", text: "Muchos encontrarán la densidad simbólica excesiva.", region: "SPAIN", setting: "café" },
        { speaker: "Mariana", text: "Si sacrificara la complejidad, la novela pierde su integridad.", region: "SPAIN", setting: "café" },
      ],
    },
    {
      id: "c2-01-dial-03",
      title: "Biblioteca Nacional España",
      region: "SPAIN",
      setting: "Biblioteca Nacional de España - Sala de Estudios",
      lines: [
        { speaker: "Prof. González", text: "Analiza el monólogo interior de Molly Bloom en 'Ulises'.", region: "SPAIN", setting: "library" },
        { speaker: "Laura", text: "Castellanos absorbe la técnica: corriente de conciencia sin puntuación.", region: "SPAIN", setting: "library" },
        { speaker: "Prof. González", text: "¿Reproduce o transforma?", region: "SPAIN", setting: "library" },
        { speaker: "Laura", text: "Transforma radicalmente. Joyce fragmenta mediante multiplicidad; Castellanos desmorona desde intención introspectiva.", region: "SPAIN", setting: "library" },
        { speaker: "Prof. González", text: "Articula esa distinción más.", region: "SPAIN", setting: "library" },
        { speaker: "Laura", text: "Joyce expone la mente como caos; Castellanos revela mente como conflicto existencial.", region: "SPAIN", setting: "library" },
      ],
    },
    {
      id: "c2-01-dial-04",
      title: "ITAM México - Seminario Avanzado",
      region: "LATAM",
      setting: "ITAM, Ciudad de México - Seminario Avanzado",
      lines: [
        { speaker: "Maestro Rodríguez", text: "García Márquez y Vargas Llosa emplean técnicas afines pero persiguen intenciones opuestas.", region: "LATAM", setting: "classroom" },
        { speaker: "Carlos", text: "García Márquez integra lo fantástico sin justificación. Vargas Llosa ancla la fantasía en contexto histórico.", region: "LATAM", setting: "classroom" },
        { speaker: "Maestro Rodríguez", text: "¿Diferencia ideológica?", region: "LATAM", setting: "classroom" },
        { speaker: "Carlos", text: "García Márquez celebra la ambigüedad; Vargas Llosa insiste en que la realidad política prevalece.", region: "LATAM", setting: "classroom" },
        { speaker: "Maestro Rodríguez", text: "¿Y Cortázar?", region: "LATAM", setting: "classroom" },
        { speaker: "Carlos", text: "Rechaza ambos. Su fragmentación propone que importa cómo el lector construye significado.", region: "LATAM", setting: "classroom" },
      ],
    },
    {
      id: "c2-01-dial-05",
      title: "Librería Santiago de Chile",
      region: "LATAM",
      setting: "Librería El Fondo, Santiago de Chile",
      lines: [
        { speaker: "Sofía", text: "Tu novela practica experimentación formal con moderación.", region: "LATAM", setting: "bookstore" },
        { speaker: "Miguel", text: "No miedo: responsabilidad. La innovación debe servir al tema.", region: "LATAM", setting: "bookstore" },
        { speaker: "Sofía", text: "Muchos considerarían eso conservadurismo.", region: "LATAM", setting: "bookstore" },
        { speaker: "Miguel", text: "Quizá. Los más radicales integran estructura y propósito indisolublemente.", region: "LATAM", setting: "bookstore" },
        { speaker: "Sofía", text: "¿Ejemplo?", region: "LATAM", setting: "bookstore" },
        { speaker: "Miguel", text: "'Operación masacre' de Valenzuela: la fragmentación documenta la represión misma.", region: "LATAM", setting: "bookstore" },
      ],
    },
    {
      id: "c2-01-dial-06",
      title: "UNAM México - Seminario de Literatura",
      region: "LATAM",
      setting: "Universidad Nacional Autónoma de México - Sala de Seminarios",
      lines: [
        { speaker: "Dra. Sáenz", text: "Examina el desorden temporal en 'La muerte de Artemio Cruz'.", region: "LATAM", setting: "classroom" },
        { speaker: "Julia", text: "Replica la fragmentación mental de Artemio en su lecho de muerte.", region: "LATAM", setting: "classroom" },
        { speaker: "Dra. Sáenz", text: "¿Por qué Fuentes eligió rechazar la cronología?", region: "LATAM", setting: "classroom" },
        { speaker: "Julia", text: "Para revelar que la identidad no es lineal. Artemio existe simultáneamente como joven, hombre poderoso y anciano.", region: "LATAM", setting: "classroom" },
        { speaker: "Dra. Sáenz", text: "La forma es inseparable del significado existencial.", region: "LATAM", setting: "classroom" },
        { speaker: "Julia", text: "Sin fragmentación, sería biografía. Con ella, es investigación metafísica sobre identidad.", region: "LATAM", setting: "classroom" },
      ],
    },
  ],
  quiz: [
    { questionId: "c2-01-q01", type: "multiple-choice", questionText: "¿Cuál es la diferencia fundamental entre García Márquez y Cortázar?", options: ["García Márquez mantiene narrativa lineal; Cortázar la fragmenta.", "García Márquez integra lo mágico sin justificación; Cortázar cuestiona la estructura narrativa misma.", "García Márquez es más realista; Cortázar es puramente fantástico.", "No existe diferencia significativa."], correctAnswer: "García Márquez integra lo mágico sin justificación; Cortázar cuestiona la estructura narrativa misma.", explanation: "García Márquez normaliza lo fantástico; Cortázar desmorona la narrativa misma." },
    { questionId: "c2-01-q02", type: "multiple-choice", questionText: "¿Qué es la intertextualidad?", options: ["La inclusión de múltiples perspectivas.", "La capacidad de un texto de referirse a otros textos mediante citas y ecos.", "El uso de técnicas de poesía en prosa.", "La fragmentación del tiempo."], correctAnswer: "La capacidad de un texto de referirse a otros textos mediante citas y ecos.", explanation: "La intertextualidad describe cómo los textos dialogan con otros textos." },
    { questionId: "c2-01-q03", type: "multiple-choice", questionText: "¿Cuál es el efecto del perspectivismo?", options: ["Crea perspectiva única del narrador.", "Permite múltiples interpretaciones simultáneas, reflejando complejidad de realidad.", "Simplifica la trama.", "Establece jerarquía clara."], correctAnswer: "Permite múltiples interpretaciones simultáneas, reflejando complejidad de realidad.", explanation: "García Márquez entrelaza múltiples perspectivas sobre Macondo." },
    { questionId: "c2-01-q04", type: "multiple-choice", questionText: "¿Qué distingue autorreferencialidad en Borges vs Cortázar?", options: ["Borges no es autorreferencial.", "Borges usa inversión intelectual (bibliotecas); Cortázar expone ruptura formal.", "Ambos son idénticamente autorreferenciales.", "Cortázar es autorreferencial; Borges practica realismo mágico."], correctAnswer: "Borges usa inversión intelectual (bibliotecas); Cortázar expone ruptura formal.", explanation: "Borges crea universo donde libros contienen otros infinitamente. Cortázar interrumpe Rayuela con notas del editor ficticio." },
    { questionId: "c2-01-q05", type: "multiple-choice", questionText: "¿Cuál es la función de densidad simbólica?", options: ["Simplificar mediante símbolos explícitos.", "Crear múltiples capas exigiendo análisis profundo.", "Eliminar interpretación mediante símbolos obvios.", "Decorar sin afectar significado."], correctAnswer: "Crear múltiples capas exigiendo análisis profundo.", explanation: "La densidad simbólica deliberada obliga al lector a participar activamente." },
  ],
  flashcards: [
    { id: "c2-01-fc01", frontSpain: "realismo mágico", frontLatam: "realismo mágico", backEnglish: "Integration of magical elements into realistic narratives (García Márquez)", variantDifferenceNote: "Identical across regions", exampleSentenceSpain: "El realismo mágico desafía lógica convencional.", exampleSentenceLatam: "García Márquez popularizó esto en Latinoamérica.", partOfSpeech: "noun" },
    { id: "c2-01-fc02", frontSpain: "fragmentación narrativa", frontLatam: "fragmentación narrativa", backEnglish: "Breaking linear structure into discontinuous pieces (Cortázar, Fuentes)", variantDifferenceNote: "Identical across regions", exampleSentenceSpain: "Cortázar desorienta deliberadamente al lector.", exampleSentenceLatam: "Fuentes revela múltiples perspectivas.", partOfSpeech: "noun" },
    { id: "c2-01-fc03", frontSpain: "perspectivismo", frontLatam: "perspectivismo", backEnglish: "Multiple simultaneous viewpoints revealing reality multiplicity", variantDifferenceNote: "Identical across regions", exampleSentenceSpain: "García Márquez permite múltiples interpretaciones.", exampleSentenceLatam: "Enriquece la complejidad narrativa.", partOfSpeech: "noun" },
    { id: "c2-01-fc04", frontSpain: "autorreferencialidad", frontLatam: "autorreferencialidad", backEnglish: "Text referring to its own creation and fictionality (Borges)", variantDifferenceNote: "Identical across regions", exampleSentenceSpain: "Borges expone la construcción textual.", exampleSentenceLatam: "Practica autorreferencialidad extrema.", partOfSpeech: "noun" },
    { id: "c2-01-fc05", frontSpain: "monólogo interior", frontLatam: "monólogo interior", backEnglish: "Stream of consciousness revealing unfiltered thought (Joyce)", variantDifferenceNote: "Identical across regions", exampleSentenceSpain: "Joyce influye en prosa moderna.", exampleSentenceLatam: "Revela la mente sin filtro.", partOfSpeech: "noun" },
    { id: "c2-01-fc06", frontSpain: "intertextualidad", frontLatam: "intertextualidad", backEnglish: "References and dialogues between texts creating new meanings", variantDifferenceNote: "Identical across regions", exampleSentenceSpain: "Borges crea redes de significado complejas.", exampleSentenceLatam: "Los textos dialogan entre sí.", partOfSpeech: "noun" },
    { id: "c2-01-fc07", frontSpain: "metáfora extendida", frontLatam: "metáfora extendida", backEnglish: "Sustained symbolic language functioning at multiple levels", variantDifferenceNote: "Identical across regions", exampleSentenceSpain: "El laberinto permea toda la novela.", exampleSentenceLatam: "Funciona como estructura narrativa.", partOfSpeech: "noun" },
    { id: "c2-01-fc08", frontSpain: "disolución temporal", frontLatam: "disolución temporal", backEnglish: "Non-linear time rejecting chronological progression", variantDifferenceNote: "Identical across regions", exampleSentenceSpain: "Rayuela confunde deliberadamente.", exampleSentenceLatam: "Revela multiplicidad del ser.", partOfSpeech: "noun" },
    { id: "c2-01-fc09", frontSpain: "pastiche literario", frontLatam: "pastiche literario", backEnglish: "Deliberate imitation or parody for critical purposes", variantDifferenceNote: "Identical across regions", exampleSentenceSpain: "Cortázar critica géneros establecidos.", exampleSentenceLatam: "Permite jugar con tradiciones.", partOfSpeech: "noun" },
    { id: "c2-01-fc10", frontSpain: "densidad simbólica", frontLatam: "densidad simbólica", backEnglish: "Layered symbolic meanings requiring active interpretation", variantDifferenceNote: "Identical across regions", exampleSentenceSpain: "Fuentes exige análisis profundo.", exampleSentenceLatam: "Enriquece la experiencia de lectura.", partOfSpeech: "noun" },
    { id: "c2-01-fc11", frontSpain: "deconstrucción textual", frontLatam: "deconstrucción textual", backEnglish: "Analysis dismantling fixed meanings, revealing instability", variantDifferenceNote: "Identical across regions", exampleSentenceSpain: "Cuestiona significados aparentes.", exampleSentenceLatam: "Revela contradicciones internas.", partOfSpeech: "noun" },
    { id: "c2-01-fc12", frontSpain: "sinestesia narrativa", frontLatam: "sinestesia narrativa", backEnglish: "Blending sensory descriptions; visual as auditory, etc.", variantDifferenceNote: "Identical across regions", exampleSentenceSpain: "Describe colores como sonidos.", exampleSentenceLatam: "Entrelaza sentidos en descripción.", partOfSpeech: "noun" },
    { id: "c2-01-fc13", frontSpain: "poesía en prosa", frontLatam: "poesía en prosa", backEnglish: "Lyrical, poetic language within narrative prose", variantDifferenceNote: "Identical across regions", exampleSentenceSpain: "Baudelaire influye en modernistas.", exampleSentenceLatam: "Eleva lo ordinario a lo sublime.", partOfSpeech: "noun" },
    { id: "c2-01-fc14", frontSpain: "realismo sucio", frontLatam: "realismo sucio", backEnglish: "Minimalist, gritty style focusing on unglamorous reality", variantDifferenceNote: "Identical across regions", exampleSentenceSpain: "Rechaza ornamentación estilística.", exampleSentenceLatam: "Presenta la vida tal como es.", partOfSpeech: "noun" },
    { id: "c2-01-fc15", frontSpain: "experimentación formal", frontLatam: "experimentación formal", backEnglish: "Breaking conventions through innovative structure", variantDifferenceNote: "Identical across regions", exampleSentenceSpain: "Desafía expectativas de vanguardia.", exampleSentenceLatam: "Abre nuevas posibilidades narrativas.", partOfSpeech: "noun" },
    { id: "c2-01-fc16", frontSpain: "nostalgia estilística", frontLatam: "nostalgia estilística", backEnglish: "Evoking past forms while critiquing/transforming them", variantDifferenceNote: "Identical across regions", exampleSentenceSpain: "Evoca novelas picarescas con ironía.", exampleSentenceLatam: "Permite reinterpretación de formas.", partOfSpeech: "noun" },
    { id: "c2-01-fc17", frontSpain: "voz narrativa", frontLatam: "voz narrativa", backEnglish: "Distinct authorial voice shaping interpretation", variantDifferenceNote: "Identical across regions", exampleSentenceSpain: "Unamuno es intensamente personal.", exampleSentenceLatam: "Cortázar es única e inconfundible.", partOfSpeech: "noun" },
    { id: "c2-01-fc18", frontSpain: "perspectiva del narrador", frontLatam: "perspectiva del narrador", backEnglish: "Narrative perspective determining revelation/interpretation", variantDifferenceNote: "Identical across regions", exampleSentenceSpain: "Omnisciente todo lo sabe.", exampleSentenceLatam: "Limita o expande comprensión.", partOfSpeech: "noun" },
    { id: "c2-01-fc19", frontSpain: "ruptura cronológica", frontLatam: "ruptura cronológica", backEnglish: "Deliberate breaking of sequential time", variantDifferenceNote: "Identical across regions", exampleSentenceSpain: "Desorienta deliberadamente.", exampleSentenceLatam: "Expone múltiples realidades.", partOfSpeech: "noun" },
    { id: "c2-01-fc20", frontSpain: "flujo de conciencia", frontLatam: "flujo de conciencia", backEnglish: "Continuous stream of thoughts without logical organization", variantDifferenceNote: "Identical across regions", exampleSentenceSpain: "Revela la mente sin censura.", exampleSentenceLatam: "Técnica de Joyce adoptada globalmente.", partOfSpeech: "noun" },
  ],
  vocabularyJson: [],
  grammarJson: [],
  content: "C2.01 Classical & Modern Literature",
};

const C2_STUB: LessonData = {
  id: "",
  slug: "",
  title: "",
  description: "",
  level: "C2",
  difficulty: "Mastery",
  order: 0,
  imageUrl: null,
  durationMinutes: 120,
  isPublished: false,
  vocabularyTable: [],
  grammarSection: [],
  dialogues: [],
  quiz: [],
  flashcards: [],
  vocabularyJson: [],
  grammarJson: [],
  content: "",
};

const LESSON_C2_02 = { ...C2_STUB, id: "c2-02", slug: "abstract-philosophical-debates", title: "Abstract Philosophical Debates", order: 32 };
const LESSON_C2_03 = { ...C2_STUB, id: "c2-03", slug: "legislative-bureaucratic-legal", title: "Legislative, Bureaucratic & Legal Registers", order: 33 };
const LESSON_C2_04 = { ...C2_STUB, id: "c2-04", slug: "systemic-irony-satire", title: "Systemic Irony, Satire & Political Cartoons", order: 34 };
const LESSON_C2_05 = { ...C2_STUB, id: "c2-05", slug: "idiomatic-micro-regions-spain", title: "Idiomatic Micro-Regions (Spain)", order: 35 };
const LESSON_C2_06 = { ...C2_STUB, id: "c2-06", slug: "idiomatic-micro-regions-latam", title: "Idiomatic Micro-Regions (LATAM)", order: 36 };
const LESSON_C2_07 = { ...C2_STUB, id: "c2-07", slug: "academic-reporting-editorial", title: "Academic Reporting & Editorial Writing", order: 37 };
const LESSON_C2_08 = { ...C2_STUB, id: "c2-08", slug: "crisis-management-public-address", title: "Crisis Management & Public Address", order: 38 };
const LESSON_C2_09 = { ...C2_STUB, id: "c2-09", slug: "archaisms-etymology-historic-sayings", title: "Archaisms, Etymology & Historic Sayings", order: 39 };
const LESSON_C2_10 = { ...C2_STUB, id: "c2-10", slug: "complete-fluency-synthesis", title: "Complete Fluency Synthesis", order: 40 };

export const C2_LESSONS = [
  LESSON_C2_01,
  LESSON_C2_02,
  LESSON_C2_03,
  LESSON_C2_04,
  LESSON_C2_05,
  LESSON_C2_06,
  LESSON_C2_07,
  LESSON_C2_08,
  LESSON_C2_09,
  LESSON_C2_10,
];