import type { LessonData, RegionalVocabItem, GrammarItem, DialogueScenario, QuizQuestion, FlashcardItem } from "./lessons-data";

const B1_LESSONS = {
  "b1-01-friends-social-life": {
    title: "Friends & Social Life",
    description: "Talk about friendships, making plans, parties, and hanging out the way Mexicans really do",
    vocabulary: [
      { word: "Friend", spainVariant: "Amigo/a", latamVariant: "Amigo/a", phoneticSpain: "[ah-MEE-go]", phoneticLatam: "[ah-MEE-go]", english: "Friend", partOfSpeech: "noun", exampleSentenceSpain: "Mi amiga es muy simpática.", exampleSentenceLatam: "Mi amiga vive aquí." },
      { word: "Best friend", spainVariant: "Mejor amigo/a", latamVariant: "Mejor amigo/a", phoneticSpain: "[meh-HOR ah-MEE-go]", phoneticLatam: "[meh-HOR ah-MEE-go]", english: "Best friend", partOfSpeech: "noun", exampleSentenceSpain: "Es mi mejor amiga.", exampleSentenceLatam: "Somos mejores amigos." },
      { word: "Close friend", spainVariant: "Amigo/a íntimo/a", latamVariant: "Amigo/a cercano/a", phoneticSpain: "[ah-MEE-go EEN-tee-mo]", phoneticLatam: "[ah-MEE-go ser-KAH-no]", english: "Close friend", partOfSpeech: "noun", exampleSentenceSpain: "Tengo amigos íntimos en la universidad.", exampleSentenceLatam: "Mis amigos cercanos me ayudan." },
      { word: "Friendship", spainVariant: "Amistad", latamVariant: "Amistad", phoneticSpain: "[ah-mis-TAHD]", phoneticLatam: "[ah-mis-TAHD]", english: "Friendship", partOfSpeech: "noun", exampleSentenceSpain: "Nuestra amistad es fuerte.", exampleSentenceLatam: "La amistad es importante." },
      { word: "To hang out", spainVariant: "Pasar tiempo", latamVariant: "Pasar el rato", phoneticSpain: "[pah-SAHR tee-EHM-po]", phoneticLatam: "[pah-SAHR el RAH-to]", english: "To hang out", partOfSpeech: "verb", exampleSentenceSpain: "Pasamos tiempo juntos.", exampleSentenceLatam: "Pasamos el rato cada semana." },
      { word: "To meet up", spainVariant: "Quedar", latamVariant: "Quedar/Encontrarse", phoneticSpain: "[keh-DAHR]", phoneticLatam: "[keh-DAHR]", english: "To meet up", partOfSpeech: "verb", exampleSentenceSpain: "¿Quedamos mañana?", exampleSentenceLatam: "¿Nos encontramos en el café?" },
      { word: "Party", spainVariant: "Fiesta", latamVariant: "Fiesta", phoneticSpain: "[fee-ES-tah]", phoneticLatam: "[fee-ES-tah]", english: "Party", partOfSpeech: "noun", exampleSentenceSpain: "Hay una fiesta el sábado.", exampleSentenceLatam: "¿Vienes a la fiesta?" },
      { word: "Gathering", spainVariant: "Reunión", latamVariant: "Reunión", phoneticSpain: "[reh-oo-nee-OHN]", phoneticLatam: "[reh-oo-nee-OHN]", english: "Gathering", partOfSpeech: "noun", exampleSentenceSpain: "Es una reunión de amigos.", exampleSentenceLatam: "Vamos a una reunión." },
      { word: "To invite", spainVariant: "Invitar", latamVariant: "Invitar", phoneticSpain: "[in-vee-TAHR]", phoneticLatam: "[in-vee-TAHR]", english: "To invite", partOfSpeech: "verb", exampleSentenceSpain: "Te invito a la fiesta.", exampleSentenceLatam: "Te invito a cenar." },
      { word: "To celebrate", spainVariant: "Celebrar", latamVariant: "Celebrar", phoneticSpain: "[seh-leh-BRAHR]", phoneticLatam: "[seh-leh-BRAHR]", english: "To celebrate", partOfSpeech: "verb", exampleSentenceSpain: "Celebramos el cumpleaños.", exampleSentenceLatam: "Vamos a celebrar." },
      { word: "Birthday", spainVariant: "Cumpleaños", latamVariant: "Cumpleaños", phoneticSpain: "[koom-pleh-AHN-yos]", phoneticLatam: "[koom-pleh-AHN-yos]", english: "Birthday", partOfSpeech: "noun", exampleSentenceSpain: "Mañana es mi cumpleaños.", exampleSentenceLatam: "¿Cuándo es tu cumpleaños?" },
      { word: "Anniversary", spainVariant: "Aniversario", latamVariant: "Aniversario", phoneticSpain: "[ah-nee-ver-SAH-ree-o]", phoneticLatam: "[ah-nee-ver-SAH-ree-o]", english: "Anniversary", partOfSpeech: "noun", exampleSentenceSpain: "Hoy es nuestro aniversario.", exampleSentenceLatam: "Cumplimos un año juntos." },
      { word: "To have fun", spainVariant: "Divertirse", latamVariant: "Divertirse", phoneticSpain: "[dee-ver-TEER-seh]", phoneticLatam: "[dee-ver-TEER-seh]", english: "To have fun", partOfSpeech: "verb", exampleSentenceSpain: "Nos divertimos mucho.", exampleSentenceLatam: "¡Que nos divirtamos!" },
      { word: "Fun", spainVariant: "Diversión", latamVariant: "Diversión", phoneticSpain: "[dee-ver-see-OHN]", phoneticLatam: "[dee-ver-see-OHN]", english: "Fun", partOfSpeech: "noun", exampleSentenceSpain: "¡Qué diversión!", exampleSentenceLatam: "Fue muy divertido." },
      { word: "Boring", spainVariant: "Aburrido/a", latamVariant: "Aburrido/a", phoneticSpain: "[ah-boo-RREE-do]", phoneticLatam: "[ah-boo-RREE-do]", english: "Boring", partOfSpeech: "adjective", exampleSentenceSpain: "La película fue aburrida.", exampleSentenceLatam: "Fue aburrido." },
      { word: "Cool/Fun", spainVariant: "Guay/Chulo", latamVariant: "Chido/Padre", phoneticSpain: "[gwye/CHOO-lo]", phoneticLatam: "[CHEE-do/PAH-dreh]", english: "Cool/Fun", partOfSpeech: "adjective", exampleSentenceSpain: "¡Eso es guay!", exampleSentenceLatam: "¡Qué padre!" },
      { word: "Awesome", spainVariant: "Genial", latamVariant: "Increíble", phoneticSpain: "[hen-ee-AHL]", phoneticLatam: "[in-kreh-EE-bleh]", english: "Awesome", partOfSpeech: "adjective", exampleSentenceSpain: "¡Fue genial!", exampleSentenceLatam: "¡Increíble!" },
      { word: "To get along", spainVariant: "Llevarse bien", latamVariant: "Llevarse bien", phoneticSpain: "[yeh-VAR-seh bee-EHN]", phoneticLatam: "[yeh-VAR-seh bee-EHN]", english: "To get along", partOfSpeech: "verb", exampleSentenceSpain: "Nos llevamos bien.", exampleSentenceLatam: "Se llevan muy bien." },
      { word: "To argue", spainVariant: "Discutir", latamVariant: "Pelear", phoneticSpain: "[dis-koo-TEER]", phoneticLatam: "[peh-leh-AHR]", english: "To argue", partOfSpeech: "verb", exampleSentenceSpain: "No discutimos.", exampleSentenceLatam: "No peleamos." },
      { word: "Group of friends", spainVariant: "Grupo de amigos", latamVariant: "Banda de amigos", phoneticSpain: "[GROO-po deh ah-MEE-gos]", phoneticLatam: "[BAHN-dah deh ah-MEE-gos]", english: "Group of friends", partOfSpeech: "noun", exampleSentenceSpain: "Mi grupo de amigos es grande.", exampleSentenceLatam: "Salimos con nuestra banda." },
    ],
  },
  "b1-02-dating-relationships": {
    title: "Dating & Relationships",
    description: "Navigate flirting, dating, and relationships naturally",
    vocabulary: [
      { word: "To flirt", spainVariant: "Coquetear", latamVariant: "Flirtear", phoneticSpain: "[ko-keh-teh-AHR]", phoneticLatam: "[flir-teh-AHR]", english: "To flirt", partOfSpeech: "verb", exampleSentenceSpain: "Está coqueteando contigo.", exampleSentenceLatam: "Está flirteando." },
      { word: "To like someone", spainVariant: "Gustar", latamVariant: "Gustar", phoneticSpain: "[goos-TAHR]", phoneticLatam: "[goos-TAHR]", english: "To like someone", partOfSpeech: "verb", exampleSentenceSpain: "Me gusta.", exampleSentenceLatam: "Me gusta." },
      { word: "Crush", spainVariant: "Ligue", latamVariant: "Crush", phoneticSpain: "[LEE-geh]", phoneticLatam: "[krosh]", english: "Crush", partOfSpeech: "noun", exampleSentenceSpain: "Tengo un ligue.", exampleSentenceLatam: "Tiene un crush." },
      { word: "To ask out", spainVariant: "Invitar a salir", latamVariant: "Invitar a salir", phoneticSpain: "[in-vee-TAHR ah sah-LEER]", phoneticLatam: "[in-vee-TAHR ah sah-LEER]", english: "To ask out", partOfSpeech: "verb", exampleSentenceSpain: "Te invito a salir.", exampleSentenceLatam: "¿Me invitas a salir?" },
      { word: "Dating", spainVariant: "Salir juntos", latamVariant: "Estar saliendo", phoneticSpain: "[sah-LEER HOON-tos]", phoneticLatam: "[es-TAHR sah-lee-EHN-do]", english: "Dating", partOfSpeech: "verb", exampleSentenceSpain: "Estamos saliendo juntos.", exampleSentenceLatam: "Estamos saliendo." },
      { word: "Boyfriend/Girlfriend", spainVariant: "Novio/a", latamVariant: "Novio/a", phoneticSpain: "[NOH-vee-o]", phoneticLatam: "[NOH-vee-o]", english: "Boyfriend/Girlfriend", partOfSpeech: "noun", exampleSentenceSpain: "Mi novio es ingeniero.", exampleSentenceLatam: "Mi novia estudia medicina." },
      { word: "Partner", spainVariant: "Pareja", latamVariant: "Pareja", phoneticSpain: "[pah-REH-hah]", phoneticLatam: "[pah-REH-hah]", english: "Partner", partOfSpeech: "noun", exampleSentenceSpain: "Mi pareja y yo viajamos juntos.", exampleSentenceLatam: "Con mi pareja nos llevamos bien." },
      { word: "Relationship", spainVariant: "Relación", latamVariant: "Relación", phoneticSpain: "[reh-lah-see-OHN]", phoneticLatam: "[reh-lah-see-OHN]", english: "Relationship", partOfSpeech: "noun", exampleSentenceSpain: "Nuestra relación es fuerte.", exampleSentenceLatam: "Tenemos una buena relación." },
      { word: "Love", spainVariant: "Amor", latamVariant: "Amor", phoneticSpain: "[ah-MOR]", phoneticLatam: "[ah-MOR]", english: "Love", partOfSpeech: "noun", exampleSentenceSpain: "Es amor verdadero.", exampleSentenceLatam: "Es amor puro." },
      { word: "To love", spainVariant: "Amar", latamVariant: "Amar", phoneticSpain: "[ah-MAHR]", phoneticLatam: "[ah-MAHR]", english: "To love", partOfSpeech: "verb", exampleSentenceSpain: "Te amo.", exampleSentenceLatam: "Te amo mucho." },
      { word: "Jealousy", spainVariant: "Celos", latamVariant: "Celos", phoneticSpain: "[SEH-los]", phoneticLatam: "[SEH-los]", english: "Jealousy", partOfSpeech: "noun", exampleSentenceSpain: "Tiene celos.", exampleSentenceLatam: "Tengo celos." },
      { word: "To cheat", spainVariant: "Traicionar", latamVariant: "Engañar", phoneticSpain: "[trah-ee-see-o-NAHR]", phoneticLatam: "[en-gahn-YAR]", english: "To cheat", partOfSpeech: "verb", exampleSentenceSpain: "No te traicionaría.", exampleSentenceLatam: "No te engañaría." },
      { word: "To break up", spainVariant: "Romper", latamVariant: "Terminar", phoneticSpain: "[rom-PER]", phoneticLatam: "[ter-mee-NAHR]", english: "To break up", partOfSpeech: "verb", exampleSentenceSpain: "Rompimos.", exampleSentenceLatam: "Terminamos." },
      { word: "Breakup", spainVariant: "Ruptura", latamVariant: "Término", phoneticSpain: "[roop-TOO-rah]", phoneticLatam: "[TER-mee-no]", english: "Breakup", partOfSpeech: "noun", exampleSentenceSpain: "La ruptura fue difícil.", exampleSentenceLatam: "Fue un término difícil." },
      { word: "To reconcile", spainVariant: "Reconciliarse", latamVariant: "Reconciliarse", phoneticSpain: "[reh-kon-see-lee-AHR-seh]", phoneticLatam: "[reh-kon-see-lee-AHR-seh]", english: "To reconcile", partOfSpeech: "verb", exampleSentenceSpain: "Se reconciliaron.", exampleSentenceLatam: "Nos reconciliamos." },
      { word: "To propose", spainVariant: "Proponer matrimonio", latamVariant: "Proponer matrimonio", phoneticSpain: "[pro-po-NER mah-tree-MOH-nee-o]", phoneticLatam: "[pro-po-NER mah-tree-MOH-nee-o]", english: "To propose", partOfSpeech: "verb", exampleSentenceSpain: "Le propuso matrimonio.", exampleSentenceLatam: "Le propuso casarse." },
      { word: "Engagement", spainVariant: "Noviazgo", latamVariant: "Compromiso", phoneticSpain: "[no-vee-AHS-go]", phoneticLatam: "[kom-pro-MEE-so]", english: "Engagement", partOfSpeech: "noun", exampleSentenceSpain: "Anunciaron el noviazgo.", exampleSentenceLatam: "Tienen un compromiso." },
      { word: "Wedding", spainVariant: "Boda", latamVariant: "Boda", phoneticSpain: "[BOH-dah]", phoneticLatam: "[BOH-dah]", english: "Wedding", partOfSpeech: "noun", exampleSentenceSpain: "La boda es en junio.", exampleSentenceLatam: "Iremos a la boda." },
      { word: "Husband/Wife", spainVariant: "Marido/Esposa", latamVariant: "Esposo/a", phoneticSpain: "[mah-REE-do/es-POH-sah]", phoneticLatam: "[es-POH-so]", english: "Husband/Wife", partOfSpeech: "noun", exampleSentenceSpain: "Mi marido trabaja aquí.", exampleSentenceLatam: "Mi esposa es doctora." },
      { word: "Marriage", spainVariant: "Matrimonio", latamVariant: "Matrimonio", phoneticSpain: "[mah-tree-MOH-nee-o]", phoneticLatam: "[mah-tree-MOH-nee-o]", english: "Marriage", partOfSpeech: "noun", exampleSentenceSpain: "El matrimonio es para siempre.", exampleSentenceLatam: "El matrimonio requiere dedicación." },
    ],
  },
  "b1-03-storytelling": {
    title: "Storytelling",
    description: "Tell engaging stories with natural connectors and reactions",
    vocabulary: [
      { word: "Once upon a time", spainVariant: "Érase una vez", latamVariant: "Érase una vez", phoneticSpain: "[EH-rah-seh OO-nah ves]", phoneticLatam: "[EH-rah-seh OO-nah ves]", english: "Once upon a time", partOfSpeech: "phrase", exampleSentenceSpain: "Érase una vez un príncipe.", exampleSentenceLatam: "Érase una vez en un país lejano." },
      { word: "There was/were", spainVariant: "Había/Había", latamVariant: "Había", phoneticSpain: "[ah-BEE-ah]", phoneticLatam: "[ah-BEE-ah]", english: "There was/were", partOfSpeech: "verb", exampleSentenceSpain: "Había un castillo.", exampleSentenceLatam: "Había mucha gente." },
      { word: "It happened that", spainVariant: "Pasó que", latamVariant: "Pasó que", phoneticSpain: "[pah-SOH keh]", phoneticLatam: "[pah-SOH keh]", english: "It happened that", partOfSpeech: "phrase", exampleSentenceSpain: "Pasó que uno de ellos desapareció.", exampleSentenceLatam: "Pasó que llegó la policía." },
      { word: "Suddenly", spainVariant: "De repente", latamVariant: "De repente", phoneticSpain: "[deh reh-PEN-teh]", phoneticLatam: "[deh reh-PEN-teh]", english: "Suddenly", partOfSpeech: "adverb", exampleSentenceSpain: "De repente, oyó un ruido.", exampleSentenceLatam: "De repente, se apagó la luz." },
      { word: "What happened next", spainVariant: "Lo que pasó después", latamVariant: "Lo que pasó después", phoneticSpain: "[lo keh pah-SOH des-PWES]", phoneticLatam: "[lo keh pah-SOH des-PWES]", english: "What happened next", partOfSpeech: "phrase", exampleSentenceSpain: "Lo que pasó después fue increíble.", exampleSentenceLatam: "Lo que pasó después cambió todo." },
      { word: "Then", spainVariant: "Entonces/Luego", latamVariant: "Entonces", phoneticSpain: "[en-TON-ses/loo-EH-go]", phoneticLatam: "[en-TON-ses]", english: "Then", partOfSpeech: "conjunction", exampleSentenceSpain: "Entonces, decidimos irnos.", exampleSentenceLatam: "Entonces nos fuimos." },
      { word: "At that moment", spainVariant: "En ese momento", latamVariant: "En ese momento", phoneticSpain: "[en EH-seh mo-MEN-to]", phoneticLatam: "[en EH-seh mo-MEN-to]", english: "At that moment", partOfSpeech: "phrase", exampleSentenceSpain: "En ese momento, sonó el teléfono.", exampleSentenceLatam: "En ese momento, entró él." },
      { word: "Finally", spainVariant: "Finalmente/Por fin", latamVariant: "Por fin", phoneticSpain: "[fee-nahl-MEN-teh/por fin]", phoneticLatam: "[por fin]", english: "Finally", partOfSpeech: "adverb", exampleSentenceSpain: "Por fin llegamos.", exampleSentenceLatam: "Finalmente, nos encontramos." },
      { word: "The moral of the story", spainVariant: "La moraleja", latamVariant: "La moraleja", phoneticSpain: "[lah mo-rah-LEH-hah]", phoneticLatam: "[lah mo-rah-LEH-hah]", english: "The moral of the story", partOfSpeech: "noun", exampleSentenceSpain: "La moraleja es: nunca rendirse.", exampleSentenceLatam: "La moraleja fue una lección importante." },
      { word: "You won't believe what happened", spainVariant: "No vas a creer lo que pasó", latamVariant: "No vas a creer lo que pasó", phoneticSpain: "[no vahs ah kreh-ER lo keh pah-SOH]", phoneticLatam: "[no vahs ah kreh-ER lo keh pah-SOH]", english: "You won't believe what happened", partOfSpeech: "phrase", exampleSentenceSpain: "No vas a creer lo que pasó después.", exampleSentenceLatam: "No vas a creer, pero es verdad." },
      { word: "I can't believe it", spainVariant: "No me lo creo", latamVariant: "No me lo creo", phoneticSpain: "[no meh lo KREH-o]", phoneticLatam: "[no meh lo KREH-o]", english: "I can't believe it", partOfSpeech: "phrase", exampleSentenceSpain: "¡No me lo creo!", exampleSentenceLatam: "¡Eso no es posible!" },
      { word: "That's crazy", spainVariant: "¡Qué locura!", latamVariant: "¡Qué locura!", phoneticSpain: "[keh lo-KOO-rah]", phoneticLatam: "[keh lo-KOO-rah]", english: "That's crazy", partOfSpeech: "interjection", exampleSentenceSpain: "¡Qué locura!", exampleSentenceLatam: "¡Eso es una locura!" },
      { word: "No way!", spainVariant: "¡Qué va!", latamVariant: "¡No manches!", phoneticSpain: "[keh vah]", phoneticLatam: "[no MAHN-ches]", english: "No way!", partOfSpeech: "interjection", exampleSentenceSpain: "¿En serio? ¡Qué va!", exampleSentenceLatam: "¡No manches, verdad?" },
      { word: "Wait, let me explain", spainVariant: "Espera, déjame explicar", latamVariant: "Espera, déjame explicar", phoneticSpain: "[es-PEH-rah DEH-hah-meh ex-plee-KAHR]", phoneticLatam: "[es-PEH-rah DEH-hah-meh ex-plee-KAHR]", english: "Wait, let me explain", partOfSpeech: "phrase", exampleSentenceSpain: "Espera, déjame explicar la situación.", exampleSentenceLatam: "Espera, no es lo que crees." },
      { word: "Let me tell you", spainVariant: "Déjame contarte", latamVariant: "Déjame contar", phoneticSpain: "[DEH-hah-meh kon-TAHR-teh]", phoneticLatam: "[DEH-hah-meh kon-TAHR]", english: "Let me tell you", partOfSpeech: "phrase", exampleSentenceSpain: "Déjame contarte una historia.", exampleSentenceLatam: "Déjame contar algo." },
      { word: "Setting", spainVariant: "Escenario", latamVariant: "Lugar", phoneticSpain: "[es-seh-NAH-ree-o]", phoneticLatam: "[loo-GAHR]", english: "Setting", partOfSpeech: "noun", exampleSentenceSpain: "El escenario era una pequeña aldea.", exampleSentenceLatam: "El lugar fue una montaña." },
      { word: "Character", spainVariant: "Personaje", latamVariant: "Personaje", phoneticSpain: "[per-so-NAH-heh]", phoneticLatam: "[per-so-NAH-heh]", english: "Character", partOfSpeech: "noun", exampleSentenceSpain: "El personaje principal era valiente.", exampleSentenceLatam: "El personaje cambió mucho." },
      { word: "Plot twist", spainVariant: "Giro inesperado", latamVariant: "Giro inesperado", phoneticSpain: "[HEE-ro in-es-peh-RAH-do]", phoneticLatam: "[HEE-ro in-es-peh-RAH-do]", english: "Plot twist", partOfSpeech: "noun", exampleSentenceSpain: "Hubo un giro inesperado.", exampleSentenceLatam: "¡Qué giro inesperado!" },
      { word: "Suspense", spainVariant: "Suspenso", latamVariant: "Suspenso", phoneticSpain: "[soos-PEN-so]", phoneticLatam: "[soos-PEN-so]", english: "Suspense", partOfSpeech: "noun", exampleSentenceSpain: "Mantuve el suspenso toda la noche.", exampleSentenceLatam: "Me tuvo en suspenso." },
      { word: "Ending", spainVariant: "Final/Desenlace", latamVariant: "Final", phoneticSpain: "[fee-NAHL/deh-sen-LAH-seh]", phoneticLatam: "[fee-NAHL]", english: "Ending", partOfSpeech: "noun", exampleSentenceSpain: "El final fue perfecto.", exampleSentenceLatam: "¿Cómo termina la historia?" },
    ],
  },
  "b1-04-opinions-discussions": {
    title: "Opinions & Discussions",
    description: "Share opinions, agree, disagree, and discuss ideas naturally",
    vocabulary: [
      { word: "I think", spainVariant: "Creo que", latamVariant: "Creo que", phoneticSpain: "[KREH-o keh]", phoneticLatam: "[KREH-o keh]", english: "I think", partOfSpeech: "phrase", exampleSentenceSpain: "Creo que tienes razón.", exampleSentenceLatam: "Creo que es una buena idea." },
      { word: "In my opinion", spainVariant: "En mi opinión", latamVariant: "En mi opinión", phoneticSpain: "[en mee o-pee-nee-OHN]", phoneticLatam: "[en mee o-pee-nee-OHN]", english: "In my opinion", partOfSpeech: "phrase", exampleSentenceSpain: "En mi opinión, es lo mejor.", exampleSentenceLatam: "En mi opinión, debes irte." },
      { word: "I agree", spainVariant: "Estoy de acuerdo", latamVariant: "Estoy de acuerdo", phoneticSpain: "[es-TOY deh ah-KWER-do]", phoneticLatam: "[es-TOY deh ah-KWER-do]", english: "I agree", partOfSpeech: "phrase", exampleSentenceSpain: "Estoy de acuerdo contigo.", exampleSentenceLatam: "Totalmente de acuerdo." },
      { word: "I disagree", spainVariant: "No estoy de acuerdo", latamVariant: "No estoy de acuerdo", phoneticSpain: "[no es-TOY deh ah-KWER-do]", phoneticLatam: "[no es-TOY deh ah-KWER-do]", english: "I disagree", partOfSpeech: "phrase", exampleSentenceSpain: "No estoy de acuerdo.", exampleSentenceLatam: "No coincido contigo." },
      { word: "I partially agree", spainVariant: "Parcialmente de acuerdo", latamVariant: "Parcialmente de acuerdo", phoneticSpain: "[par-see-ahl-MEN-teh deh ah-KWER-do]", phoneticLatam: "[par-see-ahl-MEN-teh deh ah-KWER-do]", english: "I partially agree", partOfSpeech: "phrase", exampleSentenceSpain: "Parcialmente de acuerdo.", exampleSentenceLatam: "Más o menos de acuerdo." },
      { word: "You're right", spainVariant: "Tienes razón", latamVariant: "Tienes razón", phoneticSpain: "[tee-EH-nes rah-SOHN]", phoneticLatam: "[tee-EH-nes rah-SOHN]", english: "You're right", partOfSpeech: "phrase", exampleSentenceSpain: "Tienes toda la razón.", exampleSentenceLatam: "Tienes razón, lo siento." },
      { word: "You're wrong", spainVariant: "Te equivocas", latamVariant: "Te equivocas", phoneticSpain: "[teh eh-kee-VOH-kahs]", phoneticLatam: "[teh eh-kee-VOH-kahs]", english: "You're wrong", partOfSpeech: "phrase", exampleSentenceSpain: "Creo que te equivocas.", exampleSentenceLatam: "Te equivocas, hermano." },
      { word: "That's not fair", spainVariant: "Eso no es justo", latamVariant: "Eso no es justo", phoneticSpain: "[EH-so no es HOOS-to]", phoneticLatam: "[EH-so no es HOOS-to]", english: "That's not fair", partOfSpeech: "phrase", exampleSentenceSpain: "Eso no es justo para él.", exampleSentenceLatam: "Eso no es justo." },
      { word: "It's not my fault", spainVariant: "No es mi culpa", latamVariant: "No es mi culpa", phoneticSpain: "[no es mee KOOL-pah]", phoneticLatam: "[no es mee KOOL-pah]", english: "It's not my fault", partOfSpeech: "phrase", exampleSentenceSpain: "No es mi culpa.", exampleSentenceLatam: "No tiene la culpa." },
      { word: "I can see your point", spainVariant: "Entiendo tu punto", latamVariant: "Entiendo tu punto", phoneticSpain: "[en-tee-EHN-do too POON-to]", phoneticLatam: "[en-tee-EHN-do too POON-to]", english: "I can see your point", partOfSpeech: "phrase", exampleSentenceSpain: "Entiendo tu punto.", exampleSentenceLatam: "Veo lo que dices." },
      { word: "Let's discuss this", spainVariant: "Hablemos de esto", latamVariant: "Hablemos de esto", phoneticSpain: "[ah-BLEH-mos deh ES-to]", phoneticLatam: "[ah-BLEH-mos deh ES-to]", english: "Let's discuss this", partOfSpeech: "phrase", exampleSentenceSpain: "Hablemos de esto con calma.", exampleSentenceLatam: "Vamos a hablar de esto." },
      { word: "I have a different perspective", spainVariant: "Tengo otra perspectiva", latamVariant: "Tengo otro punto de vista", phoneticSpain: "[TEN-go OH-trah per-spek-TEE-vah]", phoneticLatam: "[TEN-go OH-tro POON-to deh VIS-tah]", english: "I have a different perspective", partOfSpeech: "phrase", exampleSentenceSpain: "Tengo otra perspectiva.", exampleSentenceLatam: "Veo las cosas diferente." },
      { word: "To debate", spainVariant: "Debatir", latamVariant: "Debatir", phoneticSpain: "[deh-bah-TEER]", phoneticLatam: "[deh-bah-TEER]", english: "To debate", partOfSpeech: "verb", exampleSentenceSpain: "Debatimos durante horas.", exampleSentenceLatam: "Debatieron sobre política." },
      { word: "Argument", spainVariant: "Argumento", latamVariant: "Argumento", phoneticSpain: "[ar-goo-MEN-to]", phoneticLatam: "[ar-goo-MEN-to]", english: "Argument", partOfSpeech: "noun", exampleSentenceSpain: "Tu argumento es sólido.", exampleSentenceLatam: "Es un buen argumento." },
      { word: "Evidence", spainVariant: "Prueba", latamVariant: "Evidencia", phoneticSpain: "[proo-EH-bah]", phoneticLatam: "[eh-vee-DEN-see-ah]", english: "Evidence", partOfSpeech: "noun", exampleSentenceSpain: "Tienes prueba de eso?", exampleSentenceLatam: "¿Hay evidencia?" },
      { word: "Point of view", spainVariant: "Punto de vista", latamVariant: "Punto de vista", phoneticSpain: "[POON-to deh VIS-tah]", phoneticLatam: "[POON-to deh VIS-tah]", english: "Point of view", partOfSpeech: "noun", exampleSentenceSpain: "Desde mi punto de vista...", exampleSentenceLatam: "Desde otra perspectiva..." },
      { word: "To express an opinion", spainVariant: "Expresar una opinión", latamVariant: "Dar una opinión", phoneticSpain: "[ex-preh-SAHR OO-nah o-pee-nee-OHN]", phoneticLatam: "[dahr OO-nah o-pee-nee-OHN]", english: "To express an opinion", partOfSpeech: "verb", exampleSentenceSpain: "Expresa libremente tu opinión.", exampleSentenceLatam: "Dame tu opinión." },
      { word: "Controversial", spainVariant: "Controvertido", latamVariant: "Controvertido", phoneticSpain: "[kon-tro-ver-TEE-do]", phoneticLatam: "[kon-tro-ver-TEE-do]", english: "Controversial", partOfSpeech: "adjective", exampleSentenceSpain: "Es un tema controvertido.", exampleSentenceLatam: "Un tema muy discutido." },
      { word: "To convince", spainVariant: "Convencer", latamVariant: "Convencer", phoneticSpain: "[kon-ven-SER]", phoneticLatam: "[kon-ven-SER]", english: "To convince", partOfSpeech: "verb", exampleSentenceSpain: "No me convences.", exampleSentenceLatam: "¿Me convences?" },
      { word: "Reasonable", spainVariant: "Razonable", latamVariant: "Razonable", phoneticSpain: "[rah-zo-NAH-bleh]", phoneticLatam: "[rah-zo-NAH-bleh]", english: "Reasonable", partOfSpeech: "adjective", exampleSentenceSpain: "Eso es razonable.", exampleSentenceLatam: "Es una posición razonable." },
    ],
  },
  "b1-05-giving-advice": {
    title: "Giving Advice",
    description: "Ask for and give advice naturally and effectively",
    vocabulary: [
      { word: "To advise", spainVariant: "Aconsejar", latamVariant: "Aconsejar", phoneticSpain: "[ah-kon-seh-HAHR]", phoneticLatam: "[ah-kon-seh-HAHR]", english: "To advise", partOfSpeech: "verb", exampleSentenceSpain: "Te aconsejo que hables con él.", exampleSentenceLatam: "Te aconsejo que vayas." },
      { word: "Advice", spainVariant: "Consejo", latamVariant: "Consejo", phoneticSpain: "[kon-SEH-ho]", phoneticLatam: "[kon-SEH-ho]", english: "Advice", partOfSpeech: "noun", exampleSentenceSpain: "¿Qué consejo me das?", exampleSentenceLatam: "Necesito un consejo." },
      { word: "To ask for advice", spainVariant: "Pedir consejo", latamVariant: "Pedir consejo", phoneticSpain: "[peh-DEER kon-SEH-ho]", phoneticLatam: "[peh-DEER kon-SEH-ho]", english: "To ask for advice", partOfSpeech: "verb", exampleSentenceSpain: "Te pido consejo.", exampleSentenceLatam: "¿Me das un consejo?" },
      { word: "You should", spainVariant: "Deberías", latamVariant: "Deberías", phoneticSpain: "[deh-beh-REE-ahs]", phoneticLatam: "[deh-beh-REE-ahs]", english: "You should", partOfSpeech: "phrase", exampleSentenceSpain: "Deberías intentarlo.", exampleSentenceLatam: "Deberías hablar con ella." },
      { word: "I think you should", spainVariant: "Creo que deberías", latamVariant: "Creo que deberías", phoneticSpain: "[KREH-o keh deh-beh-REE-ahs]", phoneticLatam: "[KREH-o keh deh-beh-REE-ahs]", english: "I think you should", partOfSpeech: "phrase", exampleSentenceSpain: "Creo que deberías decirle la verdad.", exampleSentenceLatam: "Creo que deberías irte de vacaciones." },
      { word: "Why don't you", spainVariant: "¿Por qué no", latamVariant: "¿Por qué no", phoneticSpain: "[por keh no]", phoneticLatam: "[por keh no]", english: "Why don't you", partOfSpeech: "phrase", exampleSentenceSpain: "¿Por qué no lo intentas?", exampleSentenceLatam: "¿Por qué no hablas con tu jefe?" },
      { word: "If I were you", spainVariant: "Si fuera por mí", latamVariant: "Si yo fuera tú", phoneticSpain: "[see foo-EH-rah por mee]", phoneticLatam: "[see yo foo-EH-rah too]", english: "If I were you", partOfSpeech: "phrase", exampleSentenceSpain: "Si fuera por mí, me iría.", exampleSentenceLatam: "Si yo fuera tú, lo haría." },
      { word: "In my opinion, you should", spainVariant: "En mi opinión, deberías", latamVariant: "En mi opinión, deberías", phoneticSpain: "[en mee o-pee-nee-OHN, deh-beh-REE-ahs]", phoneticLatam: "[en mee o-pee-nee-OHN, deh-beh-REE-ahs]", english: "In my opinion, you should", partOfSpeech: "phrase", exampleSentenceSpain: "En mi opinión, deberías aprender inglés.", exampleSentenceLatam: "En mi opinión, deberías renunciar." },
      { word: "Consider", spainVariant: "Considera", latamVariant: "Considera", phoneticSpain: "[kon-see-DEH-rah]", phoneticLatam: "[kon-see-DEH-rah]", english: "Consider", partOfSpeech: "verb", exampleSentenceSpain: "Considera mis palabras.", exampleSentenceLatam: "Considera tomar un descanso." },
      { word: "Think about it", spainVariant: "Piénsalo", latamVariant: "Piénsalo", phoneticSpain: "[pee-EHN-sah-lo]", phoneticLatam: "[pee-EHN-sah-lo]", english: "Think about it", partOfSpeech: "phrase", exampleSentenceSpain: "Piénsalo bien.", exampleSentenceLatam: "Piénsalo." },
      { word: "Try", spainVariant: "Intenta", latamVariant: "Intenta", phoneticSpain: "[in-TEN-tah]", phoneticLatam: "[in-TEN-tah]", english: "Try", partOfSpeech: "verb", exampleSentenceSpain: "Intenta nuevamente.", exampleSentenceLatam: "Intenta hablar con él." },
      { word: "Don't worry", spainVariant: "No te preocupes", latamVariant: "No te preocupes", phoneticSpain: "[no teh preh-o-KOO-pes]", phoneticLatam: "[no teh preh-o-KOO-pes]", english: "Don't worry", partOfSpeech: "phrase", exampleSentenceSpain: "No te preocupes, todo irá bien.", exampleSentenceLatam: "No te preocupes, lo lograrás." },
      { word: "Everything will be okay", spainVariant: "Todo estará bien", latamVariant: "Todo estará bien", phoneticSpain: "[TOH-do es-tah-RAH bee-EHN]", phoneticLatam: "[TOH-do es-tah-RAH bee-EHN]", english: "Everything will be okay", partOfSpeech: "phrase", exampleSentenceSpain: "Todo estará bien, ya verás.", exampleSentenceLatam: "Todo va a estar bien." },
      { word: "You can do it", spainVariant: "Puedes hacerlo", latamVariant: "Puedes hacerlo", phoneticSpain: "[poo-EH-des ah-SER-lo]", phoneticLatam: "[poo-EH-des ah-SER-lo]", english: "You can do it", partOfSpeech: "phrase", exampleSentenceSpain: "¡Puedes hacerlo!", exampleSentenceLatam: "¡Tú puedes!" },
      { word: "Be strong", spainVariant: "Sé fuerte", latamVariant: "Sé fuerte", phoneticSpain: "[seh FWER-teh]", phoneticLatam: "[seh FWER-teh]", english: "Be strong", partOfSpeech: "phrase", exampleSentenceSpain: "Sé fuerte en esto.", exampleSentenceLatam: "Debes ser fuerte." },
      { word: "Don't give up", spainVariant: "No te rindas", latamVariant: "No te rindas", phoneticSpain: "[no teh RIN-dahs]", phoneticLatam: "[no teh RIN-dahs]", english: "Don't give up", partOfSpeech: "phrase", exampleSentenceSpain: "No te rindas ahora.", exampleSentenceLatam: "No abandones." },
      { word: "Trust yourself", spainVariant: "Confía en ti mismo", latamVariant: "Confía en ti mismo", phoneticSpain: "[kon-FEE-ah en tee MEES-mo]", phoneticLatam: "[kon-FEE-ah en tee MEES-mo]", english: "Trust yourself", partOfSpeech: "phrase", exampleSentenceSpain: "Confía en ti mismo.", exampleSentenceLatam: "Cree en ti." },
      { word: "Warning", spainVariant: "Advertencia", latamVariant: "Advertencia", phoneticSpain: "[ahd-ver-TEN-see-ah]", phoneticLatam: "[ahd-ver-TEN-see-ah]", english: "Warning", partOfSpeech: "noun", exampleSentenceSpain: "Te doy una advertencia.", exampleSentenceLatam: "Esa es una advertencia." },
      { word: "Be careful", spainVariant: "Ten cuidado", latamVariant: "Ten cuidado", phoneticSpain: "[ten koo-ee-DAH-do]", phoneticLatam: "[ten koo-ee-DAH-do]", english: "Be careful", partOfSpeech: "phrase", exampleSentenceSpain: "Ten cuidado con eso.", exampleSentenceLatam: "Ten mucho cuidado." },
      { word: "Encouragement", spainVariant: "Aliento", latamVariant: "Ánimo", phoneticSpain: "[ah-lee-EHN-to]", phoneticLatam: "[AH-nee-mo]", english: "Encouragement", partOfSpeech: "noun", exampleSentenceSpain: "Necesito tu aliento.", exampleSentenceLatam: "Gracias por el ánimo." },
    ],
  },
  "b1-06-problems-complaints": {
    title: "Problems & Complaints",
    description: "Report problems and make complaints politely and effectively",
    vocabulary: [
      { word: "Problem", spainVariant: "Problema", latamVariant: "Problema", phoneticSpain: "[pro-BLEH-mah]", phoneticLatam: "[pro-BLEH-mah]", english: "Problem", partOfSpeech: "noun", exampleSentenceSpain: "Tengo un problema.", exampleSentenceLatam: "¿Cuál es el problema?" },
      { word: "Issue", spainVariant: "Asunto", latamVariant: "Asunto", phoneticSpain: "[ah-SUN-to]", phoneticLatam: "[ah-SUN-to]", english: "Issue", partOfSpeech: "noun", exampleSentenceSpain: "Es un asunto importante.", exampleSentenceLatam: "Ese asunto necesita atención." },
      { word: "Complaint", spainVariant: "Queja", latamVariant: "Reclamación", phoneticSpain: "[KEH-hah]", phoneticLatam: "[reh-klah-mah-see-OHN]", english: "Complaint", partOfSpeech: "noun", exampleSentenceSpain: "Tengo una queja sobre el servicio.", exampleSentenceLatam: "¿Dónde presento mi reclamación?" },
      { word: "To complain", spainVariant: "Quejarse", latamVariant: "Quejarse", phoneticSpain: "[keh-HAHR-seh]", phoneticLatam: "[keh-HAHR-seh]", english: "To complain", partOfSpeech: "verb", exampleSentenceSpain: "Se queja constantemente.", exampleSentenceLatam: "No deberíamos quejarnos." },
      { word: "Excuse me, I need to report a problem", spainVariant: "Disculpe, tengo un problema", latamVariant: "Perdón, tengo un problema", phoneticSpain: "[dis-KOOL-peh, TEN-go oon pro-BLEH-mah]", phoneticLatam: "[per-DOHN, TEN-go oon pro-BLEH-mah]", english: "Excuse me, I need to report a problem", partOfSpeech: "phrase", exampleSentenceSpain: "Disculpe, tengo un problema con mi cuenta.", exampleSentenceLatam: "Perdón, necesito reportar un problema." },
      { word: "This doesn't work properly", spainVariant: "Esto no funciona correctamente", latamVariant: "Esto no funciona bien", phoneticSpain: "[ES-to no foon-see-o-nah ko-REK-tah-MEN-teh]", phoneticLatam: "[ES-to no foon-see-o-nah bee-EHN]", english: "This doesn't work properly", partOfSpeech: "phrase", exampleSentenceSpain: "Esto no funciona correctamente.", exampleSentenceLatam: "Esto no sirve." },
      { word: "I'm not satisfied", spainVariant: "No estoy satisfecho", latamVariant: "No estoy satisfecho", phoneticSpain: "[no es-TOY sah-tis-FEH-cho]", phoneticLatam: "[no es-TOY sah-tis-FEH-cho]", english: "I'm not satisfied", partOfSpeech: "phrase", exampleSentenceSpain: "No estoy satisfecho con el resultado.", exampleSentenceLatam: "No estoy conforme." },
      { word: "This is unacceptable", spainVariant: "Esto es inaceptable", latamVariant: "Esto no es aceptable", phoneticSpain: "[ES-to es in-ah-sep-TAH-bleh]", phoneticLatam: "[ES-to no es ah-sep-TAH-bleh]", english: "This is unacceptable", partOfSpeech: "phrase", exampleSentenceSpain: "Esto es inaceptable.", exampleSentenceLatam: "Esto no es aceptable." },
      { word: "I want to speak to the manager", spainVariant: "Quiero hablar con el gerente", latamVariant: "Quiero hablar con el gerente", phoneticSpain: "[kee-EH-ro ah-BLAHR kon el heh-REN-teh]", phoneticLatam: "[kee-EH-ro ah-BLAHR kon el heh-REN-teh]", english: "I want to speak to the manager", partOfSpeech: "phrase", exampleSentenceSpain: "Quiero hablar con el gerente.", exampleSentenceLatam: "Necesito hablar con el supervisor." },
      { word: "This is the third time", spainVariant: "Esta es la tercera vez", latamVariant: "Esta es la tercera vez", phoneticSpain: "[ES-tah es lah ter-SEH-rah ves]", phoneticLatam: "[ES-tah es lah ter-SEH-rah ves]", english: "This is the third time", partOfSpeech: "phrase", exampleSentenceSpain: "Esta es la tercera vez que ocurre.", exampleSentenceLatam: "Ya es la tercera ocasión." },
      { word: "I'd like a refund", spainVariant: "Quiero un reembolso", latamVariant: "Quiero que me devuelva el dinero", phoneticSpain: "[kee-EH-ro oon reh-em-BOL-so]", phoneticLatam: "[kee-EH-ro keh meh deh-VWEL-vah el dee-NEH-ro]", english: "I'd like a refund", partOfSpeech: "phrase", exampleSentenceSpain: "Quiero un reembolso.", exampleSentenceLatam: "Quiero una devolución." },
      { word: "Compensation", spainVariant: "Compensación", latamVariant: "Compensación", phoneticSpain: "[kom-pen-sah-see-OHN]", phoneticLatam: "[kom-pen-sah-see-OHN]", english: "Compensation", partOfSpeech: "noun", exampleSentenceSpain: "Exijo compensación.", exampleSentenceLatam: "Merezco una compensación." },
      { word: "Broken", spainVariant: "Roto/a", latamVariant: "Roto/a", phoneticSpain: "[ROH-to]", phoneticLatam: "[ROH-to]", english: "Broken", partOfSpeech: "adjective", exampleSentenceSpain: "Llegó roto.", exampleSentenceLatam: "Viene roto." },
      { word: "Defective", spainVariant: "Defectuoso", latamVariant: "Defectuoso", phoneticSpain: "[deh-fek-too-OH-so]", phoneticLatam: "[deh-fek-too-OH-so]", english: "Defective", partOfSpeech: "adjective", exampleSentenceSpain: "El producto es defectuoso.", exampleSentenceLatam: "Está defectuoso." },
      { word: "Damaged", spainVariant: "Dañado", latamVariant: "Dañado", phoneticSpain: "[dahn-YAH-do]", phoneticLatam: "[dahn-YAH-do]", english: "Damaged", partOfSpeech: "adjective", exampleSentenceSpain: "La caja llegó dañada.", exampleSentenceLatam: "Todo llegó dañado." },
      { word: "Wrong item", spainVariant: "Artículo incorrecto", latamVariant: "Artículo equivocado", phoneticSpain: "[ar-TEE-koo-lo in-ko-REK-to]", phoneticLatam: "[ar-TEE-koo-lo eh-kee-vo-KAH-do]", english: "Wrong item", partOfSpeech: "noun", exampleSentenceSpain: "Recibí el artículo incorrecto.", exampleSentenceLatam: "Me mandaron otra cosa." },
      { word: "Billing error", spainVariant: "Error de facturación", latamVariant: "Error en la factura", phoneticSpain: "[eh-ROR deh fak-too-rah-see-OHN]", phoneticLatam: "[eh-ROR en lah fak-TOO-rah]", english: "Billing error", partOfSpeech: "noun", exampleSentenceSpain: "Hay un error de facturación.", exampleSentenceLatam: "Hay un error en mi factura." },
      { word: "Service was poor", spainVariant: "El servicio fue pobre", latamVariant: "El servicio estuvo malo", phoneticSpain: "[el ser-VEE-see-o foo-EH POH-breh]", phoneticLatam: "[el ser-VEE-see-o es-TOO-vo MAH-lo]", english: "Service was poor", partOfSpeech: "phrase", exampleSentenceSpain: "El servicio fue pobre.", exampleSentenceLatam: "El servicio estuvo horrible." },
      { word: "Response time", spainVariant: "Tiempo de respuesta", latamVariant: "Tiempo de respuesta", phoneticSpain: "[tee-EHM-po deh res-PWES-tah]", phoneticLatam: "[tee-EHM-po deh res-PWES-tah]", english: "Response time", partOfSpeech: "noun", exampleSentenceSpain: "El tiempo de respuesta fue lento.", exampleSentenceLatam: "Tardaron mucho en responder." },
      { word: "I deserve better", spainVariant: "Merezco mejor", latamVariant: "Merezco mejor", phoneticSpain: "[meh-REH-sko meh-HOR]", phoneticLatam: "[meh-REH-sko meh-HOR]", english: "I deserve better", partOfSpeech: "phrase", exampleSentenceSpain: "Merezco mejor trato.", exampleSentenceLatam: "Merezco una mejor atención." },
    ],
  },
  "b1-07-work-adult-life": {
    title: "Work & Adult Life",
    description: "Handle real adult life in Mexico—errands, paperwork, money, work, and responsibilities",
    vocabulary: [
      { word: "Bureaucracy", spainVariant: "Burocracia", latamVariant: "Burocracia", phoneticSpain: "[boo-ro-KRAH-see-ah]", phoneticLatam: "[boo-ro-KRAH-see-ah]", english: "Bureaucracy", partOfSpeech: "noun", exampleSentenceSpain: "La burocracia es complicada.", exampleSentenceLatam: "Mucha burocracia aquí." },
      { word: "Paperwork", spainVariant: "Papeleo", latamVariant: "Papeleo", phoneticSpain: "[pah-peh-LEH-o]", phoneticLatam: "[pah-peh-LEH-o]", english: "Paperwork", partOfSpeech: "noun", exampleSentenceSpain: "Tengo mucho papeleo.", exampleSentenceLatam: "Odio el papeleo." },
      { word: "Document/Form", spainVariant: "Documento", latamVariant: "Formulario", phoneticSpain: "[do-koo-MEN-to]", phoneticLatam: "[for-moo-LAH-ree-o]", english: "Document/Form", partOfSpeech: "noun", exampleSentenceSpain: "¿Qué documentos necesito?", exampleSentenceLatam: "¿Qué formulario lleno?" },
      { word: "To sign", spainVariant: "Firmar", latamVariant: "Firmar", phoneticSpain: "[fir-MAHR]", phoneticLatam: "[fir-MAHR]", english: "To sign", partOfSpeech: "verb", exampleSentenceSpain: "Necesito firmar aquí.", exampleSentenceLatam: "¿Dónde firmo?" },
      { word: "Tax", spainVariant: "Impuesto", latamVariant: "Impuesto", phoneticSpain: "[im-PWES-to]", phoneticLatam: "[im-PWES-to]", english: "Tax", partOfSpeech: "noun", exampleSentenceSpain: "Pagué mis impuestos.", exampleSentenceLatam: "Los impuestos son altos." },
      { word: "Paycheck", spainVariant: "Nómina", latamVariant: "Cheque de pago", phoneticSpain: "[NOH-mee-nah]", phoneticLatam: "[CHEH-keh deh PAH-go]", english: "Paycheck", partOfSpeech: "noun", exampleSentenceSpain: "Recibí mi nómina.", exampleSentenceLatam: "Llegó mi cheque." },
      { word: "Bill/Invoice", spainVariant: "Factura", latamVariant: "Factura", phoneticSpain: "[fak-TOO-rah]", phoneticLatam: "[fak-TOO-rah]", english: "Bill/Invoice", partOfSpeech: "noun", exampleSentenceSpain: "¿Puedo ver la factura?", exampleSentenceLatam: "¿Me das la factura?" },
      { word: "Rent", spainVariant: "Alquiler", latamVariant: "Renta", phoneticSpain: "[ahl-kee-LER]", phoneticLatam: "[REN-tah]", english: "Rent", partOfSpeech: "noun", exampleSentenceSpain: "El alquiler es muy caro.", exampleSentenceLatam: "La renta está subiendo." },
      { word: "Utilities", spainVariant: "Servicios", latamVariant: "Servicios", phoneticSpain: "[ser-VEE-see-os]", phoneticLatam: "[ser-VEE-see-os]", english: "Utilities", partOfSpeech: "noun", exampleSentenceSpain: "Los servicios cuestan mucho.", exampleSentenceLatam: "Los servicios subieron." },
      { word: "Insurance", spainVariant: "Seguro", latamVariant: "Seguro", phoneticSpain: "[seh-GOO-ro]", phoneticLatam: "[seh-GOO-ro]", english: "Insurance", partOfSpeech: "noun", exampleSentenceSpain: "Tengo seguro de auto.", exampleSentenceLatam: "Mi seguro vence pronto." },
      { word: "Loan", spainVariant: "Préstamo", latamVariant: "Préstamo", phoneticSpain: "[PRES-tah-mo]", phoneticLatam: "[PRES-tah-mo]", english: "Loan", partOfSpeech: "noun", exampleSentenceSpain: "Solicité un préstamo.", exampleSentenceLatam: "Tengo un préstamo del banco." },
      { word: "Debt", spainVariant: "Deuda", latamVariant: "Deuda", phoneticSpain: "[DEH-oo-dah]", phoneticLatam: "[DEH-oo-dah]", english: "Debt", partOfSpeech: "noun", exampleSentenceSpain: "Estoy en deuda.", exampleSentenceLatam: "Tengo deudas." },
      { word: "To save money", spainVariant: "Ahorrar", latamVariant: "Ahorrar", phoneticSpain: "[ah-o-RAHR]", phoneticLatam: "[ah-o-RAHR]", english: "To save money", partOfSpeech: "verb", exampleSentenceSpain: "Intento ahorrar.", exampleSentenceLatam: "Estoy ahorrando para una casa." },
      { word: "Budget", spainVariant: "Presupuesto", latamVariant: "Presupuesto", phoneticSpain: "[preh-soo-PWES-to]", phoneticLatam: "[preh-soo-PWES-to]", english: "Budget", partOfSpeech: "noun", exampleSentenceSpain: "Mi presupuesto es limitado.", exampleSentenceLatam: "Tengo un presupuesto ajustado." },
      { word: "Expense", spainVariant: "Gasto", latamVariant: "Gasto", phoneticSpain: "[GAS-to]", phoneticLatam: "[GAS-to]", english: "Expense", partOfSpeech: "noun", exampleSentenceSpain: "Los gastos son altos.", exampleSentenceLatam: "¿Cuáles son tus gastos?" },
      { word: "Income", spainVariant: "Ingreso", latamVariant: "Ingreso", phoneticSpain: "[in-GREH-so]", phoneticLatam: "[in-GREH-so]", english: "Income", partOfSpeech: "noun", exampleSentenceSpain: "Mi ingreso mensual...", exampleSentenceLatam: "Los ingresos aumentaron." },
      { word: "Commission", spainVariant: "Comisión", latamVariant: "Comisión", phoneticSpain: "[ko-mee-see-OHN]", phoneticLatam: "[ko-mee-see-OHN]", english: "Commission", partOfSpeech: "noun", exampleSentenceSpain: "Gano comisión por venta.", exampleSentenceLatam: "Mi comisión fue buena." },
      { word: "Bonus", spainVariant: "Bono", latamVariant: "Bono", phoneticSpain: "[BOH-no]", phoneticLatam: "[BOH-no]", english: "Bonus", partOfSpeech: "noun", exampleSentenceSpain: "Recibiré un bono.", exampleSentenceLatam: "El bono depende del desempeño." },
      { word: "Promotion", spainVariant: "Ascenso", latamVariant: "Promoción", phoneticSpain: "[ahs-SEN-so]", phoneticLatam: "[pro-mo-see-OHN]", english: "Promotion", partOfSpeech: "noun", exampleSentenceSpain: "Espero un ascenso pronto.", exampleSentenceLatam: "Quiero una promoción." },
      { word: "Raise", spainVariant: "Aumento", latamVariant: "Aumento", phoneticSpain: "[ah-oo-MEN-to]", phoneticLatam: "[ah-oo-MEN-to]", english: "Raise", partOfSpeech: "noun", exampleSentenceSpain: "Pedí un aumento.", exampleSentenceLatam: "Merezco un aumento." },
    ],
  },
  "b1-08-gossip": {
    title: "Chisme — Gossip",
    description: "Share and react to gossip like a local",
    vocabulary: [
      { word: "Gossip", spainVariant: "Chisme", latamVariant: "Chisme", phoneticSpain: "[CHEES-meh]", phoneticLatam: "[CHEES-meh]", english: "Gossip", partOfSpeech: "noun", exampleSentenceSpain: "¿Oíste el chisme?", exampleSentenceLatam: "¿Sabes el chisme?" },
      { word: "To gossip", spainVariant: "Chismear", latamVariant: "Chismear", phoneticSpain: "[chees-meh-AHR]", phoneticLatam: "[chees-meh-AHR]", english: "To gossip", partOfSpeech: "verb", exampleSentenceSpain: "No me gusta chismear.", exampleSentenceLatam: "Andan chismeando." },
      { word: "Did you hear", spainVariant: "¿Oíste?", latamVariant: "¿Oíste?", phoneticSpain: "[OH-ee-steh]", phoneticLatam: "[OH-ee-steh]", english: "Did you hear", partOfSpeech: "phrase", exampleSentenceSpain: "¿Oíste lo que pasó?", exampleSentenceLatam: "¿Ya oíste?" },
      { word: "I heard that", spainVariant: "Me dijeron que", latamVariant: "Me contaron que", phoneticSpain: "[meh dee-HEH-ron keh]", phoneticLatam: "[meh kon-TAH-ron keh]", english: "I heard that", partOfSpeech: "phrase", exampleSentenceSpain: "Me dijeron que se fue.", exampleSentenceLatam: "Me contaron que se enojó." },
      { word: "Word on the street", spainVariant: "Lo que se dice", latamVariant: "Lo que se dice", phoneticSpain: "[lo keh seh DEE-seh]", phoneticLatam: "[lo keh seh DEE-seh]", english: "Word on the street", partOfSpeech: "phrase", exampleSentenceSpain: "Lo que se dice es que...", exampleSentenceLatam: "Dicen que..." },
      { word: "Apparently", spainVariant: "Al parecer", latamVariant: "Según parece", phoneticSpain: "[ahl pah-reh-SER]", phoneticLatam: "[seh-GOON pah-REH-seh]", english: "Apparently", partOfSpeech: "adverb", exampleSentenceSpain: "Al parecer, se fue.", exampleSentenceLatam: "Según parece, está enojado." },
      { word: "They say", spainVariant: "Dicen que", latamVariant: "Dicen que", phoneticSpain: "[DEE-sen keh]", phoneticLatam: "[DEE-sen keh]", english: "They say", partOfSpeech: "phrase", exampleSentenceSpain: "Dicen que se van a casar.", exampleSentenceLatam: "Dicen que es verdad." },
      { word: "I can't believe it", spainVariant: "No me lo creo", latamVariant: "No me lo creo", phoneticSpain: "[no meh lo KREH-o]", phoneticLatam: "[no meh lo KREH-o]", english: "I can't believe it", partOfSpeech: "phrase", exampleSentenceSpain: "¡No me lo creo!", exampleSentenceLatam: "¿De verdad?" },
      { word: "Seriously?", spainVariant: "¿De verdad?", latamVariant: "¿En serio?", phoneticSpain: "[deh ver-DAHD]", phoneticLatam: "[en SEH-ree-o]", english: "Seriously?", partOfSpeech: "interjection", exampleSentenceSpain: "¿De verdad pasó eso?", exampleSentenceLatam: "¿En serio te lo dijo?" },
      { word: "Tell me everything", spainVariant: "Cuéntame todo", latamVariant: "Cuéntame todo", phoneticSpain: "[KWEN-tah-meh TOH-do]", phoneticLatam: "[KWEN-tah-meh TOH-do]", english: "Tell me everything", partOfSpeech: "phrase", exampleSentenceSpain: "¡Cuéntame todo!", exampleSentenceLatam: "¿Qué pasó? ¡Dime!" },
      { word: "Wait, back up", spainVariant: "Espera, retrocede", latamVariant: "Espera, empecemos desde el principio", phoneticSpain: "[es-PEH-rah, reh-tro-SEH-deh]", phoneticLatam: "[es-PEH-rah, em-peh-SEH-mos]", english: "Wait, back up", partOfSpeech: "phrase", exampleSentenceSpain: "Espera, retrocede, no entendí.", exampleSentenceLatam: "Espera, cuéntame desde el inicio." },
      { word: "So what happened?", spainVariant: "¿Y qué pasó?", latamVariant: "¿Y qué pasó?", phoneticSpain: "[ee keh pah-SOH]", phoneticLatam: "[ee keh pah-SOH]", english: "So what happened?", partOfSpeech: "phrase", exampleSentenceSpain: "¿Y qué pasó después?", exampleSentenceLatam: "¿Entonces qué?" },
      { word: "No way!", spainVariant: "¡Qué va!", latamVariant: "¡No manches!", phoneticSpain: "[keh vah]", phoneticLatam: "[no MAHN-ches]", english: "No way!", partOfSpeech: "interjection", exampleSentenceSpain: "¿Qué va! Eso no es verdad.", exampleSentenceLatam: "¡No manches! ¡Dime la verdad!" },
      { word: "That's crazy", spainVariant: "¡Qué locura!", latamVariant: "¡Qué locura!", phoneticSpain: "[keh lo-KOO-rah]", phoneticLatam: "[keh lo-KOO-rah]", english: "That's crazy", partOfSpeech: "interjection", exampleSentenceSpain: "¡Qué locura!", exampleSentenceLatam: "¡Eso es una locura!" },
      { word: "I had no idea", spainVariant: "No tenía idea", latamVariant: "No tenía idea", phoneticSpain: "[no teh-NEE-ah ee-DEH-ah]", phoneticLatam: "[no teh-NEE-ah ee-DEH-ah]", english: "I had no idea", partOfSpeech: "phrase", exampleSentenceSpain: "No tenía idea.", exampleSentenceLatam: "No lo sabía." },
      { word: "Keep it quiet", spainVariant: "Mantén en secreto", latamVariant: "No lo cuentes", phoneticSpain: "[man-TEN en seh-KREH-to]", phoneticLatam: "[no lo KWEN-tes]", english: "Keep it quiet", partOfSpeech: "phrase", exampleSentenceSpain: "Mantén esto en secreto.", exampleSentenceLatam: "No le cuentes a nadie." },
      { word: "Don't spread it around", spainVariant: "No lo divulgues", latamVariant: "No lo andes contando", phoneticSpain: "[no lo dee-BOOL-ges]", phoneticLatam: "[no lo AN-des kon-TAHN-do]", english: "Don't spread it around", partOfSpeech: "phrase", exampleSentenceSpain: "No divulgues esto.", exampleSentenceLatam: "No lo andes diciendo por ahí." },
      { word: "What stays in Vegas, stays in Vegas", spainVariant: "Secreto de confesión", latamVariant: "Entre nosotros", phoneticSpain: "[seh-KREH-to deh kon-feh-see-OHN]", phoneticLatam: "[EN-treh no-SOH-tros]", english: "What stays in Vegas, stays in Vegas", partOfSpeech: "phrase", exampleSentenceSpain: "Secreto de confesión.", exampleSentenceLatam: "Entre nosotros, ¿eh?" },
      { word: "You didn't hear it from me", spainVariant: "No te lo dije", latamVariant: "Yo no dije nada", phoneticSpain: "[no teh lo DEE-heh]", phoneticLatam: "[yo no DEE-heh NAH-dah]", english: "You didn't hear it from me", partOfSpeech: "phrase", exampleSentenceSpain: "No te lo dije, ¿eh?", exampleSentenceLatam: "Yo no dije nada, ¿eh?" },
      { word: "Rumor", spainVariant: "Rumor", latamVariant: "Rumor", phoneticSpain: "[roo-MOR]", phoneticLatam: "[roo-MOR]", english: "Rumor", partOfSpeech: "noun", exampleSentenceSpain: "Es solo un rumor.", exampleSentenceLatam: "Probablemente es un rumor." },
    ],
  },
  "b1-09-idioms": {
    title: "Mexican Idioms",
    description: "Speak like a local with Mexico's most-loved idioms",
    vocabulary: [
      { word: "Piece of cake", spainVariant: "Pan comido", latamVariant: "Muy fácil", phoneticSpain: "[pahn ko-MEE-do]", phoneticLatam: "[moo-ee FAH-seel]", english: "Piece of cake", partOfSpeech: "idiom", exampleSentenceSpain: "Para mí es pan comido.", exampleSentenceLatam: "Eso está muy fácil." },
      { word: "Cost an arm and a leg", spainVariant: "Costar un ojo de la cara", latamVariant: "Costar una fortuna", phoneticSpain: "[kos-TAHR oon OH-ho deh lah KAH-rah]", phoneticLatam: "[kos-TAHR OO-nah for-TOO-nah]", english: "Cost an arm and a leg", partOfSpeech: "idiom", exampleSentenceSpain: "Te cuesta un ojo de la cara.", exampleSentenceLatam: "Cuesta una fortuna." },
      { word: "I'm broke", spainVariant: "Estoy sin blanca", latamVariant: "No tengo ni un peso", phoneticSpain: "[es-TOY seen BLAHN-kah]", phoneticLatam: "[no TEN-go nee oon PEH-so]", english: "I'm broke", partOfSpeech: "idiom", exampleSentenceSpain: "Estoy sin blanca.", exampleSentenceLatam: "No tengo dinero." },
      { word: "To have a blast", spainVariant: "Pasarlo bomba", latamVariant: "Pasarlo bien", phoneticSpain: "[pah-SAHR-lo BOM-bah]", phoneticLatam: "[pah-SAHR-lo bee-EHN]", english: "To have a blast", partOfSpeech: "idiom", exampleSentenceSpain: "Me lo pasé bomba.", exampleSentenceLatam: "Nos pasamos genial." },
      { word: "It's raining cats and dogs", spainVariant: "Llueve a cántaros", latamVariant: "Llueve mucho", phoneticSpain: "[loo-EH-veh ah KAHN-tah-ros]", phoneticLatam: "[loo-EH-veh MOO-cho]", english: "It's raining cats and dogs", partOfSpeech: "idiom", exampleSentenceSpain: "Llueve a cántaros.", exampleSentenceLatam: "Llueve a mares." },
      { word: "Kill two birds with one stone", spainVariant: "Matar dos pájaros de un tiro", latamVariant: "Resolver dos cosas a la vez", phoneticSpain: "[mah-TAHR dos PAH-hah-ros deh oon TEE-ro]", phoneticLatam: "[reh-sol-VER dos KOH-sahs ah lah ves]", english: "Kill two birds with one stone", partOfSpeech: "idiom", exampleSentenceSpain: "Matas dos pájaros de un tiro.", exampleSentenceLatam: "Resuelves dos cosas a la vez." },
      { word: "Spill the beans", spainVariant: "Irse de boca", latamVariant: "Regarse la boca", phoneticSpain: "[IR-seh deh BOH-kah]", phoneticLatam: "[reh-GAR-seh lah BOH-kah]", english: "Spill the beans", partOfSpeech: "idiom", exampleSentenceSpain: "Se fue de boca.", exampleSentenceLatam: "Se le salió de la boca." },
      { word: "Bit the dust", spainVariant: "Morder el polvo", latamVariant: "Perder", phoneticSpain: "[mor-DER el POL-vo]", phoneticLatam: "[per-DER]", english: "Bit the dust", partOfSpeech: "idiom", exampleSentenceSpain: "Mi coche mordió el polvo.", exampleSentenceLatam: "Mi proyecto se fue al traste." },
      { word: "Burning question", spainVariant: "La pregunta del millón", latamVariant: "La gran pregunta", phoneticSpain: "[lah preh-GOON-tah del mee-YOHN]", phoneticLatam: "[lah grahn preh-GOON-tah]", english: "Burning question", partOfSpeech: "idiom", exampleSentenceSpain: "Es la pregunta del millón.", exampleSentenceLatam: "Esa es la gran pregunta." },
      { word: "Don't judge a book by its cover", spainVariant: "No juzgues por la apariencia", latamVariant: "No juzgues sin conocer", phoneticSpain: "[no HOOS-ges por lah ah-pah-ree-EHN-see-ah]", phoneticLatam: "[no HOOS-ges seen ko-no-SER]", english: "Don't judge a book by its cover", partOfSpeech: "idiom", exampleSentenceSpain: "No juzgues por la apariencia.", exampleSentenceLatam: "No es lo que parece." },
      { word: "Grass is always greener", spainVariant: "La hierba siempre es más verde en otro lado", latamVariant: "Siempre quieres lo que no tienes", phoneticSpain: "[lah ee-EHR-bah see-EHM-preh es mas VER-deh]", phoneticLatam: "[see-EHM-preh kee-EH-res lo keh no tee-EH-nes]", english: "Grass is always greener", partOfSpeech: "idiom", exampleSentenceSpain: "La hierba siempre es más verde en otro lado.", exampleSentenceLatam: "Quieres lo que no tienes." },
      { word: "Hold your horses", spainVariant: "Para la olla", latamVariant: "Espérate", phoneticSpain: "[PAH-rah lah O-yah]", phoneticLatam: "[es-PEH-rah-teh]", english: "Hold your horses", partOfSpeech: "idiom", exampleSentenceSpain: "Para la olla, espera.",exampleSentenceLatam: "Espérate, no te apresures." },
      { word: "It takes one to know one", spainVariant: "Quien calla otorga", latamVariant: "Tú lo sabes bien", phoneticSpain: "[kee-EHN KAH-yah o-TOR-gah]", phoneticLatam: "[too lo SAH-bes bee-EHN]", english: "It takes one to know one", partOfSpeech: "idiom", exampleSentenceSpain: "Quien calla otorga.", exampleSentenceLatam: "Tú sabes de eso." },
      { word: "Jump on the bandwagon", spainVariant: "Subirse al carro", latamVariant: "Seguir la moda", phoneticSpain: "[soo-BIR-seh ahl KAH-rro]", phoneticLatam: "[seh-GHEER lah MOH-dah]", english: "Jump on the bandwagon", partOfSpeech: "idiom", exampleSentenceSpain: "Se subió al carro.", exampleSentenceLatam: "Sigue la moda." },
      { word: "Let sleeping dogs lie", spainVariant: "No remover el barro", latamVariant: "No busques más problemas", phoneticSpain: "[no reh-mo-VER el BAH-rro]", phoneticLatam: "[no BUS-kes mahs PROB-leh-mas]", english: "Let sleeping dogs lie", partOfSpeech: "idiom", exampleSentenceSpain: "No remuevas el barro.", exampleSentenceLatam: "Déjalo así." },
      { word: "More the merrier", spainVariant: "Cuantos más, mejor", latamVariant: "Cuantos más, mejor", phoneticSpain: "[KWAN-tos mahs, meh-HOR]", phoneticLatam: "[KWAN-tos mahs, meh-HOR]", english: "More the merrier", partOfSpeech: "idiom", exampleSentenceSpain: "Cuantos más, mejor.", exampleSentenceLatam: "Mientras más gente, mejor." },
      { word: "Never say never", spainVariant: "Nunca digas nunca", latamVariant: "Nunca digas nunca", phoneticSpain: "[NUN-kah DEE-gahs NUN-kah]", phoneticLatam: "[NUN-kah DEE-gahs NUN-kah]", english: "Never say never", partOfSpeech: "idiom", exampleSentenceSpain: "Nunca digas nunca.", exampleSentenceLatam: "Nunca se sabe." },
      { word: "On cloud nine", spainVariant: "En la novena nube", latamVariant: "Muy feliz", phoneticSpain: "[en lah no-VEH-nah NOO-beh]", phoneticLatam: "[moo-ee feh-LEES]", english: "On cloud nine", partOfSpeech: "idiom", exampleSentenceSpain: "Está en la novena nube.", exampleSentenceLatam: "Está que no toca el piso." },
      { word: "Piece of work", spainVariant: "Un personaje", latamVariant: "Un tipo raro", phoneticSpain: "[oon per-so-NAH-heh]", phoneticLatam: "[oon TEE-po RAH-ro]", english: "Piece of work", partOfSpeech: "idiom", exampleSentenceSpain: "Es todo un personaje.", exampleSentenceLatam: "Es todo un tipo." },
      { word: "The whole nine yards", spainVariant: "Todo el queso", latamVariant: "Todo de una vez", phoneticSpain: "[TOH-do el KEH-so]", phoneticLatam: "[TOH-do deh OO-nah ves]", english: "The whole nine yards", partOfSpeech: "idiom", exampleSentenceSpain: "Hizo todo el queso.", exampleSentenceLatam: "Lohizo todo." },
    ],
  },
  "b1-10-natural-conversation": {
    title: "More Natural Conversation",
    description: "Connectors and fillers that make your Mexican Spanish effortless and natural",
    vocabulary: [
      { word: "Actually", spainVariant: "Bueno, la verdad es que", latamVariant: "Bueno, pues", phoneticSpain: "[boo-EH-no, lah ver-DAHD es keh]", phoneticLatam: "[boo-EH-no, pwes]", english: "Actually", partOfSpeech: "phrase", exampleSentenceSpain: "Bueno, la verdad es que no lo sé.", exampleSentenceLatam: "Bueno, pues, creo que sí." },
      { word: "On the other hand", spainVariant: "Por otro lado", latamVariant: "Por el contrario", phoneticSpain: "[por OH-tro LAH-do]", phoneticLatam: "[por el kon-TRAH-ree-o]", english: "On the other hand", partOfSpeech: "phrase", exampleSentenceSpain: "Por otro lado, tienes razón.",exampleSentenceLatam: "Por el contrario, es cierto." },
      { word: "Anyway", spainVariant: "De todas formas", latamVariant: "Bueno, sea como sea", phoneticSpain: "[deh TOH-dahs FOR-mas]", phoneticLatam: "[boo-EH-no, seh-ah KOH-mo seh-ah]", english: "Anyway", partOfSpeech: "phrase", exampleSentenceSpain: "De todas formas, fue buena idea.",exampleSentenceLatam: "De todas maneras, valió la pena." },
      { word: "Speaking of which", spainVariant: "Hablando de eso", latamVariant: "A propósito", phoneticSpain: "[ah-BLAHN-do deh EH-so]", phoneticLatam: "[ah pro-POHSEE-to]", english: "Speaking of which", partOfSpeech: "phrase", exampleSentenceSpain: "Hablando de eso, ¿cómo estuvo?", exampleSentenceLatam: "A propósito, ¿viste lo que pasó?" },
      { word: "By the way", spainVariant: "Por cierto", latamVariant: "A propósito", phoneticSpain: "[por see-EHR-to]", phoneticLatam: "[ah pro-POHSEE-to]", english: "By the way", partOfSpeech: "phrase", exampleSentenceSpain: "Por cierto, ¿cómo estuvo?", exampleSentenceLatam: "A propósito, gracias por ayer." },
      { word: "As I was saying", spainVariant: "Como iba diciendo", latamVariant: "Como decía", phoneticSpain: "[KOH-mo EE-bah dee-see-EHN-do]", phoneticLatam: "[KOH-mo deh-SEE-ah]", english: "As I was saying", partOfSpeech: "phrase", exampleSentenceSpain: "Como iba diciendo, es importante.", exampleSentenceLatam: "Como decía, no lo creo." },
      { word: "To make a long story short", spainVariant: "Para no hacer largo", latamVariant: "A no alargar el cuento", phoneticSpain: "[PAH-rah no ah-SER LAR-go]", phoneticLatam: "[ah no ah-lar-GAHR el KWEN-to]", english: "To make a long story short", partOfSpeech: "phrase", exampleSentenceSpain: "Para no hacer largo, lo hizo.", exampleSentenceLatam: "Para no alargar el cuento, se fue." },
      { word: "Needless to say", spainVariant: "Ni que decir tiene", latamVariant: "Claro que sí", phoneticSpain: "[nee keh deh-SEER tee-EH-neh]", phoneticLatam: "[KLAH-ro keh see]", english: "Needless to say", partOfSpeech: "phrase", exampleSentenceSpain: "Ni que decir tiene, fue increíble.",exampleSentenceLatam: "Needless to say, fue genial." },
      { word: "That being said", spainVariant: "Dicho esto", latamVariant: "Habiendo dicho eso", phoneticSpain: "[DEE-cho ES-to]", phoneticLatam: "[ah-bee-EHN-do DEE-cho EH-so]", english: "That being said", partOfSpeech: "phrase", exampleSentenceSpain: "Dicho esto, creo que...", exampleSentenceLatam: "Habiendo dicho eso, pienso que..." },
      { word: "In conclusion", spainVariant: "En conclusión", latamVariant: "Para terminar", phoneticSpain: "[en kon-kloo-see-OHN]", phoneticLatam: "[PAH-rah ter-mee-NAHR]", english: "In conclusion", partOfSpeech: "phrase", exampleSentenceSpain: "En conclusión, fue un éxito.", exampleSentenceLatam: "Para terminar, fue fantástico." },
      { word: "You know what I mean", spainVariant: "Ya sabes a qué me refiero", latamVariant: "Ya entiende lo que digo", phoneticSpain: "[yah SAH-bes ah keh meh reh-fee-EH-ro]", phoneticLatam: "[yah en-tee-EHN-deh lo keh DEE-go]", english: "You know what I mean", partOfSpeech: "phrase", exampleSentenceSpain: "Ya sabes a qué me refiero.", exampleSentenceLatam: "Ya entiendes lo que digo." },
      { word: "That's neither here nor there", spainVariant: "Eso no viene al caso", latamVariant: "Eso no viene al caso", phoneticSpain: "[EH-so no vee-EH-neh ahl KAH-so]", phoneticLatam: "[EH-so no vee-EH-neh ahl KAH-so]", english: "That's neither here nor there", partOfSpeech: "phrase", exampleSentenceSpain: "Eso no viene al caso.", exampleSentenceLatam: "Eso es irrelevante." },
      { word: "I'm just playing", spainVariant: "Era broma", latamVariant: "Nomás estoy jugando", phoneticSpain: "[EH-rah BRO-mah]", phoneticLatam: "[no-MAHS es-TOY hoo-GAHN-do]", english: "I'm just playing", partOfSpeech: "phrase", exampleSentenceSpain: "Era broma, no lo dije en serio.", exampleSentenceLatam: "Nomás estoy bromeando." },
      { word: "Honestly", spainVariant: "Sinceramente", latamVariant: "Honestamente", phoneticSpain: "[sin-seh-rah-MEN-teh]", phoneticLatam: "[o-nes-tah-MEN-teh]", english: "Honestly", partOfSpeech: "adverb", exampleSentenceSpain: "Sinceramente, no lo sé.", exampleSentenceLatam: "Honestamente, no creo que sea posible." },
      { word: "To be frank", spainVariant: "Para ser franco", latamVariant: "Para ser honesto", phoneticSpain: "[PAH-rah ser FRAHN-ko]", phoneticLatam: "[PAH-rah ser o-NES-to]", english: "To be frank", partOfSpeech: "phrase", exampleSentenceSpain: "Para ser franco, no me importa.",exampleSentenceLatam: "Para serho nesto, no me interesa." },
      { word: "Now that you mention it", spainVariant: "Ahora que lo mencionas", latamVariant: "Ahora que lo dices", phoneticSpain: "[ah-OH-rah keh lo men-see-o-NAHS]", phoneticLatam: "[ah-OH-rah keh lo DEE-ses]", english: "Now that you mention it", partOfSpeech: "phrase", exampleSentenceSpain: "Ahora que lo mencionas, es verdad.",exampleSentenceLatam: "Ahora que lo dices, tienes razón." },
      { word: "It seems to me", spainVariant: "A mí me parece", latamVariant: "A mí me parece", phoneticSpain: "[ah mee meh pah-REH-seh]", phoneticLatam: "[ah mee meh pah-REH-seh]", english: "It seems to me", partOfSpeech: "phrase", exampleSentenceSpain: "A mí me parece que está bien.", exampleSentenceLatam: "A mí me parece que es correcto." },
      { word: "I tend to think", spainVariant: "Yo tiendo a pensar", latamVariant: "Yo pienso que", phoneticSpain: "[yo tee-EHN-do ah pen-SAHR]", phoneticLatam: "[yo pee-EHN-so keh]", english: "I tend to think", partOfSpeech: "phrase", exampleSentenceSpain: "Yo tiendo a pensar que sí.", exampleSentenceLatam: "Yo pienso que es lo correcto." },
      { word: "In my humble opinion", spainVariant: "A mi humilde parecer", latamVariant: "En mi opinión", phoneticSpain: "[ah mee OO-mil-deh pah-reh-SER]", phoneticLatam: "[en mee o-pee-nee-OHN]", english: "In my humble opinion", partOfSpeech: "phrase", exampleSentenceSpain: "A mi humilde parecer, está bien.", exampleSentenceLatam: "En mi opinión, es lo mejor." },
      { word: "Without a doubt", spainVariant: "Sin duda alguna", latamVariant: "Sin duda", phoneticSpain: "[seen DOO-dah AHL-goo-nah]", phoneticLatam: "[seen DOO-dah]", english: "Without a doubt", partOfSpeech: "phrase", exampleSentenceSpain: "Sin duda alguna, es lo mejor.", exampleSentenceLatam: "Sin duda, tienes razón." },
    ],
  },
};

function buildB1Lesson(slug: string): LessonData {
  const lessonDef = B1_LESSONS[slug as keyof typeof B1_LESSONS];
  if (!lessonDef) {
    throw new Error(`B1 lesson ${slug} not found`);
  }

  const slughyphen = slug.split("-");
  const order = parseInt(slughyphen[2]) || 1;

  const grammarSection: GrammarItem[] = [
    {
      title: "Subjunctive Mood & More Complex Structures",
      spainContent: `B1 introduces the subjunctive mood for expressing opinions, desires, doubts, and emotions. Example: "Espero que vengas a la fiesta." Use conditional sentences and more complex narrative structures.`,
      latamContent: `Mexican Spanish uses subjunctive the same way, with regional expressions making it sound natural. "Ojalá que viene" vs formal "Espero que venga."`,
      note: "Subjunctive mood is essential at B1 level. Practice extensively.",
    },
    {
      title: `${lessonDef.title} Advanced Vocabulary`,
      spainContent: `Key verbs, expressions, and nuanced vocabulary for ${lessonDef.title} in Peninsular Spanish with regional cultural context.`,
      latamContent: `Same vocabulary with Mexican cultural touches and expressions that sound natural in everyday speech and social situations.`,
      note: "Both regions share the grammar; vocabulary and expressions vary for naturalness.",
    },
  ];

  const dialogues: DialogueScenario[] = [];

  for (let i = 0; i < 3; i++) {
    dialogues.push({
      id: `dialogue-spain-${i + 1}`,
      title: `${lessonDef.title} - Scene ${i + 1} (Spain)`,
      region: "SPAIN",
      setting: `Madrid/Barcelona setting for ${lessonDef.title}`,
      lines: [
        { speaker: "Ana", text: lessonDef.vocabulary[i]?.exampleSentenceSpain || `Hablando de ${lessonDef.title}...`, region: "SPAIN", setting: `Madrid/Barcelona setting for ${lessonDef.title}` },
        { speaker: "Carlos", text: lessonDef.vocabulary[(i + 1) % lessonDef.vocabulary.length]?.exampleSentenceSpain || `Claro, en España...`, region: "SPAIN", setting: `Madrid/Barcelona setting for ${lessonDef.title}` },
        { speaker: "Ana", text: `¿Verdad? Qué interesante.`, region: "SPAIN", setting: `Madrid/Barcelona setting for ${lessonDef.title}` },
      ],
    });
  }

  for (let i = 0; i < 3; i++) {
    dialogues.push({
      id: `dialogue-latam-${i + 1}`,
      title: `${lessonDef.title} - Scene ${i + 1} (Mexico)`,
      region: "LATAM",
      setting: `Mexico City/Guadalajara setting for ${lessonDef.title}`,
      lines: [
        { speaker: "María", text: lessonDef.vocabulary[i]?.exampleSentenceLatam || `Oye, ${lessonDef.title.toLowerCase()}...`, region: "LATAM", setting: `Mexico City/Guadalajara setting for ${lessonDef.title}` },
        { speaker: "Diego", text: lessonDef.vocabulary[(i + 1) % lessonDef.vocabulary.length]?.exampleSentenceLatam || `Sí, aquí en México...`, region: "LATAM", setting: `Mexico City/Guadalajara setting for ${lessonDef.title}` },
        { speaker: "María", text: `¡Órale! Qué padre.`, region: "LATAM", setting: `Mexico City/Guadalajara setting for ${lessonDef.title}` },
      ],
    });
  }

  const quiz: QuizQuestion[] = [
    {
      questionId: "q1",
      type: "multiple-choice",
      questionText: `Which mood is used to express hopes and desires in Spanish?`,
      options: ["Indicative", "Subjunctive", "Imperative", "Conditional"],
      correctAnswer: "Subjunctive",
      explanation: "The subjunctive mood is used for expressing wishes, doubts, emotions, and hypothetical situations.",
    },
    {
      questionId: "q2",
      type: "multiple-choice",
      questionText: `In Mexico, how do you express "I hope you come"?`,
      options: ["Espero que vienes", "Espero que vengas", "Quiero que vienes", "Deseo venir"],
      correctAnswer: "Espero que vengas",
      explanation: "The correct subjunctive form is 'vengas' because 'espero que' requires the subjunctive mood.",
    },
    {
      questionId: "q3",
      type: "multiple-choice",
      questionText: `What's a characteristic of B1-level Spanish?`,
      options: ["Using only present tense", "Using subjunctive for complex ideas", "Avoiding opinions", "No use of conditional"],
      correctAnswer: "Using subjunctive for complex ideas",
      explanation: "B1 Spanish introduces subjunctive for expressing opinions, desires, doubts, and complex narratives.",
    },
    {
      questionId: "q4",
      type: "multiple-choice",
      questionText: `How would you express "It's important that you study" using subjunctive?`,
      options: ["Es importante que estudias", "Es importante que estudies", "Es importante estudiar", "Es importante que es importante"],
      correctAnswer: "Es importante que estudies",
      explanation: "'Que estudies' is the correct subjunctive form after 'es importante que.'",
    },
    {
      questionId: "q5",
      type: "multiple-choice",
      questionText: `Which is a common connector in natural Mexican conversation at B1 level?`,
      options: ["Pues", "Allá", "Sólo", "Hace"],
      correctAnswer: "Pues",
      explanation: "'Pues' is a natural filler and connector widely used in Mexican Spanish for fluent, natural conversation.",
    },
  ];

  const flashcards: FlashcardItem[] = lessonDef.vocabulary.map((v, idx) => ({
    id: `fc-${slug}-${idx + 1}`,
    frontSpain: v.spainVariant,
    frontLatam: v.latamVariant,
    backEnglish: v.english,
    variantDifferenceNote: v.spainVariant !== v.latamVariant ? `Spain: "${v.spainVariant}", Mexico: "${v.latamVariant}"` : "Same in both regions",
    exampleSentenceSpain: v.exampleSentenceSpain || "",
    exampleSentenceLatam: v.exampleSentenceLatam || "",
    partOfSpeech: v.partOfSpeech,
  }));

  return {
    id: `lesson-${slug}`,
    slug,
    title: lessonDef.title,
    description: lessonDef.description,
    level: "B1",
    difficulty: "INTERMEDIATE",
    order,
    imageUrl: null,
    durationMinutes: 25,
    isPublished: true,
    vocabularyTable: lessonDef.vocabulary,
    grammarSection,
    dialogues,
    quiz,
    flashcards,
    vocabularyJson: lessonDef.vocabulary.map((v) => ({
      word: v.word,
      translation: `${v.spainVariant} / ${v.latamVariant}`,
      partOfSpeech: v.partOfSpeech,
      example: v.exampleSentenceLatam,
    })),
    grammarJson: grammarSection.map((g) => ({
      title: g.title,
      content: `${g.spainContent} | ${g.latamContent}`,
    })),
    content: `# ${lessonDef.title}\n\n${lessonDef.description}\n\nThis B1 lesson builds on A-level foundations, introducing subjunctive mood, complex narratives, and advanced conversational skills. Understand nuance, express opinions, and navigate sophisticated social interactions.`,
  };
}

export function generateB1Lessons(): LessonData[] {
  const b1Slugs = Object.keys(B1_LESSONS);
  return b1Slugs.map((slug) => buildB1Lesson(slug));
}