import type { LessonData, RegionalVocabItem, GrammarItem, DialogueScenario, QuizQuestion, FlashcardItem } from "./lessons-data";

const A2_LESSONS = {
  "a2-01-small-talk": {
    title: "Small Talk & Casual Conversation",
    description: "Master casual conversation starters and small talk in both Spain and Mexico",
    vocabulary: [
      { word: "How was your day?", spainVariant: "¿Qué tal tu día?", latamVariant: "¿Cómo estuvo tu día?", phoneticSpain: "[keh tahl too DEE-ah]", phoneticLatam: "[KOH-mo es-TOO-vo too DEE-ah]", english: "How was your day?", partOfSpeech: "phrase", exampleSentenceSpain: "¿Qué tal tu día en el trabajo?", exampleSentenceLatam: "¿Cómo estuvo tu día en la escuela?" },
      { word: "It was good", spainVariant: "Fue bien", latamVariant: "Estuvo bien", phoneticSpain: "[foo-EH bee-EHN]", phoneticLatam: "[es-TOO-vo bee-EHN]", english: "It was good", partOfSpeech: "phrase", exampleSentenceSpain: "Fue bien, gracias.", exampleSentenceLatam: "Estuvo bien, gracias." },
      { word: "Not bad", spainVariant: "Bien, bien", latamVariant: "Bien, bien", phoneticSpain: "[bee-EHN, bee-EHN]", phoneticLatam: "[bee-EHN, bee-EHN]", english: "Not bad", partOfSpeech: "phrase", exampleSentenceSpain: "Bien, bien, sin quejas.", exampleSentenceLatam: "Bien, bien, todo tranquilo." },
      { word: "Did you do anything fun?", spainVariant: "¿Hiciste algo divertido?", latamVariant: "¿Hiciste algo divertido?", phoneticSpain: "[ee-SIS-teh AHL-go dee-ver-TEE-do]", phoneticLatam: "[ee-SIS-teh AHL-go dee-ver-TEE-do]", english: "Did you do anything fun?", partOfSpeech: "phrase", exampleSentenceSpain: "¿Hiciste algo divertido el fin de semana?", exampleSentenceLatam: "¿Hiciste algo divertido?" },
      { word: "Yes, I went to...", spainVariant: "Sí, fui a...", latamVariant: "Sí, fui a...", phoneticSpain: "[see, foo-EE ah]", phoneticLatam: "[see, foo-EE ah]", english: "Yes, I went to...", partOfSpeech: "phrase", exampleSentenceSpain: "Sí, fui a la playa.", exampleSentenceLatam: "Sí, fui al cine." },
      { word: "That sounds nice", spainVariant: "Suena bien", latamVariant: "Suena bien", phoneticSpain: "[soo-EH-nah bee-EHN]", phoneticLatam: "[soo-EH-nah bee-EHN]", english: "That sounds nice", partOfSpeech: "phrase", exampleSentenceSpain: "Suena bien, me gustaría ir.", exampleSentenceLatam: "Suena bien, ¡qué padre!" },
      { word: "What about you?", spainVariant: "¿Y tú?", latamVariant: "¿Y tú?", phoneticSpain: "[ee too]", phoneticLatam: "[ee too]", english: "What about you?", partOfSpeech: "phrase", exampleSentenceSpain: "¿Y tú qué hiciste?", exampleSentenceLatam: "¿Y tú, qué hiciste?" },
      { word: "I'm tired", spainVariant: "Estoy cansado/a", latamVariant: "Estoy cansado/a", phoneticSpain: "[es-TOY kahn-SAH-do]", phoneticLatam: "[es-TOY kahn-SAH-do]", english: "I'm tired", partOfSpeech: "phrase", exampleSentenceSpain: "Estoy cansado de trabajar.", exampleSentenceLatam: "Estoy cansada hoy." },
      { word: "I'm excited", spainVariant: "Estoy emocionado/a", latamVariant: "Estoy emocionado/a", phoneticSpain: "[es-TOY eh-mo-see-o-NAH-do]", phoneticLatam: "[es-TOY eh-mo-see-o-NAH-do]", english: "I'm excited", partOfSpeech: "phrase", exampleSentenceSpain: "Estoy emocionado por las vacaciones.", exampleSentenceLatam: "Estoy emocionada de verte." },
      { word: "Same here", spainVariant: "Yo también", latamVariant: "Yo también", phoneticSpain: "[yo tam-bee-EHN]", phoneticLatam: "[yo tam-bee-EHN]", english: "Same here", partOfSpeech: "phrase", exampleSentenceSpain: "Yo también estoy cansado.", exampleSentenceLatam: "Yo también, hermano." },
      { word: "Really?", spainVariant: "¿De verdad?", latamVariant: "¿De verdad?", phoneticSpain: "[deh ver-DAHD]", phoneticLatam: "[deh ver-DAHD]", english: "Really?", partOfSpeech: "interjection", exampleSentenceSpain: "¿De verdad? No me lo esperaba.", exampleSentenceLatam: "¿De verdad? ¡Qué interesante!" },
      { word: "That's cool", spainVariant: "Qué guay", latamVariant: "Qué padre", phoneticSpain: "[keh GWAI]", phoneticLatam: "[keh PAH-dreh]", english: "That's cool", partOfSpeech: "phrase", exampleSentenceSpain: "¡Qué guay! Me encanta.", exampleSentenceLatam: "¡Qué padre! Me encantaría." },
      { word: "I totally agree", spainVariant: "Totalmente de acuerdo", latamVariant: "Totalmente de acuerdo", phoneticSpain: "[to-tahl-MEN-teh deh ah-KWER-do]", phoneticLatam: "[to-tahl-MEN-teh deh ah-KWER-do]", english: "I totally agree", partOfSpeech: "phrase", exampleSentenceSpain: "Totalmente de acuerdo contigo.", exampleSentenceLatam: "Totalmente de acuerdo." },
      { word: "You're right", spainVariant: "Tienes razón", latamVariant: "Tienes razón", phoneticSpain: "[tee-EH-nes rah-SOHN]", phoneticLatam: "[tee-EH-nes rah-SOHN]", english: "You're right", partOfSpeech: "phrase", exampleSentenceSpain: "Tienes razón, no lo había pensado.", exampleSentenceLatam: "Tienes razón, es verdad." },
      { word: "I don't think so", spainVariant: "No creo", latamVariant: "No creo", phoneticSpain: "[no KREH-o]", phoneticLatam: "[no KREH-o]", english: "I don't think so", partOfSpeech: "phrase", exampleSentenceSpain: "No creo, me parece diferente.", exampleSentenceLatam: "No creo, pienso diferente." },
      { word: "What do you think?", spainVariant: "¿Qué piensas?", latamVariant: "¿Qué piensas?", phoneticSpain: "[keh pee-EHN-sas]", phoneticLatam: "[keh pee-EHN-sas]", english: "What do you think?", partOfSpeech: "phrase", exampleSentenceSpain: "¿Qué piensas de esto?", exampleSentenceLatam: "¿Qué opinas?" },
      { word: "It depends", spainVariant: "Depende", latamVariant: "Depende", phoneticSpain: "[deh-PEN-deh]", phoneticLatam: "[deh-PEN-deh]", english: "It depends", partOfSpeech: "phrase", exampleSentenceSpain: "Depende de la situación.", exampleSentenceLatam: "Depende, no es tan simple." },
      { word: "Interesting", spainVariant: "Interesante", latamVariant: "Interesante", phoneticSpain: "[in-teh-reh-SAHN-teh]", phoneticLatam: "[in-teh-reh-SAHN-teh]", english: "Interesting", partOfSpeech: "adjective", exampleSentenceSpain: "Eso es muy interesante.", exampleSentenceLatam: "¡Qué interesante!" },
      { word: "I understand", spainVariant: "Entiendo", latamVariant: "Entiendo", phoneticSpain: "[en-tee-EHN-do]", phoneticLatam: "[en-tee-EHN-do]", english: "I understand", partOfSpeech: "phrase", exampleSentenceSpain: "Entiendo perfectamente.", exampleSentenceLatam: "Entiendo lo que quieres decir." },
      { word: "Tell me more", spainVariant: "Cuéntame más", latamVariant: "Cuéntame más", phoneticSpain: "[KWEN-tah-meh MAHS]", phoneticLatam: "[KWEN-tah-meh MAHS]", english: "Tell me more", partOfSpeech: "phrase", exampleSentenceSpain: "Cuéntame más de eso.", exampleSentenceLatam: "¡Cuéntame más, me encanta!" },
    ],
  },
  "a2-02-daily-routines": {
    title: "Daily Routines & Habits",
    description: "Talk about your daily schedule and regular activities with confidence",
    vocabulary: [
      { word: "Wake up", spainVariant: "Despertarse", latamVariant: "Despertarse", phoneticSpain: "[des-per-TAR-seh]", phoneticLatam: "[des-per-TAR-seh]", english: "Wake up", partOfSpeech: "verb", exampleSentenceSpain: "Me despierto a las 7.", exampleSentenceLatam: "Me despierto temprano." },
      { word: "Go to bed", spainVariant: "Acostarse", latamVariant: "Acostarse", phoneticSpain: "[ah-kos-TAR-seh]", phoneticLatam: "[ah-kos-TAR-seh]", english: "Go to bed", partOfSpeech: "verb", exampleSentenceSpain: "Me acuesto a las 11.", exampleSentenceLatam: "Me acuesto tarde." },
      { word: "Breakfast", spainVariant: "Desayunar", latamVariant: "Desayunar", phoneticSpain: "[deh-sah-yoo-NAHR]", phoneticLatam: "[deh-sah-yoo-NAHR]", english: "Have breakfast", partOfSpeech: "verb", exampleSentenceSpain: "Desayuno a las 8.", exampleSentenceLatam: "Desayuno con café." },
      { word: "Work", spainVariant: "Trabajar", latamVariant: "Trabajar", phoneticSpain: "[trah-bah-HAHR]", phoneticLatam: "[trah-bah-HAHR]", english: "Work", partOfSpeech: "verb", exampleSentenceSpain: "Trabajo en una oficina.", exampleSentenceLatam: "Trabajo en casa." },
      { word: "Exercise", spainVariant: "Hacer ejercicio", latamVariant: "Hacer ejercicio", phoneticSpain: "[ah-SER eh-her-SEE-see-o]", phoneticLatam: "[ah-SER eh-her-SEE-see-o]", english: "Exercise", partOfSpeech: "phrase", exampleSentenceSpain: "Hago ejercicio tres veces a la semana.", exampleSentenceLatam: "Hago ejercicio en la mañana." },
      { word: "Shower", spainVariant: "Duchar", latamVariant: "Duchar", phoneticSpain: "[doo-CHAHR]", phoneticLatam: "[doo-CHAHR]", english: "Shower", partOfSpeech: "verb", exampleSentenceSpain: "Me ducho después del trabajo.", exampleSentenceLatam: "Me ducho en la noche." },
      { word: "Lunch", spainVariant: "Comer", latamVariant: "Almorzar", phoneticSpain: "[ko-MER]", phoneticLatam: "[ahl-mor-SAHR]", english: "Have lunch", partOfSpeech: "verb", exampleSentenceSpain: "Como a las 2.", exampleSentenceLatam: "Almuerzo al mediodía." },
      { word: "Dinner", spainVariant: "Cenar", latamVariant: "Cenar", phoneticSpain: "[seh-NAHR]", phoneticLatam: "[seh-NAHR]", english: "Have dinner", partOfSpeech: "verb", exampleSentenceSpain: "Ceno a las 9.", exampleSentenceLatam: "Ceno temprano." },
      { word: "Watch TV", spainVariant: "Ver la tele", latamVariant: "Ver la tele", phoneticSpain: "[ver lah TEH-leh]", phoneticLatam: "[ver lah TEH-leh]", english: "Watch TV", partOfSpeech: "phrase", exampleSentenceSpain: "Veo la tele por la noche.", exampleSentenceLatam: "Veo televisión." },
      { word: "Read", spainVariant: "Leer", latamVariant: "Leer", phoneticSpain: "[leh-EHR]", phoneticLatam: "[leh-EHR]", english: "Read", partOfSpeech: "verb", exampleSentenceSpain: "Leo un libro antes de dormir.", exampleSentenceLatam: "Leo el periódico." },
      { word: "Everyday", spainVariant: "Todos los días", latamVariant: "Todos los días", phoneticSpain: "[TOH-dos los DEE-ahs]", phoneticLatam: "[TOH-dos los DEE-ahs]", english: "Everyday", partOfSpeech: "phrase", exampleSentenceSpain: "Voy al gimnasio todos los días.", exampleSentenceLatam: "Como sano todos los días." },
      { word: "Usually", spainVariant: "Normalmente", latamVariant: "Normalmente", phoneticSpain: "[nor-mahl-MEN-teh]", phoneticLatam: "[nor-mahl-MEN-teh]", english: "Usually", partOfSpeech: "adverb", exampleSentenceSpain: "Normalmente me despierto temprano.", exampleSentenceLatam: "Normalmente trabajo de 9 a 5." },
      { word: "Sometimes", spainVariant: "A veces", latamVariant: "A veces", phoneticSpain: "[ah VEH-ses]", phoneticLatam: "[ah VEH-ses]", english: "Sometimes", partOfSpeech: "adverb", exampleSentenceSpain: "A veces salgo con amigos.", exampleSentenceLatam: "A veces como fuera." },
      { word: "Never", spainVariant: "Nunca", latamVariant: "Nunca", phoneticSpain: "[NOON-kah]", phoneticLatam: "[NOON-kah]", english: "Never", partOfSpeech: "adverb", exampleSentenceSpain: "Nunca llego tarde.", exampleSentenceLatam: "Nunca salto el desayuno." },
      { word: "Always", spainVariant: "Siempre", latamVariant: "Siempre", phoneticSpain: "[see-EHM-preh]", phoneticLatam: "[see-EHM-preh]", english: "Always", partOfSpeech: "adverb", exampleSentenceSpain: "Siempre me cepillo los dientes.", exampleSentenceLatam: "Siempre llego a tiempo." },
      { word: "Morning routine", spainVariant: "Rutina matutina", latamVariant: "Rutina de la mañana", phoneticSpain: "[roo-TEE-nah mah-too-TEE-nah]", phoneticLatam: "[roo-TEE-nah deh lah mahn-YAH-nah]", english: "Morning routine", partOfSpeech: "noun", exampleSentenceSpain: "Mi rutina matutina es rápida.", exampleSentenceLatam: "Mi rutina de la mañana toma una hora." },
      { word: "Evening routine", spainVariant: "Rutina nocturna", latamVariant: "Rutina de la noche", phoneticSpain: "[roo-TEE-nah nok-TUR-nah]", phoneticLatam: "[roo-TEE-nah deh lah NOH-cheh]", english: "Evening routine", partOfSpeech: "noun", exampleSentenceSpain: "Mi rutina nocturna es relajante.", exampleSentenceLatam: "Mi rutina nocturna es importante." },
      { word: "Busy day", spainVariant: "Día ocupado", latamVariant: "Día ocupado", phoneticSpain: "[DEE-ah o-koo-PAH-do]", phoneticLatam: "[DEE-ah o-koo-PAH-do]", english: "Busy day", partOfSpeech: "phrase", exampleSentenceSpain: "Hoy fue un día ocupado.", exampleSentenceLatam: "Fue un día muy ocupado." },
      { word: "Relaxing day", spainVariant: "Día relajante", latamVariant: "Día tranquilo", phoneticSpain: "[DEE-ah reh-lah-HAHN-teh]", phoneticLatam: "[DEE-ah trahn-KEE-lo]", english: "Relaxing day", partOfSpeech: "phrase", exampleSentenceSpain: "Hoy fue un día relajante.", exampleSentenceLatam: "¡Qué día tan tranquilo!" },
      { word: "Free time", spainVariant: "Tiempo libre", latamVariant: "Tiempo libre", phoneticSpain: "[tee-EHM-po LEE-breh]", phoneticLatam: "[tee-EHM-po LEE-breh]", english: "Free time", partOfSpeech: "noun", exampleSentenceSpain: "En mi tiempo libre leo.", exampleSentenceLatam: "Uso mi tiempo libre para relajarme." },
    ],
  },
  "a2-03-hobbies": {
    title: "Hobbies & Interests",
    description: "Talk about your favorite activities and what you love to do",
    vocabulary: [
      { word: "Like", spainVariant: "Gustar", latamVariant: "Gustar", phoneticSpain: "[goos-TAHR]", phoneticLatam: "[goos-TAHR]", english: "Like", partOfSpeech: "verb", exampleSentenceSpain: "Me gusta leer.", exampleSentenceLatam: "Me gusta la música." },
      { word: "Love", spainVariant: "Encantar", latamVariant: "Encantar", phoneticSpain: "[en-kahn-TAHR]", phoneticLatam: "[en-kahn-TAHR]", english: "Love", partOfSpeech: "verb", exampleSentenceSpain: "Me encanta viajar.", exampleSentenceLatam: "Me encanta cocinar." },
      { word: "Hate", spainVariant: "Odiar", latamVariant: "Odiar", phoneticSpain: "[o-dee-AHR]", phoneticLatam: "[o-dee-AHR]", english: "Hate", partOfSpeech: "verb", exampleSentenceSpain: "Odio limpiar.", exampleSentenceLatam: "Odio el tráfico." },
      { word: "Sports", spainVariant: "Deporte", latamVariant: "Deporte", phoneticSpain: "[deh-POR-teh]", phoneticLatam: "[deh-POR-teh]", english: "Sports", partOfSpeech: "noun", exampleSentenceSpain: "Me encanta el deporte.", exampleSentenceLatam: "Practico deporte." },
      { word: "Football", spainVariant: "Fútbol", latamVariant: "Fútbol", phoneticSpain: "[FOOT-bol]", phoneticLatam: "[FOOT-bol]", english: "Football/Soccer", partOfSpeech: "noun", exampleSentenceSpain: "Juego fútbol los domingos.", exampleSentenceLatam: "Me encanta el fútbol." },
      { word: "Tennis", spainVariant: "Tenis", latamVariant: "Tenis", phoneticSpain: "[TEH-nis]", phoneticLatam: "[TEH-nis]", english: "Tennis", partOfSpeech: "noun", exampleSentenceSpain: "Juego tenis en verano.", exampleSentenceLatam: "Jugamos tenis." },
      { word: "Swimming", spainVariant: "Natación", latamVariant: "Natación", phoneticSpain: "[nah-tah-see-OHN]", phoneticLatam: "[nah-tah-see-OHN]", english: "Swimming", partOfSpeech: "noun", exampleSentenceSpain: "Me encanta la natación.", exampleSentenceLatam: "Nado tres veces a la semana." },
      { word: "Music", spainVariant: "Música", latamVariant: "Música", phoneticSpain: "[MOO-see-kah]", phoneticLatam: "[MOO-see-kah]", english: "Music", partOfSpeech: "noun", exampleSentenceSpain: "Me gusta la música clásica.", exampleSentenceLatam: "Escucho música todas las noches." },
      { word: "Guitar", spainVariant: "Guitarra", latamVariant: "Guitarra", phoneticSpain: "[gee-TAH-rrah]", phoneticLatam: "[gee-TAH-rrah]", english: "Guitar", partOfSpeech: "noun", exampleSentenceSpain: "Toco la guitarra.", exampleSentenceLatam: "Quiero aprender guitarra." },
      { word: "Piano", spainVariant: "Piano", latamVariant: "Piano", phoneticSpain: "[pee-AH-no]", phoneticLatam: "[pee-AH-no]", english: "Piano", partOfSpeech: "noun", exampleSentenceSpain: "Ella toca piano.", exampleSentenceLatam: "Mi hermana toca piano." },
      { word: "Drawing", spainVariant: "Dibujo", latamVariant: "Dibujo", phoneticSpain: "[dee-BOO-ho]", phoneticLatam: "[dee-BOO-ho]", english: "Drawing", partOfSpeech: "noun", exampleSentenceSpain: "Me encanta dibujar.", exampleSentenceLatam: "Dibujo en mis ratos libres." },
      { word: "Painting", spainVariant: "Pintura", latamVariant: "Pintura", phoneticSpain: "[pin-TOO-rah]", phoneticLatam: "[pin-TOO-rah]", english: "Painting", partOfSpeech: "noun", exampleSentenceSpain: "Practico pintura al óleo.", exampleSentenceLatam: "Me gusta la pintura." },
      { word: "Photography", spainVariant: "Fotografía", latamVariant: "Fotografía", phoneticSpain: "[fo-to-grah-FEE-ah]", phoneticLatam: "[fo-to-grah-FEE-ah]", english: "Photography", partOfSpeech: "noun", exampleSentenceSpain: "La fotografía es mi pasión.", exampleSentenceLatam: "Hago fotografía." },
      { word: "Traveling", spainVariant: "Viajar", latamVariant: "Viajar", phoneticSpain: "[vee-ah-HAHR]", phoneticLatam: "[vee-ah-HAHR]", english: "Traveling", partOfSpeech: "verb", exampleSentenceSpain: "Me encanta viajar.", exampleSentenceLatam: "Viajo cada verano." },
      { word: "Reading", spainVariant: "Lectura", latamVariant: "Lectura", phoneticSpain: "[lek-TOO-rah]", phoneticLatam: "[lek-TOO-rah]", english: "Reading", partOfSpeech: "noun", exampleSentenceSpain: "La lectura es mi pasatiempo.", exampleSentenceLatam: "Me encanta leer." },
      { word: "Cooking", spainVariant: "Cocinar", latamVariant: "Cocinar", phoneticSpain: "[ko-see-NAHR]", phoneticLatam: "[ko-see-NAHR]", english: "Cooking", partOfSpeech: "verb", exampleSentenceSpain: "Me encanta cocinar.", exampleSentenceLatam: "Cocino los fines de semana." },
      { word: "Gaming", spainVariant: "Videojuegos", latamVariant: "Videojuegos", phoneticSpain: "[vee-deh-o-hoo-EH-gos]", phoneticLatam: "[vee-deh-o-hoo-EH-gos]", english: "Gaming", partOfSpeech: "noun", exampleSentenceSpain: "Juego videojuegos en la tarde.", exampleSentenceLatam: "Me gustan los videojuegos." },
      { word: "Favorite", spainVariant: "Favorito/a", latamVariant: "Favorito/a", phoneticSpain: "[fah-vor-EE-to]", phoneticLatam: "[fah-vor-EE-to]", english: "Favorite", partOfSpeech: "adjective", exampleSentenceSpain: "Mi libro favorito es...", exampleSentenceLatam: "Mi película favorita es..." },
      { word: "Hobby", spainVariant: "Pasatiempo", latamVariant: "Pasatiempo", phoneticSpain: "[pah-sah-tee-EHM-po]", phoneticLatam: "[pah-sah-tee-EHM-po]", english: "Hobby", partOfSpeech: "noun", exampleSentenceSpain: "¿Cuál es tu pasatiempo?", exampleSentenceLatam: "Mi pasatiempo favorito es..." },
      { word: "Interested in", spainVariant: "Interesado en", latamVariant: "Interesado en", phoneticSpain: "[in-teh-reh-SAH-do en]", phoneticLatam: "[in-teh-reh-SAH-do en]", english: "Interested in", partOfSpeech: "phrase", exampleSentenceSpain: "Estoy interesado en la astronomía.", exampleSentenceLatam: "Me interesa el cine." },
    ],
  },
  "a2-04-making-plans": {
    title: "Making Plans & Invitations",
    description: "Invite friends, make plans, and suggest activities confidently",
    vocabulary: [
      { word: "Want to...", spainVariant: "¿Quieres...?", latamVariant: "¿Quieres...?", phoneticSpain: "[kee-EH-res]", phoneticLatam: "[kee-EH-res]", english: "Want to...?", partOfSpeech: "phrase", exampleSentenceSpain: "¿Quieres ir al cine?", exampleSentenceLatam: "¿Quieres salir mañana?" },
      { word: "Would you like...?", spainVariant: "¿Te gustaría...?", latamVariant: "¿Te gustaría...?", phoneticSpain: "[teh goos-tah-REE-ah]", phoneticLatam: "[teh goos-tah-REE-ah]", english: "Would you like...?", partOfSpeech: "phrase", exampleSentenceSpain: "¿Te gustaría tomar café?", exampleSentenceLatam: "¿Te gustaría venir?" },
      { word: "I'd love to", spainVariant: "Me encantaría", latamVariant: "Me encantaría", phoneticSpain: "[meh en-kahn-tah-REE-ah]", phoneticLatam: "[meh en-kahn-tah-REE-ah]", english: "I'd love to", partOfSpeech: "phrase", exampleSentenceSpain: "Me encantaría ir contigo.", exampleSentenceLatam: "Me encantaría, ¡gracias!" },
      { word: "That sounds great", spainVariant: "Suena fenomenal", latamVariant: "Suena perfecto", phoneticSpain: "[soo-EH-nah feh-no-meh-NAHL]", phoneticLatam: "[soo-EH-nah per-FEK-to]", english: "That sounds great", partOfSpeech: "phrase", exampleSentenceSpain: "Suena fenomenal, ¡vamos!", exampleSentenceLatam: "¡Suena perfecto!" },
      { word: "When?", spainVariant: "¿Cuándo?", latamVariant: "¿Cuándo?", phoneticSpain: "[KWAN-do]", phoneticLatam: "[KWAN-do]", english: "When?", partOfSpeech: "adverb", exampleSentenceSpain: "¿Cuándo quieres ir?", exampleSentenceLatam: "¿Cuándo es?" },
      { word: "This weekend", spainVariant: "Este fin de semana", latamVariant: "Este fin de semana", phoneticSpain: "[ES-teh fin deh seh-MAH-nah]", phoneticLatam: "[ES-teh fin deh seh-MAH-nah]", english: "This weekend", partOfSpeech: "phrase", exampleSentenceSpain: "¿Quieres este fin de semana?", exampleSentenceLatam: "¿Este fin de semana?" },
      { word: "Next week", spainVariant: "La próxima semana", latamVariant: "La próxima semana", phoneticSpain: "[lah PROHK-see-mah seh-MAH-nah]", phoneticLatam: "[lah PROHK-see-mah seh-MAH-nah]", english: "Next week", partOfSpeech: "phrase", exampleSentenceSpain: "La próxima semana está bien.", exampleSentenceLatam: "¿La próxima semana?" },
      { word: "How about...", spainVariant: "¿Qué tal...?", latamVariant: "¿Qué tal...?", phoneticSpain: "[keh tahl]", phoneticLatam: "[keh tahl]", english: "How about...?", partOfSpeech: "phrase", exampleSentenceSpain: "¿Qué tal el sábado?", exampleSentenceLatam: "¿Qué tal a las 7?" },
      { word: "Let's meet at...", spainVariant: "Nos vemos en...", latamVariant: "Nos vemos en...", phoneticSpain: "[nos VEH-mos en]", phoneticLatam: "[nos VEH-mos en]", english: "Let's meet at...", partOfSpeech: "phrase", exampleSentenceSpain: "Nos vemos en el parque.", exampleSentenceLatam: "Nos vemos en la plaza." },
      { word: "I'm busy", spainVariant: "Estoy ocupado/a", latamVariant: "Estoy ocupado/a", phoneticSpain: "[es-TOY o-koo-PAH-do]", phoneticLatam: "[es-TOY o-koo-PAH-do]", english: "I'm busy", partOfSpeech: "phrase", exampleSentenceSpain: "Lo siento, estoy ocupado.", exampleSentenceLatam: "Estoy ocupado ese día." },
      { word: "I'm free", spainVariant: "Estoy libre", latamVariant: "Estoy libre", phoneticSpain: "[es-TOY LEE-breh]", phoneticLatam: "[es-TOY LEE-breh]", english: "I'm free", partOfSpeech: "phrase", exampleSentenceSpain: "Estoy libre el viernes.", exampleSentenceLatam: "¡Sí, estoy libre!" },
      { word: "Let's go to...", spainVariant: "Vamos a...", latamVariant: "Vamos a...", phoneticSpain: "[VAH-mos ah]", phoneticLatam: "[VAH-mos ah]", english: "Let's go to...", partOfSpeech: "phrase", exampleSentenceSpain: "Vamos a la playa.", exampleSentenceLatam: "Vamos al restaurante." },
      { word: "What time?", spainVariant: "¿A qué hora?", latamVariant: "¿A qué hora?", phoneticSpain: "[ah keh OH-rah]", phoneticLatam: "[ah keh OH-rah]", english: "What time?", partOfSpeech: "phrase", exampleSentenceSpain: "¿A qué hora quedamos?", exampleSentenceLatam: "¿A qué hora nos vemos?" },
      { word: "I apologize", spainVariant: "Me disculpo", latamVariant: "Me disculpo", phoneticSpain: "[meh dis-KOOL-po]", phoneticLatam: "[meh dis-KOOL-po]", english: "I apologize", partOfSpeech: "phrase", exampleSentenceSpain: "Me disculpo, no puedo ir.", exampleSentenceLatam: "Me disculpo, tengo otro compromiso." },
      { word: "Rain check?", spainVariant: "¿Lo dejamos para otro día?", latamVariant: "¿Lo dejamos para otro día?", phoneticSpain: "[lo deh-HAH-mos PAH-rah OH-tro DEE-ah]", phoneticLatam: "[lo deh-HAH-mos PAH-rah OH-tro DEE-ah]", english: "Rain check?", partOfSpeech: "phrase", exampleSentenceSpain: "¿Lo dejamos para otro día?", exampleSentenceLatam: "¿Podemos reagendar?" },
      { word: "Fun activity", spainVariant: "Actividad divertida", latamVariant: "Actividad divertida", phoneticSpain: "[ak-tee-vee-DAHD dee-ver-TEE-dah]", phoneticLatam: "[ak-tee-vee-DAHD dee-ver-TEE-dah]", english: "Fun activity", partOfSpeech: "phrase", exampleSentenceSpain: "¿Qué actividad divertida sugieres?", exampleSentenceLatam: "¿Una actividad divertida?" },
      { word: "Dinner party", spainVariant: "Cena", latamVariant: "Cena", phoneticSpain: "[SEH-nah]", phoneticLatam: "[SEH-nah]", english: "Dinner party", partOfSpeech: "noun", exampleSentenceSpain: "Tengo una cena el viernes.", exampleSentenceLatam: "¿Vienes a una cena?" },
      { word: "Concert", spainVariant: "Concierto", latamVariant: "Concierto", phoneticSpain: "[kon-see-EHR-to]", phoneticLatam: "[kon-see-EHR-to]", english: "Concert", partOfSpeech: "noun", exampleSentenceSpain: "¿Quieres ir a un concierto?", exampleSentenceLatam: "Hay un concierto el sábado." },
      { word: "Movie", spainVariant: "Película", latamVariant: "Película", phoneticSpain: "[peh-LEE-koo-lah]", phoneticLatam: "[peh-LEE-koo-lah]", english: "Movie", partOfSpeech: "noun", exampleSentenceSpain: "¿Vamos a ver una película?", exampleSentenceLatam: "¿Qué película quieres ver?" },
      { word: "Party", spainVariant: "Fiesta", latamVariant: "Fiesta", phoneticSpain: "[fee-ES-tah]", phoneticLatam: "[fee-ES-tah]", english: "Party", partOfSpeech: "noun", exampleSentenceSpain: "Hay una fiesta mañana.", exampleSentenceLatam: "¿Quieres venir a una fiesta?" },
    ],
  },
  "a2-05-phone-calls": {
    title: "Phone Calls & Messaging",
    description: "Make and take calls, leave messages, and text naturally in Spanish",
    vocabulary: [
      { word: "Hello?", spainVariant: "¿Hola?", latamVariant: "¿Hola?", phoneticSpain: "[OH-lah]", phoneticLatam: "[OH-lah]", english: "Hello?", partOfSpeech: "interjection", exampleSentenceSpain: "¿Hola? ¿Quién habla?", exampleSentenceLatam: "¿Hola? ¿Cuál es tu nombre?" },
      { word: "Is ... there?", spainVariant: "¿Está...?", latamVariant: "¿Está...?", phoneticSpain: "[es-TAH]", phoneticLatam: "[es-TAH]", english: "Is ... there?", partOfSpeech: "phrase", exampleSentenceSpain: "¿Está María?", exampleSentenceLatam: "¿Está tu hermano?" },
      { word: "Speaking", spainVariant: "Aquí habla", latamVariant: "Habla él/ella", phoneticSpain: "[ah-KEE AH-blah]", phoneticLatam: "[AH-blah]", english: "Speaking", partOfSpeech: "phrase", exampleSentenceSpain: "Aquí habla Carlos.", exampleSentenceLatam: "Habla ella." },
      { word: "Hold on", spainVariant: "Un momento", latamVariant: "Un momento", phoneticSpain: "[oon mo-MEN-to]", phoneticLatam: "[oon mo-MEN-to]", english: "Hold on", partOfSpeech: "phrase", exampleSentenceSpain: "Un momento, por favor.", exampleSentenceLatam: "Espera un momento." },
      { word: "Can you call me back?", spainVariant: "¿Puedes llamarme después?", latamVariant: "¿Me llamas después?", phoneticSpain: "[PWEH-des yah-MAR-meh des-PWES]", phoneticLatam: "[meh YAH-mas des-PWES]", english: "Can you call me back?", partOfSpeech: "phrase", exampleSentenceSpain: "¿Puedes llamarme después?", exampleSentenceLatam: "¿Me llamas luego?" },
      { word: "Message", spainVariant: "Mensaje", latamVariant: "Mensaje", phoneticSpain: "[men-SAH-heh]", phoneticLatam: "[men-SAH-heh]", english: "Message", partOfSpeech: "noun", exampleSentenceSpain: "Te envié un mensaje.", exampleSentenceLatam: "¿Recibiste mi mensaje?" },
      { word: "Text message", spainVariant: "SMS", latamVariant: "SMS/Texto", phoneticSpain: "[es-eh-meh]", phoneticLatam: "[teks-TO]", english: "Text message", partOfSpeech: "noun", exampleSentenceSpain: "Te mando un SMS.", exampleSentenceLatam: "Te envío un texto." },
      { word: "WhatsApp", spainVariant: "WhatsApp", latamVariant: "WhatsApp", phoneticSpain: "[whats-app]", phoneticLatam: "[whats-app]", english: "WhatsApp", partOfSpeech: "noun", exampleSentenceSpain: "¿Me mandas un WhatsApp?", exampleSentenceLatam: "Te mando WhatsApp." },
      { word: "Email", spainVariant: "Correo", latamVariant: "Email", phoneticSpain: "[ko-RREH-o]", phoneticLatam: "[eh-MAIL]", english: "Email", partOfSpeech: "noun", exampleSentenceSpain: "Te envío un correo.", exampleSentenceLatam: "¿Cuál es tu email?" },
      { word: "Phone number", spainVariant: "Número de teléfono", latamVariant: "Número de teléfono", phoneticSpain: "[NOO-meh-ro deh teh-LEH-fo-no]", phoneticLatam: "[NOO-meh-ro deh teh-LEH-fo-no]", english: "Phone number", partOfSpeech: "phrase", exampleSentenceSpain: "¿Cuál es tu número de teléfono?", exampleSentenceLatam: "¿Cuál es tu número?" },
      { word: "Call", spainVariant: "Llamada", latamVariant: "Llamada", phoneticSpain: "[yah-MAH-dah]", phoneticLatam: "[yah-MAH-dah]", english: "Call", partOfSpeech: "noun", exampleSentenceSpain: "Recibí tu llamada.", exampleSentenceLatam: "Te llamaré." },
      { word: "Hang up", spainVariant: "Colgar", latamVariant: "Colgar", phoneticSpain: "[kol-GAHR]", phoneticLatam: "[kol-GAHR]", english: "Hang up", partOfSpeech: "verb", exampleSentenceSpain: "Vamos a colgar.", exampleSentenceLatam: "Tengo que colgar." },
      { word: "I'll call you", spainVariant: "Te llamo", latamVariant: "Te llamo", phoneticSpain: "[teh YAH-mo]", phoneticLatam: "[teh YAH-mo]", english: "I'll call you", partOfSpeech: "phrase", exampleSentenceSpain: "Te llamo luego.", exampleSentenceLatam: "Te llamo mañana." },
      { word: "Can I leave a message?", spainVariant: "¿Puedo dejar un mensaje?", latamVariant: "¿Puedo dejar un mensaje?", phoneticSpain: "[PWEH-do deh-HAHR oon men-SAH-heh]", phoneticLatam: "[PWEH-do deh-HAHR oon men-SAH-heh]", english: "Can I leave a message?", partOfSpeech: "phrase", exampleSentenceSpain: "¿Puedo dejar un mensaje?", exampleSentenceLatam: "¿Quieres que deje un mensaje?" },
      { word: "Bad connection", spainVariant: "Mala conexión", latamVariant: "Mala conexión", phoneticSpain: "[MAH-lah ko-nek-see-OHN]", phoneticLatam: "[MAH-lah ko-nek-see-OHN]", english: "Bad connection", partOfSpeech: "phrase", exampleSentenceSpain: "Tengo mala conexión.", exampleSentenceLatam: "La conexión está mala." },
      { word: "Can you speak louder?", spainVariant: "¿Puedes hablar más fuerte?", latamVariant: "¿Puedes hablar más fuerte?", phoneticSpain: "[PWEH-des ah-BLAHR mahs FWER-teh]", phoneticLatam: "[PWEH-des ah-BLAHR mahs FWER-teh]", english: "Can you speak louder?", partOfSpeech: "phrase", exampleSentenceSpain: "¿Puedes hablar más fuerte?", exampleSentenceLatam: "No te escucho, ¿más fuerte?" },
      { word: "I didn't hear you", spainVariant: "No te escuché", latamVariant: "No te escuché", phoneticSpain: "[no teh es-koo-CHEH]", phoneticLatam: "[no teh es-koo-CHEH]", english: "I didn't hear you", partOfSpeech: "phrase", exampleSentenceSpain: "No te escuché, repite.", exampleSentenceLatam: "¿Qué dijiste? No escuché." },
      { word: "My phone died", spainVariant: "Se me descargó el teléfono", latamVariant: "Se me acabó la batería", phoneticSpain: "[seh meh des-kar-GOH el teh-LEH-fo-no]", phoneticLatam: "[seh meh ah-kah-BOH lah bah-teh-REE-ah]", english: "My phone died", partOfSpeech: "phrase", exampleSentenceSpain: "Se me descargó el teléfono.", exampleSentenceLatam: "Se me acabó la batería." },
      { word: "I'll try again", spainVariant: "Vuelvo a intentar", latamVariant: "Vuelvo a llamar", phoneticSpain: "[VWEL-vo ah in-ten-TAHR]", phoneticLatam: "[VWEL-vo ah yah-MAHR]", english: "I'll try again", partOfSpeech: "phrase", exampleSentenceSpain: "Vuelvo a intentar.", exampleSentenceLatam: "Vuelvo a llamar." },
      { word: "Thanks for calling", spainVariant: "Gracias por llamar", latamVariant: "Gracias por llamar", phoneticSpain: "[GRAH-see-ahs por yah-MAHR]", phoneticLatam: "[GRAH-see-ahs por yah-MAHR]", english: "Thanks for calling", partOfSpeech: "phrase", exampleSentenceSpain: "Gracias por llamar.", exampleSentenceLatam: "Gracias por comunicarte." },
    ],
  },
  "a2-06-weather": {
    title: "Weather & Nature",
    description: "Talk about the weather, seasons, and describe natural phenomena",
    vocabulary: [
      { word: "Weather", spainVariant: "Clima", latamVariant: "Clima", phoneticSpain: "[KLEE-mah]", phoneticLatam: "[KLEE-mah]", english: "Weather", partOfSpeech: "noun", exampleSentenceSpain: "¿Qué tal el clima hoy?", exampleSentenceLatam: "El clima es caluroso." },
      { word: "Rain", spainVariant: "Lluvia", latamVariant: "Lluvia", phoneticSpain: "[YOO-vee-ah]", phoneticLatam: "[YOO-vee-ah]", english: "Rain", partOfSpeech: "noun", exampleSentenceSpain: "Hay mucha lluvia.", exampleSentenceLatam: "Espero que no llueva." },
      { word: "Snow", spainVariant: "Nieve", latamVariant: "Nieve", phoneticSpain: "[nee-EH-veh]", phoneticLatam: "[nee-EH-veh]", english: "Snow", partOfSpeech: "noun", exampleSentenceSpain: "¡Qué nieve tan hermosa!", exampleSentenceLatam: "Nieva en las montañas." },
      { word: "Sun", spainVariant: "Sol", latamVariant: "Sol", phoneticSpain: "[sol]", phoneticLatam: "[sol]", english: "Sun", partOfSpeech: "noun", exampleSentenceSpain: "El sol está muy fuerte.", exampleSentenceLatam: "¡Qué sol!" },
      { word: "Wind", spainVariant: "Viento", latamVariant: "Viento", phoneticSpain: "[vee-EHN-to]", phoneticLatam: "[vee-EHN-to]", english: "Wind", partOfSpeech: "noun", exampleSentenceSpain: "Hay mucho viento.", exampleSentenceLatam: "El viento es muy fuerte." },
      { word: "Cloud", spainVariant: "Nube", latamVariant: "Nube", phoneticSpain: "[NOO-beh]", phoneticLatam: "[NOO-beh]", english: "Cloud", partOfSpeech: "noun", exampleSentenceSpain: "Hay muchas nubes.", exampleSentenceLatam: "Sin una nube en el cielo." },
      { word: "Storm", spainVariant: "Tormenta", latamVariant: "Tormenta", phoneticSpain: "[tor-MEN-tah]", phoneticLatam: "[tor-MEN-tah]", english: "Storm", partOfSpeech: "noun", exampleSentenceSpain: "Hay una tormenta.", exampleSentenceLatam: "Se acerca la tormenta." },
      { word: "Lightning", spainVariant: "Rayo", latamVariant: "Rayo", phoneticSpain: "[RAH-yo]", phoneticLatam: "[RAH-yo]", english: "Lightning", partOfSpeech: "noun", exampleSentenceSpain: "¡Qué rayo tan brillante!", exampleSentenceLatam: "Hay rayos en la tormenta." },
      { word: "Thunder", spainVariant: "Trueno", latamVariant: "Trueno", phoneticSpain: "[troo-EH-no]", phoneticLatam: "[troo-EH-no]", english: "Thunder", partOfSpeech: "noun", exampleSentenceSpain: "Escucho un trueno.", exampleSentenceLatam: "El trueno fue muy fuerte." },
      { word: "Temperature", spainVariant: "Temperatura", latamVariant: "Temperatura", phoneticSpain: "[tem-peh-rah-TOO-rah]", phoneticLatam: "[tem-peh-rah-TOO-rah]", english: "Temperature", partOfSpeech: "noun", exampleSentenceSpain: "¿Cuál es la temperatura?", exampleSentenceLatam: "La temperatura está a 30 grados." },
      { word: "Hot", spainVariant: "Caluroso/a", latamVariant: "Caliente", phoneticSpain: "[kah-loo-ROH-so]", phoneticLatam: "[kah-lee-EHN-teh]", english: "Hot", partOfSpeech: "adjective", exampleSentenceSpain: "¡Qué día tan caluroso!", exampleSentenceLatam: "Hace mucho calor." },
      { word: "Cold", spainVariant: "Frío/a", latamVariant: "Frío/a", phoneticSpain: "[FREE-o]", phoneticLatam: "[FREE-o]", english: "Cold", partOfSpeech: "adjective", exampleSentenceSpain: "Hace mucho frío.", exampleSentenceLatam: "Está muy frío." },
      { word: "Spring", spainVariant: "Primavera", latamVariant: "Primavera", phoneticSpain: "[pree-mah-VEH-rah]", phoneticLatam: "[pree-mah-VEH-rah]", english: "Spring", partOfSpeech: "noun", exampleSentenceSpain: "En primavera hace buen clima.", exampleSentenceLatam: "La primavera es hermosa." },
      { word: "Summer", spainVariant: "Verano", latamVariant: "Verano", phoneticSpain: "[veh-RAH-no]", phoneticLatam: "[veh-RAH-no]", english: "Summer", partOfSpeech: "noun", exampleSentenceSpain: "En verano hace calor.", exampleSentenceLatam: "Me encanta el verano." },
      { word: "Autumn/Fall", spainVariant: "Otoño", latamVariant: "Otoño", phoneticSpain: "[o-TOH-nyoh]", phoneticLatam: "[o-TOH-nyoh]", english: "Autumn/Fall", partOfSpeech: "noun", exampleSentenceSpain: "En otoño hace templado.", exampleSentenceLatam: "El otoño es fresco." },
      { word: "Winter", spainVariant: "Invierno", latamVariant: "Invierno", phoneticSpain: "[in-vee-EHR-no]", phoneticLatam: "[in-vee-EHR-no]", english: "Winter", partOfSpeech: "noun", exampleSentenceSpain: "En invierno hace frío.", exampleSentenceLatam: "No me gusta el invierno." },
      { word: "Forecast", spainVariant: "Pronóstico", latamVariant: "Pronóstico", phoneticSpain: "[pro-NOS-tee-ko]", phoneticLatam: "[pro-NOS-tee-ko]", english: "Forecast", partOfSpeech: "noun", exampleSentenceSpain: "Según el pronóstico lloverá.", exampleSentenceLatam: "El pronóstico dice que hará calor." },
      { word: "Humidity", spainVariant: "Humedad", latamVariant: "Humedad", phoneticSpain: "[oo-meh-DAHD]", phoneticLatam: "[oo-meh-DAHD]", english: "Humidity", partOfSpeech: "noun", exampleSentenceSpain: "Hay mucha humedad.", exampleSentenceLatam: "La humedad es insoportable." },
      { word: "Breeze", spainVariant: "Brisa", latamVariant: "Brisa", phoneticSpain: "[BREE-sah]", phoneticLatam: "[BREE-sah]", english: "Breeze", partOfSpeech: "noun", exampleSentenceSpain: "Una brisa agradable.", exampleSentenceLatam: "Hay una brisa fresca." },
      { word: "Rainbow", spainVariant: "Arcoíris", latamVariant: "Arcoíris", phoneticSpain: "[ar-ko-EE-ris]", phoneticLatam: "[ar-ko-EE-ris]", english: "Rainbow", partOfSpeech: "noun", exampleSentenceSpain: "¡Mira el arcoíris!", exampleSentenceLatam: "¡Qué arcoíris tan bonito!" },
      { word: "Foggy", spainVariant: "Brumoso/a", latamVariant: "Brumoso/a", phoneticSpain: "[broo-MOH-so]", phoneticLatam: "[broo-MOH-so]", english: "Foggy", partOfSpeech: "adjective", exampleSentenceSpain: "Un día brumoso.", exampleSentenceLatam: "Está muy brumoso hoy." },
    ],
  },
  "a2-07-work-school": {
    title: "Work & School Life",
    description: "Discuss your job, studies, classes, and professional life naturally",
    vocabulary: [
      { word: "Work", spainVariant: "Trabajo", latamVariant: "Trabajo", phoneticSpain: "[trah-BAH-ho]", phoneticLatam: "[trah-BAH-ho]", english: "Work", partOfSpeech: "noun", exampleSentenceSpain: "¿Cómo te va en el trabajo?", exampleSentenceLatam: "Mi trabajo es interesante." },
      { word: "Job", spainVariant: "Empleo", latamVariant: "Empleo", phoneticSpain: "[em-PLEH-o]", phoneticLatam: "[em-PLEH-o]", english: "Job", partOfSpeech: "noun", exampleSentenceSpain: "Busco un nuevo empleo.", exampleSentenceLatam: "Tengo un buen empleo." },
      { word: "Boss", spainVariant: "Jefe", latamVariant: "Jefe", phoneticSpain: "[HEH-feh]", phoneticLatam: "[HEH-feh]", english: "Boss", partOfSpeech: "noun", exampleSentenceSpain: "Mi jefe es muy amable.", exampleSentenceLatam: "El jefe llegó temprano." },
      { word: "Colleague", spainVariant: "Colega", latamVariant: "Colega", phoneticSpain: "[ko-LEH-gah]", phoneticLatam: "[ko-LEH-gah]", english: "Colleague", partOfSpeech: "noun", exampleSentenceSpain: "Mi colega es de España.", exampleSentenceLatam: "Mis colegas son amables." },
      { word: "Office", spainVariant: "Oficina", latamVariant: "Oficina", phoneticSpain: "[o-fee-SEE-nah]", phoneticLatam: "[o-fee-SEE-nah]", english: "Office", partOfSpeech: "noun", exampleSentenceSpain: "Trabajo en una oficina.", exampleSentenceLatam: "La oficina está en el centro." },
      { word: "Meeting", spainVariant: "Reunión", latamVariant: "Reunión", phoneticSpain: "[reh-oo-nee-OHN]", phoneticLatam: "[reh-oo-nee-OHN]", english: "Meeting", partOfSpeech: "noun", exampleSentenceSpain: "Tengo una reunión a las 3.", exampleSentenceLatam: "La reunión fue larga." },
      { word: "Project", spainVariant: "Proyecto", latamVariant: "Proyecto", phoneticSpain: "[pro-YEK-to]", phoneticLatam: "[pro-YEK-to]", english: "Project", partOfSpeech: "noun", exampleSentenceSpain: "Trabajo en un proyecto importante.", exampleSentenceLatam: "El proyecto termina el viernes." },
      { word: "Deadline", spainVariant: "Plazo", latamVariant: "Plazo", phoneticSpain: "[PLAH-so]", phoneticLatam: "[PLAH-so]", english: "Deadline", partOfSpeech: "noun", exampleSentenceSpain: "El plazo es mañana.", exampleSentenceLatam: "¿Cuál es el plazo?" },
      { word: "Salary", spainVariant: "Sueldo", latamVariant: "Salario", phoneticSpain: "[SWEL-do]", phoneticLatam: "[sah-LAH-ree-o]", english: "Salary", partOfSpeech: "noun", exampleSentenceSpain: "Mi sueldo es justo.", exampleSentenceLatam: "El salario es bajo." },
      { word: "School", spainVariant: "Escuela", latamVariant: "Escuela", phoneticSpain: "[es-KWEH-lah]", phoneticLatam: "[es-KWEH-lah]", english: "School", partOfSpeech: "noun", exampleSentenceSpain: "Voy a la escuela.", exampleSentenceLatam: "La escuela está cerca." },
      { word: "University", spainVariant: "Universidad", latamVariant: "Universidad", phoneticSpain: "[oo-nee-ver-see-DAHD]", phoneticLatam: "[oo-nee-ver-see-DAHD]", english: "University", partOfSpeech: "noun", exampleSentenceSpain: "Estudio en la universidad.", exampleSentenceLatam: "¿Cuál universidad?" },
      { word: "Class", spainVariant: "Clase", latamVariant: "Clase", phoneticSpain: "[KLAH-seh]", phoneticLatam: "[KLAH-seh]", english: "Class", partOfSpeech: "noun", exampleSentenceSpain: "Tengo clase a las 9.", exampleSentenceLatam: "La clase es en la 305." },
      { word: "Teacher/Professor", spainVariant: "Profesor/a", latamVariant: "Profesor/a", phoneticSpain: "[pro-feh-SOR]", phoneticLatam: "[pro-feh-SOR]", english: "Teacher/Professor", partOfSpeech: "noun", exampleSentenceSpain: "Mi profesor es inteligente.", exampleSentenceLatam: "La profesora explica bien." },
      { word: "Student", spainVariant: "Estudiante", latamVariant: "Estudiante", phoneticSpain: "[es-too-dee-AHN-teh]", phoneticLatam: "[es-too-dee-AHN-teh]", english: "Student", partOfSpeech: "noun", exampleSentenceSpain: "Soy estudiante de ingeniería.", exampleSentenceLatam: "Los estudiantes estudian." },
      { word: "Exam", spainVariant: "Examen", latamVariant: "Examen", phoneticSpain: "[ek-SAH-men]", phoneticLatam: "[ek-SAH-men]", english: "Exam", partOfSpeech: "noun", exampleSentenceSpain: "El examen es mañana.", exampleSentenceLatam: "¿Pasaste el examen?" },
      { word: "Grade", spainVariant: "Calificación", latamVariant: "Calificación", phoneticSpain: "[kah-lee-fee-kah-see-OHN]", phoneticLatam: "[kah-lee-fee-kah-see-OHN]", english: "Grade", partOfSpeech: "noun", exampleSentenceSpain: "Mi calificación fue buena.", exampleSentenceLatam: "¿Qué calificación sacaste?" },
      { word: "Assignment", spainVariant: "Tarea", latamVariant: "Tarea", phoneticSpain: "[tah-REH-ah]", phoneticLatam: "[tah-REH-ah]", english: "Assignment", partOfSpeech: "noun", exampleSentenceSpain: "Tengo tarea para mañana.", exampleSentenceLatam: "La tarea es difícil." },
      { word: "Break/Recess", spainVariant: "Descanso", latamVariant: "Receso", phoneticSpain: "[des-KAHN-so]", phoneticLatam: "[reh-SEH-so]", english: "Break/Recess", partOfSpeech: "noun", exampleSentenceSpain: "El descanso es a las 11.", exampleSentenceLatam: "El receso es de 15 minutos." },
      { word: "Tired", spainVariant: "Cansado/a", latamVariant: "Cansado/a", phoneticSpain: "[kahn-SAH-do]", phoneticLatam: "[kahn-SAH-do]", english: "Tired", partOfSpeech: "adjective", exampleSentenceSpain: "Estoy cansado del trabajo.", exampleSentenceLatam: "Estoy muy cansado." },
      { word: "Stressed", spainVariant: "Estresado/a", latamVariant: "Estresado/a", phoneticSpain: "[es-treh-SAH-do]", phoneticLatam: "[es-treh-SAH-do]", english: "Stressed", partOfSpeech: "adjective", exampleSentenceSpain: "Estoy estresado con los exámenes.", exampleSentenceLatam: "Me siento estresado." },
    ],
  },
  "a2-08-emotions": {
    title: "Expressing Emotions & Feelings",
    description: "Describe your feelings and understand emotions deeply",
    vocabulary: [
      { word: "Happy", spainVariant: "Feliz", latamVariant: "Feliz", phoneticSpain: "[feh-LEES]", phoneticLatam: "[feh-LEES]", english: "Happy", partOfSpeech: "adjective", exampleSentenceSpain: "Estoy muy feliz hoy.", exampleSentenceLatam: "¡Qué feliz estoy!" },
      { word: "Sad", spainVariant: "Triste", latamVariant: "Triste", phoneticSpain: "[TRIS-teh]", phoneticLatam: "[TRIS-teh]", english: "Sad", partOfSpeech: "adjective", exampleSentenceSpain: "Estoy triste por eso.", exampleSentenceLatam: "Se ve triste." },
      { word: "Angry", spainVariant: "Enfadado/a", latamVariant: "Enojado/a", phoneticSpain: "[en-fah-DAH-do]", phoneticLatam: "[eh-no-HAH-do]", english: "Angry", partOfSpeech: "adjective", exampleSentenceSpain: "No estoy enfadado.", exampleSentenceLatam: "Está enojado conmigo." },
      { word: "Scared", spainVariant: "Asustado/a", latamVariant: "Asustado/a", phoneticSpain: "[ah-sus-TAH-do]", phoneticLatam: "[ah-sus-TAH-do]", english: "Scared", partOfSpeech: "adjective", exampleSentenceSpain: "Estoy asustado.", exampleSentenceLatam: "Tiene miedo." },
      { word: "Excited", spainVariant: "Emocionado/a", latamVariant: "Emocionado/a", phoneticSpain: "[eh-mo-see-o-NAH-do]", phoneticLatam: "[eh-mo-see-o-NAH-do]", english: "Excited", partOfSpeech: "adjective", exampleSentenceSpain: "¡Estoy emocionado!", exampleSentenceLatam: "¡Qué emocionada estoy!" },
      { word: "Bored", spainVariant: "Aburrido/a", latamVariant: "Aburrido/a", phoneticSpain: "[ah-boo-RREE-do]", phoneticLatam: "[ah-boo-RREE-do]", english: "Bored", partOfSpeech: "adjective", exampleSentenceSpain: "Estoy aburrido.", exampleSentenceLatam: "Me aburre." },
      { word: "Confused", spainVariant: "Confundido/a", latamVariant: "Confundido/a", phoneticSpain: "[kon-foon-DEE-do]", phoneticLatam: "[kon-foon-DEE-do]", english: "Confused", partOfSpeech: "adjective", exampleSentenceSpain: "Estoy un poco confundido.", exampleSentenceLatam: "No entiendo, estoy confundida." },
      { word: "Surprised", spainVariant: "Sorprendido/a", latamVariant: "Sorprendido/a", phoneticSpain: "[sor-pren-DEE-do]", phoneticLatam: "[sor-pren-DEE-do]", english: "Surprised", partOfSpeech: "adjective", exampleSentenceSpain: "¡Qué sorprendido estoy!", exampleSentenceLatam: "Estoy sorprendida." },
      { word: "Proud", spainVariant: "Orgulloso/a", latamVariant: "Orgulloso/a", phoneticSpain: "[or-goo-YOH-so]", phoneticLatam: "[or-goo-YOH-so]", english: "Proud", partOfSpeech: "adjective", exampleSentenceSpain: "Estoy orgulloso de ti.", exampleSentenceLatam: "Estoy orgullosa." },
      { word: "Disappointed", spainVariant: "Decepcionado/a", latamVariant: "Decepcionado/a", phoneticSpain: "[deh-sep-see-o-NAH-do]", phoneticLatam: "[deh-sep-see-o-NAH-do]", english: "Disappointed", partOfSpeech: "adjective", exampleSentenceSpain: "Estoy decepcionado.", exampleSentenceLatam: "Qué decepción." },
      { word: "Worried", spainVariant: "Preocupado/a", latamVariant: "Preocupado/a", phoneticSpain: "[preh-o-koo-PAH-do]", phoneticLatam: "[preh-o-koo-PAH-do]", english: "Worried", partOfSpeech: "adjective", exampleSentenceSpain: "Estoy preocupado.", exampleSentenceLatam: "No estés preocupada." },
      { word: "Nervous", spainVariant: "Nervioso/a", latamVariant: "Nervioso/a", phoneticSpain: "[ner-vee-OH-so]", phoneticLatam: "[ner-vee-OH-so]", english: "Nervous", partOfSpeech: "adjective", exampleSentenceSpain: "Estoy un poco nervioso.", exampleSentenceLatam: "Está nerviosa." },
      { word: "Calm", spainVariant: "Tranquilo/a", latamVariant: "Tranquilo/a", phoneticSpain: "[trahn-KEE-lo]", phoneticLatam: "[trahn-KEE-lo]", english: "Calm", partOfSpeech: "adjective", exampleSentenceSpain: "Mantén la calma.", exampleSentenceLatam: "Estoy tranquilo." },
      { word: "Angry (furious)", spainVariant: "Furioso/a", latamVariant: "Furioso/a", phoneticSpain: "[foo-ree-OH-so]", phoneticLatam: "[foo-ree-OH-so]", english: "Angry (furious)", partOfSpeech: "adjective", exampleSentenceSpain: "Está furioso.", exampleSentenceLatam: "¡Estoy furioso!" },
      { word: "Guilty", spainVariant: "Culpable", latamVariant: "Culpable", phoneticSpain: "[kool-PAH-bleh]", phoneticLatam: "[kool-PAH-bleh]", english: "Guilty", partOfSpeech: "adjective", exampleSentenceSpain: "Me siento culpable.", exampleSentenceLatam: "No me siento culpable." },
      { word: "Grateful", spainVariant: "Agradecido/a", latamVariant: "Agradecido/a", phoneticSpain: "[ah-grah-deh-SEE-do]", phoneticLatam: "[ah-grah-deh-SEE-do]", english: "Grateful", partOfSpeech: "adjective", exampleSentenceSpain: "Estoy agradecido.", exampleSentenceLatam: "Te estoy agradecida." },
      { word: "Anxious", spainVariant: "Ansioso/a", latamVariant: "Ansioso/a", phoneticSpain: "[ahn-see-OH-so]", phoneticLatam: "[ahn-see-OH-so]", english: "Anxious", partOfSpeech: "adjective", exampleSentenceSpain: "Me siento ansiosa.", exampleSentenceLatam: "Está ansioso." },
      { word: "Hopeful", spainVariant: "Esperanzado/a", latamVariant: "Esperanzado/a", phoneticSpain: "[es-peh-rahn-ZAH-do]", phoneticLatam: "[es-peh-rahn-ZAH-do]", english: "Hopeful", partOfSpeech: "adjective", exampleSentenceSpain: "Me siento esperanzado.", exampleSentenceLatam: "Tengo esperanza." },
      { word: "Lonely", spainVariant: "Solo/a", latamVariant: "Solo/a", phoneticSpain: "[SOH-lo]", phoneticLatam: "[SOH-lo]", english: "Lonely", partOfSpeech: "adjective", exampleSentenceSpain: "Me siento solo.", exampleSentenceLatam: "A veces me siento sola." },
      { word: "Comfortable", spainVariant: "Cómodo/a", latamVariant: "Cómodo/a", phoneticSpain: "[KOH-mo-do]", phoneticLatam: "[KOH-mo-do]", english: "Comfortable", partOfSpeech: "adjective", exampleSentenceSpain: "Me siento cómodo aquí.", exampleSentenceLatam: "Estoy muy cómoda." },
    ],
  },
  "a2-09-mexican-fillers": {
    title: "Mexican Fillers & Expressions",
    description: "Learn natural Mexican filler words and colloquial expressions",
    vocabulary: [
      { word: "Like (filler)", spainVariant: "Este", latamVariant: "Pues", phoneticSpain: "[ES-teh]", phoneticLatam: "[pwes]", english: "Like (filler)", partOfSpeech: "interjection", exampleSentenceSpain: "Este... no sé qué decir.", exampleSentenceLatam: "Pues, la verdad es que..." },
      { word: "Well/Actually", spainVariant: "Bueno", latamVariant: "Pues", phoneticSpain: "[boo-EH-no]", phoneticLatam: "[pwes]", english: "Well/Actually", partOfSpeech: "interjection", exampleSentenceSpain: "Bueno, ahora que lo dices...", exampleSentenceLatam: "Pues sí, tienes razón." },
      { word: "You know", spainVariant: "¿Sabes?", latamVariant: "¿Sabes?", phoneticSpain: "[SAH-bes]", phoneticLatam: "[SAH-bes]", english: "You know?", partOfSpeech: "phrase", exampleSentenceSpain: "Sabes, creo que...", exampleSentenceLatam: "¿Sabes qué? Es verdad." },
      { word: "Right? (confirmation)", spainVariant: "¿Verdad?", latamVariant: "¿Verdad?", phoneticSpain: "[ver-DAHD]", phoneticLatam: "[ver-DAHD]", english: "Right?", partOfSpeech: "interjection", exampleSentenceSpain: "Es importante, ¿verdad?", exampleSentenceLatam: "Es bonito, ¿verdad?" },
      { word: "I mean", spainVariant: "O sea", latamVariant: "O sea", phoneticSpain: "[o SEH-ah]", phoneticLatam: "[o SEH-ah]", english: "I mean", partOfSpeech: "phrase", exampleSentenceSpain: "O sea, que no estoy de acuerdo.", exampleSentenceLatam: "O sea, eso es raro." },
      { word: "So...", spainVariant: "Entonces", latamVariant: "Entonces", phoneticSpain: "[en-TON-ses]", phoneticLatam: "[en-TON-ses]", english: "So...", partOfSpeech: "interjection", exampleSentenceSpain: "Entonces, ¿qué pasó?", exampleSentenceLatam: "Entonces, ¿vienes o no?" },
      { word: "Like (similar to)", spainVariant: "Como", latamVariant: "Como", phoneticSpain: "[KO-mo]", phoneticLatam: "[KO-mo]", english: "Like (similar to)", partOfSpeech: "preposition", exampleSentenceSpain: "Fue como si nada.", exampleSentenceLatam: "Como cuando éramos niños." },
      { word: "Anyway", spainVariant: "De todas formas", latamVariant: "De todas formas", phoneticSpain: "[deh TOH-das FOR-mas]", phoneticLatam: "[deh TOH-das FOR-mas]", english: "Anyway", partOfSpeech: "adverb", exampleSentenceSpain: "De todas formas, vamos.", exampleSentenceLatam: "De todas formas, fue bueno." },
      { word: "That's crazy", spainVariant: "¡Qué loco!", latamVariant: "¡Qué loco!", phoneticSpain: "[keh LOH-ko]", phoneticLatam: "[keh LOH-ko]", english: "That's crazy!", partOfSpeech: "phrase", exampleSentenceSpain: "¡Qué loco! No lo creo.", exampleSentenceLatam: "¡Qué loco, hermano!" },
      { word: "Seriously?", spainVariant: "¿En serio?", latamVariant: "¿En serio?", phoneticSpain: "[en SEH-ree-o]", phoneticLatam: "[en SEH-ree-o]", english: "Seriously?", partOfSpeech: "phrase", exampleSentenceSpain: "¿En serio? No lo sabía.", exampleSentenceLatam: "¿En serio? ¡No!"}}
    ],
  },
  "a2-10-mexican-expressions": {
    title: "Mexican Colloquial Expressions",
    description: "Master authentic Mexican slang and everyday expressions",
    vocabulary: [
      { word: "Cool/Awesome", spainVariant: "¡Qué padre!", latamVariant: "¡Qué padre!", phoneticSpain: "[keh PAH-dreh]", phoneticLatam: "[keh PAH-dreh]", english: "Cool/Awesome!", partOfSpeech: "interjection", exampleSentenceSpain: "¡Qué padre!", exampleSentenceLatam: "¡Eso es qué padre!" },
      { word: "Dude", spainVariant: "Hermano", latamVariant: "Hermano", phoneticSpain: "[er-MAH-no]", phoneticLatam: "[er-MAH-no]", english: "Dude", partOfSpeech: "noun", exampleSentenceSpain: "Hermano, ¿qué onda?", exampleSentenceLatam: "Hermano, ¡qué tal!" },
      { word: "What's up?", spainVariant: "¿Qué onda?", latamVariant: "¿Qué onda?", phoneticSpain: "[keh OHN-dah]", phoneticLatam: "[keh OHN-dah]", english: "What's up?", partOfSpeech: "phrase", exampleSentenceSpain: "¿Qué onda, compa?", exampleSentenceLatam: "¿Qué onda, mi cuate?" },
      { word: "My friend/buddy", spainVariant: "Compa", latamVariant: "Compa", phoneticSpain: "[KOM-pah]", phoneticLatam: "[KOM-pah]", english: "My friend/buddy", partOfSpeech: "noun", exampleSentenceSpain: "Ey, compa, ¿cómo estás?", exampleSentenceLatam: "¿Vienes, compa?" },
      { word: "Got it", spainVariant: "Vale", latamVariant: "Órale", phoneticSpain: "[VAH-leh]", phoneticLatam: "[OH-rah-leh]", english: "Got it/Alright", partOfSpeech: "interjection", exampleSentenceSpain: "Vale, nos vemos.", exampleSentenceLatam: "¡Órale, hermano!" },
      { word: "Money", spainVariant: "Pasta", latamVariant: "Feria", phoneticSpain: "[PAS-tah]", phoneticLatam: "[FEH-ree-ah]", english: "Money", partOfSpeech: "noun", exampleSentenceSpain: "No tengo pasta.", exampleSentenceLatam: "No tengo feria hoy." },
      { word: "Cool guy", spainVariant: "Tipo enrollado", latamVariant: "Tipo rifado", phoneticSpain: "[TEE-po en-ro-YAH-do]", phoneticLatam: "[TEE-po ree-FAH-do]", english: "Cool guy", partOfSpeech: "phrase", exampleSentenceSpain: "Es un tipo enrollado.", exampleSentenceLatam: "¡Qué tipo tan rifado!" },
      { word: "Boring", spainVariant: "Aburrido", latamVariant: "Aburrido", phoneticSpain: "[ah-boo-RREE-do]", phoneticLatam: "[ah-boo-RREE-do]", english: "Boring", partOfSpeech: "adjective", exampleSentenceSpain: "Eso es muy aburrido.", exampleSentenceLatam: "¡Qué aburrido!" },
      { word: "Party!", spainVariant: "¡A festejar!", latamVariant: "¡Qué rola!", phoneticSpain: "[ah fes-teh-HAHR]", phoneticLatam: "[keh ROH-lah]", english: "Let's party!", partOfSpeech: "interjection", exampleSentenceSpain: "¡A festejar!", exampleSentenceLatam: "¡Qué rola, vamos a bailar!" },
      { word: "No problem", spainVariant: "Sin pedo", latamVariant: "Sin pedo", phoneticSpain: "[seen PEH-do]", phoneticLatam: "[seen PEH-do]", english: "No problem", partOfSpeech: "phrase", exampleSentenceSpain: "Sin pedo, viejo.", exampleSentenceLatam: "Sin pedo, hermano." },
      { word: "I don't care", spainVariant: "Me vale", latamVariant: "Me vale", phoneticSpain: "[meh VAH-leh]", phoneticLatam: "[meh VAH-leh]", english: "I don't care", partOfSpeech: "phrase", exampleSentenceSpain: "Me vale, haz lo que quieras.", exampleSentenceLatam: "A mí me vale, tú decides." },
      { word: "That's it!", spainVariant: "¡Eso es!", latamVariant: "¡Eso es!", phoneticSpain: "[EH-so es]", phoneticLatam: "[EH-so es]", english: "That's it!", partOfSpeech: "interjection", exampleSentenceSpain: "¡Eso es! Exactamente.", exampleSentenceLatam: "¡Eso es, hermano!" },
      { word: "Watch out", spainVariant: "¡Cuidado!", latamVariant: "¡Ojo!", phoneticSpain: "[koo-ee-DAH-do]", phoneticLatam: "[OH-ho]", english: "Watch out!", partOfSpeech: "interjection", exampleSentenceSpain: "¡Cuidado con eso!", exampleSentenceLatam: "¡Ojo, hermano!" },
      { word: "I messed up", spainVariant: "La cagué", latamVariant: "La cagué", phoneticSpain: "[lah kah-GEH]", phoneticLatam: "[lah kah-GEH]", english: "I messed up", partOfSpeech: "phrase", exampleSentenceSpain: "Ay, la cagué.", exampleSentenceLatam: "La cagué, perdón." },
      { word: "Stop bugging me", spainVariant: "No me molestes", latamVariant: "No me molestes", phoneticSpain: "[no meh mo-LES-tes]", phoneticLatam: "[no meh mo-LES-tes]", english: "Stop bugging me", partOfSpeech: "phrase", exampleSentenceSpain: "No me molestes, viejo.",exampleSentenceLatam: "No me molestes, compa." },
      { word: "You're right", spainVariant: "Tienes razón", latamVariant: "Tienes razón", phoneticSpain: "[tee-EH-nes rah-SOHN]", phoneticLatam: "[tee-EH-nes rah-SOHN]", english: "You're right", partOfSpeech: "phrase", exampleSentenceSpain: "Tienes razón, no pensé en eso.", exampleSentenceLatam: "Tienes razón, disculpa." },
      { word: "That's funny", spainVariant: "Eso es gracioso", latamVariant: "Eso es chistoso", phoneticSpain: "[EH-so es grah-see-OH-so]", phoneticLatam: "[EH-so es chees-TOH-so]", english: "That's funny", partOfSpeech: "phrase", exampleSentenceSpain: "Eso es muy gracioso.", exampleSentenceLatam: "¡Qué chistoso!" },
      { word: "I believe you", spainVariant: "Te creo", latamVariant: "Te creo", phoneticSpain: "[teh KREH-o]", phoneticLatam: "[teh KREH-o]", english: "I believe you", partOfSpeech: "phrase", exampleSentenceSpain: "Te creo, no dudo.",exampleSentenceLatam: "Te creo, hermano." },
      { word: "Let me think", spainVariant: "Déjame pensar", latamVariant: "Déjame pensar", phoneticSpain: "[DEH-hah-meh pen-SAHR]", phoneticLatam: "[DEH-hah-meh pen-SAHR]", english: "Let me think", partOfSpeech: "phrase", exampleSentenceSpain: "Déjame pensar un momento.", exampleSentenceLatam: "Déjame pensar en eso." },
      { word: "See you later", spainVariant: "Nos vidrios", latamVariant: "Nos vemos", phoneticSpain: "[nos VEE-dree-os]", phoneticLatam: "[nos VEH-mos]", english: "See you later", partOfSpeech: "phrase", exampleSentenceSpain: "¡Nos vidrios, hermano!",exampleSentenceLatam: "¡Nos vemos luego!" },
    ],
  },
};

function buildA2Lesson(slug: string): LessonData {
  const lessonDef = A2_LESSONS[slug as keyof typeof A2_LESSONS];
  if (!lessonDef) {
    throw new Error(`A2 lesson ${slug} not found`);
  }

  const slughyphen = slug.split("-");
  const order = parseInt(slughyphen[2]) || 1;

  const grammarSection: GrammarItem[] = [
    {
      title: "Vosotros vs Ustedes",
      spainContent: `In Spain, "vosotros/vosotras" is used to address a group of friends informally. Example: "¿Vosotros estáis bien?"`,
      latamContent: `In Latin America, "ustedes" serves for both formal and informal groups. Example: "¿Ustedes están bien?"`,
      note: "This is the most fundamental structural difference between Spain and Latin American Spanish.",
    },
    {
      title: `${lessonDef.title} Structures`,
      spainContent: `Key grammatical patterns for this lesson in Peninsular Spanish.`,
      latamContent: `Key grammatical patterns for this lesson in Mexican/Latin American Spanish.`,
      note: "Pay close attention to how each region naturally constructs sentences.",
    },
  ];

  const dialogues: DialogueScenario[] = [];

  for (let i = 0; i < 3; i++) {
    dialogues.push({
      id: `dialogue-spain-${i + 1}`,
      title: `${lessonDef.title} - Spain Scene ${i + 1}`,
      region: "SPAIN",
      setting: `Spain setting for ${lessonDef.title}`,
      lines: [
        { speaker: "Ana", text: lessonDef.vocabulary[i]?.exampleSentenceSpain || "Hola.", region: "SPAIN", setting: `Spain setting for ${lessonDef.title}` },
        { speaker: "Carlos", text: lessonDef.vocabulary[(i + 1) % lessonDef.vocabulary.length]?.exampleSentenceSpain || "¡Hola!", region: "SPAIN", setting: `Spain setting for ${lessonDef.title}` },
        { speaker: "Ana", text: "Gracias.", region: "SPAIN", setting: `Spain setting for ${lessonDef.title}` },
      ],
    });
  }

  for (let i = 0; i < 3; i++) {
    dialogues.push({
      id: `dialogue-latam-${i + 1}`,
      title: `${lessonDef.title} - Mexico Scene ${i + 1}`,
      region: "LATAM",
      setting: `Mexico setting for ${lessonDef.title}`,
      lines: [
        { speaker: "María", text: lessonDef.vocabulary[i]?.exampleSentenceLatam || "Hola, ¿qué onda?", region: "LATAM", setting: `Mexico setting for ${lessonDef.title}` },
        { speaker: "Diego", text: lessonDef.vocabulary[(i + 1) % lessonDef.vocabulary.length]?.exampleSentenceLatam || "¡Qué tal!", region: "LATAM", setting: `Mexico setting for ${lessonDef.title}` },
        { speaker: "María", text: "Bien.", region: "LATAM", setting: `Mexico setting for ${lessonDef.title}` },
      ],
    });
  }

  const quiz: QuizQuestion[] = [
    {
      questionId: "q1",
      type: "multiple-choice",
      questionText: `What is the key difference between Spain and Latin America in this lesson?`,
      options: ["Grammar", "Vocabulary choice", "Regional expressions", "All of the above"],
      correctAnswer: "Regional expressions",
      explanation: "This lesson focuses on regional variations in how people naturally speak in Spain vs Latin America.",
    },
    {
      questionId: "q2",
      type: "multiple-choice",
      questionText: `In Spain, what is used to address a group of friends informally?`,
      options: ["Ustedes", "Vosotros", "Ellos", "Vosotras"],
      correctAnswer: "Vosotros",
      explanation: "In Spain, 'vosotros' is the informal plural 'you' for groups of friends.",
    },
    {
      questionId: "q3",
      type: "multiple-choice",
      questionText: `What does '¿Qué onda?' mean in Mexican Spanish?`,
      options: ["What's wrong?", "What's up?", "Where are you?", "What time is it?"],
      correctAnswer: "What's up?",
      explanation: "'¿Qué onda?' is a very casual Mexican greeting meaning 'What's up?' or 'How's it going?'",
    },
    {
      questionId: "q4",
      type: "multiple-choice",
      questionText: `What regional word does Mexico use instead of Spain's 'coche' (car)?`,
      options: ["Auto", "Carro", "Vehículo", "Máquina"],
      correctAnswer: "Carro",
      explanation: "In Mexico and much of Latin America, 'carro' is commonly used instead of Spain's 'coche'.",
    },
    {
      questionId: "q5",
      type: "multiple-choice",
      questionText: `Why is learning regional expressions important?`,
      options: ["They're fun", "Native speakers use them constantly", "It's required", "All of the above"],
      correctAnswer: "Native speakers use them constantly",
      explanation: "Native speakers use regional expressions naturally, so learning them helps you communicate authentically.",
    },
  ];

  const flashcards: FlashcardItem[] = lessonDef.vocabulary.map((v, idx) => ({
    id: `fc-${slug}-${idx + 1}`,
    frontSpain: v.spainVariant,
    frontLatam: v.latamVariant,
    backEnglish: v.english,
    variantDifferenceNote: v.spainVariant !== v.latamVariant ? `Spain: "${v.spainVariant}", Mexico: "${v.latamVariant}"` : "Same in both regions",
    exampleSentenceSpain: v.exampleSentenceSpain || "",
    exampleSentenceLatam: v.exampleSentenceLatam || "",
    partOfSpeech: v.partOfSpeech,
  }));

  return {
    id: `lesson-${slug}`,
    slug,
    title: lessonDef.title,
    description: lessonDef.description,
    level: "A2",
    difficulty: "ELEMENTARY",
    order,
    imageUrl: null,
    durationMinutes: 25,
    isPublished: true,
    vocabularyTable: lessonDef.vocabulary,
    grammarSection,
    dialogues,
    quiz,
    flashcards,
    vocabularyJson: lessonDef.vocabulary.map((v) => ({
      word: v.word,
      translation: `${v.spainVariant} / ${v.latamVariant}`,
      partOfSpeech: v.partOfSpeech,
      example: v.exampleSentenceSpain,
    })),
    grammarJson: grammarSection.map((g) => ({
      title: g.title,
      content: `${g.spainContent} | ${g.latamContent}`,
    })),
    content: `# ${lessonDef.title}\n\n${lessonDef.description}\n\nThis A2 lesson covers regional vocabulary, grammar patterns, and natural speech. Study the vocabulary, learn the dialogues, and master the quiz.`,
  };
}

export function generateA2Lessons(): LessonData[] {
  const a2Slugs = Object.keys(A2_LESSONS);
  return a2Slugs.map((slug) => buildA2Lesson(slug));
}