import type { LessonData, RegionalVocabItem, GrammarItem, DialogueScenario, QuizQuestion, FlashcardItem } from "./lessons-data";

const A2_LESSONS = {
  "a2-01-small-talk": {
    title: "Small Talk",
    description: "Break the ice and keep conversations flowing with natural Mexican Spanish greetings and catch-up phrases",
    vocabulary: [
      { word: "How's everything?", spainVariant: "¿Qué tal todo?", latamVariant: "¿Qué onda todo?", phoneticSpain: "[keh TAHL TOH-do]", phoneticLatam: "[keh OHN-dah TOH-do]", english: "How's everything?", partOfSpeech: "phrase", exampleSentenceSpain: "¿Qué tal todo, tío?", exampleSentenceLatam: "¿Qué onda todo, hermano?" },
      { word: "What's new?", spainVariant: "¿Qué hay de nuevo?", latamVariant: "¿Qué hay de nuevo?", phoneticSpain: "[keh AHY deh noo-EH-vo]", phoneticLatam: "[keh AHY deh noo-EH-vo]", english: "What's new?", partOfSpeech: "phrase", exampleSentenceSpain: "¿Qué hay de nuevo en tu vida?", exampleSentenceLatam: "¿Qué hay de nuevo contigo?" },
      { word: "Same old, same old", spainVariant: "Lo de siempre", latamVariant: "Lo de siempre", phoneticSpain: "[lo deh see-EHM-preh]", phoneticLatam: "[lo deh see-EHM-preh]", english: "Same old, same old", partOfSpeech: "phrase", exampleSentenceSpain: "Lo de siempre, trabajando.", exampleSentenceLatam: "Lo de siempre, sobreviviendo." },
      { word: "I'm doing fine", spainVariant: "Me va bien", latamVariant: "Me va bien", phoneticSpain: "[meh vah bee-EHN]", phoneticLatam: "[meh vah bee-EHN]", english: "I'm doing fine", partOfSpeech: "phrase", exampleSentenceSpain: "Me va bien, gracias por preguntar.", exampleSentenceLatam: "Me va bien, ¿y a ti?" },
      { word: "Can't complain", spainVariant: "Sin quejas", latamVariant: "Sin quejas", phoneticSpain: "[seen KEH-has]", phoneticLatam: "[seen KEH-has]", english: "Can't complain", partOfSpeech: "phrase", exampleSentenceSpain: "Sin quejas, todo va bien.", exampleSentenceLatam: "Sin quejas, está todo tranquilo." },
      { word: "Busy as always", spainVariant: "Ocupado/a como siempre", latamVariant: "Ocupado/a como siempre", phoneticSpain: "[o-koo-PAH-do KOH-mo see-EHM-preh]", phoneticLatam: "[o-koo-PAH-do KOH-mo see-EHM-preh]", english: "Busy as always", partOfSpeech: "phrase", exampleSentenceSpain: "Ocupado como siempre con el trabajo.", exampleSentenceLatam: "Ocupado como siempre, pero bien." },
      { word: "You look great!", spainVariant: "¡Te ves genial!", latamVariant: "¡Te ves increíble!", phoneticSpain: "[teh ves heh-nee-AHL]", phoneticLatam: "[teh ves in-kreh-EE-bleh]", english: "You look great!", partOfSpeech: "phrase", exampleSentenceSpain: "¡Te ves genial, has bajado de peso!", exampleSentenceLatam: "¡Te ves increíble, qué estás haciendo?" },
      { word: "You haven't changed", spainVariant: "No has cambiado", latamVariant: "No has cambiado", phoneticSpain: "[no ahs kahm-bee-AH-do]", phoneticLatam: "[no ahs kahm-bee-AH-do]", english: "You haven't changed", partOfSpeech: "phrase", exampleSentenceSpain: "No has cambiado nada.", exampleSentenceLatam: "Sigues igual de guapo/a." },
      { word: "We should catch up!", spainVariant: "¡Deberíamos ponernos al día!", latamVariant: "¡Deberíamos platicar!", phoneticSpain: "[deh-beh-REE-ah-mos po-ner-nos ahl DEE-ah]", phoneticLatam: "[deh-beh-REE-ah-mos plah-tee-KAR]", english: "We should catch up!", partOfSpeech: "phrase", exampleSentenceSpain: "Deberíamos vernos pronto.", exampleSentenceLatam: "Deberíamos juntarnos para platicar." },
      { word: "Long time no see!", spainVariant: "¡Cuánto tiempo sin verte!", latamVariant: "¡Cuánto tiempo sin verte!", phoneticSpain: "[KWAN-to tee-EHM-po seen VER-teh]", phoneticLatam: "[KWAN-to tee-EHM-po seen VER-teh]", english: "Long time no see!", partOfSpeech: "phrase", exampleSentenceSpain: "¡Cuánto tiempo! ¿Dónde estabas?", exampleSentenceLatam: "¡Cuánto que no te veo!" },
      { word: "Tell me about yourself", spainVariant: "Cuéntame de ti", latamVariant: "Cuéntame de ti", phoneticSpain: "[koo-EHN-tah-meh deh tee]", phoneticLatam: "[koo-EHN-tah-meh deh tee]", english: "Tell me about yourself", partOfSpeech: "phrase", exampleSentenceSpain: "Cuéntame qué has estado haciendo.", exampleSentenceLatam: "Cuéntame cómo ha sido tu vida." },
      { word: "I've missed you", spainVariant: "Te he echado de menos", latamVariant: "Te he extrañado", phoneticSpain: "[teh eh eh-CHAH-do deh MEH-nos]", phoneticLatam: "[teh eh ehk-strah-NYAH-do]", english: "I've missed you", partOfSpeech: "phrase", exampleSentenceSpain: "Te he echado de menos, amigo.", exampleSentenceLatam: "Te he extrañado mucho, hermano." },
      { word: "Stay in touch", spainVariant: "Mantengámonos en contacto", latamVariant: "Mantente en contacto", phoneticSpain: "[mahn-ten-GAH-mo-nos en kon-TAHK-to]", phoneticLatam: "[mahn-TEN-teh en kon-TAHK-to]", english: "Stay in touch", partOfSpeech: "phrase", exampleSentenceSpain: "Mantengámonos en contacto, ¿vale?", exampleSentenceLatam: "Mantente en contacto, me gustaría saber de ti." },
      { word: "It's been ages", spainVariant: "Ha pasado una eternidad", latamVariant: "Hace una eternidad", phoneticSpain: "[ah pah-SAH-do oo-nah eh-ter-nee-DAHD]", phoneticLatam: "[AH-seh oo-nah eh-ter-nee-DAHD]", english: "It's been ages", partOfSpeech: "phrase", exampleSentenceSpain: "Ha pasado una eternidad desde la última vez.", exampleSentenceLatam: "Hace siglos que no nos vemos." },
      { word: "Great to see you", spainVariant: "¡Qué alegría verte!", latamVariant: "¡Qué gusto verte!", phoneticSpain: "[keh ah-leh-GREE-ah VER-teh]", phoneticLatam: "[keh GUS-to VER-teh]", english: "Great to see you", partOfSpeech: "phrase", exampleSentenceSpain: "¡Qué alegría verte, hermano!", exampleSentenceLatam: "¡Qué gusto verte después de tanto tiempo!" },
      { word: "You're looking well", spainVariant: "Te ves bien", latamVariant: "Te ves muy bien", phoneticSpain: "[teh ves bee-EHN]", phoneticLatam: "[teh ves moo-ee bee-EHN]", english: "You're looking well", partOfSpeech: "phrase", exampleSentenceSpain: "Te ves bien, ¿qué estás haciendo?", exampleSentenceLatam: "Te ves muy bien, ¿qué es tu secreto?" },
      { word: "How have you been?", spainVariant: "¿Cómo has estado?", latamVariant: "¿Cómo has estado?", phoneticSpain: "[KOH-mo ahs es-TAH-do]", phoneticLatam: "[KOH-mo ahs es-TAH-do]", english: "How have you been?", partOfSpeech: "phrase", exampleSentenceSpain: "¿Cómo has estado estos días?", exampleSentenceLatam: "¿Cómo has estado, no nos vemos hace mucho?" },
      { word: "Living the dream", spainVariant: "Viviendo el sueño", latamVariant: "Viviendo el sueño", phoneticSpain: "[vee-vee-EHN-do el soo-EHN-yo]", phoneticLatam: "[vee-vee-EHN-do el soo-EHN-yo]", english: "Living the dream", partOfSpeech: "phrase", exampleSentenceSpain: "Viviendo el sueño, trabajando y disfrutando.", exampleSentenceLatam: "Viviendo el sueño, día a día." },
    ],
  },
  "a2-02-daily-routines": {
    title: "Daily Routines",
    description: "Talk about your everyday life—waking up, getting ready, working, and winding down in natural Mexican Spanish",
    vocabulary: [
      { word: "Wake up", spainVariant: "Despertarse", latamVariant: "Despertarse", phoneticSpain: "[des-per-TAR-seh]", phoneticLatam: "[des-per-TAR-seh]", english: "Wake up", partOfSpeech: "verb", exampleSentenceSpain: "Me despierto a las 7.", exampleSentenceLatam: "Me despierto a las 6:30." },
      { word: "Get out of bed", spainVariant: "Levantarse", latamVariant: "Levantarse", phoneticSpain: "[leh-vahn-TAR-seh]", phoneticLatam: "[leh-vahn-TAR-seh]", english: "Get out of bed", partOfSpeech: "verb", exampleSentenceSpain: "Me levanto rápidamente.", exampleSentenceLatam: "Me levanto con dificultad." },
      { word: "Take a shower", spainVariant: "Ducha", latamVariant: "Ducha", phoneticSpain: "[DOO-chah]", phoneticLatam: "[DOO-chah]", english: "Take a shower", partOfSpeech: "noun", exampleSentenceSpain: "Me ducho por la mañana.", exampleSentenceLatam: "Me ducho para despertarme." },
      { word: "Get ready", spainVariant: "Arreglarse", latamVariant: "Arreglarse", phoneticSpain: "[ah-rreh-GLAHR-seh]", phoneticLatam: "[ah-rreh-GLAHR-seh]", english: "Get ready", partOfSpeech: "verb", exampleSentenceSpain: "Me arreglo en 30 minutos.", exampleSentenceLatam: "Me arreglo y salgo." },
      { word: "Brush teeth", spainVariant: "Cepillarse los dientes", latamVariant: "Cepillarse los dientes", phoneticSpain: "[seh-pee-YAHR-seh los dee-EHN-tes]", phoneticLatam: "[seh-pee-YAHR-seh los dee-EHN-tes]", english: "Brush teeth", partOfSpeech: "phrase", exampleSentenceSpain: "Me cepillo los dientes después del desayuno.", exampleSentenceLatam: "Me cepillo dos veces al día." },
      { word: "Breakfast", spainVariant: "Desayuno", latamVariant: "Desayuno", phoneticSpain: "[deh-sah-YOO-no]", phoneticLatam: "[deh-sah-YOO-no]", english: "Breakfast", partOfSpeech: "noun", exampleSentenceSpain: "Desayuno café y tostadas.", exampleSentenceLatam: "Desayuno café con pan dulce." },
      { word: "Go to work", spainVariant: "Ir al trabajo", latamVariant: "Ir al trabajo", phoneticSpain: "[eer ahl trah-BAH-ho]", phoneticLatam: "[eer ahl trah-BAH-ho]", english: "Go to work", partOfSpeech: "phrase", exampleSentenceSpain: "Voy al trabajo en coche.", exampleSentenceLatam: "Voy al trabajo en autobús." },
      { word: "Work", spainVariant: "Trabajar", latamVariant: "Trabajar", phoneticSpain: "[trah-bah-HAR]", phoneticLatam: "[trah-bah-HAR]", english: "Work", partOfSpeech: "verb", exampleSentenceSpain: "Trabajo 8 horas al día.", exampleSentenceLatam: "Trabajo en una oficina." },
      { word: "Lunch break", spainVariant: "Descanso para comer", latamVariant: "Hora de comida", phoneticSpain: "[des-KAHN-so PAH-rah ko-MER]", phoneticLatam: "[OH-rah deh ko-MEE-dah]", english: "Lunch break", partOfSpeech: "noun", exampleSentenceSpain: "Tengo una hora para comer.", exampleSentenceLatam: "Salgo a comer al mediodía." },
      { word: "Finish work", spainVariant: "Terminar el trabajo", latamVariant: "Terminar el trabajo", phoneticSpain: "[ter-mee-NAR el trah-BAH-ho]", phoneticLatam: "[ter-mee-NAR el trah-BAH-ho]", english: "Finish work", partOfSpeech: "phrase", exampleSentenceSpain: "Termino a las 6 de la tarde.", exampleSentenceLatam: "Salgo del trabajo a las 5." },
      { word: "Go home", spainVariant: "Ir a casa", latamVariant: "Ir a casa", phoneticSpain: "[eer ah KAH-sah]", phoneticLatam: "[eer ah KAH-sah]", english: "Go home", partOfSpeech: "phrase", exampleSentenceSpain: "Me voy a casa.", exampleSentenceLatam: "Regreso a casa cansado." },
      { word: "Have dinner", spainVariant: "Cenar", latamVariant: "Cenar", phoneticSpain: "[seh-NAR]", phoneticLatam: "[seh-NAR]", english: "Have dinner", partOfSpeech: "verb", exampleSentenceSpain: "Ceno a las 9.", exampleSentenceLatam: "Ceno temprano, alrededor de las 7." },
      { word: "Watch TV", spainVariant: "Ver la televisión", latamVariant: "Ver la tele", phoneticSpain: "[ver lah teh-leh-vee-see-OHN]", phoneticLatam: "[ver lah TEH-leh]", english: "Watch TV", partOfSpeech: "phrase", exampleSentenceSpain: "Veo la televisión antes de dormir.", exampleSentenceLatam: "Veo la tele un rato." },
      { word: "Read", spainVariant: "Leer", latamVariant: "Leer", phoneticSpain: "[leh-EHR]", phoneticLatam: "[leh-EHR]", english: "Read", partOfSpeech: "verb", exampleSentenceSpain: "Leo un libro todas las noches.", exampleSentenceLatam: "Leo antes de dormir." },
      { word: "Go to bed", spainVariant: "Acostarse", latamVariant: "Acostarse", phoneticSpain: "[ah-kos-TAR-seh]", phoneticLatam: "[ah-kos-TAR-seh]", english: "Go to bed", partOfSpeech: "verb", exampleSentenceSpain: "Me acuesto a las 11.", exampleSentenceLatam: "Me acuesto alrededor de las 10:30." },
      { word: "Sleep", spainVariant: "Dormir", latamVariant: "Dormir", phoneticSpain: "[dor-MEER]", phoneticLatam: "[dor-MEER]", english: "Sleep", partOfSpeech: "verb", exampleSentenceSpain: "Duermo 8 horas.", exampleSentenceLatam: "Duermo bien la mayoría de las noches." },
      { word: "Morning routine", spainVariant: "Rutina matutina", latamVariant: "Rutina matutina", phoneticSpain: "[roo-TEE-nah mah-too-TEE-nah]", phoneticLatam: "[roo-TEE-nah mah-too-TEE-nah]", english: "Morning routine", partOfSpeech: "noun", exampleSentenceSpain: "Mi rutina matutina es rápida.", exampleSentenceLatam: "Tengo una rutina muy consistente." },
      { word: "Evening", spainVariant: "Noche", latamVariant: "Noche", phoneticSpain: "[NOH-cheh]", phoneticLatam: "[NOH-cheh]", english: "Evening", partOfSpeech: "noun", exampleSentenceSpain: "Por la noche descanso.", exampleSentenceLatam: "En la noche paso tiempo con mi familia." },
      { word: "I'm tired", spainVariant: "Estoy cansado/a", latamVariant: "Estoy cansado/a", phoneticSpain: "[es-TOY kahn-SAH-do]", phoneticLatam: "[es-TOY kahn-SAH-do]", english: "I'm tired", partOfSpeech: "phrase", exampleSentenceSpain: "Estoy muy cansado después del trabajo.", exampleSentenceLatam: "Estoy exhausto/a." },
      { word: "I'm busy", spainVariant: "Estoy ocupado/a", latamVariant: "Estoy ocupado/a", phoneticSpain: "[es-TOY o-koo-PAH-do]", phoneticLatam: "[es-TOY o-koo-PAH-do]", english: "I'm busy", partOfSpeech: "phrase", exampleSentenceSpain: "Estoy muy ocupado esta semana.", exampleSentenceLatam: "Estoy muy ocupado con todo." },
    ],
  },
  "a2-03-hobbies": {
    title: "Hobbies & Free Time",
    description: "Talk about your hobbies, interests, and what you love doing in your free time",
    vocabulary: [
      { word: "Hobby", spainVariant: "Afición", latamVariant: "Pasatiempo", phoneticSpain: "[ah-fee-see-OHN]", phoneticLatam: "[pah-sah-tee-EHM-po]", english: "Hobby", partOfSpeech: "noun", exampleSentenceSpain: "Mis aficiones son leer y viajar.", exampleSentenceLatam: "Mi pasatiempo favorito es jugar fútbol." },
      { word: "Free time", spainVariant: "Tiempo libre", latamVariant: "Tiempo libre", phoneticSpain: "[tee-EHM-po LEE-breh]", phoneticLatam: "[tee-EHM-po LEE-breh]", english: "Free time", partOfSpeech: "noun", exampleSentenceSpain: "En mi tiempo libre me relajo.", exampleSentenceLatam: "En mi tiempo libre veo películas." },
      { word: "I like...", spainVariant: "Me gusta...", latamVariant: "Me gusta...", phoneticSpain: "[meh GUS-tah]", phoneticLatam: "[meh GUS-tah]", english: "I like...", partOfSpeech: "phrase", exampleSentenceSpain: "Me gusta jugar al tenis.", exampleSentenceLatam: "Me gusta escuchar música." },
      { word: "I love...", spainVariant: "Me encanta...", latamVariant: "Me encanta...", phoneticSpain: "[meh en-KAHN-tah]", phoneticLatam: "[meh en-KAHN-tah]", english: "I love...", partOfSpeech: "phrase", exampleSentenceSpain: "Me encanta viajar.", exampleSentenceLatam: "Me encanta cocinar." },
      { word: "Sport", spainVariant: "Deporte", latamVariant: "Deporte", phoneticSpain: "[deh-POR-teh]", phoneticLatam: "[deh-POR-teh]", english: "Sport", partOfSpeech: "noun", exampleSentenceSpain: "Hago deporte tres veces a la semana.", exampleSentenceLatam: "Mi deporte favorito es el fútbol." },
      { word: "Football/Soccer", spainVariant: "Fútbol", latamVariant: "Fútbol", phoneticSpain: "[FOOT-bol]", phoneticLatam: "[FOOT-bol]", english: "Football/Soccer", partOfSpeech: "noun", exampleSentenceSpain: "Juego al fútbol los domingos.", exampleSentenceLatam: "Veo fútbol todos los sábados." },
      { word: "Reading", spainVariant: "Lectura", latamVariant: "Lectura", phoneticSpain: "[lek-TOO-rah]", phoneticLatam: "[lek-TOO-rah]", english: "Reading", partOfSpeech: "noun", exampleSentenceSpain: "La lectura es mi hobby favorito.", exampleSentenceLatam: "Me gusta la lectura de novelas." },
      { word: "Travel", spainVariant: "Viajar", latamVariant: "Viajar", phoneticSpain: "[vee-ah-HAR]", phoneticLatam: "[vee-ah-HAR]", english: "Travel", partOfSpeech: "verb", exampleSentenceSpain: "Me encanta viajar por Europa.", exampleSentenceLatam: "Viajar es mi pasión." },
      { word: "Cooking", spainVariant: "Cocina", latamVariant: "Cocina", phoneticSpain: "[ko-SEE-nah]", phoneticLatam: "[ko-SEE-nah]", english: "Cooking", partOfSpeech: "noun", exampleSentenceSpain: "Cocino casi todos los días.", exampleSentenceLatam: "Me gusta cocinar comida mexicana." },
      { word: "Music", spainVariant: "Música", latamVariant: "Música", phoneticSpain: "[MOO-see-kah]", phoneticLatam: "[MOO-see-kah]", english: "Music", partOfSpeech: "noun", exampleSentenceSpain: "Escucho música mientras trabajo.", exampleSentenceLatam: "Toco guitarra en mi tiempo libre." },
      { word: "Movies", spainVariant: "Películas", latamVariant: "Películas", phoneticSpain: "[peh-LEE-koo-lahs]", phoneticLatam: "[peh-LEE-koo-lahs]", english: "Movies", partOfSpeech: "noun", exampleSentenceSpain: "Me encantan las películas de acción.", exampleSentenceLatam: "Ver películas es mi cosa favorita." },
      { word: "Exercise", spainVariant: "Hacer ejercicio", latamVariant: "Hacer ejercicio", phoneticSpain: "[ah-SER eh-her-SEE-see-o]", phoneticLatam: "[ah-SER eh-her-SEE-see-o]", english: "Exercise", partOfSpeech: "phrase", exampleSentenceSpain: "Hago ejercicio en el gimnasio.", exampleSentenceLatam: "Hago ejercicio cada mañana." },
      { word: "Dancing", spainVariant: "Baile", latamVariant: "Baile", phoneticSpain: "[bah-EE-leh]", phoneticLatam: "[bah-EE-leh]", english: "Dancing", partOfSpeech: "noun", exampleSentenceSpain: "Me encanta bailar.", exampleSentenceLatam: "Bailo salsa los viernes." },
      { word: "Photography", spainVariant: "Fotografía", latamVariant: "Fotografía", phoneticSpain: "[fo-to-grah-FEE-ah]", phoneticLatam: "[fo-to-grah-FEE-ah]", english: "Photography", partOfSpeech: "noun", exampleSentenceSpain: "Mi hobby es la fotografía.", exampleSentenceLatam: "Hago fotografía de naturaleza." },
      { word: "Drawing", spainVariant: "Dibujo", latamVariant: "Dibujo", phoneticSpain: "[dee-BOO-ho]", phoneticLatam: "[dee-BOO-ho]", english: "Drawing", partOfSpeech: "noun", exampleSentenceSpain: "Dibujo en mis ratos libres.", exampleSentenceLatam: "Me gusta dibujar personajes." },
      { word: "Gaming", spainVariant: "Videojuegos", latamVariant: "Videojuegos", phoneticSpain: "[vee-deh-o-hoo-EH-gos]", phoneticLatam: "[vee-deh-o-hoo-EH-gos]", english: "Gaming", partOfSpeech: "noun", exampleSentenceSpain: "Juego videojuegos en el fin de semana.", exampleSentenceLatam: "Juego videojuegos en línea." },
      { word: "Gardening", spainVariant: "Jardinería", latamVariant: "Jardinería", phoneticSpain: "[har-dee-neh-REE-ah]", phoneticLatam: "[har-dee-neh-REE-ah]", english: "Gardening", partOfSpeech: "noun", exampleSentenceSpain: "La jardinería es relajante.", exampleSentenceLatam: "Cultivo plantas en mi patio." },
      { word: "Fun", spainVariant: "Diversión", latamVariant: "Diversión", phoneticSpain: "[dee-ver-see-OHN]", phoneticLatam: "[dee-ver-see-OHN]", english: "Fun", partOfSpeech: "noun", exampleSentenceSpain: "Es muy divertido.", exampleSentenceLatam: "¡Qué diversión!" },
      { word: "Interesting", spainVariant: "Interesante", latamVariant: "Interesante", phoneticSpain: "[in-teh-reh-SAHN-teh]", phoneticLatam: "[in-teh-reh-SAHN-teh]", english: "Interesting", partOfSpeech: "adjective", exampleSentenceSpain: "Es muy interesante.", exampleSentenceLatam: "¡Qué interesante!" },
      { word: "Relaxing", spainVariant: "Relajante", latamVariant: "Relajante", phoneticSpain: "[reh-lah-HAHN-teh]", phoneticLatam: "[reh-lah-HAHN-teh]", english: "Relaxing", partOfSpeech: "adjective", exampleSentenceSpain: "Es muy relajante.", exampleSentenceLatam: "Me ayuda a relajarme." },
    ],
  },
  "a2-04-making-plans": {
    title: "Making Plans",
    description: "Invite friends out, set a time and place, and handle plans on the fly",
    vocabulary: [
      { word: "Let's meet up", spainVariant: "Nos vemos", latamVariant: "Nos vemos", phoneticSpain: "[nos VEH-mos]", phoneticLatam: "[nos VEH-mos]", english: "Let's meet up", partOfSpeech: "phrase", exampleSentenceSpain: "¿Nos vemos el viernes?", exampleSentenceLatam: "¿Nos vemos este fin de semana?" },
      { word: "When are you free?", spainVariant: "¿Cuándo tienes tiempo?", latamVariant: "¿Cuándo tienes tiempo?", phoneticSpain: "[KWAN-do tee-EH-nes tee-EHM-po]", phoneticLatam: "[KWAN-do tee-EH-nes tee-EHM-po]", english: "When are you free?", partOfSpeech: "phrase", exampleSentenceSpain: "¿Cuándo tienes tiempo para vernos?", exampleSentenceLatam: "¿Cuándo estás disponible?" },
      { word: "I'm free on...", spainVariant: "Estoy libre el...", latamVariant: "Estoy libre el...", phoneticSpain: "[es-TOY LEE-breh el]", phoneticLatam: "[es-TOY LEE-breh el]", english: "I'm free on...", partOfSpeech: "phrase", exampleSentenceSpain: "Estoy libre el sábado.", exampleSentenceLatam: "Estoy libre el viernes por la noche." },
      { word: "What time works for you?", spainVariant: "¿Qué hora te viene bien?", latamVariant: "¿Qué hora te viene bien?", phoneticSpain: "[keh OH-rah teh vee-EH-neh bee-EHN]", phoneticLatam: "[keh OH-rah teh vee-EH-neh bee-EHN]", english: "What time works for you?", partOfSpeech: "phrase", exampleSentenceSpain: "¿Qué hora te viene bien?", exampleSentenceLatam: "¿Qué hora te parece?" },
      { word: "How about 8 PM?", spainVariant: "¿Qué tal a las 8?", latamVariant: "¿Qué tal a las 8?", phoneticSpain: "[keh TAHL ah lahs ocho]", phoneticLatam: "[keh TAHL ah lahs ocho]", english: "How about 8 PM?", partOfSpeech: "phrase", exampleSentenceSpain: "¿Qué tal a las 8 de la tarde?", exampleSentenceLatam: "¿Te parece a las 8 de la noche?" },
      { word: "Where should we meet?", spainVariant: "¿Dónde nos vemos?", latamVariant: "¿Dónde nos vemos?", phoneticSpain: "[DOHN-deh nos VEH-mos]", phoneticLatam: "[DOHN-deh nos VEH-mos]", english: "Where should we meet?", partOfSpeech: "phrase", exampleSentenceSpain: "¿Dónde nos vemos?", exampleSentenceLatam: "¿En dónde hacemos la junta?" },
      { word: "Let's go to...", spainVariant: "Vamos a...", latamVariant: "Vamos a...", phoneticSpain: "[VAH-mos ah]", phoneticLatam: "[VAH-mos ah]", english: "Let's go to...", partOfSpeech: "phrase", exampleSentenceSpain: "Vamos a ese café nuevo.", exampleSentenceLatam: "Vamos a la cantina." },
      { word: "Restaurant", spainVariant: "Restaurante", latamVariant: "Restaurante", phoneticSpain: "[res-tow-RAHN-teh]", phoneticLatam: "[res-tow-RAHN-teh]", english: "Restaurant", partOfSpeech: "noun", exampleSentenceSpain: "Hay un restaurante muy bueno por aquí.", exampleSentenceLatam: "¿Qué restaurante prefieres?" },
      { word: "Cinema/Movie theater", spainVariant: "Cine", latamVariant: "Cine", phoneticSpain: "[SEE-neh]", phoneticLatam: "[SEE-neh]", english: "Cinema/Movie theater", partOfSpeech: "noun", exampleSentenceSpain: "¿Vamos al cine el sábado?", exampleSentenceLatam: "Hay una película nueva en el cine." },
      { word: "Bar", spainVariant: "Bar", latamVariant: "Bar", phoneticSpain: "[bar]", phoneticLatam: "[bar]", english: "Bar", partOfSpeech: "noun", exampleSentenceSpain: "Después vamos a un bar.", exampleSentenceLatam: "Hay un bar muy cool en el centro." },
      { word: "Park", spainVariant: "Parque", latamVariant: "Parque", phoneticSpain: "[PAR-keh]", phoneticLatam: "[PAR-keh]", english: "Park", partOfSpeech: "noun", exampleSentenceSpain: "Podemos pasear por el parque.", exampleSentenceLatam: "El parque es bonito para caminar." },
      { word: "Party", spainVariant: "Fiesta", latamVariant: "Fiesta", phoneticSpain: "[fee-EHS-tah]", phoneticLatam: "[fee-EHS-tah]", english: "Party", partOfSpeech: "noun", exampleSentenceSpain: "Hay una fiesta el sábado.", exampleSentenceLatam: "¡Vamos a la fiesta!" },
      { word: "Concert", spainVariant: "Concierto", latamVariant: "Concierto", phoneticSpain: "[kon-see-EHR-to]", phoneticLatam: "[kon-see-EHR-to]", english: "Concert", partOfSpeech: "noun", exampleSentenceSpain: "¿Quieres ir a un concierto?", exampleSentenceLatam: "Hay un concierto de rock este fin de semana." },
      { word: "I can't, sorry", spainVariant: "No puedo, disculpa", latamVariant: "No puedo, disculpa", phoneticSpain: "[no PWEH-do, dis-KOOL-pah]", phoneticLatam: "[no PWEH-do, dis-KOOL-pah]", english: "I can't, sorry", partOfSpeech: "phrase", exampleSentenceSpain: "No puedo el viernes, disculpa.", exampleSentenceLatam: "No puedo ese día, lo siento." },
      { word: "Something came up", spainVariant: "Surgió algo", latamVariant: "Surgió algo", phoneticSpain: "[sur-HEE-o AHL-go]", phoneticLatam: "[sur-HEE-o AHL-go]", english: "Something came up", partOfSpeech: "phrase", exampleSentenceSpain: "Surgió algo en el trabajo.", exampleSentenceLatam: "Me surgió algo de última hora." },
      { word: "Can we reschedule?", spainVariant: "¿Podemos reagendar?", latamVariant: "¿Podemos reagendar?", phoneticSpain: "[po-DEH-mos reh-ah-hen-DAR]", phoneticLatam: "[po-DEH-mos reh-ah-hen-DAR]", english: "Can we reschedule?", partOfSpeech: "phrase", exampleSentenceSpain: "¿Podemos reagendar?", exampleSentenceLatam: "¿Podemos cambiar la fecha?" },
      { word: "How long will it take?", spainVariant: "¿Cuánto tiempo tardará?", latamVariant: "¿Cuánto tiempo le toma?", phoneticSpain: "[KWAN-to tee-EHM-po tar-dah-RAH]", phoneticLatam: "[KWAN-to tee-EHM-po leh TOH-mah]", english: "How long will it take?", partOfSpeech: "phrase", exampleSentenceSpain: "¿Cuánto tiempo tardará en llegar?", exampleSentenceLatam: "¿Cuánto tarda de aquí?" },
      { word: "Let's make it early", spainVariant: "Hagámoslo más temprano", latamVariant: "Hagámoslo más temprano", phoneticSpain: "[ah-GAH-mos-lo mahs tem-PRAH-no]", phoneticLatam: "[ah-GAH-mos-lo mahs tem-PRAH-no]", english: "Let's make it early", partOfSpeech: "phrase", exampleSentenceSpain: "Hagámoslo más temprano, así termino antes.", exampleSentenceLatam: "Mejor a las 6 en lugar de las 8." },
      { word: "See you there!", spainVariant: "¡Nos vemos allí!", latamVariant: "¡Nos vemos allá!", phoneticSpain: "[nos VEH-mos ah-YEE]", phoneticLatam: "[nos VEH-mos ah-YAH]", english: "See you there!", partOfSpeech: "phrase", exampleSentenceSpain: "¡Nos vemos allí!", exampleSentenceLatam: "¡Nos vemos allá!" },
    ],
  },
  "a2-05-phone-calls": {
    title: "Phone Calls & Texting",
    description: "Answer calls the Mexican way, handle bad signal, and text like a local on WhatsApp",
    vocabulary: [
      { word: "Hello (on phone)", spainVariant: "¿Diga?", latamVariant: "¿Hola?", phoneticSpain: "[DEE-gah]", phoneticLatam: "[OH-lah]", english: "Hello (on phone)", partOfSpeech: "interjection", exampleSentenceSpain: "¿Diga? Aquí habla Juan.", exampleSentenceLatam: "¿Hola, quién habla?" },
      { word: "Who is this?", spainVariant: "¿Quién habla?", latamVariant: "¿Quién habla?", phoneticSpain: "[kee-EHN AH-blah]", phoneticLatam: "[kee-EHN AH-blah]", english: "Who is this?", partOfSpeech: "phrase", exampleSentenceSpain: "¿Quién habla?", exampleSentenceLatam: "¿Quién es?" },
      { word: "It's me, [name]", spainVariant: "Soy yo, [nombre]", latamVariant: "Soy yo, [nombre]", phoneticSpain: "[soy yo]", phoneticLatam: "[soy yo]", english: "It's me, [name]", partOfSpeech: "phrase", exampleSentenceSpain: "Soy yo, María.", exampleSentenceLatam: "Soy Carlos, ¿cómo estás?" },
      { word: "Can you call me back?", spainVariant: "¿Puedes devolverme la llamada?", latamVariant: "¿Me llamas después?", phoneticSpain: "[PWEH-des deh-vol-VER-meh lah yah-MAH-dah]", phoneticLatam: "[meh YAH-mas DEHS-pwehs]", english: "Can you call me back?", partOfSpeech: "phrase", exampleSentenceSpain: "¿Puedes devolverme la llamada?", exampleSentenceLatam: "¿Me llamas después?" },
      { word: "I can't hear you", spainVariant: "No te oigo bien", latamVariant: "No te escucho", phoneticSpain: "[no teh OY-go bee-EHN]", phoneticLatam: "[no teh es-KOO-cho]", english: "I can't hear you", partOfSpeech: "phrase", exampleSentenceSpain: "No te oigo bien, ¿puedes hablar más fuerte?", exampleSentenceLatam: "No te escucho bien, hay mala señal." },
      { word: "Bad signal", spainVariant: "Mala señal", latamVariant: "Mala señal", phoneticSpain: "[MAH-lah seh-NYAHL]", phoneticLatam: "[MAH-lah seh-NYAHL]", english: "Bad signal", partOfSpeech: "noun", exampleSentenceSpain: "Tengo mala señal en este lugar.", exampleSentenceLatam: "La señal está muy mala." },
      { word: "Can you hear me?", spainVariant: "¿Me oyes?", latamVariant: "¿Me escuchas?", phoneticSpain: "[meh OY-es]", phoneticLatam: "[meh es-KOO-chas]", english: "Can you hear me?", partOfSpeech: "phrase", exampleSentenceSpain: "¿Me oyes bien?", exampleSentenceLatam: "¿Me escuchas ahora?" },
      { word: "I'll call you later", spainVariant: "Te llamo luego", latamVariant: "Te llamo después", phoneticSpain: "[teh YAH-mo loo-EH-go]", phoneticLatam: "[teh YAH-mo DEHS-pwehs]", english: "I'll call you later", partOfSpeech: "phrase", exampleSentenceSpain: "Te llamo luego, estoy en una reunión.", exampleSentenceLatam: "Te llamo después, ahorita estoy ocupado." },
      { word: "Text me", spainVariant: "Mándame un mensaje", latamVariant: "Mándame un mensaje", phoneticSpain: "[MAHN-dah-meh oon men-SAH-heh]", phoneticLatam: "[MAHN-dah-meh oon men-SAH-heh]", english: "Text me", partOfSpeech: "phrase", exampleSentenceSpain: "Mándame un mensaje cuando llegues.", exampleSentenceLatam: "Mándame un WhatsApp." },
      { word: "Send me a message", spainVariant: "Envíame un mensaje", latamVariant: "Envíame un mensaje", phoneticSpain: "[en-VEE-ah-meh oon men-SAH-heh]", phoneticLatam: "[en-VEE-ah-meh oon men-SAH-heh]", english: "Send me a message", partOfSpeech: "phrase", exampleSentenceSpain: "Envíame un mensaje cuando puedas.", exampleSentenceLatam: "Envíame un mensaje por WhatsApp." },
      { word: "I'll text you", spainVariant: "Te mando un mensaje", latamVariant: "Te mando un mensaje", phoneticSpain: "[teh MAHN-do oon men-SAH-heh]", phoneticLatam: "[teh MAHN-do oon men-SAH-heh]", english: "I'll text you", partOfSpeech: "phrase", exampleSentenceSpain: "Te mando un mensaje cuando llego.", exampleSentenceLatam: "Te mando un WhatsApp en un rato." },
      { word: "WhatsApp me", spainVariant: "Mándame un WhatsApp", latamVariant: "Mándame un WhatsApp", phoneticSpain: "[MAHN-dah-meh oon WhatsApp]", phoneticLatam: "[MAHN-dah-meh oon WhatsApp]", english: "WhatsApp me", partOfSpeech: "phrase", exampleSentenceSpain: "Mándame un WhatsApp con tu dirección.", exampleSentenceLatam: "Mándame un WhatsApp ahorita." },
      { word: "What's up?", spainVariant: "¿Qué tal?", latamVariant: "¿Qué onda?", phoneticSpain: "[keh TAHL]", phoneticLatam: "[keh OHN-dah]", english: "What's up?", partOfSpeech: "phrase", exampleSentenceSpain: "¿Qué tal? ¿Cómo estás?", exampleSentenceLatam: "¿Qué onda? ¿Cómo va todo?" },
      { word: "Missed call", spainVariant: "Llamada perdida", latamVariant: "Llamada perdida", phoneticSpain: "[yah-MAH-dah per-DEE-dah]", phoneticLatam: "[yah-MAH-dah per-DEE-dah]", english: "Missed call", partOfSpeech: "noun", exampleSentenceSpain: "Me perdí una llamada tuya.", exampleSentenceLatam: "Tengo una llamada perdida de ti." },
      { word: "Call me", spainVariant: "Llámame", latamVariant: "Llámame", phoneticSpain: "[YAH-mah-meh]", phoneticLatam: "[YAH-mah-meh]", english: "Call me", partOfSpeech: "phrase", exampleSentenceSpain: "Llámame cuando puedas.", exampleSentenceLatam: "Llámame ahorita." },
      { word: "I'm calling you", spainVariant: "Te estoy llamando", latamVariant: "Te estoy llamando", phoneticSpain: "[teh es-TOY yah-MAHN-do]", phoneticLatam: "[teh es-TOY yah-MAHN-do]", english: "I'm calling you", partOfSpeech: "phrase", exampleSentenceSpain: "Te estoy llamando ahora.", exampleSentenceLatam: "Te estoy llamando en este momento." },
      { word: "One second", spainVariant: "Un segundo", latamVariant: "Un segundo", phoneticSpain: "[oon seh-GOON-do]", phoneticLatam: "[oon seh-GOON-do]", english: "One second", partOfSpeech: "phrase", exampleSentenceSpain: "Un segundo, que voy.", exampleSentenceLatam: "Ahorita me pongo, un momentito." },
      { word: "Hang up", spainVariant: "Colgar", latamVariant: "Colgar", phoneticSpain: "[kol-GAR]", phoneticLatam: "[kol-GAR]", english: "Hang up", partOfSpeech: "verb", exampleSentenceSpain: "Vamos a colgar, se corta la conexión.", exampleSentenceLatam: "Te cuelgo, la señal está mal." },
      { word: "Hold on", spainVariant: "Espera", latamVariant: "Espera", phoneticSpain: "[es-PEH-rah]", phoneticLatam: "[es-PEH-rah]", english: "Hold on", partOfSpeech: "interjection", exampleSentenceSpain: "Espera un momento.", exampleSentenceLatam: "Espera, que me pongo." },
    ],
  },
  "a2-06-weather": {
    title: "Weather & Seasons",
    description: "Chat about the weather, temperature, and seasons in natural Mexican Spanish",
    vocabulary: [
      { word: "Weather", spainVariant: "Clima", latamVariant: "Clima", phoneticSpain: "[KLEE-mah]", phoneticLatam: "[KLEE-mah]", english: "Weather", partOfSpeech: "noun", exampleSentenceSpain: "¿Qué tal el clima?", exampleSentenceLatam: "El clima está muy caluroso." },
      { word: "It's sunny", spainVariant: "Hace sol", latamVariant: "Hace sol", phoneticSpain: "[AH-seh sol]", phoneticLatam: "[AH-seh sol]", english: "It's sunny", partOfSpeech: "phrase", exampleSentenceSpain: "Hace mucho sol hoy.", exampleSentenceLatam: "Hace sol, está muy bonito." },
      { word: "It's rainy", spainVariant: "Llueve", latamVariant: "Llueve", phoneticSpain: "[YOO-EH-veh]", phoneticLatam: "[YOO-EH-veh]", english: "It's rainy", partOfSpeech: "phrase", exampleSentenceSpain: "Llueve mucho.", exampleSentenceLatam: "Está lloviendo." },
      { word: "It's cloudy", spainVariant: "Está nublado", latamVariant: "Está nublado", phoneticSpain: "[es-TAH noo-BLAH-do]", phoneticLatam: "[es-TAH noo-BLAH-do]", english: "It's cloudy", partOfSpeech: "phrase", exampleSentenceSpain: "Está muy nublado.", exampleSentenceLatam: "El cielo está nublado." },
      { word: "It's windy", spainVariant: "Hace viento", latamVariant: "Hace viento", phoneticSpain: "[AH-seh vee-EHN-to]", phoneticLatam: "[AH-seh vee-EHN-to]", english: "It's windy", partOfSpeech: "phrase", exampleSentenceSpain: "Hace mucho viento hoy.", exampleSentenceLatam: "Sopla el viento fuerte." },
      { word: "It's hot", spainVariant: "Hace calor", latamVariant: "Hace calor", phoneticSpain: "[AH-seh kah-LOR]", phoneticLatam: "[AH-seh kah-LOR]", english: "It's hot", partOfSpeech: "phrase", exampleSentenceSpain: "Hace mucho calor.", exampleSentenceLatam: "Está muy caluroso." },
      { word: "It's cold", spainVariant: "Hace frío", latamVariant: "Hace frío", phoneticSpain: "[AH-seh FREE-o]", phoneticLatam: "[AH-seh FREE-o]", english: "It's cold", partOfSpeech: "phrase", exampleSentenceSpain: "Hace frío esta mañana.", exampleSentenceLatam: "Está muy frío hoy." },
      { word: "Temperature", spainVariant: "Temperatura", latamVariant: "Temperatura", phoneticSpain: "[tem-peh-rah-TOO-rah]", phoneticLatam: "[tem-peh-rah-TOO-rah]", english: "Temperature", partOfSpeech: "noun", exampleSentenceSpain: "La temperatura es 25 grados.", exampleSentenceLatam: "¿Cuál es la temperatura?" },
      { word: "Degrees", spainVariant: "Grados", latamVariant: "Grados", phoneticSpain: "[GRAH-dos]", phoneticLatam: "[GRAH-dos]", english: "Degrees", partOfSpeech: "noun", exampleSentenceSpain: "Treinta grados Celsius.", exampleSentenceLatam: "Está a 28 grados." },
      { word: "Spring", spainVariant: "Primavera", latamVariant: "Primavera", phoneticSpain: "[pree-mah-VEH-rah]", phoneticLatam: "[pree-mah-VEH-rah]", english: "Spring", partOfSpeech: "noun", exampleSentenceSpain: "En primavera hay flores.", exampleSentenceLatam: "La primavera es mi estación favorita." },
      { word: "Summer", spainVariant: "Verano", latamVariant: "Verano", phoneticSpain: "[veh-RAH-no]", phoneticLatam: "[veh-RAH-no]", english: "Summer", partOfSpeech: "noun", exampleSentenceSpain: "En verano hace mucho calor.", exampleSentenceLatam: "El verano es muy caluroso aquí." },
      { word: "Autumn/Fall", spainVariant: "Otoño", latamVariant: "Otoño", phoneticSpain: "[o-TOH-nyoh]", phoneticLatam: "[o-TOH-nyoh]", english: "Autumn/Fall", partOfSpeech: "noun", exampleSentenceSpain: "En otoño caen las hojas.", exampleSentenceLatam: "El otoño es la mejor época." },
      { word: "Winter", spainVariant: "Invierno", latamVariant: "Invierno", phoneticSpain: "[in-vee-EHR-no]", phoneticLatam: "[in-vee-EHR-no]", english: "Winter", partOfSpeech: "noun", exampleSentenceSpain: "En invierno hace frío.", exampleSentenceLatam: "El invierno no es muy frío aquí." },
      { word: "Rain", spainVariant: "Lluvia", latamVariant: "Lluvia", phoneticSpain: "[YOO-vee-ah]", phoneticLatam: "[YOO-vee-ah]", english: "Rain", partOfSpeech: "noun", exampleSentenceSpain: "Hay mucha lluvia en junio.", exampleSentenceLatam: "La lluvia es refrescante." },
      { word: "Snow", spainVariant: "Nieve", latamVariant: "Nieve", phoneticSpain: "[nee-EH-veh]", phoneticLatam: "[nee-EH-veh]", english: "Snow", partOfSpeech: "noun", exampleSentenceSpain: "Nieva en las montañas.", exampleSentenceLatam: "Aquí no nieva casi nunca." },
      { word: "Wind", spainVariant: "Viento", latamVariant: "Viento", phoneticSpain: "[vee-EHN-to]", phoneticLatam: "[vee-EHN-to]", english: "Wind", partOfSpeech: "noun", exampleSentenceSpain: "El viento es fuerte hoy.", exampleSentenceLatam: "Sopla mucho viento." },
      { word: "Storm", spainVariant: "Tormenta", latamVariant: "Tormenta", phoneticSpain: "[tor-MEN-tah]", phoneticLatam: "[tor-MEN-tah]", english: "Storm", partOfSpeech: "noun", exampleSentenceSpain: "Hay una tormenta acercándose.", exampleSentenceLatam: "Se acerca una tormenta." },
      { word: "Humid", spainVariant: "Húmedo/a", latamVariant: "Húmedo/a", phoneticSpain: "[OO-meh-do]", phoneticLatam: "[OO-meh-do]", english: "Humid", partOfSpeech: "adjective", exampleSentenceSpain: "Está muy húmedo hoy.", exampleSentenceLatam: "La humedad es sofocante." },
      { word: "Dry", spainVariant: "Seco/a", latamVariant: "Seco/a", phoneticSpain: "[SEH-ko]", phoneticLatam: "[SEH-ko]", english: "Dry", partOfSpeech: "adjective", exampleSentenceSpain: "El clima es muy seco.", exampleSentenceLatam: "Hace mucho calor y está seco." },
      { word: "Forecast", spainVariant: "Pronóstico", latamVariant: "Pronóstico", phoneticSpain: "[pro-NOS-tee-ko]", phoneticLatam: "[pro-NOS-tee-ko]", english: "Forecast", partOfSpeech: "noun", exampleSentenceSpain: "Según el pronóstico lloverá.", exampleSentenceLatam: "El pronóstico dice que mañana llueve." },
    ],
  },
  "a2-07-work": {
    title: "Work & School",
    description: "Talk about your studies, homework, job, meetings, and coworkers in natural Mexican Spanish",
    vocabulary: [
      { word: "Work", spainVariant: "Trabajo", latamVariant: "Trabajo", phoneticSpain: "[trah-BAH-ho]", phoneticLatam: "[trah-BAH-ho]", english: "Work", partOfSpeech: "noun", exampleSentenceSpain: "Mi trabajo es interesante.", exampleSentenceLatam: "El trabajo está muy ocupado." },
      { word: "Job", spainVariant: "Empleo", latamVariant: "Empleo", phoneticSpain: "[em-PLEH-o]", phoneticLatam: "[em-PLEH-o]", english: "Job", partOfSpeech: "noun", exampleSentenceSpain: "Encontré un nuevo empleo.", exampleSentenceLatam: "¿Dónde trabajas? ¿Cuál es tu empleo?" },
      { word: "Boss", spainVariant: "Jefe", latamVariant: "Jefe", phoneticSpain: "[HEH-feh]", phoneticLatam: "[HEH-feh]", english: "Boss", partOfSpeech: "noun", exampleSentenceSpain: "Mi jefe es muy amable.", exampleSentenceLatam: "El jefe está en una reunión." },
      { word: "Coworker", spainVariant: "Compañero de trabajo", latamVariant: "Compañero de trabajo", phoneticSpain: "[kom-pahn-YEH-ro deh trah-BAH-ho]", phoneticLatam: "[kom-pahn-YEH-ro deh trah-BAH-ho]", english: "Coworker", partOfSpeech: "noun", exampleSentenceSpain: "Mis compañeros son simpáticos.", exampleSentenceLatam: "Mis compañeros me ayudan." },
      { word: "Office", spainVariant: "Oficina", latamVariant: "Oficina", phoneticSpain: "[o-fee-SEE-nah]", phoneticLatam: "[o-fee-SEE-nah]", english: "Office", partOfSpeech: "noun", exampleSentenceSpain: "La oficina está en el centro.", exampleSentenceLatam: "Trabajo en una oficina grande." },
      { word: "Meeting", spainVariant: "Reunión", latamVariant: "Junta", phoneticSpain: "[reh-oo-nee-OHN]", phoneticLatam: "[HOON-tah]", english: "Meeting", partOfSpeech: "noun", exampleSentenceSpain: "Tengo una reunión a las 3.", exampleSentenceLatam: "Hay junta con el cliente." },
      { word: "Email", spainVariant: "Correo electrónico", latamVariant: "Email", phoneticSpain: "[ko-REH-o eh-lek-TROH-nee-ko]", phoneticLatam: "[EE-mail]", english: "Email", partOfSpeech: "noun", exampleSentenceSpain: "Tengo muchos correos por responder.", exampleSentenceLatam: "Mándame un email con los detalles." },
      { word: "Project", spainVariant: "Proyecto", latamVariant: "Proyecto", phoneticSpain: "[pro-YHEK-to]", phoneticLatam: "[pro-YHEK-to]", english: "Project", partOfSpeech: "noun", exampleSentenceSpain: "Trabajo en un nuevo proyecto.", exampleSentenceLatam: "El proyecto termina pronto." },
      { word: "Deadline", spainVariant: "Plazo", latamVariant: "Plazo", phoneticSpain: "[PLAH-so]", phoneticLatam: "[PLAH-so]", english: "Deadline", partOfSpeech: "noun", exampleSentenceSpain: "El plazo es mañana.", exampleSentenceLatam: "Tenemos un plazo muy ajustado." },
      { word: "School", spainVariant: "Escuela", latamVariant: "Escuela", phoneticSpain: "[es-KWEH-lah]", phoneticLatam: "[es-KWEH-lah]", english: "School", partOfSpeech: "noun", exampleSentenceSpain: "Voy a la escuela cada día.", exampleSentenceLatam: "Estoy en la escuela." },
      { word: "University", spainVariant: "Universidad", latamVariant: "Universidad", phoneticSpain: "[oo-nee-ver-see-DAHD]", phoneticLatam: "[oo-nee-ver-see-DAHD]", english: "University", partOfSpeech: "noun", exampleSentenceSpain: "Estudio en la universidad.", exampleSentenceLatam: "Voy a la universidad." },
      { word: "Homework", spainVariant: "Deberes", latamVariant: "Tarea", phoneticSpain: "[deh-BEH-res]", phoneticLatam: "[tah-REH-ah]", english: "Homework", partOfSpeech: "noun", exampleSentenceSpain: "Tengo muchos deberes.", exampleSentenceLatam: "¿Hiciste la tarea?" },
      { word: "Test/Exam", spainVariant: "Examen", latamVariant: "Examen", phoneticSpain: "[ehk-SAH-men]", phoneticLatam: "[ehk-SAH-men]", english: "Test/Exam", partOfSpeech: "noun", exampleSentenceSpain: "Tengo un examen mañana.", exampleSentenceLatam: "Me va el examen bien." },
      { word: "Subject", spainVariant: "Asignatura", latamVariant: "Materia", phoneticSpain: "[ah-sig-nah-TOO-rah]", phoneticLatam: "[mah-TEH-ree-ah]", english: "Subject", partOfSpeech: "noun", exampleSentenceSpain: "Mi asignatura favorita es historia.", exampleSentenceLatam: "¿Cuál es tu materia favorita?" },
      { word: "Salary", spainVariant: "Salario", latamVariant: "Salario", phoneticSpain: "[sah-LAH-ree-o]", phoneticLatam: "[sah-LAH-ree-o]", english: "Salary", partOfSpeech: "noun", exampleSentenceSpain: "El salario es justo.", exampleSentenceLatam: "El salario es bueno aquí." },
      { word: "Promotion", spainVariant: "Ascenso", latamVariant: "Promoción", phoneticSpain: "[ahs-SEN-so]", phoneticLatam: "[pro-mo-see-OHN]", english: "Promotion", partOfSpeech: "noun", exampleSentenceSpain: "Me ofrecieron un ascenso.", exampleSentenceLatam: "Espero una promoción pronto." },
      { word: "Vacation", spainVariant: "Vacaciones", latamVariant: "Vacaciones", phoneticSpain: "[vah-kah-see-OHN-es]", phoneticLatam: "[vah-kah-see-OHN-es]", english: "Vacation", partOfSpeech: "noun", exampleSentenceSpain: "Tengo una semana de vacaciones.", exampleSentenceLatam: "Voy de vacaciones en julio." },
      { word: "Busy", spainVariant: "Ocupado/a", latamVariant: "Ocupado/a", phoneticSpain: "[o-koo-PAH-do]", phoneticLatam: "[o-koo-PAH-do]", english: "Busy", partOfSpeech: "adjective", exampleSentenceSpain: "Estoy muy ocupado esta semana.", exampleSentenceLatam: "He estado muy ocupado en el trabajo." },
      { word: "Tired", spainVariant: "Cansado/a", latamVariant: "Cansado/a", phoneticSpain: "[kahn-SAH-do]", phoneticLatam: "[kahn-SAH-do]", english: "Tired", partOfSpeech: "adjective", exampleSentenceSpain: "Estoy muy cansado del trabajo.", exampleSentenceLatam: "Me siento agotado/a." },
      { word: "Stressed", spainVariant: "Estresado/a", latamVariant: "Estresado/a", phoneticSpain: "[es-treh-SAH-do]", phoneticLatam: "[es-treh-SAH-do]", english: "Stressed", partOfSpeech: "adjective", exampleSentenceSpain: "Estoy estresado por el proyecto.", exampleSentenceLatam: "Ando muy estresado/a." },
    ],
  },
  "a2-08-emotions": {
    title: "Emotions & Feelings",
    description: "Express how you feel and check in on others—from happy and excited to worried and stressed",
    vocabulary: [
      { word: "Happy", spainVariant: "Feliz", latamVariant: "Feliz", phoneticSpain: "[feh-LEES]", phoneticLatam: "[feh-LEES]", english: "Happy", partOfSpeech: "adjective", exampleSentenceSpain: "Estoy muy feliz hoy.", exampleSentenceLatam: "Me siento feliz." },
      { word: "Sad", spainVariant: "Triste", latamVariant: "Triste", phoneticSpain: "[TRIS-teh]", phoneticLatam: "[TRIS-teh]", english: "Sad", partOfSpeech: "adjective", exampleSentenceSpain: "Me siento triste.", exampleSentenceLatam: "Estoy un poco triste hoy." },
      { word: "Excited", spainVariant: "Emocionado/a", latamVariant: "Emocionado/a", phoneticSpain: "[eh-mo-see-o-NAH-do]", phoneticLatam: "[eh-mo-see-o-NAH-do]", english: "Excited", partOfSpeech: "adjective", exampleSentenceSpain: "¡Estoy emocionado de las vacaciones!", exampleSentenceLatam: "¡Qué emoción!" },
      { word: "Nervous", spainVariant: "Nervioso/a", latamVariant: "Nervioso/a", phoneticSpain: "[ner-vee-OH-so]", phoneticLatam: "[ner-vee-OH-so]", english: "Nervous", partOfSpeech: "adjective", exampleSentenceSpain: "Estoy nervioso por la entrevista.", exampleSentenceLatam: "Me pone nervioso/a." },
      { word: "Worried", spainVariant: "Preocupado/a", latamVariant: "Preocupado/a", phoneticSpain: "[preh-o-koo-PAH-do]", phoneticLatam: "[preh-o-koo-PAH-do]", english: "Worried", partOfSpeech: "adjective", exampleSentenceSpain: "Estoy preocupado por mi hermano.", exampleSentenceLatam: "Me preocupa la situación." },
      { word: "Angry", spainVariant: "Enfadado/a", latamVariant: "Enojado/a", phoneticSpain: "[en-fah-DAH-do]", phoneticLatam: "[eh-no-HAH-do]", english: "Angry", partOfSpeech: "adjective", exampleSentenceSpain: "Estoy enfadado contigo.", exampleSentenceLatam: "Estoy enojado/a." },
      { word: "Confused", spainVariant: "Confundido/a", latamVariant: "Confundido/a", phoneticSpain: "[kon-foon-DEE-do]", phoneticLatam: "[kon-foon-DEE-do]", english: "Confused", partOfSpeech: "adjective", exampleSentenceSpain: "Estoy confundido.", exampleSentenceLatam: "No entiendo, estoy confundido/a." },
      { word: "Surprised", spainVariant: "Sorprendido/a", latamVariant: "Sorprendido/a", phoneticSpain: "[sor-pren-DEE-do]", phoneticLatam: "[sor-pren-DEE-do]", english: "Surprised", partOfSpeech: "adjective", exampleSentenceSpain: "¡Estoy sorprendido!", exampleSentenceLatam: "¡Qué sorpresa!" },
      { word: "Tired", spainVariant: "Cansado/a", latamVariant: "Cansado/a", phoneticSpain: "[kahn-SAH-do]", phoneticLatam: "[kahn-SAH-do]", english: "Tired", partOfSpeech: "adjective", exampleSentenceSpain: "Estoy muy cansado.", exampleSentenceLatam: "Me siento agotado/a." },
      { word: "Frustrated", spainVariant: "Frustrado/a", latamVariant: "Frustrado/a", phoneticSpain: "[frus-TRAH-do]", phoneticLatam: "[frus-TRAH-do]", english: "Frustrated", partOfSpeech: "adjective", exampleSentenceSpain: "Estoy frustrado con esto.", exampleSentenceLatam: "Me siento frustrado/a." },
      { word: "Proud", spainVariant: "Orgulloso/a", latamVariant: "Orgulloso/a", phoneticSpain: "[or-goo-YOH-so]", phoneticLatam: "[or-goo-YOH-so]", english: "Proud", partOfSpeech: "adjective", exampleSentenceSpain: "Estoy orgulloso de mi trabajo.", exampleSentenceLatam: "Me siento orgulloso/a." },
      { word: "Grateful", spainVariant: "Agradecido/a", latamVariant: "Agradecido/a", phoneticSpain: "[ah-grah-deh-SEE-do]", phoneticLatam: "[ah-grah-deh-SEE-do]", english: "Grateful", partOfSpeech: "adjective", exampleSentenceSpain: "Estoy muy agradecido.", exampleSentenceLatam: "Te estoy muy agradecido/a." },
      { word: "Lonely", spainVariant: "Solo/a", latamVariant: "Solo/a", phoneticSpain: "[SOH-lo]", phoneticLatam: "[SOH-lo]", english: "Lonely", partOfSpeech: "adjective", exampleSentenceSpain: "Me siento solo/a.", exampleSentenceLatam: "Estoy solo/a y triste." },
      { word: "Hopeful", spainVariant: "Esperanzado/a", latamVariant: "Esperanzado/a", phoneticSpain: "[es-peh-rahn-SAH-do]", phoneticLatam: "[es-peh-rahn-SAH-do]", english: "Hopeful", partOfSpeech: "adjective", exampleSentenceSpain: "Estoy esperanzado en el futuro.", exampleSentenceLatam: "Tengo esperanza." },
      { word: "Disappointed", spainVariant: "Decepcionado/a", latamVariant: "Decepcionado/a", phoneticSpain: "[deh-sep-see-o-NAH-do]", phoneticLatam: "[deh-sep-see-o-NAH-do]", english: "Disappointed", partOfSpeech: "adjective", exampleSentenceSpain: "Estoy decepcionado.", exampleSentenceLatam: "Me siento decepcionado/a." },
      { word: "Calm", spainVariant: "Tranquilo/a", latamVariant: "Tranquilo/a", phoneticSpain: "[trahn-KEE-lo]", phoneticLatam: "[trahn-KEE-lo]", english: "Calm", partOfSpeech: "adjective", exampleSentenceSpain: "Mantente tranquilo.", exampleSentenceLatam: "Está muy tranquilo/a." },
      { word: "Relaxed", spainVariant: "Relajado/a", latamVariant: "Relajado/a", phoneticSpain: "[reh-lah-HAH-do]", phoneticLatam: "[reh-lah-HAH-do]", english: "Relaxed", partOfSpeech: "adjective", exampleSentenceSpain: "Me siento relajado.", exampleSentenceLatam: "Estoy muy relajado/a." },
      { word: "Anxious", spainVariant: "Ansioso/a", latamVariant: "Ansioso/a", phoneticSpain: "[ahn-see-OH-so]", phoneticLatam: "[ahn-see-OH-so]", english: "Anxious", partOfSpeech: "adjective", exampleSentenceSpain: "Estoy ansioso por empezar.", exampleSentenceLatam: "Tengo ansias de verte." },
      { word: "Afraid", spainVariant: "Asustado/a", latamVariant: "Asustado/a", phoneticSpain: "[ah-sus-TAH-do]", phoneticLatam: "[ah-sus-TAH-do]", english: "Afraid", partOfSpeech: "adjective", exampleSentenceSpain: "No tengas miedo.", exampleSentenceLatam: "Tengo miedo." },
      { word: "Bored", spainVariant: "Aburrido/a", latamVariant: "Aburrido/a", phoneticSpain: "[ah-boo-REE-do]", phoneticLatam: "[ah-boo-REE-do]", english: "Bored", partOfSpeech: "adjective", exampleSentenceSpain: "Me aburre esto.", exampleSentenceLatam: "Estoy aburrido/a." },
    ],
  },
  "a2-09-fillers": {
    title: "Mexican Fillers & Conversation Builders",
    description: "Sound natural and buy yourself time with the fillers and connectors Mexicans use",
    vocabulary: [
      { word: "Well...", spainVariant: "Pues...", latamVariant: "Pues...", phoneticSpain: "[pwes]", phoneticLatam: "[pwes]", english: "Well...", partOfSpeech: "interjection", exampleSentenceSpain: "Pues, no estoy seguro.", exampleSentenceLatam: "Pues mira, es complicado." },
      { word: "I mean...", spainVariant: "O sea...", latamVariant: "O sea...", phoneticSpain: "[o SEH-ah]", phoneticLatam: "[o SEH-ah]", english: "I mean...", partOfSpeech: "phrase", exampleSentenceSpain: "O sea, no es difícil.", exampleSentenceLatam: "O sea, ya ves." },
      { word: "Like...", spainVariant: "Así que...", latamVariant: "Así que...", phoneticSpain: "[ah-SEE keh]", phoneticLatam: "[ah-SEE keh]", english: "Like...", partOfSpeech: "phrase", exampleSentenceSpain: "Así que voy a hacerlo.", exampleSentenceLatam: "Así que me decidí." },
      { word: "Kind of...", spainVariant: "Más o menos...", latamVariant: "Más o menos...", phoneticSpain: "[mas o MEH-nos]", phoneticLatam: "[mas o MEH-nos]", english: "Kind of...", partOfSpeech: "phrase", exampleSentenceSpain: "Más o menos, estoy de acuerdo.", exampleSentenceLatam: "Más o menos, así es." },
      { word: "You know?", spainVariant: "¿Sabes?", latamVariant: "¿Sabes?", phoneticSpain: "[SAH-bes]", phoneticLatam: "[SAH-bes]", english: "You know?", partOfSpeech: "phrase", exampleSentenceSpain: "Es difícil, ¿sabes?", exampleSentenceLatam: "¿Sabes lo que te quiero decir?" },
      { word: "I don't know...", spainVariant: "No sé...", latamVariant: "No sé...", phoneticSpain: "[no seh]", phoneticLatam: "[no seh]", english: "I don't know...", partOfSpeech: "phrase", exampleSentenceSpain: "No sé, tal vez mañana.", exampleSentenceLatam: "No sé, primero déjame pensar." },
      { word: "Maybe...", spainVariant: "Quizá...", latamVariant: "Quizá...", phoneticSpain: "[kee-SAH]", phoneticLatam: "[kee-SAH]", english: "Maybe...", partOfSpeech: "phrase", exampleSentenceSpain: "Quizá vaya.", exampleSentenceLatam: "Quizá después." },
      { word: "Um...", spainVariant: "Ehm...", latamVariant: "Ehm...", phoneticSpain: "[em]", phoneticLatam: "[em]", english: "Um...", partOfSpeech: "interjection", exampleSentenceSpain: "Ehm, déjame pensar.", exampleSentenceLatam: "Ehm, buena pregunta." },
      { word: "But anyway...", spainVariant: "Pero bueno...", latamVariant: "Pero bueno...", phoneticSpain: "[PEH-ro boo-EH-no]", phoneticLatam: "[PEH-ro boo-EH-no]", english: "But anyway...", partOfSpeech: "phrase", exampleSentenceSpain: "Pero bueno, qué se le va a hacer.", exampleSentenceLatam: "Pero bueno, así es la vida." },
      { word: "By the way...", spainVariant: "Por cierto...", latamVariant: "Por cierto...", phoneticSpain: "[por see-EHR-to]", phoneticLatam: "[por see-EHR-to]", english: "By the way...", partOfSpeech: "phrase", exampleSentenceSpain: "Por cierto, ¿viste al jefe?", exampleSentenceLatam: "Por cierto, María preguntaba por ti." },
      { word: "Speaking of which...", spainVariant: "Hablando de eso...", latamVariant: "Hablando de eso...", phoneticSpain: "[ah-BLAHN-do deh EH-so]", phoneticLatam: "[ah-BLAHN-do deh EH-so]", english: "Speaking of which...", partOfSpeech: "phrase", exampleSentenceSpain: "Hablando de eso, ¿cómo estuvo?", exampleSentenceLatam: "Hablando de eso, me pasó algo." },
      { word: "Actually...", spainVariant: "Actualmente...", latamVariant: "Actualmente...", phoneticSpain: "[ahk-too-ahl-MEN-teh]", phoneticLatam: "[ahk-too-ahl-MEN-teh]", english: "Actually...", partOfSpeech: "phrase", exampleSentenceSpain: "Actualmente, no tengo tiempo.", exampleSentenceLatam: "Actualmente estoy muy ocupado." },
      { word: "In fact...", spainVariant: "De hecho...", latamVariant: "De hecho...", phoneticSpain: "[deh EH-cho]", phoneticLatam: "[deh EH-cho]", english: "In fact...", partOfSpeech: "phrase", exampleSentenceSpain: "De hecho, tienes razón.", exampleSentenceLatam: "De hecho, creo que sí." },
      { word: "Basically...", spainVariant: "Básicamente...", latamVariant: "Básicamente...", phoneticSpain: "[bah-see-kah-MEN-teh]", phoneticLatam: "[bah-see-kah-MEN-teh]", english: "Basically...", partOfSpeech: "phrase", exampleSentenceSpain: "Básicamente, no me gusta.", exampleSentenceLatam: "Básicamente, así es." },
      { word: "You see...", spainVariant: "Ves...", latamVariant: "Ves...", phoneticSpain: "[ves]", phoneticLatam: "[ves]", english: "You see...", partOfSpeech: "phrase", exampleSentenceSpain: "Ves, por eso no vinieron.", exampleSentenceLatam: "Ves, te lo dije." },
      { word: "It seems to me...", spainVariant: "Me parece...", latamVariant: "Me parece...", phoneticSpain: "[meh pah-REH-seh]", phoneticLatam: "[meh pah-REH-seh]", english: "It seems to me...", partOfSpeech: "phrase", exampleSentenceSpain: "Me parece que es una buena idea.", exampleSentenceLatam: "Me parece que tienes razón." },
      { word: "So then...", spainVariant: "Entonces...", latamVariant: "Entonces...", phoneticSpain: "[en-TON-ses]", phoneticLatam: "[en-TON-ses]", english: "So then...", partOfSpeech: "phrase", exampleSentenceSpain: "Entonces decidimos irmos.", exampleSentenceLatam: "Entonces me fui." },
      { word: "And then...", spainVariant: "Y luego...", latamVariant: "Y después...", phoneticSpain: "[ee loo-EH-go]", phoneticLatam: "[ee DEHS-pwehs]", english: "And then...", partOfSpeech: "phrase", exampleSentenceSpain: "Y luego vinieron mis amigos.", exampleSentenceLatam: "Y después llegó mi mamá." },
      { word: "On the other hand...", spainVariant: "Por otro lado...", latamVariant: "Por otro lado...", phoneticSpain: "[por OH-tro LAH-do]", phoneticLatam: "[por OH-tro LAH-do]", english: "On the other hand...", partOfSpeech: "phrase", exampleSentenceSpain: "Por otro lado, es caro.", exampleSentenceLatam: "Por otro lado, valía la pena." },
      { word: "All in all...", spainVariant: "En fin...", latamVariant: "En fin...", phoneticSpain: "[en FEEN]", phoneticLatam: "[en FEEN]", english: "All in all...", partOfSpeech: "phrase", exampleSentenceSpain: "En fin, fue un buen viaje.", exampleSentenceLatam: "En fin, así es la vida." },
    ],
  },
  "a2-10-expressions": {
    title: "Everyday Mexican Expressions",
    description: "The classic go-to phrases and reactions you'll hear all day in Mexico",
    vocabulary: [
      { word: "Right on!", spainVariant: "¡Órale!", latamVariant: "¡Órale!", phoneticSpain: "[OH-rah-leh]", phoneticLatam: "[OH-rah-leh]", english: "Right on!", partOfSpeech: "interjection", exampleSentenceSpain: "¡Órale, qué noticias!", exampleSentenceLatam: "¡Órale, eso es!" },
      { word: "Go on!", spainVariant: "¡Va!", latamVariant: "¡Ándale!", phoneticSpain: "[vah]", phoneticLatam: "[AHN-dah-leh]", english: "Go on!", partOfSpeech: "interjection", exampleSentenceSpain: "¡Va, vamos rápido!", exampleSentenceLatam: "¡Ándale, apúrate!" },
      { word: "Come on!", spainVariant: "¡Anda!", latamVariant: "¡Ándale!", phoneticSpain: "[AHN-dah]", phoneticLatam: "[AHN-dah-leh]", english: "Come on!", partOfSpeech: "interjection", exampleSentenceSpain: "¡Anda, no seas así!", exampleSentenceLatam: "¡Ándale, que se hace tarde!" },
      { word: "No way!", spainVariant: "¡Ni modo!", latamVariant: "¡Ni modo!", phoneticSpain: "[nee MOH-do]", phoneticLatam: "[nee MOH-do]", english: "No way!", partOfSpeech: "interjection", exampleSentenceSpain: "Ni modo, tengo que irme.", exampleSentenceLatam: "¡Ni modo, qué lástima!" },
      { word: "That's too bad", spainVariant: "Qué lástima", latamVariant: "Qué lástima", phoneticSpain: "[keh LAHS-tee-mah]", phoneticLatam: "[keh LAHS-tee-mah]", english: "That's too bad", partOfSpeech: "phrase", exampleSentenceSpain: "Qué lástima que no puedas ir.", exampleSentenceLatam: "Qué lástima, hubiera estado bien." },
      { word: "How cool!", spainVariant: "¡Qué bien!", latamVariant: "¡Qué cool!", phoneticSpain: "[keh bee-EHN]", phoneticLatam: "[keh KOOL]", english: "How cool!", partOfSpeech: "interjection", exampleSentenceSpain: "¡Qué bien, me encanta!", exampleSentenceLatam: "¡Qué cool, eso mola!" },
      { word: "Perfect!", spainVariant: "¡Perfecto!", latamVariant: "¡Perfecto!", phoneticSpain: "[per-FEK-to]", phoneticLatam: "[per-FEK-to]", english: "Perfect!", partOfSpeech: "interjection", exampleSentenceSpain: "¡Perfecto, así está bien!", exampleSentenceLatam: "¡Perfecto, te veo mañana!" },
      { word: "Exactly!", spainVariant: "¡Exacto!", latamVariant: "¡Exacto!", phoneticSpain: "[ehk-SAHK-to]", phoneticLatam: "[ehk-SAHK-to]", english: "Exactly!", partOfSpeech: "interjection", exampleSentenceSpain: "¡Exacto, eso es!", exampleSentenceLatam: "¡Exactamente, tienes razón!" },
      { word: "Of course!", spainVariant: "¡Claro!", latamVariant: "¡Claro!", phoneticSpain: "[KLAH-ro]", phoneticLatam: "[KLAH-ro]", english: "Of course!", partOfSpeech: "interjection", exampleSentenceSpain: "¡Claro que sí!", exampleSentenceLatam: "¡Claro, sin problema!" },
      { word: "No problem", spainVariant: "Sin problema", latamVariant: "Sin problema", phoneticSpain: "[seen pro-BLEH-mah]", phoneticLatam: "[seen pro-BLEH-mah]", english: "No problem", partOfSpeech: "phrase", exampleSentenceSpain: "Sin problema, lo haré.", exampleSentenceLatam: "Sin problema, lo puedo hacer." },
      { word: "All good", spainVariant: "Está todo bien", latamVariant: "Está todo bien", phoneticSpain: "[es-TAH TOH-do bee-EHN]", phoneticLatam: "[es-TAH TOH-do bee-EHN]", english: "All good", partOfSpeech: "phrase", exampleSentenceSpain: "Está todo bien, tranquilo.", exampleSentenceLatam: "Está todo bien, no te preocupes." },
      { word: "That's it!", spainVariant: "¡Eso es!", latamVariant: "¡Eso es!", phoneticSpain: "[EH-so es]", phoneticLatam: "[EH-so es]", english: "That's it!", partOfSpeech: "interjection", exampleSentenceSpain: "¡Eso es, así quería!", exampleSentenceLatam: "¡Eso es, acabaste!" },
      { word: "I'm dying!", spainVariant: "¡Me muero!", latamVariant: "¡Me muero!", phoneticSpain: "[meh moo-EH-ro]", phoneticLatam: "[meh moo-EH-ro]", english: "I'm dying!", partOfSpeech: "phrase", exampleSentenceSpain: "¡Me muero de risa!", exampleSentenceLatam: "¡Me muero de hambre!" },
      { word: "No way!", spainVariant: "¿De verdad?", latamVariant: "¿De verdad?", phoneticSpain: "[deh ver-DAHD]", phoneticLatam: "[deh ver-DAHD]", english: "No way!", partOfSpeech: "phrase", exampleSentenceSpain: "¿De verdad? ¡No lo puedo creer!", exampleSentenceLatam: "¿De verdad? ¡Qué loco!" },
      { word: "No kidding!", spainVariant: "¡Sin bromas!", latamVariant: "¡Sin bromas!", phoneticSpain: "[seen BRO-mas]", phoneticLatam: "[seen BRO-mas]", english: "No kidding!", partOfSpeech: "interjection", exampleSentenceSpain: "¡Sin bromas, en serio?", exampleSentenceLatam: "¡Sin bromas, pasó en verdad!" },
      { word: "For real?", spainVariant: "¿En serio?", latamVariant: "¿En serio?", phoneticSpain: "[en SEH-ree-o]", phoneticLatam: "[en SEH-ree-o]", english: "For real?", partOfSpeech: "phrase", exampleSentenceSpain: "¿En serio, te lo prometo?", exampleSentenceLatam: "¿En serio, no estás bromeando?" },
      { word: "You're lying!", spainVariant: "¡Me tomas el pelo!", latamVariant: "¡Me estás mintiendo!", phoneticSpain: "[meh TOH-mas el PEH-lo]", phoneticLatam: "[meh es-TAHS min-tee-EHN-do]", english: "You're lying!", partOfSpeech: "phrase", exampleSentenceSpain: "¡Me tomas el pelo, eso no es verdad!", exampleSentenceLatam: "¡Me estás mintiendo, ¡imposible!" },
      { word: "No way in hell!", spainVariant: "¡Qué va!", latamVariant: "¡Qué va!", phoneticSpain: "[keh vah]", phoneticLatam: "[keh vah]", english: "No way in hell!", partOfSpeech: "interjection", exampleSentenceSpain: "¡Qué va, eso nunca!", exampleSentenceLatam: "¡Qué va, ni hablar!" },
      { word: "Bro/Dude", spainVariant: "Tío", latamVariant: "Hermano/Compa", phoneticSpain: "[TEE-o]", phoneticLatam: "[er-MAH-no / KOM-pah]", english: "Bro/Dude", partOfSpeech: "noun", exampleSentenceSpain: "¡Tío, cómo estás!", exampleSentenceLatam: "¡Hermano, qué paso!" },
      { word: "My friend", spainVariant: "Colega", latamVariant: "Cuate", phoneticSpain: "[ko-LEH-gah]", phoneticLatam: "[KWAH-teh]", english: "My friend", partOfSpeech: "noun", exampleSentenceSpain: "Ey colega, ¿vamos?", exampleSentenceLatam: "Oye cuate, ¿qué tal?" },
    ],
  },
};

function buildA2Lesson(slug: string): LessonData {
  const lessonDef = A2_LESSONS[slug as keyof typeof A2_LESSONS];
  if (!lessonDef) {
    throw new Error(`A2 lesson ${slug} not found`);
  }

  const slughyphen = slug.split("-");
  const order = parseInt(slughyphen[2]) || 1;

  const grammarSection: GrammarItem[] = [
    {
      title: "Present Tense & Informal You",
      spainContent: `Spain uses "tú" for informal address. Example: "¿Tú hablas español?" (Do you speak Spanish?)`,
      latamContent: `Latin America also uses "tú" but with slightly different conjugations in some regions. Example: "¿Vos hablas español?" (Some regions use vos instead of tú).`,
      note: "Most of Mexico uses 'tú' like Spain, but be aware regional variations exist.",
    },
    {
      title: `${lessonDef.title} Grammar`,
      spainContent: `Key structures for ${lessonDef.title} in Peninsular Spanish with authentic usage examples.`,
      latamContent: `Key structures for ${lessonDef.title} in Mexican/Latin American Spanish reflecting natural speech patterns.`,
      note: "Pay attention to verb forms and how they're used naturally in context.",
    },
  ];

  const dialogues: DialogueScenario[] = [];

  for (let i = 0; i < 3; i++) {
    dialogues.push({
      id: `dialogue-spain-${i + 1}`,
      title: `${lessonDef.title} - Scene ${i + 1} (Spain)`,
      region: "SPAIN",
      setting: `Madrid/Barcelona setting for ${lessonDef.title}`,
      lines: [
        { speaker: "Ana", text: lessonDef.vocabulary[i]?.exampleSentenceSpain || `Hola, ¿qué tal? (Spain ${i + 1})`, region: "SPAIN", setting: `Madrid/Barcelona setting for ${lessonDef.title}` },
        { speaker: "Carlos", text: lessonDef.vocabulary[(i + 1) % lessonDef.vocabulary.length]?.exampleSentenceSpain || `¡Muy bien! (Spain ${i + 1})`, region: "SPAIN", setting: `Madrid/Barcelona setting for ${lessonDef.title}` },
        { speaker: "Ana", text: `Qué bueno. (Spain ${i + 1})`, region: "SPAIN", setting: `Madrid/Barcelona setting for ${lessonDef.title}` },
      ],
    });
  }

  for (let i = 0; i < 3; i++) {
    dialogues.push({
      id: `dialogue-latam-${i + 1}`,
      title: `${lessonDef.title} - Scene ${i + 1} (Mexico)`,
      region: "LATAM",
      setting: `Mexico City/Guadalajara setting for ${lessonDef.title}`,
      lines: [
        { speaker: "María", text: lessonDef.vocabulary[i]?.exampleSentenceLatam || `¡Hola, qué onda! (Mexico ${i + 1})`, region: "LATAM", setting: `Mexico City/Guadalajara setting for ${lessonDef.title}` },
        { speaker: "Diego", text: lessonDef.vocabulary[(i + 1) % lessonDef.vocabulary.length]?.exampleSentenceLatam || `¡Muy bien! (Mexico ${i + 1})`, region: "LATAM", setting: `Mexico City/Guadalajara setting for ${lessonDef.title}` },
        { speaker: "María", text: `Qué bueno saber. (Mexico ${i + 1})`, region: "LATAM", setting: `Mexico City/Guadalajara setting for ${lessonDef.title}` },
      ],
    });
  }

  const quiz: QuizQuestion[] = [
    {
      questionId: "q1",
      type: "multiple-choice",
      questionText: `Which is a common Mexican expression meaning "I can't do it"?`,
      options: ["Ni modo", "Puede ser", "Está bien", "Qué tal"],
      correctAnswer: "Ni modo",
      explanation: "'Ni modo' is a very Mexican expression meaning 'There's nothing to be done' or 'I can't help it'. It expresses resignation or impossibility.",
    },
    {
      questionId: "q2",
      type: "multiple-choice",
      questionText: `What does "Qué onda" mean in Mexican Spanish?`,
      options: ["What's wrong?", "What's up?", "What happened?", "What do you think?"],
      correctAnswer: "What's up?",
      explanation: "'Qué onda' is a very casual, friendly Mexican greeting meaning 'What's up?' It's used all the time in Mexico.",
    },
    {
      questionId: "q3",
      type: "multiple-choice",
      questionText: `Which word means "dude/bro" in Mexico?`,
      options: ["Compa", "Tío", "Amigo", "Hermano"],
      correctAnswer: "Compa",
      explanation: "'Compa' is very Mexican slang for a close friend or 'dude'. 'Tío' is more Spanish/European.",
    },
    {
      questionId: "q4",
      type: "multiple-choice",
      questionText: `What's the Mexican word for 'task/homework'?`,
      options: ["Deberes", "Tarea", "Trabajo", "Lección"],
      correctAnswer: "Tarea",
      explanation: "In Mexico, 'tarea' is used for homework or a task. In Spain, 'deberes' is more common for homework specifically.",
    },
    {
      questionId: "q5",
      type: "multiple-choice",
      questionText: `What does 'Cuate' mean?`,
      options: ["Friend", "Brother", "Coworker", "Family"],
      correctAnswer: "Friend",
      explanation: "'Cuate' is very Mexican slang for a close friend, similar to 'compa' or 'hermano'. It's very commonly used.",
    },
  ];

  const flashcards: FlashcardItem[] = lessonDef.vocabulary.slice(0, 20).map((v, idx) => ({
    id: `fc-${slug}-${idx + 1}`,
    frontSpain: v.spainVariant,
    frontLatam: v.latamVariant,
    backEnglish: v.english,
    variantDifferenceNote: v.spainVariant !== v.latamVariant ? `Spain: "${v.spainVariant}", Mexico: "${v.latamVariant}"` : "Same in both regions",
    exampleSentenceSpain: v.exampleSentenceSpain || "",
    exampleSentenceLatam: v.exampleSentenceLatam || "",
    partOfSpeech: v.partOfSpeech,
  }));

  return {
    id: `lesson-${slug}`,
    slug,
    title: lessonDef.title,
    description: lessonDef.description,
    level: "A2",
    difficulty: "ELEMENTARY",
    order,
    imageUrl: null,
    durationMinutes: 20,
    isPublished: true,
    vocabularyTable: lessonDef.vocabulary.slice(0, 20),
    grammarSection,
    dialogues,
    quiz,
    flashcards,
    vocabularyJson: lessonDef.vocabulary.slice(0, 20).map((v) => ({
      word: v.word,
      translation: `${v.spainVariant} / ${v.latamVariant}`,
      partOfSpeech: v.partOfSpeech,
      example: v.exampleSentenceSpain,
    })),
    grammarJson: grammarSection.map((g) => ({
      title: g.title,
      content: `${g.spainContent} | ${g.latamContent}`,
    })),
    content: `# ${lessonDef.title}\n\n${lessonDef.description}\n\nThis comprehensive A2 lesson covers conversational vocabulary, natural grammar patterns, regional expressions, and interactive practice. Master the vocabulary table, study grammar patterns, review authentic dialogues, and test yourself with the quiz.`,
  };
}

export function generateA2Lessons(): LessonData[] {
  const a2Slugs = Object.keys(A2_LESSONS);
  return a2Slugs.map((slug) => buildA2Lesson(slug));
}