import type { LessonData, RegionalVocabItem, GrammarItem, DialogueScenario, QuizQuestion, FlashcardItem } from "./lessons-data";

const B2_LESSONS = {
  "b2-01-everyday-slang": {
    title: "Everyday Slang",
    description: "The everyday slang Mexicans really use—chido, chamba, lana, and more",
    vocabulary: [
      { word: "Cool/Great", spainVariant: "Guay/Chulo", latamVariant: "Chido/Padre", phoneticSpain: "[gwye/CHOO-lo]", phoneticLatam: "[CHEE-do/PAH-dreh]", english: "Cool/Great", partOfSpeech: "adjective", exampleSentenceSpain: "¡Eso es guay!", exampleSentenceLatam: "¡Qué padre!" },
      { word: "Money/Cash", spainVariant: "Pasta/Guita", latamVariant: "Lana/Pisto", phoneticSpain: "[PAS-tah/GEE-tah]", phoneticLatam: "[LAH-nah/PEES-to]", english: "Money/Cash", partOfSpeech: "noun", exampleSentenceSpain: "No tengo pasta.", exampleSentenceLatam: "Me falta lana." },
      { word: "Job/Work", spainVariant: "Curro/Laburo", latamVariant: "Chamba/Chambita", phoneticSpain: "[KOO-rro/lah-BOO-ro]", phoneticLatam: "[CHAHM-bah]", english: "Job/Work", partOfSpeech: "noun", exampleSentenceSpain: "Tengo un curro nuevo.", exampleSentenceLatam: "Conseguí una chamba." },
      { word: "Tired", spainVariant: "Reventado", latamVariant: "Cansado/Muerto", phoneticSpain: "[reh-ven-TAH-do]", phoneticLatam: "[kahn-SAH-do/moo-EHR-to]", english: "Tired", partOfSpeech: "adjective", exampleSentenceSpain: "Estoy reventado.", exampleSentenceLatam: "Estoy muerto de cansancio." },
      { word: "Stupid/Silly", spainVariant: "Tonto/Bobo", latamVariant: "Pendejo/Baboso", phoneticSpain: "[TON-to/BOH-bo]", phoneticLatam: "[pen-DEH-ho/bah-BOH-so]", english: "Stupid/Silly", partOfSpeech: "adjective", exampleSentenceSpain: "Eres un tonto.", exampleSentenceLatam: "No seas pendejo." },
      { word: "Liar", spainVariant: "Mentiroso", latamVariant: "Mentiroso", phoneticSpain: "[men-tee-ROH-so]", phoneticLatam: "[men-tee-ROH-so]", english: "Liar", partOfSpeech: "noun", exampleSentenceSpain: "¡Qué mentiroso eres!", exampleSentenceLatam: "Eres un mentiroso." },
      { word: "Trouble/Problem", spainVariant: "Follón/Lío", latamVariant: "Pedo/Bronca", phoneticSpain: "[fo-YOHN/LEE-o]", phoneticLatam: "[PEH-do/BRON-kah]", english: "Trouble/Problem", partOfSpeech: "noun", exampleSentenceSpain: "¡Qué follón!", exampleSentenceLatam: "¿Qué pedo?" },
      { word: "Awesome/Excellent", spainVariant: "Flipante", latamVariant: "Increíble/Alucinante", phoneticSpain: "[flee-PAHN-teh]", phoneticLatam: "[in-kreh-EE-bleh]", english: "Awesome", partOfSpeech: "adjective", exampleSentenceSpain: "¡Eso es flipante!", exampleSentenceLatam: "¡Eso es alucinante!" },
      { word: "Attractive", spainVariant: "Guapo/a", latamVariant: "Guapo/a", phoneticSpain: "[GWAH-po]", phoneticLatam: "[GWAH-po]", english: "Attractive", partOfSpeech: "adjective", exampleSentenceSpain: "Es muy guapa.", exampleSentenceLatam: "Está bien guapa." },
      { word: "Ugly", spainVariant: "Feo/a", latamVariant: "Feo/a", phoneticSpain: "[FEH-o]", phoneticLatam: "[FEH-o]", english: "Ugly", partOfSpeech: "adjective", exampleSentenceSpain: "Eso es feo.", exampleSentenceLatam: "Está muy feo." },
      { word: "Crazy", spainVariant: "Loco/a", latamVariant: "Loco/a", phoneticSpain: "[LOH-ko]", phoneticLatam: "[LOH-ko]", english: "Crazy", partOfSpeech: "adjective", exampleSentenceSpain: "¡Estás loco!", exampleSentenceLatam: "¡Que loco!" },
      { word: "Fun/Enjoyable", spainVariant: "Molón", latamVariant: "Divertido", phoneticSpain: "[mo-LOHN]", phoneticLatam: "[dee-ver-TEE-do]", english: "Fun", partOfSpeech: "adjective", exampleSentenceSpain: "¡Qué molón!", exampleSentenceLatam: "¡Fue muy divertido!" },
      { word: "No problem", spainVariant: "Sin problema", latamVariant: "Sin problema", phoneticSpain: "[seen pro-BLEH-mah]", phoneticLatam: "[seen pro-BLEH-mah]", english: "No problem", partOfSpeech: "phrase", exampleSentenceSpain: "Sin problema, cuéntame.", exampleSentenceLatam: "Sin problema, hermano." },
      { word: "Let's go", spainVariant: "Vamos/Vamonos", latamVariant: "Vamos/Ándele", phoneticSpain: "[VAH-mos]", phoneticLatam: "[VAH-mos/AHN-deh-leh]", english: "Let's go", partOfSpeech: "phrase", exampleSentenceSpain: "¡Vamonos!", exampleSentenceLatam: "¡Ándele, vámonos!" },
      { word: "What a mess", spainVariant: "¡Qué rollo!", latamVariant: "¡Qué onda!", phoneticSpain: "[keh ROH-yoh]", phoneticLatam: "[keh OHN-dah]", english: "What a mess", partOfSpeech: "interjection", exampleSentenceSpain: "¡Qué rollo!", exampleSentenceLatam: "¡Qué onda, tío!" },
      { word: "Friend (buddy)", spainVariant: "Colega/Tío", latamVariant: "Compa/Güey", phoneticSpain: "[ko-LEH-gah/TEE-o]", phoneticLatam: "[KOM-pah/WAY]", english: "Friend (buddy)", partOfSpeech: "noun", exampleSentenceSpain: "¡Oye, colega!", exampleSentenceLatam: "¡Órale, compa!" },
      { word: "Party", spainVariant: "Juerga/Parranda", latamVariant: "Peda/Fiestón", phoneticSpain: "[hoo-ER-gah]", phoneticLatam: "[PEH-dah]", english: "Party", partOfSpeech: "noun", exampleSentenceSpain: "¡Vamos de juerga!", exampleSentenceLatam: "¡Nos vamos de peda!" },
      { word: "Drunk", spainVariant: "Borracho/Pedo", latamVariant: "Borracho/Crudo", phoneticSpain: "[bo-RAH-cho]", phoneticLatam: "[bo-RAH-cho]", english: "Drunk", partOfSpeech: "adjective", exampleSentenceSpain: "Está borracho.", exampleSentenceLatam: "Está crudo." },
      { word: "Nonsense", spainVariant: "Chorrada", latamVariant: "Pendejada", phoneticSpain: "[cho-RRAH-dah]", phoneticLatam: "[pen-deh-HAH-dah]", english: "Nonsense", partOfSpeech: "noun", exampleSentenceSpain: "¡Qué chorrada!", exampleSentenceLatam: "¡Qué pendejada!" },
      { word: "To laugh", spainVariant: "Reír a carcajadas", latamVariant: "Reír/Carcajada", phoneticSpain: "[reh-EER ah kar-kah-HAH-dahs]", phoneticLatam: "[reh-EER]", english: "To laugh", partOfSpeech: "verb", exampleSentenceSpain: "Me reí a carcajadas.", exampleSentenceLatam: "Me reí mucho." },
    ],
  },
  "b2-02-stronger-slang": {
    title: "Stronger Slang",
    description: "Bolder, rougher Mexican slang for close friends",
    vocabulary: [
      { word: "Guy/Dude", spainVariant: "Tío", latamVariant: "Güey/Wey", phoneticSpain: "[TEE-o]", phoneticLatam: "[WAY]", english: "Guy/Dude", partOfSpeech: "noun", exampleSentenceSpain: "¡Oye, tío!", exampleSentenceLatam: "¡Órale, güey!" },
      { word: "No way/Bullshit", spainVariant: "¡Qué va!", latamVariant: "¡No manches!", phoneticSpain: "[keh vah]", phoneticLatam: "[no MAHN-ches]", english: "No way", partOfSpeech: "interjection", exampleSentenceSpain: "¿En serio? ¡Qué va!", exampleSentenceLatam: "¡No manches, de verdad?" },
      { word: "Fuck/Damn", spainVariant: "Joder", latamVariant: "Chingar", phoneticSpain: "[ho-DER]", phoneticLatam: "[chin-GAHR]", english: "Damn", partOfSpeech: "verb", exampleSentenceSpain: "¡Joder!", exampleSentenceLatam: "¡Chinga!" },
      { word: "Asshole", spainVariant: "Capullo", latamVariant: "Cabrón/Culero", phoneticSpain: "[kah-POO-yoh]", phoneticLatam: "[kah-BROHN]", english: "Asshole", partOfSpeech: "noun", exampleSentenceSpain: "¡Eres un capullo!", exampleSentenceLatam: "¡Eres un cabrón!" },
      { word: "Damn it/Shit", spainVariant: "¡Mierda!", latamVariant: "¡Chingada!", phoneticSpain: "[mee-ER-dah]", phoneticLatam: "[chin-GAH-dah]", english: "Damn it", partOfSpeech: "interjection", exampleSentenceSpain: "¡Mierda!", exampleSentenceLatam: "¡Chingada!" },
      { word: "Bastard", spainVariant: "Cabrón", latamVariant: "Cabrón/Pendejo", phoneticSpain: "[kah-BROHN]", phoneticLatam: "[kah-BROHN]", english: "Bastard", partOfSpeech: "noun", exampleSentenceSpain: "Eres un cabrón.", exampleSentenceLatam: "¡Eres un pendejo!" },
      { word: "Bitch/Prick", spainVariant: "Hijo de puta", latamVariant: "Hijo de la chingada", phoneticSpain: "[EE-ho deh POO-tah]", phoneticLatam: "[EE-ho deh lah chin-GAH-dah]", english: "Son of a bitch", partOfSpeech: "noun", exampleSentenceSpain: "¡Hijo de puta!", exampleSentenceLatam: "¡Hijo de la chingada!" },
      { word: "Pissed off", spainVariant: "Cabreado", latamVariant: "Enojado/Molesto", phoneticSpain: "[kah-breh-AH-do]", phoneticLatam: "[eh-no-HAH-do]", english: "Pissed off", partOfSpeech: "adjective", exampleSentenceSpain: "Estoy cabreado.", exampleSentenceLatam: "Estoy enojado." },
      { word: "Screw up", spainVariant: "Joderse", latamVariant: "Chingarse", phoneticSpain: "[ho-DER-seh]", phoneticLatam: "[chin-GAHR-seh]", english: "Screw up", partOfSpeech: "verb", exampleSentenceSpain: "La jodí.", exampleSentenceLatam: "La chinqué." },
      { word: "Bastard (friendly)", spainVariant: "Cabronazo", latamVariant: "Compa", phoneticSpain: "[kah-bro-NAH-so]", phoneticLatam: "[KOM-pah]", english: "Buddy (emphatic)", partOfSpeech: "noun", exampleSentenceSpain: "¡Cabronazo!", exampleSentenceLatam: "¡Compa!" },
      { word: "Bullshit", spainVariant: "Gilipolleces", latamVariant: "Pendejadas", phoneticSpain: "[hee-lee-po-YEH-ses]", phoneticLatam: "[pen-deh-HAH-dahs]", english: "Bullshit", partOfSpeech: "noun", exampleSentenceSpain: "¡Qué gilipolleces!", exampleSentenceLatam: "¡Qué pendejadas!" },
      { word: "Asshole", spainVariant: "Gilipollas", latamVariant: "Pendejo", phoneticSpain: "[hee-lee-POH-yahs]", phoneticLatam: "[pen-DEH-ho]", english: "Asshole", partOfSpeech: "noun", exampleSentenceSpain: "¡Qué gilipollas!", exampleSentenceLatam: "¡Eres un pendejo!" },
      { word: "Damn/Shit", spainVariant: "¡Coño!", latamVariant: "¡Caramba!", phoneticSpain: "[KOH-nyoh]", phoneticLatam: "[kah-RAHM-bah]", english: "Damn!", partOfSpeech: "interjection", exampleSentenceSpain: "¡Coño!", exampleSentenceLatam: "¡Caramba!" },
      { word: "Crap/Rubbish", spainVariant: "Basura", latamVariant: "Porquería", phoneticSpain: "[bah-SOO-rah]", phoneticLatam: "[por-keh-REE-ah]", english: "Crap", partOfSpeech: "noun", exampleSentenceSpain: "¡Eso es basura!", exampleSentenceLatam: "¡Qué porquería!" },
      { word: "Dumbass", spainVariant: "Mamón", latamVariant: "Güevón", phoneticSpain: "[mah-MOHN]", phoneticLatam: "[weh-VOHN]", english: "Dumbass", partOfSpeech: "noun", exampleSentenceSpain: "¡Eres un mamón!", exampleSentenceLatam: "¡Eres un güevón!" },
      { word: "Fuck off", spainVariant: "¡Vete a tomar por culo!", latamVariant: "¡Chinga tu madre!", phoneticSpain: "[VEH-teh ah to-MAHR]", phoneticLatam: "[CHIN-gah too MAH-dreh]", english: "Fuck off", partOfSpeech: "phrase", exampleSentenceSpain: "¡Vete a tomar por culo!", exampleSentenceLatam: "¡Chinga tu madre!" },
      { word: "Cock/Dick", spainVariant: "Polla", latamVariant: "Verga", phoneticSpain: "[POH-yah]", phoneticLatam: "[VER-gah]", english: "Dick", partOfSpeech: "noun", exampleSentenceSpain: "¡Qué polla!", exampleSentenceLatam: "¡Qué verga!" },
      { word: "Pussy", spainVariant: "Coño", latamVariant: "Concha", phoneticSpain: "[KOH-nyoh]", phoneticLatam: "[KON-chah]", english: "Pussy", partOfSpeech: "noun", exampleSentenceSpain: "¡Coño!", exampleSentenceLatam: "¡Concha!" },
      { word: "Motherfucker", spainVariant: "Hijo de puta", latamVariant: "Hijo de la chingada", phoneticSpain: "[EE-ho deh POO-tah]", phoneticLatam: "[EE-ho deh lah chin-GAH-dah]", english: "Motherfucker", partOfSpeech: "noun", exampleSentenceSpain: "¡Hijo de puta!", exampleSentenceLatam: "¡Hijo de la chingada!" },
      { word: "Fucking", spainVariant: "Jodido/Maldito", latamVariant: "Chingón/Chingado", phoneticSpain: "[ho-DEE-do]", phoneticLatam: "[chin-GOHN]", english: "Fucking", partOfSpeech: "adjective", exampleSentenceSpain: "¡Qué jodido!", exampleSentenceLatam: "¡Qué chingón!" },
    ],
  },
  "b2-03-humor-sarcasm": {
    title: "Humor & Sarcasm",
    description: "Read between the lines—Mexican sarcasm, teasing, and comebacks",
    vocabulary: [
      { word: "That's funny", spainVariant: "Eso es gracioso", latamVariant: "Eso me hace reír", phoneticSpain: "[EH-so es grah-see-OH-so]", phoneticLatam: "[EH-so meh AH-seh reh-EER]", english: "That's funny", partOfSpeech: "phrase", exampleSentenceSpain: "Eso es gracioso.", exampleSentenceLatam: "Eso me hace reír." },
      { word: "You're joking", spainVariant: "Estás de broma", latamVariant: "Estás bromeando", phoneticSpain: "[es-TAHS deh BRO-mah]", phoneticLatam: "[es-TAHS bro-meh-AHN-do]", english: "You're joking", partOfSpeech: "phrase", exampleSentenceSpain: "¿Estás de broma?", exampleSentenceLatam: "¿Estás bromeando?" },
      { word: "I'm not falling for it", spainVariant: "No me engañas", latamVariant: "No me engañas", phoneticSpain: "[no meh en-GAHN-yahs]", phoneticLatam: "[no meh en-GAHN-yahs]", english: "I'm not falling for it", partOfSpeech: "phrase", exampleSentenceSpain: "No me engañas.", exampleSentenceLatam: "No me engañas." },
      { word: "Stop messing with me", spainVariant: "Déjame en paz", latamVariant: "Déjame de bromas", phoneticSpain: "[DEH-hah-meh en pahs]", phoneticLatam: "[DEH-hah-meh deh BRO-mahs]", english: "Stop messing with me", partOfSpeech: "phrase", exampleSentenceSpain: "Déjame en paz.", exampleSentenceLatam: "Déjame de bromas." },
      { word: "Sarcasm", spainVariant: "Sarcasmo", latamVariant: "Sarcasmo", phoneticSpain: "[sar-KAHS-mo]", phoneticLatam: "[sar-KAHS-mo]", english: "Sarcasm", partOfSpeech: "noun", exampleSentenceSpain: "Eso fue sarcasmo.", exampleSentenceLatam: "Lo dije con sarcasmo." },
      { word: "Witty/Clever", spainVariant: "Ingenioso/a", latamVariant: "Ingenioso/a", phoneticSpain: "[in-heh-nee-OH-so]", phoneticLatam: "[in-heh-nee-OH-so]", english: "Witty", partOfSpeech: "adjective", exampleSentenceSpain: "¡Qué ingenioso!", exampleSentenceLatam: "¡Muy ingenioso!" },
      { word: "That's a good one", spainVariant: "¡Buena esa!", latamVariant: "¡Buena!", phoneticSpain: "[boo-EH-nah EH-sah]", phoneticLatam: "[boo-EH-nah]", english: "That's a good one", partOfSpeech: "interjection", exampleSentenceSpain: "¡Buena esa!", exampleSentenceLatam: "¡Buena!" },
      { word: "Laugh at yourself", spainVariant: "Reírse de sí mismo", latamVariant: "Reírse de uno", phoneticSpain: "[reh-EER-seh deh see MEES-mo]", phoneticLatam: "[reh-EER-seh]", english: "Laugh at yourself", partOfSpeech: "verb", exampleSentenceSpain: "Riéte de ti mismo.", exampleSentenceLatam: "Ríete de una." },
      { word: "Pun/Wordplay", spainVariant: "Juego de palabras", latamVariant: "Albur", phoneticSpain: "[hoo-EH-go deh pah-LAH-bras]", phoneticLatam: "[ahl-BOOR]", english: "Pun", partOfSpeech: "noun", exampleSentenceSpain: "Ese es un buen juego de palabras.", exampleSentenceLatam: "¡Qué albur!" },
      { word: "Mock/Tease", spainVariant: "Burlarse", latamVariant: "Burlarse", phoneticSpain: "[boor-LAHR-seh]", phoneticLatam: "[boor-LAHR-seh]", english: "To tease", partOfSpeech: "verb", exampleSentenceSpain: "No te burles de mí.", exampleSentenceLatam: "No me burles." },
      { word: "Comeback/Retort", spainVariant: "Respuesta ingeniosa", latamVariant: "Réplica", phoneticSpain: "[res-PWES-tah in-heh-nee-OH-sah]", phoneticLatam: "[REH-plee-kah]", english: "Comeback", partOfSpeech: "noun", exampleSentenceSpain: "¡Buena réplica!", exampleSentenceLatam: "¡Buena respuesta!" },
      { word: "Irony", spainVariant: "Ironía", latamVariant: "Ironía", phoneticSpain: "[ee-ro-NEE-ah]", phoneticLatam: "[ee-ro-NEE-ah]", english: "Irony", partOfSpeech: "noun", exampleSentenceSpain: "¡Qué ironía!", exampleSentenceLatam: "¡Qué ironía!" },
      { word: "Parody/Imitation", spainVariant: "Parodia", latamVariant: "Burla", phoneticSpain: "[pah-ROH-dee-ah]", phoneticLatam: "[BOOR-lah]", english: "Parody", partOfSpeech: "noun", exampleSentenceSpain: "Eso es una parodia.", exampleSentenceLatam: "Es una burla." },
      { word: "Obvious sarcasm", spainVariant: "Obviamente", latamVariant: "Claro que sí", phoneticSpain: "[ob-vee-ah-MEN-teh]", phoneticLatam: "[KLAH-ro keh see]", english: "Obviously", partOfSpeech: "adverb", exampleSentenceSpain: "Obviamente lo creo.", exampleSentenceLatam: "Claro que sí, con sarcasmo." },
      { word: "Eye roll", spainVariant: "Poner los ojos en blanco", latamVariant: "Rodar los ojos", phoneticSpain: "[po-NER los OH-hos]", phoneticLatam: "[ro-DAHR los OH-hos]", english: "Eye roll", partOfSpeech: "verb", exampleSentenceSpain: "Puse los ojos en blanco.", exampleSentenceLatam: "Rodé los ojos." },
      { word: "Deadpan", spainVariant: "Cara de póker", latamVariant: "Cara seria", phoneticSpain: "[KAH-rah deh POH-ker]", phoneticLatam: "[KAH-rah seh-REE-ah]", english: "Deadpan", partOfSpeech: "adjective", exampleSentenceSpain: "Dijo con cara de póker.", exampleSentenceLatam: "Lo dijo con cara seria." },
      { word: "Tease", spainVariant: "Bromista", latamVariant: "Bromista", phoneticSpain: "[bro-MES-tah]", phoneticLatam: "[bro-MES-tah]", english: "Tease", partOfSpeech: "noun", exampleSentenceSpain: "¡Qué bromista eres!", exampleSentenceLatam: "¡Eres un bromista!" },
      { word: "Got you!", spainVariant: "¡Te atrapé!", latamVariant: "¡Te cacé!", phoneticSpain: "[teh ah-trah-PEH]", phoneticLatam: "[teh kah-SEH]", english: "Got you!", partOfSpeech: "interjection", exampleSentenceSpain: "¡Te atrapé!", exampleSentenceLatam: "¡Te cacé!" },
      { word: "Kidding", spainVariant: "Bromear", latamVariant: "Bromear", phoneticSpain: "[bro-meh-AHR]", phoneticLatam: "[bro-meh-AHR]", english: "Kidding", partOfSpeech: "verb", exampleSentenceSpain: "Solo bromeo.", exampleSentenceLatam: "Solo bromeo." },
      { word: "Funny face", spainVariant: "Mueca", latamVariant: "Cara de bobo", phoneticSpain: "[moo-EH-kah]", phoneticLatam: "[KAH-rah deh BOH-bo]", english: "Funny face", partOfSpeech: "noun", exampleSentenceSpain: "Hace una mueca.", exampleSentenceLatam: "Pone cara de bobo." },
    ],
  },
  "b2-04-arguments-conflict": {
    title: "Arguments & Conflict",
    description: "Handle disagreements with confidence—set boundaries, de-escalate, apologize",
    vocabulary: [
      { word: "Disagree", spainVariant: "Estar en desacuerdo", latamVariant: "No estar de acuerdo", phoneticSpain: "[es-TAHR en des-ah-KWER-do]", phoneticLatam: "[no es-TAHR deh ah-KWER-do]", english: "Disagree", partOfSpeech: "verb", exampleSentenceSpain: "Estoy en desacuerdo.", exampleSentenceLatam: "No estoy de acuerdo." },
      { word: "Argument", spainVariant: "Discusión", latamVariant: "Pelea", phoneticSpain: "[dis-koo-see-OHN]", phoneticLatam: "[peh-LEH-ah]", english: "Argument", partOfSpeech: "noun", exampleSentenceSpain: "Tuvimos una discusión.", exampleSentenceLatam: "Tuvimos una pelea." },
      { word: "Fight", spainVariant: "Pelea", latamVariant: "Pelea", phoneticSpain: "[peh-LEH-ah]", phoneticLatam: "[peh-LEH-ah]", english: "Fight", partOfSpeech: "noun", exampleSentenceSpain: "Nos peleamos.", exampleSentenceLatam: "Tuvimos una pelea." },
      { word: "Set a boundary", spainVariant: "Poner un límite", latamVariant: "Establecer límites", phoneticSpain: "[po-NER oon LEE-mee-teh]", phoneticLatam: "[es-tah-bleh-SER LEE-mee-tes]", english: "Set a boundary", partOfSpeech: "verb", exampleSentenceSpain: "Tengo que poner un límite.", exampleSentenceLatam: "Necesito establecer límites." },
      { word: "Don't raise your voice", spainVariant: "No grites", latamVariant: "No grites", phoneticSpain: "[no GREE-tes]", phoneticLatam: "[no GREES-tes]", english: "Don't raise your voice", partOfSpeech: "phrase", exampleSentenceSpain: "¡No grites!", exampleSentenceLatam: "¡No grites conmigo!" },
      { word: "Calm down", spainVariant: "Tranquilízate", latamVariant: "Tranquilízate", phoneticSpain: "[trahn-kee-LEE-zah-teh]", phoneticLatam: "[trahn-kee-LEE-zah-teh]", english: "Calm down", partOfSpeech: "verb", exampleSentenceSpain: "¡Tranquilízate!", exampleSentenceLatam: "¡Tranquilízate, por favor!" },
      { word: "I'm sorry", spainVariant: "Lo siento", latamVariant: "Lo siento", phoneticSpain: "[lo see-EHN-to]", phoneticLatam: "[lo see-EHN-to]", english: "I'm sorry", partOfSpeech: "phrase", exampleSentenceSpain: "Lo siento, fue mi culpa.", exampleSentenceLatam: "Lo siento mucho." },
      { word: "Apologize", spainVariant: "Disculparse", latamVariant: "Disculparse", phoneticSpain: "[dis-kool-PAHR-seh]", phoneticLatam: "[dis-kool-PAHR-seh]", english: "Apologize", partOfSpeech: "verb", exampleSentenceSpain: "Debo disculparme.", exampleSentenceLatam: "Debería disculparme." },
      { word: "That's not fair", spainVariant: "Eso no es justo", latamVariant: "Eso no es justo", phoneticSpain: "[EH-so no es HOOS-to]", phoneticLatam: "[EH-so no es HOOS-to]", english: "That's not fair", partOfSpeech: "phrase", exampleSentenceSpain: "Eso no es justo para mí.", exampleSentenceLatam: "Eso no es justo." },
      { word: "It's not your fault", spainVariant: "No es tu culpa", latamVariant: "No es tu culpa", phoneticSpain: "[no es too KOOL-pah]", phoneticLatam: "[no es too KOOL-pah]", english: "It's not your fault", partOfSpeech: "phrase", exampleSentenceSpain: "No es tu culpa.", exampleSentenceLatam: "No tiene la culpa." },
      { word: "I need space", spainVariant: "Necesito espacio", latamVariant: "Necesito espacio", phoneticSpain: "[neh-seh-SEE-to es-PAH-see-o]", phoneticLatam: "[neh-seh-SEE-to es-PAH-see-o]", english: "I need space", partOfSpeech: "phrase", exampleSentenceSpain: "Necesito espacio ahora.", exampleSentenceLatam: "Necesito un tiempo." },
      { word: "Let's talk about this", spainVariant: "Hablemos de esto", latamVariant: "Platicamos", phoneticSpain: "[ah-BLEH-mos deh ES-to]", phoneticLatam: "[plah-tee-KAH-mos]", english: "Let's talk about this", partOfSpeech: "phrase", exampleSentenceSpain: "Hablemos de esto con calma.", exampleSentenceLatam: "Platicamos sin enojo." },
      { word: "Forgive me", spainVariant: "Perdóname", latamVariant: "Perdóname", phoneticSpain: "[per-DOH-nah-meh]", phoneticLatam: "[per-DOH-nah-meh]", english: "Forgive me", partOfSpeech: "verb", exampleSentenceSpain: "¿Me perdonas?", exampleSentenceLatam: "¿Me perdonas?" },
      { word: "Make it up to you", spainVariant: "Compensarte", latamVariant: "Resarcir", phoneticSpain: "[kom-pen-SAHR-teh]", phoneticLatam: "[reh-sar-SEER]", english: "Make it up to you", partOfSpeech: "verb", exampleSentenceSpain: "Te lo compensaré.", exampleSentenceLatam: "Te lo resarciré." },
      { word: "Move forward", spainVariant: "Seguir adelante", latamVariant: "Seguir adelante", phoneticSpain: "[seh-GHEER ah-deh-LAHN-teh]", phoneticLatam: "[seh-GHEER ah-deh-LAHN-teh]", english: "Move forward", partOfSpeech: "verb", exampleSentenceSpain: "Sigamos adelante.", exampleSentenceLatam: "Sigamos de largo." },
      { word: "Reconcile", spainVariant: "Reconciliarse", latamVariant: "Reconciliarse", phoneticSpain: "[reh-kon-see-lee-AHR-seh]", phoneticLatam: "[reh-kon-see-lee-AHR-seh]", english: "Reconcile", partOfSpeech: "verb", exampleSentenceSpain: "Nos reconciliamos.", exampleSentenceLatam: "Nos reconciliamos." },
      { word: "Peace", spainVariant: "Paz", latamVariant: "Paz", phoneticSpain: "[pahs]", phoneticLatam: "[pahs]", english: "Peace", partOfSpeech: "noun", exampleSentenceSpain: "Necesitamos paz.", exampleSentenceLatam: "Queremos hacer las paces." },
      { word: "Truce", spainVariant: "Tregua", latamVariant: "Tregua", phoneticSpain: "[TREH-gwah]", phoneticLatam: "[TREH-gwah]", english: "Truce", partOfSpeech: "noun", exampleSentenceSpain: "Hagamos una tregua.", exampleSentenceLatam: "Hagamos una tregua." },
      { word: "Hurt/Offended", spainVariant: "Ofendido/a", latamVariant: "Ofendido/a", phoneticSpain: "[o-fen-DEE-do]", phoneticLatam: "[o-fen-DEE-do]", english: "Hurt", partOfSpeech: "adjective", exampleSentenceSpain: "Estoy ofendido.", exampleSentenceLatam: "Me siento ofendido." },
      { word: "Resentment", spainVariant: "Resentimiento", latamVariant: "Resentimiento", phoneticSpain: "[reh-sen-tee-mee-EHN-to]", phoneticLatam: "[reh-sen-tee-mee-EHN-to]", english: "Resentment", partOfSpeech: "noun", exampleSentenceSpain: "No tengo resentimiento.", exampleSentenceLatam: "Sin resentimiento." },
    ],
  },
  "b2-05-texting-internet": {
    title: "Texting & Internet Spanish",
    description: "Chat like a local—texting shorthand, read receipts, ghosting, and online expressions",
    vocabulary: [
      { word: "Text message", spainVariant: "Mensaje de texto", latamVariant: "Mensaje", phoneticSpain: "[men-SAH-heh deh TEK-sto]", phoneticLatam: "[men-SAH-heh]", english: "Text message", partOfSpeech: "noun", exampleSentenceSpain: "Te mandé un mensaje.", exampleSentenceLatam: "¿Recibiste mi mensaje?" },
      { word: "WhatsApp", spainVariant: "WhatsApp", latamVariant: "WhatsApp", phoneticSpain: "[WAHT-sahp]", phoneticLatam: "[WAHT-sahp]", english: "WhatsApp", partOfSpeech: "noun", exampleSentenceSpain: "Mándame por WhatsApp.", exampleSentenceLatam: "Te mando un WhatsApp." },
      { word: "Typing...", spainVariant: "Escribiendo...", latamVariant: "Escribiendo...", phoneticSpain: "[es-kree-bee-EHN-do]", phoneticLatam: "[es-kree-bee-EHN-do]", english: "Typing...", partOfSpeech: "verb", exampleSentenceSpain: "Estoy escribiendo.", exampleSentenceLatam: "Estoy escribiendo." },
      { word: "Read", spainVariant: "Leído", latamVariant: "Leído", phoneticSpain: "[leh-EE-do]", phoneticLatam: "[leh-EE-do]", english: "Read", partOfSpeech: "adjective", exampleSentenceSpain: "Ya lo leí.", exampleSentenceLatam: "Ya lo leí." },
      { word: "Online", spainVariant: "En línea", latamVariant: "En línea", phoneticSpain: "[en LEE-neh-ah]", phoneticLatam: "[en LEE-neh-ah]", english: "Online", partOfSpeech: "adverb", exampleSentenceSpain: "Estoy en línea.", exampleSentenceLatam: "Estoy en línea." },
      { word: "Offline", spainVariant: "Desconectado", latamVariant: "Desconectado", phoneticSpain: "[des-ko-nek-TAH-do]", phoneticLatam: "[des-ko-nek-TAH-do]", english: "Offline", partOfSpeech: "adjective", exampleSentenceSpain: "Está desconectado.", exampleSentenceLatam: "Está offline." },
      { word: "Ghost (ignore)", spainVariant: "Ignorar", latamVariant: "Ignorar", phoneticSpain: "[ig-no-RAHR]", phoneticLatam: "[ig-no-RAHR]", english: "To ghost", partOfSpeech: "verb", exampleSentenceSpain: "Me ignoró.", exampleSentenceLatam: "Me ignoró completamente." },
      { word: "DM (Direct Message)", spainVariant: "Mensaje privado", latamVariant: "Mensaje directo", phoneticSpain: "[men-SAH-heh pree-VAH-do]", phoneticLatam: "[men-SAH-heh dee-REK-to]", english: "DM", partOfSpeech: "noun", exampleSentenceSpain: "Te mando un mensaje privado.", exampleSentenceLatam: "Te envío un DM." },
      { word: "Like (social media)", spainVariant: "Me gusta", latamVariant: "Like", phoneticSpain: "[meh GUS-tah]", phoneticLatam: "[LIKE]", english: "Like", partOfSpeech: "verb", exampleSentenceSpain: "Dio like a mi foto.", exampleSentenceLatam: "Le diste like a mi foto." },
      { word: "Comment", spainVariant: "Comentario", latamVariant: "Comentario", phoneticSpain: "[ko-men-TAH-ree-o]", phoneticLatam: "[ko-men-TAH-ree-o]", english: "Comment", partOfSpeech: "noun", exampleSentenceSpain: "Hizo un comentario.", exampleSentenceLatam: "Pasó un comentario." },
      { word: "Post", spainVariant: "Publicación", latamVariant: "Post", phoneticSpain: "[poo-blee-kah-see-OHN]", phoneticLatam: "[POHST]", english: "Post", partOfSpeech: "noun", exampleSentenceSpain: "Vi tu publicación.", exampleSentenceLatam: "Vi tu post." },
      { word: "Story (Instagram)", spainVariant: "Historia", latamVariant: "Story", phoneticSpain: "[is-TO-ree-ah]", phoneticLatam: "[STO-ree]", english: "Story", partOfSpeech: "noun", exampleSentenceSpain: "Subí una historia.", exampleSentenceLatam: "Subí un story." },
      { word: "Emoji", spainVariant: "Emoji/Emoticono", latamVariant: "Emoji", phoneticSpain: "[eh-MOH-hee]", phoneticLatam: "[eh-MOH-hee]", english: "Emoji", partOfSpeech: "noun", exampleSentenceSpain: "Usa un emoji.", exampleSentenceLatam: "Usa un emoji." },
      { word: "Lol/Laugh", spainVariant: "Jajaja", latamVariant: "Jajaja", phoneticSpain: "[hah-hah-hah]", phoneticLatam: "[hah-hah-hah]", english: "Lol", partOfSpeech: "interjection", exampleSentenceSpain: "¡Jajaja!", exampleSentenceLatam: "¡Jajaja!" },
      { word: "Haha", spainVariant: "Jaja", latamVariant: "Jaja", phoneticSpain: "[hah-hah]", phoneticLatam: "[hah-hah]", english: "Haha", partOfSpeech: "interjection", exampleSentenceSpain: "¡Jaja!", exampleSentenceLatam: "¡Jaja!" },
      { word: "Notification", spainVariant: "Notificación", latamVariant: "Notificación", phoneticSpain: "[no-tee-fee-kah-see-OHN]", phoneticLatam: "[no-tee-fee-kah-see-OHN]", english: "Notification", partOfSpeech: "noun", exampleSentenceSpain: "Recibí una notificación.", exampleSentenceLatam: "Tengo una notificación." },
      { word: "Username", spainVariant: "Nombre de usuario", latamVariant: "Nombre de usuario", phoneticSpain: "[NOM-breh deh oo-soo-AH-ree-o]", phoneticLatam: "[NOM-breh deh oo-soo-AH-ree-o]", english: "Username", partOfSpeech: "noun", exampleSentenceSpain: "¿Cuál es tu nombre de usuario?", exampleSentenceLatam: "¿Cuál es tu username?" },
      { word: "Follow", spainVariant: "Seguir", latamVariant: "Seguir", phoneticSpain: "[seh-GHEER]", phoneticLatam: "[seh-GHEER]", english: "Follow", partOfSpeech: "verb", exampleSentenceSpain: "Te sigo en redes.", exampleSentenceLatam: "Te sigo en Instagram." },
      { word: "Unfollow", spainVariant: "Dejar de seguir", latamVariant: "Dejar de seguir", phoneticSpain: "[deh-HAHR deh seh-GHEER]", phoneticLatam: "[deh-HAHR deh seh-GHEER]", english: "Unfollow", partOfSpeech: "verb", exampleSentenceSpain: "Dejé de seguirlo.", exampleSentenceLatam: "Ya no lo sigo." },
      { word: "Block", spainVariant: "Bloquear", latamVariant: "Bloquear", phoneticSpain: "[blo-keh-AHR]", phoneticLatam: "[blo-keh-AHR]", english: "Block", partOfSpeech: "verb", exampleSentenceSpain: "Te bloqueé.", exampleSentenceLatam: "Te bloqueé." },
    ],
  },
  "b2-06-mexican-reactions": {
    title: "Mexican Reactions",
    description: "React like a Mexican—¡No manches!, ¿Neta?, ¡Órale! and punchy expressions",
    vocabulary: [
      { word: "No way!", spainVariant: "¡Qué va!", latamVariant: "¡No manches!", phoneticSpain: "[keh vah]", phoneticLatam: "[no MAHN-ches]", english: "No way!", partOfSpeech: "interjection", exampleSentenceSpain: "¿Qué va!", exampleSentenceLatam: "¡No manches!" },
      { word: "Really?/For real?", spainVariant: "¿De verdad?", latamVariant: "¿Neta?", phoneticSpain: "[deh ver-DAHD]", phoneticLatam: "[NEH-tah]", english: "Really?", partOfSpeech: "interjection", exampleSentenceSpain: "¿De verdad?", exampleSentenceLatam: "¿Neta?" },
      { word: "Wow!", spainVariant: "¡Vaya!", latamVariant: "¡Órale!", phoneticSpain: "[VAH-yah]", phoneticLatam: "[OH-rah-leh]", english: "Wow!", partOfSpeech: "interjection", exampleSentenceSpain: "¡Vaya!", exampleSentenceLatam: "¡Órale!" },
      { word: "Cool/Awesome", spainVariant: "¡Guay!", latamVariant: "¡Órale!", phoneticSpain: "[gwye]", phoneticLatam: "[OH-rah-leh]", english: "Cool!", partOfSpeech: "interjection", exampleSentenceSpain: "¡Guay!", exampleSentenceLatam: "¡Órale!" },
      { word: "That's crazy", spainVariant: "¡Qué locura!", latamVariant: "¡Qué locura!", phoneticSpain: "[keh lo-KOO-rah]", phoneticLatam: "[keh lo-KOO-rah]", english: "That's crazy", partOfSpeech: "interjection", exampleSentenceSpain: "¡Qué locura!", exampleSentenceLatam: "¡Eso es una locura!" },
      { word: "I swear", spainVariant: "Te lo juro", latamVariant: "Te lo juro", phoneticSpain: "[teh lo HOO-ro]", phoneticLatam: "[teh lo HOO-ro]", english: "I swear", partOfSpeech: "phrase", exampleSentenceSpain: "Te lo juro.", exampleSentenceLatam: "Te lo juro." },
      { word: "Obviously/Duh", spainVariant: "Obviamente", latamVariant: "Claro", phoneticSpain: "[ob-vee-ah-MEN-teh]", phoneticLatam: "[KLAH-ro]", english: "Obviously", partOfSpeech: "adverb", exampleSentenceSpain: "Obviamente.", exampleSentenceLatam: "¡Claro!" },
      { word: "Of course", spainVariant: "Por supuesto", latamVariant: "Por supuesto", phoneticSpain: "[por soo-poo-ES-to]", phoneticLatam: "[por soo-poo-ES-to]", english: "Of course", partOfSpeech: "phrase", exampleSentenceSpain: "Por supuesto.", exampleSentenceLatam: "Claro que sí." },
      { word: "Definitely", spainVariant: "Definitivamente", latamVariant: "Definitivamente", phoneticSpain: "[deh-fee-nee-tee-vah-MEN-teh]", phoneticLatam: "[deh-fee-nee-tee-vah-MEN-teh]", english: "Definitely", partOfSpeech: "adverb", exampleSentenceSpain: "Definitivamente.", exampleSentenceLatam: "Definitivamente." },
      { word: "Absolutely", spainVariant: "Absolutamente", latamVariant: "Absolutamente", phoneticSpain: "[ab-so-loo-tah-MEN-teh]", phoneticLatam: "[ab-so-loo-tah-MEN-teh]", english: "Absolutely", partOfSpeech: "adverb", exampleSentenceSpain: "Absolutamente.", exampleSentenceLatam: "Absolutamente." },
      { word: "Incredible!", spainVariant: "¡Increíble!", latamVariant: "¡Increíble!", phoneticSpain: "[in-kreh-EE-bleh]", phoneticLatam: "[in-kreh-EE-bleh]", english: "Incredible!", partOfSpeech: "interjection", exampleSentenceSpain: "¡Increíble!", exampleSentenceLatam: "¡Increíble!" },
      { word: "That's great!", spainVariant: "¡Qué bien!", latamVariant: "¡Qué bien!", phoneticSpain: "[keh bee-EHN]", phoneticLatam: "[keh bee-EHN]", english: "That's great!", partOfSpeech: "interjection", exampleSentenceSpain: "¡Qué bien!", exampleSentenceLatam: "¡Qué bien!" },
      { word: "I can't believe it", spainVariant: "No me lo creo", latamVariant: "No me lo creo", phoneticSpain: "[no meh lo KREH-o]", phoneticLatam: "[no meh lo KREH-o]", english: "I can't believe it", partOfSpeech: "phrase", exampleSentenceSpain: "No me lo creo.", exampleSentenceLatam: "¡Ni lo creo!" },
      { word: "No shit!", spainVariant: "¡Qué barbaridad!", latamVariant: "¡Órale!", phoneticSpain: "[keh bar-bah-ree-DAHD]", phoneticLatam: "[OH-rah-leh]", english: "No shit!", partOfSpeech: "interjection", exampleSentenceSpain: "¡Qué barbaridad!", exampleSentenceLatam: "¡Órale, pues!" },
      { word: "Unbelievable", spainVariant: "Increíble", latamVariant: "Increíble", phoneticSpain: "[in-kreh-EE-bleh]", phoneticLatam: "[in-kreh-EE-bleh]", english: "Unbelievable", partOfSpeech: "adjective", exampleSentenceSpain: "¡Increíble!", exampleSentenceLatam: "¡Eso es increíble!" },
      { word: "Awesome sauce", spainVariant: "¡Que alucine!", latamVariant: "¡Que padre!", phoneticSpain: "[keh ah-loo-SEE-neh]", phoneticLatam: "[keh PAH-dreh]", english: "That's awesome", partOfSpeech: "interjection", exampleSentenceSpain: "¡Que alucine!", exampleSentenceLatam: "¡Que padre!" },
      { word: "For real though", spainVariant: "En serio", latamVariant: "De verdad", phoneticSpain: "[en SEH-ree-o]", phoneticLatam: "[deh ver-DAHD]", english: "For real though", partOfSpeech: "phrase", exampleSentenceSpain: "En serio.", exampleSentenceLatam: "De verdad." },
      { word: "Not gonna lie", spainVariant: "No mentiré", latamVariant: "No voy a mentir", phoneticSpain: "[no men-tee-REH]", phoneticLatam: "[no voy ah men-TEER]", english: "Not gonna lie", partOfSpeech: "phrase", exampleSentenceSpain: "No mentiré.", exampleSentenceLatam: "No voy a mentir." },
      { word: "To be honest", spainVariant: "Honestamente", latamVariant: "Honestamente", phoneticSpain: "[o-nes-tah-MEN-teh]", phoneticLatam: "[o-nes-tah-MEN-teh]", english: "To be honest", partOfSpeech: "phrase", exampleSentenceSpain: "Honestamente.", exampleSentenceLatam: "Para serlo." },
      { word: "Trust me", spainVariant: "Créeme", latamVariant: "Créeme", phoneticSpain: "[KREH-eh-meh]", phoneticLatam: "[KREH-eh-meh]", english: "Trust me", partOfSpeech: "phrase", exampleSentenceSpain: "Créeme, es verdad.", exampleSentenceLatam: "Créeme, funcionará." },
    ],
  },
  "b2-07-expressive-mexican": {
    title: "Expressive Mexican Spanish",
    description: "Say it with feeling—emphatic, exaggerated, emotional expressions",
    vocabulary: [
      { word: "I love it!", spainVariant: "¡Me encanta!", latamVariant: "¡Me encanta!", phoneticSpain: "[meh en-KAHN-tah]", phoneticLatam: "[meh en-KAHN-tah]", english: "I love it!", partOfSpeech: "interjection", exampleSentenceSpain: "¡Me encanta!", exampleSentenceLatam: "¡Me encanta!" },
      { word: "I hate it!", spainVariant: "¡Lo odio!", latamVariant: "¡Lo odio!", phoneticSpain: "[lo OH-dee-o]", phoneticLatam: "[lo OH-dee-o]", english: "I hate it!", partOfSpeech: "interjection", exampleSentenceSpain: "¡Lo odio!", exampleSentenceLatam: "¡Lo odio!" },
      { word: "It's amazing!", spainVariant: "¡Es asombroso!", latamVariant: "¡Es increíble!", phoneticSpain: "[es ah-SOM-bro-so]", phoneticLatam: "[es in-kreh-EE-bleh]", english: "It's amazing!", partOfSpeech: "phrase", exampleSentenceSpain: "¡Es asombroso!", exampleSentenceLatam: "¡Es increíble!" },
      { word: "It's terrible!", spainVariant: "¡Es terrible!", latamVariant: "¡Es horrible!", phoneticSpain: "[es teh-RREE-bleh]", phoneticLatam: "[es o-RREE-bleh]", english: "It's terrible!", partOfSpeech: "phrase", exampleSentenceSpain: "¡Es terrible!", exampleSentenceLatam: "¡Es horrible!" },
      { word: "I'm dying (laughing)", spainVariant: "Me muero de risa", latamVariant: "Me muero de risa", phoneticSpain: "[meh moo-EH-ro deh REE-sah]", phoneticLatam: "[meh moo-EH-ro deh REE-sah]", english: "I'm dying", partOfSpeech: "phrase", exampleSentenceSpain: "Me muero de risa.", exampleSentenceLatam: "¡Me muero de risa!" },
      { word: "You're the best!", spainVariant: "¡Eres el mejor!", latamVariant: "¡Eres el mejor!", phoneticSpain: "[EH-res el meh-HOR]", phoneticLatam: "[EH-res el meh-HOR]", english: "You're the best!", partOfSpeech: "phrase", exampleSentenceSpain: "¡Eres el mejor!", exampleSentenceLatam: "¡Eres el mejor!" },
      { word: "You're the worst!", spainVariant: "¡Eres lo peor!", latamVariant: "¡Eres lo peor!", phoneticSpain: "[EH-res lo peh-OR]", phoneticLatam: "[EH-res lo peh-OR]", english: "You're the worst!", partOfSpeech: "phrase", exampleSentenceSpain: "¡Eres lo peor!", exampleSentenceLatam: "¡Eres lo peor!" },
      { word: "This is insane!", spainVariant: "¡Esto es una locura!", latamVariant: "¡Esto es una locura!", phoneticSpain: "[ES-to es OO-nah lo-KOO-rah]", phoneticLatam: "[ES-to es OO-nah lo-KOO-rah]", english: "This is insane!", partOfSpeech: "phrase", exampleSentenceSpain: "¡Esto es una locura!", exampleSentenceLatam: "¡Eso es una locura!" },
      { word: "I'm so happy!", spainVariant: "¡Estoy muy feliz!", latamVariant: "¡Estoy muy feliz!", phoneticSpain: "[es-TOY moo-ee feh-LEES]", phoneticLatam: "[es-TOY moo-ee feh-LEES]", english: "I'm so happy!", partOfSpeech: "phrase", exampleSentenceSpain: "¡Estoy muy feliz!", exampleSentenceLatam: "¡Estoy bien feliz!" },
      { word: "I'm devastated", spainVariant: "Estoy destrozado", latamVariant: "Estoy destrozado", phoneticSpain: "[es-TOY des-tro-ZAH-do]", phoneticLatam: "[es-TOY des-tro-ZAH-do]", english: "I'm devastated", partOfSpeech: "phrase", exampleSentenceSpain: "Estoy destrozado.", exampleSentenceLatam: "Estoy destrozado." },
      { word: "That kills me!", spainVariant: "¡Eso me mata!", latamVariant: "¡Eso me mata!", phoneticSpain: "[EH-so meh MAH-tah]", phoneticLatam: "[EH-so meh MAH-tah]", english: "That kills me!", partOfSpeech: "phrase", exampleSentenceSpain: "¡Eso me mata!", exampleSentenceLatam: "¡Eso me mata!" },
      { word: "I'm obsessed!", spainVariant: "¡Estoy obsesionado!", latamVariant: "¡Estoy obsesionado!", phoneticSpain: "[es-TOY obs-seh-see-o-NAH-do]", phoneticLatam: "[es-TOY obs-seh-see-o-NAH-do]", english: "I'm obsessed!", partOfSpeech: "phrase", exampleSentenceSpain: "¡Estoy obsesionado!", exampleSentenceLatam: "¡Estoy obsesionado!" },
      { word: "I'm head over heels", spainVariant: "Estoy loco por ti", latamVariant: "Estoy loco por ti", phoneticSpain: "[es-TOY LOH-ko por tee]", phoneticLatam: "[es-TOY LOH-ko por tee]", english: "I'm head over heels", partOfSpeech: "phrase", exampleSentenceSpain: "Estoy loco por ti.", exampleSentenceLatam: "Estoy loquito por ti." },
      { word: "I can't take it!", spainVariant: "¡No aguanto más!", latamVariant: "¡No aguanto más!", phoneticSpain: "[no ah-GWAHN-to mahs]", phoneticLatam: "[no ah-GWAHN-to mahs]", english: "I can't take it!", partOfSpeech: "phrase", exampleSentenceSpain: "¡No aguanto más!", exampleSentenceLatam: "¡Ya no aguanto!" },
      { word: "Absolutely!", spainVariant: "¡Sin duda!", latamVariant: "¡Claro!", phoneticSpain: "[seen DOO-dah]", phoneticLatam: "[KLAH-ro]", english: "Absolutely!", partOfSpeech: "interjection", exampleSentenceSpain: "¡Sin duda!", exampleSentenceLatam: "¡Claro que sí!" },
      { word: "Never!", spainVariant: "¡Nunca!", latamVariant: "¡Nunca!", phoneticSpain: "[NUN-kah]", phoneticLatam: "[NUN-kah]", english: "Never!", partOfSpeech: "interjection", exampleSentenceSpain: "¡Nunca!", exampleSentenceLatam: "¡Nunca jamás!" },
      { word: "Always!", spainVariant: "¡Siempre!", latamVariant: "¡Siempre!", phoneticSpain: "[see-EHM-preh]", phoneticLatam: "[see-EHM-preh]", english: "Always!", partOfSpeech: "interjection", exampleSentenceSpain: "¡Siempre!", exampleSentenceLatam: "¡Siempre estaré aquí!" },
      { word: "I swear to God", spainVariant: "Te lo juro por Dios", latamVariant: "Te lo juro por Dios", phoneticSpain: "[teh lo HOO-ro por dee-OHS]", phoneticLatam: "[teh lo HOO-ro por dee-OHS]", english: "I swear to God", partOfSpeech: "phrase", exampleSentenceSpain: "Te lo juro por Dios.", exampleSentenceLatam: "Te lo juro por Dios." },
      { word: "Honestly!", spainVariant: "¡De verdad!", latamVariant: "¡De verdad!", phoneticSpain: "[deh ver-DAHD]", phoneticLatam: "[deh ver-DAHD]", english: "Honestly!", partOfSpeech: "interjection", exampleSentenceSpain: "¡De verdad!", exampleSentenceLatam: "¡De verdad!" },
    ],
  },
  "b2-08-cursing-adult": {
    title: "Cursing & Adult Language",
    description: "Strong, mature Mexican slang and profanity—for adults who want to understand real language",
    vocabulary: [
      { word: "Fuck/Shit", spainVariant: "Joder/Mierda", latamVariant: "Chingar/Chingada", phoneticSpain: "[ho-DER / mee-ER-dah]", phoneticLatam: "[chin-GAHR / chin-GAH-dah]", english: "Fuck/Shit", partOfSpeech: "noun/verb", exampleSentenceSpain: "¡Joder!", exampleSentenceLatam: "¡Chingada!" },
      { word: "Bullshit", spainVariant: "Chorradas", latamVariant: "Pendejadas", phoneticSpain: "[cho-RRAH-dahs]", phoneticLatam: "[pen-deh-HAH-dahs]", english: "Bullshit", partOfSpeech: "noun", exampleSentenceSpain: "¡Qué chorradas!", exampleSentenceLatam: "¡Qué pendejadas!" },
      { word: "Asshole", spainVariant: "Culo/Culazos", latamVariant: "Culero/Pendejo", phoneticSpain: "[KOO-lo]", phoneticLatam: "[koo-LEH-ro]", english: "Asshole", partOfSpeech: "noun", exampleSentenceSpain: "¡Eres un culo!", exampleSentenceLatam: "¡Eres un culero!" },
      { word: "Bastard", spainVariant: "Hijo de puta", latamVariant: "Hijo de la chingada", phoneticSpain: "[EE-ho deh POO-tah]", phoneticLatam: "[EE-ho deh lah chin-GAH-dah]", english: "Bastard", partOfSpeech: "noun", exampleSentenceSpain: "¡Hijo de puta!", exampleSentenceLatam: "¡Hijo de la chingada!" },
      { word: "Damn", spainVariant: "Maldita sea", latamVariant: "Que chinge", phoneticSpain: "[mal-DEE-tah SEH-ah]", phoneticLatam: "[keh CHIN-geh]", english: "Damn", partOfSpeech: "interjection", exampleSentenceSpain: "¡Maldita sea!", exampleSentenceLatam: "¡Que chinge!" },
      { word: "Crap", spainVariant: "Basura/Mierda", latamVariant: "Porquería/Chingadera", phoneticSpain: "[bah-SOO-rah]", phoneticLatam: "[por-keh-REE-ah]", english: "Crap", partOfSpeech: "noun", exampleSentenceSpain: "¡Eso es basura!", exampleSentenceLatam: "¡Qué chingadera!" },
      { word: "Asshat", spainVariant: "Memo/Mamón", latamVariant: "Güevón", phoneticSpain: "[MEH-mo / mah-MOHN]", phoneticLatam: "[weh-VOHN]", english: "Asshat", partOfSpeech: "noun", exampleSentenceSpain: "¡Eres un memo!", exampleSentenceLatam: "¡Eres un güevón!" },
      { word: "Motherfucker", spainVariant: "Cabronazo", latamVariant: "Cabronzote", phoneticSpain: "[kah-bro-NAH-so]", phoneticLatam: "[kah-bron-ZO-teh]", english: "Motherfucker", partOfSpeech: "noun", exampleSentenceSpain: "¡Cabronazo!", exampleSentenceLatam: "¡Qué cabronzote!" },
      { word: "Prick", spainVariant: "Gilipollas", latamVariant: "Pendejo", phoneticSpain: "[hee-lee-POH-yahs]", phoneticLatam: "[pen-DEH-ho]", english: "Prick", partOfSpeech: "noun", exampleSentenceSpain: "¡Gilipollas!", exampleSentenceLatam: "¡Pendejo!" },
      { word: "Scumbag", spainVariant: "Canalla", latamVariant: "Canalla", phoneticSpain: "[kah-NAH-yah]", phoneticLatam: "[kah-NAH-yah]", english: "Scumbag", partOfSpeech: "noun", exampleSentenceSpain: "¡Canalla!", exampleSentenceLatam: "¡Eres una canalla!" },
      { word: "Dumbass", spainVariant: "Tarado/Capullo", latamVariant: "Baboso", phoneticSpain: "[tah-RAH-do]", phoneticLatam: "[bah-BOH-so]", english: "Dumbass", partOfSpeech: "noun", exampleSentenceSpain: "¡Eres tarado!", exampleSentenceLatam: "¡Baboso!" },
      { word: "Fuckwit", spainVariant: "Gilipollas", latamVariant: "Pendejete", phoneticSpain: "[hee-lee-POH-yahs]", phoneticLatam: "[pen-deh-HEH-teh]", english: "Fuckwit", partOfSpeech: "noun", exampleSentenceSpain: "¡Gilipollas!", exampleSentenceLatam: "¡Pendejete!" },
      { word: "Whore", spainVariant: "Puta", latamVariant: "Puta", phoneticSpain: "[POO-tah]", phoneticLatam: "[POO-tah]", english: "Whore", partOfSpeech: "noun", exampleSentenceSpain: "¡Puta!", exampleSentenceLatam: "¡Puta!" },
      { word: "Bitchy", spainVariant: "Cabrona", latamVariant: "Cabrona", phoneticSpain: "[kah-BRO-nah]", phoneticLatam: "[kah-BRO-nah]", english: "Bitchy", partOfSpeech: "adjective", exampleSentenceSpain: "¡Qué cabrona!", exampleSentenceLatam: "¡Está cabrona!" },
      { word: "Horny", spainVariant: "Cachondo/a", latamVariant: "Caliente", phoneticSpain: "[kah-CHON-do]", phoneticLatam: "[kah-lee-EHN-teh]", english: "Horny", partOfSpeech: "adjective", exampleSentenceSpain: "Está muy cachondo.", exampleSentenceLatam: "Está bien caliente." },
      { word: "Fuck off", spainVariant: "Vete a la mierda", latamVariant: "Chinga tu madre", phoneticSpain: "[VEH-teh ah lah mee-ER-dah]", phoneticLatam: "[CHIN-gah too MAH-dreh]", english: "Fuck off", partOfSpeech: "phrase", exampleSentenceSpain: "¡Vete a la mierda!", exampleSentenceLatam: "¡Chinga tu madre!" },
      { word: "Go to hell", spainVariant: "Vete al infierno", latamVariant: "Vete al diablo", phoneticSpain: "[VEH-teh ahl in-fee-EHR-no]", phoneticLatam: "[VEH-teh ahl dee-AH-blo]", english: "Go to hell", partOfSpeech: "phrase", exampleSentenceSpain: "¡Vete al infierno!", exampleSentenceLatam: "¡Vete al diablo!" },
      { word: "Shit yourself", spainVariant: "Cagarse", latamVariant: "Cagarse", phoneticSpain: "[kah-GAHR-seh]", phoneticLatam: "[kah-GAHR-seh]", english: "Shit yourself", partOfSpeech: "verb", exampleSentenceSpain: "Se cagó de miedo.", exampleSentenceLatam: "Se cagó de risa." },
      { word: "Damn it", spainVariant: "¡Mierda!", latamVariant: "¡Chingada!", phoneticSpain: "[mee-ER-dah]", phoneticLatam: "[chin-GAH-dah]", english: "Damn it", partOfSpeech: "interjection", exampleSentenceSpain: "¡Mierda!", exampleSentenceLatam: "¡Chingada!" },
      { word: "Holy shit", spainVariant: "¡Puta madre!", latamVariant: "¡Órale!", phoneticSpain: "[POO-tah MAH-dreh]", phoneticLatam: "[OH-rah-leh]", english: "Holy shit", partOfSpeech: "interjection", exampleSentenceSpain: "¡Puta madre!", exampleSentenceLatam: "¡Órale!" },
    ],
  },
  "b2-09-regional-cultural": {
    title: "Regional & Cultural Expressions",
    description: "Sound like you belong—Mexican courtesies, hospitality phrases, and regional slang",
    vocabulary: [
      { word: "You're welcome", spainVariant: "De nada", latamVariant: "De nada", phoneticSpain: "[deh NAH-dah]", phoneticLatam: "[deh NAH-dah]", english: "You're welcome", partOfSpeech: "phrase", exampleSentenceSpain: "De nada.", exampleSentenceLatam: "De nada, para eso estamos." },
      { word: "Make yourself at home", spainVariant: "Ponte cómodo", latamVariant: "Sírvete", phoneticSpain: "[PON-teh KOH-mo-do]", phoneticLatam: "[SEER-veh-teh]", english: "Make yourself at home", partOfSpeech: "phrase", exampleSentenceSpain: "Ponte cómodo.", exampleSentenceLatam: "Sírvete lo que quieras." },
      { word: "Help yourself", spainVariant: "Sírvete", latamVariant: "Sírvete", phoneticSpain: "[SEER-veh-teh]", phoneticLatam: "[SEER-veh-teh]", english: "Help yourself", partOfSpeech: "verb", exampleSentenceSpain: "Sírvete comida.", exampleSentenceLatam: "Sírvete bebida." },
      { word: "The pleasure is mine", spainVariant: "El gusto es mío", latamVariant: "El gusto es mío", phoneticSpain: "[el GUS-to es MEE-oh]", phoneticLatam: "[el GUS-to es MEE-oh]", english: "The pleasure is mine", partOfSpeech: "phrase", exampleSentenceSpain: "El gusto es mío.", exampleSentenceLatam: "El gusto es mío." },
      { word: "How's the family?", spainVariant: "¿Cómo va la familia?", latamVariant: "¿Cómo está la familia?", phoneticSpain: "[KOH-mo vah lah fah-MEE-lee-ah]", phoneticLatam: "[KOH-mo es-TAH lah fah-MEE-lee-ah]", english: "How's the family?", partOfSpeech: "phrase", exampleSentenceSpain: "¿Cómo va la familia?", exampleSentenceLatam: "¿Cómo está tu gente?" },
      { word: "God bless you", spainVariant: "Que Dios te bendiga", latamVariant: "Que Dios te cuide", phoneticSpain: "[keh dee-OHS teh ben-DEE-gah]", phoneticLatam: "[keh dee-OHS teh KOO-ee-deh]", english: "God bless you", partOfSpeech: "phrase", exampleSentenceSpain: "Que Dios te bendiga.", exampleSentenceLatam: "Que Dios te cuidé." },
      { word: "My condolences", spainVariant: "Mi más sentido pésame", latamVariant: "Mi pésame", phoneticSpain: "[mee MAHS sen-TEE-do PEH-sah-meh]", phoneticLatam: "[mee PEH-sah-meh]", english: "My condolences", partOfSpeech: "phrase", exampleSentenceSpain: "Mi más sentido pésame.", exampleSentenceLatam: "Mi pésame a la familia." },
      { word: "Rest in peace", spainVariant: "Que descanse en paz", latamVariant: "Que descanse en paz", phoneticSpain: "[keh des-KAHN-seh en pahs]", phoneticLatam: "[keh des-KAHN-seh en pahs]", english: "Rest in peace", partOfSpeech: "phrase", exampleSentenceSpain: "Que descanse en paz.", exampleSentenceLatam: "Que descanse en paz." },
      { word: "Happy birthday", spainVariant: "Feliz cumpleaños", latamVariant: "Feliz cumpleaños", phoneticSpain: "[feh-LEES koom-pleh-AHN-yos]", phoneticLatam: "[feh-LEES koom-pleh-AHN-yos]", english: "Happy birthday", partOfSpeech: "phrase", exampleSentenceSpain: "Feliz cumpleaños.", exampleSentenceLatam: "Feliz cumpleaños, hermano." },
      { word: "Merry Christmas", spainVariant: "Feliz Navidad", latamVariant: "Feliz Navidad", phoneticSpain: "[feh-LEES nah-vee-DAHD]", phoneticLatam: "[feh-LEES nah-vee-DAHD]", english: "Merry Christmas", partOfSpeech: "phrase", exampleSentenceSpain: "Feliz Navidad.", exampleSentenceLatam: "Feliz Navidad a todos." },
      { word: "Happy New Year", spainVariant: "Próspero Año Nuevo", latamVariant: "Feliz Año Nuevo", phoneticSpain: "[PRAHS-peh-ro AHN-yo NOO-eh-vo]", phoneticLatam: "[feh-LEES AHN-yo NOO-eh-vo]", english: "Happy New Year", partOfSpeech: "phrase", exampleSentenceSpain: "Próspero Año Nuevo.", exampleSentenceLatam: "Feliz Año Nuevo." },
      { word: "Cheers!", spainVariant: "¡Salud!", latamVariant: "¡Salud!", phoneticSpain: "[sah-LOOD]", phoneticLatam: "[sah-LOOD]", english: "Cheers!", partOfSpeech: "interjection", exampleSentenceSpain: "¡Salud!", exampleSentenceLatam: "¡Salud, amigos!" },
      { word: "To your health", spainVariant: "A tu salud", latamVariant: "A tu salud", phoneticSpain: "[ah too sah-LOOD]", phoneticLatam: "[ah too sah-LOOD]", english: "To your health", partOfSpeech: "phrase", exampleSentenceSpain: "A tu salud.", exampleSentenceLatam: "A tu salud." },
      { word: "Enjoy your meal", spainVariant: "Buen provecho", latamVariant: "Buen provecho", phoneticSpain: "[boo-EHN pro-VEH-cho]", phoneticLatam: "[boo-EHN pro-VEH-cho]", english: "Enjoy your meal", partOfSpeech: "phrase", exampleSentenceSpain: "¡Buen provecho!", exampleSentenceLatam: "¡Buen provecho!" },
      { word: "Thank God", spainVariant: "Gracias a Dios", latamVariant: "Gracias a Dios", phoneticSpain: "[GRAH-see-ahs ah dee-OHS]", phoneticLatam: "[GRAH-see-ahs ah dee-OHS]", english: "Thank God", partOfSpeech: "phrase", exampleSentenceSpain: "Gracias a Dios.", exampleSentenceLatam: "Gracias a Dios que está bien." },
      { word: "In God we trust", spainVariant: "En Dios confiamos", latamVariant: "En Dios creemos", phoneticSpain: "[en dee-OHS kon-fee-AH-mos]", phoneticLatam: "[en dee-OHS kreh-EH-mos]", english: "In God we trust", partOfSpeech: "phrase", exampleSentenceSpain: "En Dios confiamos.", exampleSentenceLatam: "En Dios creemos." },
      { word: "Beautiful country", spainVariant: "Lindo país", latamVariant: "Hermoso país", phoneticSpain: "[LEEN-do pah-EES]", phoneticLatam: "[er-MOH-so pah-EES]", english: "Beautiful country", partOfSpeech: "phrase", exampleSentenceSpain: "Lindo país.", exampleSentenceLatam: "Qué hermoso es México." },
      { word: "Warm hospitality", spainVariant: "Calidez", latamVariant: "Calidez", phoneticSpain: "[kah-lee-DEHZ]", phoneticLatam: "[kah-lee-DEHZ]", english: "Warm hospitality", partOfSpeech: "noun", exampleSentenceSpain: "La calidez de la gente.", exampleSentenceLatam: "La calidez mexicana." },
      { word: "Good luck", spainVariant: "Buena suerte", latamVariant: "Buena suerte", phoneticSpain: "[boo-EH-nah SWER-teh]", phoneticLatam: "[boo-EH-nah SWER-teh]", english: "Good luck", partOfSpeech: "phrase", exampleSentenceSpain: "¡Buena suerte!", exampleSentenceLatam: "¡Buena suerte en todo!" },
      { word: "Thank you for having me", spainVariant: "Gracias por invitarme", latamVariant: "Gracias por la invitación", phoneticSpain: "[GRAH-see-ahs por in-vee-TAHR-meh]", phoneticLatam: "[GRAH-see-ahs por lah in-vee-tah-see-OHN]", english: "Thank you for having me", partOfSpeech: "phrase", exampleSentenceSpain: "Gracias por invitarme.", exampleSentenceLatam: "Gracias por la invitación." },
    ],
  },
  "b2-10-native-conversation": {
    title: "Native-Level Conversation",
    description: "The connectors, hedges, and discourse markers native speakers weave into every conversation",
    vocabulary: [
      { word: "Like", spainVariant: "Tipo", latamVariant: "Like/Así", phoneticSpain: "[TEE-po]", phoneticLatam: "[LIKE / ah-SEE]", english: "Like", partOfSpeech: "discourse marker", exampleSentenceSpain: "Tipo, no sé qué pasó.", exampleSentenceLatam: "Like, ¿qué onda?" },
      { word: "You know", spainVariant: "¿Sabes?", latamVariant: "¿Sabes?", phoneticSpain: "[SAH-bes]", phoneticLatam: "[SAH-bes]", english: "You know", partOfSpeech: "phrase", exampleSentenceSpain: "¿Sabes? Fue muy bueno.", exampleSentenceLatam: "¿Sabes? No me esperaba eso." },
      { word: "I mean", spainVariant: "O sea", latamVariant: "O sea", phoneticSpain: "[o SEH-ah]", phoneticLatam: "[o SEH-ah]", english: "I mean", partOfSpeech: "discourse marker", exampleSentenceSpain: "O sea, era raro.", exampleSentenceLatam: "O sea, ¿qué esperas?" },
      { word: "Like really", spainVariant: "Es que", latamVariant: "Es que", phoneticSpain: "[es keh]", phoneticLatam: "[es keh]", english: "It's that", partOfSpeech: "discourse marker", exampleSentenceSpain: "Es que fue muy extraño.", exampleSentenceLatam: "Es que no sabía qué hacer." },
      { word: "Anyway", spainVariant: "De todas formas", latamVariant: "De todas formas", phoneticSpain: "[deh TOH-dahs FOR-mas]", phoneticLatam: "[deh TOH-dahs FOR-mas]", english: "Anyway", partOfSpeech: "discourse marker", exampleSentenceSpain: "De todas formas, no importa.", exampleSentenceLatam: "De todas formas, valió la pena." },
      { word: "Actually", spainVariant: "Bueno, la verdad es", latamVariant: "Bueno, pues", phoneticSpain: "[boo-EH-no, lah ver-DAHD es]", phoneticLatam: "[boo-EH-no, pwes]", english: "Actually", partOfSpeech: "discourse marker", exampleSentenceSpain: "Bueno, la verdad es que no.", exampleSentenceLatam: "Bueno, pues, depende." },
      { word: "Kind of/Sort of", spainVariant: "Más o menos", latamVariant: "Medio/Más o menos", phoneticSpain: "[mahs o MEH-nos]", phoneticLatam: "[MEH-dee-o]", english: "Kind of", partOfSpeech: "discourse marker", exampleSentenceSpain: "Más o menos bien.", exampleSentenceLatam: "Medio enojado, más o menos." },
      { word: "Right?", spainVariant: "¿Verdad?", latamVariant: "¿Verdad?", phoneticSpain: "[ver-DAHD]", phoneticLatam: "[ver-DAHD]", english: "Right?", partOfSpeech: "discourse marker", exampleSentenceSpain: "Fue bueno, ¿verdad?", exampleSentenceLatam: "Estuvo padre, ¿verdad?" },
      { word: "Basically", spainVariant: "Básicamente", latamVariant: "Básicamente", phoneticSpain: "[bah-see-kah-MEN-teh]", phoneticLatam: "[bah-see-kah-MEN-teh]", english: "Basically", partOfSpeech: "discourse marker", exampleSentenceSpain: "Básicamente fue un desastre.", exampleSentenceLatam: "Básicamente me fui sin avisar." },
      { word: "Obviously", spainVariant: "Obviamente", latamVariant: "Obvio", phoneticSpain: "[ob-vee-ah-MEN-teh]", phoneticLatam: "[OB-vee-o]", english: "Obviously", partOfSpeech: "discourse marker", exampleSentenceSpain: "Obviamente no fue así.", exampleSentenceLatam: "Obvio que no." },
      { word: "Honestly speaking", spainVariant: "Siendo sincero", latamVariant: "Siendo honesto", phoneticSpain: "[see-EHN-do sin-SEH-ro]", phoneticLatam: "[see-EHN-do o-NES-to]", english: "Being honest", partOfSpeech: "discourse marker", exampleSentenceSpain: "Siendo sincero, no me gusta.", exampleSentenceLatam: "Siendo honesto, dudo mucho." },
      { word: "By the way", spainVariant: "Por cierto", latamVariant: "A propósito", phoneticSpain: "[por see-EHR-to]", phoneticLatam: "[ah pro-POH-see-to]", english: "By the way", partOfSpeech: "discourse marker", exampleSentenceSpain: "Por cierto, ¿cómo estás?", exampleSentenceLatam: "A propósito, ¿cómo te va?" },
      { word: "Speaking of which", spainVariant: "Hablando de eso", latamVariant: "A propósito", phoneticSpain: "[ah-BLAHN-do deh EH-so]", phoneticLatam: "[ah pro-POH-see-to]", english: "Speaking of which", partOfSpeech: "discourse marker", exampleSentenceSpain: "Hablando de eso...", exampleSentenceLatam: "A propósito de eso..." },
      { word: "That said", spainVariant: "Dicho esto", latamVariant: "Habiendo dicho eso", phoneticSpain: "[DEE-cho ES-to]", phoneticLatam: "[ah-bee-EHN-do DEE-cho EH-so]", english: "That said", partOfSpeech: "discourse marker", exampleSentenceSpain: "Dicho esto, fue difícil.", exampleSentenceLatam: "Habiendo dicho eso, fue bonito." },
      { word: "Now that", spainVariant: "Ahora que", latamVariant: "Ahora que", phoneticSpain: "[ah-OH-rah keh]", phoneticLatam: "[ah-OH-rah keh]", english: "Now that", partOfSpeech: "discourse marker", exampleSentenceSpain: "Ahora que lo pienso...", exampleSentenceLatam: "Ahora que mencionas eso..." },
      { word: "Thing is", spainVariant: "El caso es que", latamVariant: "Lo que pasa es que", phoneticSpain: "[el KAH-so es keh]", phoneticLatam: "[lo keh PAH-sah es keh]", english: "Thing is", partOfSpeech: "discourse marker", exampleSentenceSpain: "El caso es que no sé.", exampleSentenceLatam: "Lo que pasa es que me olvidé." },
      { word: "At the end of the day", spainVariant: "Al final del día", latamVariant: "Al final de cuentas", phoneticSpain: "[ahl fee-NAHL del DEE-ah]", phoneticLatam: "[ahl fee-NAHL deh KWEN-tas]", english: "At the end of the day", partOfSpeech: "discourse marker", exampleSentenceSpain: "Al final del día, fue bueno.", exampleSentenceLatam: "Al final de cuentas, todo está bien." },
      { word: "All things considered", spainVariant: "Considerando todo", latamVariant: "Considerando todo", phoneticSpain: "[kon-see-deh-RAHN-do TOH-do]", phoneticLatam: "[kon-see-deh-RAHN-do TOH-do]", english: "All things considered", partOfSpeech: "discourse marker", exampleSentenceSpain: "Considerando todo, estuvo bien.", exampleSentenceLatam: "Considerando todo, no estuvo tan mal." },
      { word: "You get me?", spainVariant: "¿Me entiendes?", latamVariant: "¿Me entiende?", phoneticSpain: "[meh en-tee-EHN-des]", phoneticLatam: "[meh en-tee-EHN-deh]", english: "You get me?", partOfSpeech: "discourse marker", exampleSentenceSpain: "¿Me entiendes? Fue feo.", exampleSentenceLatam: "¿Me entiende lo que digo?" },
      { word: "No pressure, but", spainVariant: "Sin presión, pero", latamVariant: "Sin presión, pero", phoneticSpain: "[seen preh-see-OHN, PEH-ro]", phoneticLatam: "[seen preh-see-OHN, PEH-ro]", english: "No pressure, but", partOfSpeech: "discourse marker", exampleSentenceSpain: "Sin presión, pero necesito respuesta.", exampleSentenceLatam: "Sin presión, pero avísame pronto." },
    ],
  },
};

function buildB2Lesson(slug: string): LessonData {
  const lessonDef = B2_LESSONS[slug as keyof typeof B2_LESSONS];
  if (!lessonDef) {
    throw new Error(`B2 lesson ${slug} not found`);
  }

  const slughyphen = slug.split("-");
  const order = parseInt(slughyphen[2]) || 1;

  const grammarSection: GrammarItem[] = [
    {
      title: "Advanced Constructions & Subjunctive Mastery",
      spainContent: `B2 focuses on mastering subjunctive in all contexts, conditional sentences, and expressing nuance. Example: "Si hubiera sabido, no lo habría hecho."`,
      latamContent: `Mexican Spanish uses the same advanced structures, with regional preferences for certain constructions. The subjunctive is more flexible in everyday speech.`,
      note: "B2 grammar is advanced; focus on nuance and regional variation rather than basic rules.",
    },
    {
      title: `${lessonDef.title} in Context`,
      spainContent: `Understanding ${lessonDef.title} requires knowing not just vocabulary but also cultural context and when/how Spaniards use these terms naturally.`,
      latamContent: `In Mexico and Latin America, ${lessonDef.title} terminology and usage patterns reflect different social norms, humor styles, and regional preferences.`,
      note: "Context and tone are everything at B2 level; the same word can have very different meanings depending on situation.",
    },
  ];

  const dialogues: DialogueScenario[] = [];

  for (let i = 0; i < 3; i++) {
    dialogues.push({
      id: `dialogue-spain-${i + 1}`,
      title: `${lessonDef.title} - Scene ${i + 1} (Spain)`,
      region: "SPAIN",
      setting: `Madrid/Barcelona setting for ${lessonDef.title}`,
      lines: [
        { speaker: "Ana", text: lessonDef.vocabulary[i]?.exampleSentenceSpain || `Hablando de ${lessonDef.title}... (Spain ${i + 1})`, region: "SPAIN", setting: `Madrid/Barcelona setting for ${lessonDef.title}` },
        { speaker: "Carlos", text: lessonDef.vocabulary[(i + 1) % lessonDef.vocabulary.length]?.exampleSentenceSpain || `Claro, en España... (Spain ${i + 1})`, region: "SPAIN", setting: `Madrid/Barcelona setting for ${lessonDef.title}` },
        { speaker: "Ana", text: `Exactamente. (Spain ${i + 1})`, region: "SPAIN", setting: `Madrid/Barcelona setting for ${lessonDef.title}` },
      ],
    });
  }

  for (let i = 0; i < 3; i++) {
    dialogues.push({
      id: `dialogue-latam-${i + 1}`,
      title: `${lessonDef.title} - Scene ${i + 1} (Mexico)`,
      region: "LATAM",
      setting: `Mexico City/Guadalajara setting for ${lessonDef.title}`,
      lines: [
        { speaker: "María", text: lessonDef.vocabulary[i]?.exampleSentenceLatam || `Oye, ${lessonDef.title.toLowerCase()}... (Mexico ${i + 1})`, region: "LATAM", setting: `Mexico City/Guadalajara setting for ${lessonDef.title}` },
        { speaker: "Diego", text: lessonDef.vocabulary[(i + 1) % lessonDef.vocabulary.length]?.exampleSentenceLatam || `Sí, aquí en México... (Mexico ${i + 1})`, region: "LATAM", setting: `Mexico City/Guadalajara setting for ${lessonDef.title}` },
        { speaker: "María", text: `Neta, eso es verdad. (Mexico ${i + 1})`, region: "LATAM", setting: `Mexico City/Guadalajara setting for ${lessonDef.title}` },
      ],
    });
  }

  const quiz: QuizQuestion[] = [
    {
      questionId: "q1",
      type: "multiple-choice",
      questionText: `What characterizes B2-level Spanish?`,
      options: ["Using only simple present tense", "Mastering subjunctive and expressing nuance", "Avoiding slang entirely", "Not using idioms"],
      correctAnswer: "Mastering subjunctive and expressing nuance",
      explanation: "B2 Spanish is about expressing complex ideas, mastering subjunctive in all contexts, and understanding cultural nuance.",
    },
    {
      questionId: "q2",
      type: "multiple-choice",
      questionText: `In this lesson, what regional difference do we study?`,
      options: ["Spain vs Mexico vocabulary", "Different greetings", "No differences", "Only grammar differences"],
      correctAnswer: "Spain vs Mexico vocabulary",
      explanation: `This lesson (${lessonDef.title}) covers vocabulary and expressions that differ between Spain and Mexico/Latin America.`,
    },
    {
      questionId: "q3",
      type: "multiple-choice",
      questionText: `How should you approach B2 material?`,
      options: ["Learn lists of words", "Focus on context and cultural understanding", "Avoid reading", "Study only grammar"],
      correctAnswer: "Focus on context and cultural understanding",
      explanation: "At B2, it's not just what you say but when, where, and to whom you say it. Context is everything.",
    },
    {
      questionId: "q4",
      type: "multiple-choice",
      questionText: `What is a key skill at B2 level?`,
      options: ["Asking for directions", "Understanding nuance and subtlety", "Basic greetings", "Ordering food"],
      correctAnswer: "Understanding nuance and subtlety",
      explanation: "B2 learners understand sarcasm, idioms, tone, and can express complex emotions and ideas.",
    },
    {
      questionId: "q5",
      type: "multiple-choice",
      questionText: `Why is regional variation important at B2?`,
      options: ["It's not important", "To sound more authentic and avoid offending", "For grammar only", "To learn more words"],
      correctAnswer: "To sound more authentic and avoid offending",
      explanation: "Regional vocabulary and slang differ significantly; using the wrong term in the wrong region can cause offense or confusion.",
    },
  ];

  const flashcards: FlashcardItem[] = lessonDef.vocabulary.map((v, idx) => ({
    id: `fc-${slug}-${idx + 1}`,
    frontSpain: v.spainVariant,
    frontLatam: v.latamVariant,
    backEnglish: v.english,
    variantDifferenceNote: v.spainVariant !== v.latamVariant ? `Spain: "${v.spainVariant}", Mexico: "${v.latamVariant}"` : "Same in both regions",
    exampleSentenceSpain: v.exampleSentenceSpain || "",
    exampleSentenceLatam: v.exampleSentenceLatam || "",
    partOfSpeech: v.partOfSpeech,
  }));

  return {
    id: `lesson-${slug}`,
    slug,
    title: lessonDef.title,
    description: lessonDef.description,
    level: "B2",
    difficulty: "UPPER_INTERMEDIATE",
    order,
    imageUrl: null,
    durationMinutes: 30,
    isPublished: true,
    vocabularyTable: lessonDef.vocabulary,
    grammarSection,
    dialogues,
    quiz,
    flashcards,
    vocabularyJson: lessonDef.vocabulary.map((v) => ({
      word: v.word,
      translation: `${v.spainVariant} / ${v.latamVariant}`,
      partOfSpeech: v.partOfSpeech,
      example: v.exampleSentenceLatam,
    })),
    grammarJson: grammarSection.map((g) => ({
      title: g.title,
      content: `${g.spainContent} | ${g.latamContent}`,
    })),
    content: `# ${lessonDef.title}\n\n${lessonDef.description}\n\nThis B2 lesson emphasizes understanding regional variation, cultural context, and nuance. These are not just words—they're windows into how Spaniards and Mexicans think, joke, and communicate in real life.`,
  };
}

export function generateB2Lessons(): LessonData[] {
  const b2Slugs = Object.keys(B2_LESSONS);
  return b2Slugs.map((slug) => buildB2Lesson(slug));
}