ALTER TABLE "users" 
ADD COLUMN IF NOT EXISTS daily_goal INTEGER NOT NULL DEFAULT 20,
ADD COLUMN IF NOT EXISTS preferred_accent TEXT NOT NULL DEFAULT 'Spain',
ADD COLUMN IF NOT EXISTS email_reminders BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS streak_warnings BOOLEAN NOT NULL DEFAULT true;